-- V12 — seed vocabulary: Oxford 3000 (American English) A1 band, 899 headwords.
-- Generated from authored Bengali glosses + bilingual examples (scratchpad/a1_chunk_*.json).
-- Standalone reference data; see V11 for the table. A2/B1/B2 bands follow in later migrations.

insert into vocabulary
    (headword, sense_label, part_of_speech, cefr_level, bn_gloss, example_en, example_bn, ordinal)
values
    ('a, an', null, 'indefinite article', 'A1', 'একটি; একটা (অনির্দিষ্ট)', 'I have a pen and an apple.', 'আমার কাছে একটি কলম আর একটি আপেল আছে।', 1),
    ('about', null, 'prep., adv.', 'A1', 'সম্পর্কে; প্রায়', 'This book is about animals.', 'এই বইটি প্রাণীদের সম্পর্কে।', 2),
    ('above', null, 'prep., adv.', 'A1', 'উপরে', 'The clock is above the door.', 'ঘড়িটি দরজার উপরে।', 3),
    ('across', null, 'prep., adv.', 'A1', 'আড়াআড়ি; ওপারে', 'We walked across the road.', 'আমরা রাস্তা পার হয়ে হাঁটলাম।', 4),
    ('action', null, 'n.', 'A1', 'কাজ; ক্রিয়া', 'We must take action now.', 'আমাদের এখনই ব্যবস্থা নিতে হবে।', 5),
    ('activity', null, 'n.', 'A1', 'কার্যকলাপ', 'Reading is my favorite activity.', 'পড়া আমার প্রিয় কাজ।', 6),
    ('actor', null, 'n.', 'A1', 'অভিনেতা', 'He is a famous actor.', 'তিনি একজন বিখ্যাত অভিনেতা।', 7),
    ('actress', null, 'n.', 'A1', 'অভিনেত্রী', 'She is a great actress.', 'তিনি একজন দুর্দান্ত অভিনেত্রী।', 8),
    ('add', null, 'v.', 'A1', 'যোগ করা', 'Please add some sugar.', 'দয়া করে কিছু চিনি যোগ করুন।', 9),
    ('address', null, 'n., v.', 'A1', 'ঠিকানা', 'What is your home address?', 'আপনার বাড়ির ঠিকানা কী?', 10),
    ('adult', null, 'adj., n.', 'A1', 'প্রাপ্তবয়স্ক', 'My brother is an adult now.', 'আমার ভাই এখন প্রাপ্তবয়স্ক।', 11),
    ('advice', null, 'n.', 'A1', 'পরামর্শ', 'She gave me good advice.', 'তিনি আমাকে ভালো পরামর্শ দিলেন।', 12),
    ('afraid', null, 'adj.', 'A1', 'ভীত; ভয় পাওয়া', 'I am afraid of dogs.', 'আমি কুকুরকে ভয় পাই।', 13),
    ('after', null, 'prep., conj., adv.', 'A1', 'পরে', 'We play after school.', 'আমরা স্কুলের পরে খেলি।', 14),
    ('afternoon', null, 'n.', 'A1', 'বিকাল', 'See you this afternoon.', 'আজ বিকেলে দেখা হবে।', 15),
    ('again', null, 'adv.', 'A1', 'আবার', 'Please say it again.', 'দয়া করে আবার বলুন।', 16),
    ('age', null, 'n., v.', 'A1', 'বয়স', 'What is your age?', 'আপনার বয়স কত?', 17),
    ('ago', null, 'adv.', 'A1', 'আগে', 'He left an hour ago.', 'তিনি এক ঘণ্টা আগে চলে গেছেন।', 18),
    ('agree', null, 'v.', 'A1', 'একমত হওয়া', 'I agree with you.', 'আমি আপনার সাথে একমত।', 19),
    ('air', null, 'n.', 'A1', 'বাতাস; বায়ু', 'The air is fresh here.', 'এখানকার বাতাস তাজা।', 20),
    ('airport', null, 'n.', 'A1', 'বিমানবন্দর', 'We drove to the airport.', 'আমরা বিমানবন্দরে গাড়ি চালিয়ে গেলাম।', 21),
    ('all', null, 'pron., det., adv.', 'A1', 'সব; সকল', 'All the students are here.', 'সব ছাত্র এখানে আছে।', 22),
    ('also', null, 'adv.', 'A1', 'এছাড়াও; আরও', 'I also like tea.', 'আমিও চা পছন্দ করি।', 23),
    ('always', null, 'adv.', 'A1', 'সবসময়', 'She is always happy.', 'সে সবসময় খুশি থাকে।', 24),
    ('amazing', null, 'adj.', 'A1', 'বিস্ময়কর; দারুণ', 'The view is amazing.', 'দৃশ্যটি অসাধারণ।', 25),
    ('and', null, 'conj.', 'A1', 'এবং; আর', 'I like rice and fish.', 'আমি ভাত আর মাছ পছন্দ করি।', 26),
    ('angry', null, 'adj.', 'A1', 'রাগান্বিত', 'Do not be angry.', 'রাগ করো না।', 27),
    ('animal', null, 'n.', 'A1', 'প্রাণী', 'A dog is an animal.', 'কুকুর একটি প্রাণী।', 28),
    ('another', null, 'pron., det.', 'A1', 'আরেকটি; অন্য একটি', 'Can I have another cup?', 'আমি কি আরেকটি কাপ পেতে পারি?', 29),
    ('answer', null, 'n., v.', 'A1', 'উত্তর', 'I know the answer.', 'আমি উত্তরটি জানি।', 30),
    ('any', null, 'pron., det., adv.', 'A1', 'কোনো; কিছু', 'Do you have any money?', 'আপনার কি কোনো টাকা আছে?', 31),
    ('anyone', null, 'pron.', 'A1', 'যে কেউ; কেউ', 'Is anyone home?', 'বাড়িতে কি কেউ আছে?', 32),
    ('anything', null, 'pron.', 'A1', 'যেকোনো কিছু; কিছু', 'I cannot see anything.', 'আমি কিছুই দেখতে পাচ্ছি না।', 33),
    ('apartment', null, 'n.', 'A1', 'অ্যাপার্টমেন্ট; ফ্ল্যাট', 'They live in a small apartment.', 'তারা একটি ছোট অ্যাপার্টমেন্টে থাকে।', 34),
    ('apple', null, 'n.', 'A1', 'আপেল', 'I eat an apple every day.', 'আমি প্রতিদিন একটি আপেল খাই।', 35),
    ('April', null, 'n.', 'A1', 'এপ্রিল (মাস)', 'My birthday is in April.', 'আমার জন্মদিন এপ্রিল মাসে।', 36),
    ('area', null, 'n.', 'A1', 'এলাকা; অঞ্চল', 'This is a quiet area.', 'এটি একটি শান্ত এলাকা।', 37),
    ('arm', null, 'n.', 'A1', 'বাহু; হাত', 'He hurt his arm.', 'সে তার হাতে ব্যথা পেয়েছে।', 38),
    ('around', null, 'prep., adv.', 'A1', 'চারপাশে; ঘিরে', 'We sat around the table.', 'আমরা টেবিলের চারপাশে বসলাম।', 39),
    ('arrive', null, 'v.', 'A1', 'পৌঁছানো', 'The train will arrive soon.', 'ট্রেনটি শীঘ্রই পৌঁছাবে।', 40),
    ('art', null, 'n.', 'A1', 'শিল্প; চারুকলা', 'She loves art.', 'সে শিল্প ভালোবাসে।', 41),
    ('article', null, 'n.', 'A1', 'প্রবন্ধ; নিবন্ধ', 'I read an article today.', 'আমি আজ একটি প্রবন্ধ পড়েছি।', 42),
    ('artist', null, 'n.', 'A1', 'শিল্পী', 'The artist painted a picture.', 'শিল্পী একটি ছবি আঁকলেন।', 43),
    ('as', null, 'prep., conj., adv.', 'A1', 'যেমন; হিসেবে; যখন', 'She works as a teacher.', 'তিনি শিক্ষক হিসেবে কাজ করেন।', 44),
    ('ask', null, 'v.', 'A1', 'জিজ্ঞাসা করা', 'Ask her a question.', 'তাকে একটি প্রশ্ন জিজ্ঞাসা করো।', 45),
    ('at', null, 'prep.', 'A1', '-এ; -তে (স্থান/সময়)', 'I am at home.', 'আমি বাড়িতে আছি।', 46),
    ('August', null, 'n.', 'A1', 'আগস্ট (মাস)', 'School starts in August.', 'স্কুল আগস্ট মাসে শুরু হয়।', 47),
    ('aunt', null, 'n.', 'A1', 'খালা; ফুপু; মাসি; চাচি', 'My aunt lives nearby.', 'আমার খালা কাছেই থাকেন।', 48),
    ('away', null, 'adv.', 'A1', 'দূরে', 'He walked away.', 'সে দূরে হেঁটে গেল।', 49),
    ('awesome', null, 'adj.', 'A1', 'চমৎকার; দারুণ', 'That was an awesome game.', 'সেটা একটা দারুণ খেলা ছিল।', 50),
    ('baby', null, 'n.', 'A1', 'শিশু; বাচ্চা', 'The baby is sleeping.', 'বাচ্চাটি ঘুমাচ্ছে।', 51),
    ('back', null, 'adv., adj., n., v.', 'A1', 'পিছনে; পিঠ', 'Please come back soon.', 'দয়া করে শীঘ্রই ফিরে এসো।', 52),
    ('bad', null, 'adj.', 'A1', 'খারাপ; মন্দ', 'The weather is bad today.', 'আজ আবহাওয়া খারাপ।', 53),
    ('bag', null, 'n.', 'A1', 'ব্যাগ; থলে', 'My bag is heavy.', 'আমার ব্যাগটি ভারী।', 54),
    ('ball', null, 'n.', 'A1', 'বল', 'The children play with a ball.', 'বাচ্চারা একটি বল নিয়ে খেলে।', 55),
    ('banana', null, 'n.', 'A1', 'কলা', 'I want a banana.', 'আমি একটি কলা চাই।', 56),
    ('band', null, 'n.', 'A1', 'ব্যান্ড; বাদকদল', 'The band played music.', 'ব্যান্ডটি গান বাজাল।', 57),
    ('bank', 'money', 'n.', 'A1', 'ব্যাংক', 'I keep my money in a bank.', 'আমি আমার টাকা ব্যাংকে রাখি।', 58),
    ('bar', null, 'n., v.', 'A1', 'বার; দণ্ড; পানশালা', 'He bought a bar of chocolate.', 'সে এক টুকরো চকলেট কিনল।', 59),
    ('baseball', null, 'n.', 'A1', 'বেসবল', 'They play baseball on Sunday.', 'তারা রবিবারে বেসবল খেলে।', 60),
    ('basketball', null, 'n.', 'A1', 'বাস্কেটবল', 'He is good at basketball.', 'সে বাস্কেটবলে ভালো।', 61),
    ('bath', null, 'n.', 'A1', 'স্নান; গোসল', 'I take a bath every morning.', 'আমি প্রতিদিন সকালে গোসল করি।', 62),
    ('bathroom', null, 'n.', 'A1', 'স্নানঘর; বাথরুম', 'Where is the bathroom?', 'বাথরুম কোথায়?', 63),
    ('be', null, 'auxiliary v., v.', 'A1', 'হওয়া; থাকা', 'I want to be a doctor.', 'আমি একজন ডাক্তার হতে চাই।', 64),
    ('beach', null, 'n.', 'A1', 'সৈকত; সমুদ্রতীর', 'We walked on the beach.', 'আমরা সৈকতে হাঁটলাম।', 65),
    ('beautiful', null, 'adj.', 'A1', 'সুন্দর', 'What a beautiful flower!', 'কী সুন্দর একটি ফুল!', 66),
    ('because', null, 'conj.', 'A1', 'কারণ; কেননা', 'I stayed home because it rained.', 'বৃষ্টি হয়েছিল বলে আমি বাড়িতে ছিলাম।', 67),
    ('become', null, 'v.', 'A1', 'হয়ে ওঠা; পরিণত হওয়া', 'She wants to become a nurse.', 'সে একজন নার্স হতে চায়।', 68),
    ('bed', null, 'n.', 'A1', 'বিছানা; খাট', 'I go to bed at ten.', 'আমি দশটায় ঘুমাতে যাই।', 69),
    ('bedroom', null, 'n.', 'A1', 'শোবার ঘর', 'My bedroom is small.', 'আমার শোবার ঘরটি ছোট।', 70),
    ('beer', null, 'n.', 'A1', 'বিয়ার', 'He drank a glass of beer.', 'সে এক গ্লাস বিয়ার পান করল।', 71),
    ('before', null, 'prep., conj., adv.', 'A1', 'আগে; পূর্বে', 'Wash your hands before dinner.', 'রাতের খাবারের আগে হাত ধুয়ে নাও।', 72),
    ('begin', null, 'v.', 'A1', 'শুরু করা', 'The class will begin at nine.', 'ক্লাস নয়টায় শুরু হবে।', 73),
    ('beginning', null, 'n.', 'A1', 'শুরু; সূচনা', 'This is just the beginning.', 'এটি কেবল শুরু।', 74),
    ('behind', null, 'prep., adv.', 'A1', 'পিছনে', 'The car is behind the house.', 'গাড়িটি বাড়ির পিছনে।', 75),
    ('believe', null, 'v.', 'A1', 'বিশ্বাস করা', 'I believe you.', 'আমি তোমাকে বিশ্বাস করি।', 76),
    ('below', null, 'prep., adv.', 'A1', 'নিচে', 'Write your name below.', 'নিচে তোমার নাম লেখো।', 77),
    ('best', null, 'adv., adj., n.', 'A1', 'সেরা; সবচেয়ে ভালো', 'She is my best friend.', 'সে আমার সবচেয়ে ভালো বন্ধু।', 78),
    ('better', null, 'adv., adj., n.', 'A1', 'আরও ভালো', 'This one is better.', 'এটি আরও ভালো।', 79),
    ('between', null, 'prep., adv.', 'A1', 'মধ্যে; মাঝে', 'Sit between us.', 'আমাদের মাঝে বসো।', 80),
    ('bicycle', null, 'n.', 'A1', 'সাইকেল', 'She rides a bicycle to school.', 'সে সাইকেলে করে স্কুলে যায়।', 81),
    ('big', null, 'adj.', 'A1', 'বড়', 'They have a big house.', 'তাদের একটি বড় বাড়ি আছে।', 82),
    ('bike', null, 'n.', 'A1', 'সাইকেল; বাইক', 'My bike is red.', 'আমার বাইকটি লাল।', 83),
    ('bill', null, 'n., v.', 'A1', 'বিল; হিসাব', 'Can I have the bill, please?', 'দয়া করে বিলটি দিন।', 84),
    ('bird', null, 'n.', 'A1', 'পাখি', 'A bird is singing.', 'একটি পাখি গান গাইছে।', 85),
    ('birthday', null, 'n.', 'A1', 'জন্মদিন', 'Happy birthday to you!', 'তোমাকে জন্মদিনের শুভেচ্ছা!', 86),
    ('black', null, 'adj., n.', 'A1', 'কালো', 'He wore a black shirt.', 'সে একটি কালো শার্ট পরেছিল।', 87),
    ('blog', null, 'n.', 'A1', 'ব্লগ', 'She writes a food blog.', 'সে একটি খাবারের ব্লগ লেখে।', 88),
    ('blond', null, 'adj.', 'A1', 'সোনালি চুলের', 'She has blond hair.', 'তার সোনালি চুল।', 89),
    ('blue', null, 'adj., n.', 'A1', 'নীল', 'The sky is blue.', 'আকাশ নীল।', 90),
    ('boat', null, 'n.', 'A1', 'নৌকা', 'We crossed the river by boat.', 'আমরা নৌকায় করে নদী পার হলাম।', 91),
    ('body', null, 'n.', 'A1', 'শরীর; দেহ', 'Exercise is good for the body.', 'ব্যায়াম শরীরের জন্য ভালো।', 92),
    ('book', null, 'n., v.', 'A1', 'বই; আগাম সংরক্ষণ করা', 'I am reading a good book.', 'আমি একটি ভালো বই পড়ছি।', 93),
    ('boot', null, 'n.', 'A1', 'বুট জুতা', 'He wears black boots.', 'সে কালো বুট পরে।', 94),
    ('bored', null, 'adj.', 'A1', 'বিরক্ত; একঘেয়ে লাগা', 'I am bored at home.', 'আমি বাড়িতে বিরক্ত হয়ে আছি।', 95),
    ('boring', null, 'adj.', 'A1', 'একঘেয়ে; বিরক্তিকর', 'The movie was boring.', 'সিনেমাটি একঘেয়ে ছিল।', 96),
    ('born', null, 'v.', 'A1', 'জন্মগ্রহণ করা', 'I was born in Dhaka.', 'আমি ঢাকায় জন্মগ্রহণ করেছি।', 97),
    ('both', null, 'pron., det.', 'A1', 'উভয়; দুটোই', 'Both boys are tall.', 'দুটো ছেলেই লম্বা।', 98),
    ('bottle', null, 'n.', 'A1', 'বোতল', 'Give me a bottle of water.', 'আমাকে এক বোতল পানি দাও।', 99),
    ('box', null, 'n.', 'A1', 'বাক্স', 'The toys are in the box.', 'খেলনাগুলো বাক্সে আছে।', 100),
    ('boy', null, 'n.', 'A1', 'ছেলে', 'The boy is playing.', 'ছেলেটি খেলছে।', 101),
    ('boyfriend', null, 'n.', 'A1', 'প্রেমিক; বয়ফ্রেন্ড', 'Her boyfriend is kind.', 'তার বয়ফ্রেন্ড দয়ালু।', 102),
    ('bread', null, 'n.', 'A1', 'রুটি; পাউরুটি', 'I eat bread for breakfast.', 'আমি সকালের নাস্তায় রুটি খাই।', 103),
    ('break', null, 'n., v.', 'A1', 'ভাঙা; বিরতি', 'Let''s take a short break.', 'চলো একটু বিরতি নিই।', 104),
    ('breakfast', null, 'n.', 'A1', 'সকালের নাস্তা', 'Breakfast is ready.', 'সকালের নাস্তা তৈরি।', 105),
    ('bring', null, 'v.', 'A1', 'নিয়ে আসা', 'Please bring your book.', 'দয়া করে তোমার বইটি নিয়ে এসো।', 106),
    ('brother', null, 'n.', 'A1', 'ভাই', 'My brother is a student.', 'আমার ভাই একজন ছাত্র।', 107),
    ('brown', null, 'adj., n.', 'A1', 'বাদামি', 'She has brown eyes.', 'তার চোখ বাদামি।', 108),
    ('build', null, 'v.', 'A1', 'নির্মাণ করা; বানানো', 'They will build a new school.', 'তারা একটি নতুন স্কুল নির্মাণ করবে।', 109),
    ('building', null, 'n.', 'A1', 'ভবন; দালান', 'That building is very tall.', 'ওই ভবনটি খুব উঁচু।', 110),
    ('bus', null, 'n.', 'A1', 'বাস', 'I go to work by bus.', 'আমি বাসে করে কাজে যাই।', 111),
    ('business', null, 'n.', 'A1', 'ব্যবসা', 'He runs a small business.', 'সে একটি ছোট ব্যবসা চালায়।', 112),
    ('busy', null, 'adj.', 'A1', 'ব্যস্ত', 'I am busy today.', 'আমি আজ ব্যস্ত।', 113),
    ('but', null, 'prep., conj.', 'A1', 'কিন্তু', 'I am tired but happy.', 'আমি ক্লান্ত কিন্তু খুশি।', 114),
    ('butter', null, 'n.', 'A1', 'মাখন', 'She put butter on the bread.', 'সে রুটিতে মাখন লাগাল।', 115),
    ('buy', null, 'v.', 'A1', 'কেনা', 'I want to buy a phone.', 'আমি একটি ফোন কিনতে চাই।', 116),
    ('by', null, 'prep., adv.', 'A1', 'দ্বারা; দিয়ে; কাছে', 'The book was written by her.', 'বইটি তার দ্বারা লেখা হয়েছে।', 117),
    ('bye', null, 'exclam.', 'A1', 'বিদায়; আবার দেখা হবে', 'Bye, see you tomorrow!', 'বিদায়, কাল দেখা হবে!', 118),
    ('cafe', null, 'n.', 'A1', 'ক্যাফে; ছোট রেস্তোরাঁ', 'We met at a cafe.', 'আমরা একটি ক্যাফেতে দেখা করেছিলাম।', 119),
    ('cake', null, 'n.', 'A1', 'কেক', 'She baked a cake.', 'সে একটি কেক বানাল।', 120),
    ('call', null, 'n., v.', 'A1', 'ডাকা; ফোন করা', 'Please call me tonight.', 'দয়া করে আজ রাতে আমাকে ফোন করো।', 121),
    ('camera', null, 'n.', 'A1', 'ক্যামেরা', 'This camera takes good photos.', 'এই ক্যামেরায় ভালো ছবি ওঠে।', 122),
    ('can', null, 'modal v., v.', 'A1', 'পারা; সক্ষম হওয়া', 'I can speak English.', 'আমি ইংরেজি বলতে পারি।', 123),
    ('cannot', null, 'v.', 'A1', 'পারি না; পারে না', 'I cannot swim.', 'আমি সাঁতার কাটতে পারি না।', 124),
    ('capital', null, 'adj., n.', 'A1', 'রাজধানী; বড় হাতের অক্ষর', 'Dhaka is the capital of Bangladesh.', 'ঢাকা বাংলাদেশের রাজধানী।', 125),
    ('car', null, 'n.', 'A1', 'গাড়ি', 'They bought a new car.', 'তারা একটি নতুন গাড়ি কিনেছে।', 126),
    ('card', null, 'n.', 'A1', 'কার্ড', 'I sent her a birthday card.', 'আমি তাকে একটি জন্মদিনের কার্ড পাঠিয়েছি।', 127),
    ('career', null, 'n.', 'A1', 'পেশা; কর্মজীবন', 'She has a good career.', 'তার একটি ভালো কর্মজীবন আছে।', 128),
    ('carrot', null, 'n.', 'A1', 'গাজর', 'Rabbits like carrots.', 'খরগোশ গাজর পছন্দ করে।', 129),
    ('carry', null, 'v.', 'A1', 'বহন করা; বয়ে নেওয়া', 'Can you carry this bag?', 'তুমি কি এই ব্যাগটি বইতে পারবে?', 130),
    ('cat', null, 'n.', 'A1', 'বিড়াল', 'The cat is on the chair.', 'বিড়ালটি চেয়ারের উপর।', 131),
    ('CD', null, 'n.', 'A1', 'সিডি', 'He bought a music CD.', 'সে একটি গানের সিডি কিনল।', 132),
    ('cent', null, 'n.', 'A1', 'সেন্ট (মুদ্রা)', 'It costs fifty cents.', 'এর দাম পঞ্চাশ সেন্ট।', 133),
    ('center', null, 'n., v.', 'A1', 'কেন্দ্র; মাঝখান', 'The park is in the center of the city.', 'পার্কটি শহরের কেন্দ্রে।', 134),
    ('chair', null, 'n., v.', 'A1', 'চেয়ার; কেদারা', 'Please sit on this chair.', 'দয়া করে এই চেয়ারে বসুন।', 135),
    ('change', null, 'n., v.', 'A1', 'পরিবর্তন; বদলানো', 'I need to change my clothes.', 'আমার জামাকাপড় বদলাতে হবে।', 136),
    ('chart', null, 'n., v.', 'A1', 'চার্ট; তালিকাচিত্র', 'Look at the chart on the wall.', 'দেয়ালের চার্টটি দেখো।', 137),
    ('cheap', null, 'adv., adj.', 'A1', 'সস্তা', 'This shirt is cheap.', 'এই শার্টটি সস্তা।', 138),
    ('check', null, 'n., v.', 'A1', 'পরীক্ষা করা; যাচাই করা', 'Check your answers again.', 'তোমার উত্তরগুলো আবার যাচাই করো।', 139),
    ('cheese', null, 'n.', 'A1', 'পনির; চিজ', 'I like cheese on my pizza.', 'আমি পিৎজায় চিজ পছন্দ করি।', 140),
    ('chicken', null, 'n.', 'A1', 'মুরগি', 'We ate chicken for dinner.', 'আমরা রাতের খাবারে মুরগি খেয়েছি।', 141),
    ('child', null, 'n.', 'A1', 'শিশু; সন্তান', 'The child is very happy.', 'শিশুটি খুব খুশি।', 142),
    ('chocolate', null, 'n.', 'A1', 'চকলেট', 'She loves chocolate.', 'সে চকলেট খুব ভালোবাসে।', 143),
    ('choose', null, 'v.', 'A1', 'বেছে নেওয়া; নির্বাচন করা', 'Choose your favorite color.', 'তোমার প্রিয় রঙ বেছে নাও।', 144),
    ('city', null, 'n.', 'A1', 'শহর; নগর', 'Dhaka is a big city.', 'ঢাকা একটি বড় শহর।', 145),
    ('class', null, 'n.', 'A1', 'শ্রেণি; ক্লাস', 'Our class has thirty students.', 'আমাদের ক্লাসে ত্রিশজন ছাত্র আছে।', 146),
    ('classroom', null, 'n.', 'A1', 'শ্রেণিকক্ষ', 'The classroom is clean.', 'শ্রেণিকক্ষটি পরিষ্কার।', 147),
    ('clean', null, 'adj., v.', 'A1', 'পরিষ্কার; পরিষ্কার করা', 'Please clean your room.', 'দয়া করে তোমার ঘরটি পরিষ্কার করো।', 148),
    ('climb', null, 'n., v.', 'A1', 'আরোহণ করা; ওঠা', 'They climb the mountain.', 'তারা পাহাড়ে ওঠে।', 149),
    ('clock', null, 'n.', 'A1', 'ঘড়ি (দেয়াল/টেবিল)', 'The clock is on the wall.', 'ঘড়িটি দেয়ালে আছে।', 150),
    ('close', null, 'n., v.', 'A1', 'বন্ধ করা', 'Please close the window.', 'দয়া করে জানালাটি বন্ধ করো।', 151),
    ('clothes', null, 'n.', 'A1', 'পোশাক; জামাকাপড়', 'She is buying new clothes.', 'সে নতুন জামাকাপড় কিনছে।', 152),
    ('club', null, 'n.', 'A1', 'ক্লাব; সংঘ', 'He joined a football club.', 'সে একটি ফুটবল ক্লাবে যোগ দিয়েছে।', 153),
    ('coat', null, 'n.', 'A1', 'কোট; ওভারকোট', 'Wear your coat, it is cold.', 'তোমার কোটটি পরো, ঠান্ডা লাগছে।', 154),
    ('coffee', null, 'n.', 'A1', 'কফি', 'I drink coffee in the morning.', 'আমি সকালে কফি পান করি।', 155),
    ('cold', null, 'adj., n.', 'A1', 'ঠান্ডা; শীতল', 'The water is cold.', 'পানি ঠান্ডা।', 156),
    ('college', null, 'n.', 'A1', 'কলেজ', 'My sister goes to college.', 'আমার বোন কলেজে যায়।', 157),
    ('color', null, 'n.', 'A1', 'রঙ', 'What is your favorite color?', 'তোমার প্রিয় রঙ কোনটি?', 158),
    ('come', null, 'v.', 'A1', 'আসা', 'Please come here.', 'দয়া করে এখানে এসো।', 159),
    ('common', null, 'adj.', 'A1', 'সাধারণ; প্রচলিত', 'This is a common name.', 'এটি একটি প্রচলিত নাম।', 160),
    ('company', null, 'n.', 'A1', 'কোম্পানি; প্রতিষ্ঠান', 'He works for a big company.', 'সে একটি বড় কোম্পানিতে কাজ করে।', 161),
    ('compare', null, 'v.', 'A1', 'তুলনা করা', 'Compare the two pictures.', 'দুটো ছবির তুলনা করো।', 162),
    ('complete', null, 'adj., v.', 'A1', 'সম্পূর্ণ; সম্পন্ন করা', 'Please complete the form.', 'দয়া করে ফরমটি পূরণ করুন।', 163),
    ('computer', null, 'n.', 'A1', 'কম্পিউটার', 'I use a computer at work.', 'আমি কাজে কম্পিউটার ব্যবহার করি।', 164),
    ('concert', null, 'n.', 'A1', 'কনসার্ট; সঙ্গীতানুষ্ঠান', 'We went to a concert.', 'আমরা একটি কনসার্টে গিয়েছিলাম।', 165),
    ('conversation', null, 'n.', 'A1', 'কথোপকথন; আলাপ', 'We had a long conversation.', 'আমাদের দীর্ঘ আলাপ হলো।', 166),
    ('cook', null, 'n., v.', 'A1', 'রান্না করা; রাঁধুনি', 'My mother cooks well.', 'আমার মা ভালো রান্না করেন।', 167),
    ('cooking', null, 'n.', 'A1', 'রান্না', 'I enjoy cooking.', 'আমি রান্না করতে পছন্দ করি।', 168),
    ('cool', null, 'adj., v.', 'A1', 'ঠান্ডা; দারুণ', 'The evening is cool.', 'সন্ধ্যাটা ঠান্ডা।', 169),
    ('correct', null, 'adj., v.', 'A1', 'সঠিক; শুদ্ধ করা', 'Your answer is correct.', 'তোমার উত্তরটি সঠিক।', 170),
    ('cost', null, 'n., v.', 'A1', 'দাম; খরচ হওয়া', 'How much does it cost?', 'এর দাম কত?', 171),
    ('could', null, 'modal v., v.', 'A1', 'পারতাম; পারত (সম্ভাবনা)', 'Could you help me?', 'তুমি কি আমাকে সাহায্য করতে পারবে?', 172),
    ('country', null, 'n.', 'A1', 'দেশ', 'Bangladesh is a beautiful country.', 'বাংলাদেশ একটি সুন্দর দেশ।', 173),
    ('course', null, 'n.', 'A1', 'কোর্স; পাঠক্রম', 'I am taking an English course.', 'আমি একটি ইংরেজি কোর্স করছি।', 174),
    ('cousin', null, 'n.', 'A1', 'চাচাতো/মামাতো/খালাতো ভাই-বোন', 'My cousin lives in London.', 'আমার চাচাতো ভাই লন্ডনে থাকে।', 175),
    ('cow', null, 'n.', 'A1', 'গরু', 'The cow eats grass.', 'গরু ঘাস খায়।', 176),
    ('cream', null, 'adj., n.', 'A1', 'ক্রিম; সর', 'I like cream in my coffee.', 'আমি কফিতে ক্রিম পছন্দ করি।', 177),
    ('create', null, 'v.', 'A1', 'সৃষ্টি করা; তৈরি করা', 'She wants to create a website.', 'সে একটি ওয়েবসাইট তৈরি করতে চায়।', 178),
    ('culture', null, 'n.', 'A1', 'সংস্কৃতি', 'I love Bengali culture.', 'আমি বাংলা সংস্কৃতি ভালোবাসি।', 179),
    ('cup', null, 'n.', 'A1', 'কাপ; পেয়ালা', 'I want a cup of tea.', 'আমি এক কাপ চা চাই।', 180),
    ('customer', null, 'n.', 'A1', 'ক্রেতা; খদ্দের', 'The shop has many customers.', 'দোকানে অনেক ক্রেতা আছে।', 181),
    ('cut', null, 'n., v.', 'A1', 'কাটা', 'Please cut the cake.', 'দয়া করে কেকটি কাটো।', 182),
    ('dad', null, 'n.', 'A1', 'বাবা', 'My dad is a teacher.', 'আমার বাবা একজন শিক্ষক।', 183),
    ('dance', null, 'n., v.', 'A1', 'নাচ; নাচা', 'They dance at the party.', 'তারা পার্টিতে নাচে।', 184),
    ('dancer', null, 'n.', 'A1', 'নর্তক; নর্তকী', 'She is a beautiful dancer.', 'সে একজন সুন্দর নর্তকী।', 185),
    ('dancing', null, 'n.', 'A1', 'নাচ; নৃত্য', 'Dancing is fun.', 'নাচ মজার।', 186),
    ('dangerous', null, 'adj.', 'A1', 'বিপজ্জনক', 'This road is dangerous.', 'এই রাস্তাটি বিপজ্জনক।', 187),
    ('dark', null, 'adj., n.', 'A1', 'অন্ধকার', 'The room is dark.', 'ঘরটি অন্ধকার।', 188),
    ('date', null, 'n., v.', 'A1', 'তারিখ', 'What is the date today?', 'আজ কত তারিখ?', 189),
    ('daughter', null, 'n.', 'A1', 'কন্যা; মেয়ে', 'They have one daughter.', 'তাদের একটি মেয়ে আছে।', 190),
    ('day', null, 'n.', 'A1', 'দিন', 'Have a nice day!', 'শুভ দিন কাটুক!', 191),
    ('dear', null, 'adj.', 'A1', 'প্রিয়', 'Dear friend, how are you?', 'প্রিয় বন্ধু, কেমন আছো?', 192),
    ('December', null, 'n.', 'A1', 'ডিসেম্বর (মাস)', 'It is cold in December.', 'ডিসেম্বরে ঠান্ডা পড়ে।', 193),
    ('decide', null, 'v.', 'A1', 'সিদ্ধান্ত নেওয়া', 'I cannot decide.', 'আমি সিদ্ধান্ত নিতে পারছি না।', 194),
    ('delicious', null, 'adj.', 'A1', 'সুস্বাদু', 'This food is delicious.', 'এই খাবারটি সুস্বাদু।', 195),
    ('describe', null, 'v.', 'A1', 'বর্ণনা করা', 'Describe your house.', 'তোমার বাড়ির বর্ণনা করো।', 196),
    ('description', null, 'n.', 'A1', 'বর্ণনা', 'Write a short description.', 'একটি সংক্ষিপ্ত বর্ণনা লেখো।', 197),
    ('design', null, 'n., v.', 'A1', 'নকশা; নকশা করা', 'I like the design of this bag.', 'আমি এই ব্যাগের নকশাটি পছন্দ করি।', 198),
    ('desk', null, 'n.', 'A1', 'ডেস্ক; পড়ার টেবিল', 'The books are on the desk.', 'বইগুলো ডেস্কের উপর।', 199),
    ('detail', null, 'n., v.', 'A1', 'বিস্তারিত; খুঁটিনাটি', 'Tell me every detail.', 'আমাকে সব খুঁটিনাটি বলো।', 200),
    ('dialogue', null, 'n.', 'A1', 'সংলাপ', 'Read the dialogue aloud.', 'সংলাপটি জোরে পড়ো।', 201),
    ('dictionary', null, 'n.', 'A1', 'অভিধান; শব্দকোষ', 'Look it up in the dictionary.', 'এটি অভিধানে খুঁজে দেখো।', 202),
    ('die', null, 'v.', 'A1', 'মারা যাওয়া', 'The plant will die without water.', 'পানি ছাড়া গাছটি মরে যাবে।', 203),
    ('diet', null, 'n.', 'A1', 'খাদ্যাভ্যাস; পথ্য', 'She is on a healthy diet.', 'সে স্বাস্থ্যকর খাদ্যাভ্যাস মেনে চলছে।', 204),
    ('difference', null, 'n.', 'A1', 'পার্থক্য; ভিন্নতা', 'What is the difference?', 'পার্থক্যটা কী?', 205),
    ('different', null, 'adj.', 'A1', 'ভিন্ন; আলাদা', 'These two are different.', 'এই দুটো আলাদা।', 206),
    ('difficult', null, 'adj.', 'A1', 'কঠিন', 'This question is difficult.', 'এই প্রশ্নটি কঠিন।', 207),
    ('dinner', null, 'n.', 'A1', 'রাতের খাবার', 'We eat dinner at eight.', 'আমরা আটটায় রাতের খাবার খাই।', 208),
    ('dirty', null, 'adj.', 'A1', 'নোংরা; ময়লা', 'Your hands are dirty.', 'তোমার হাত নোংরা।', 209),
    ('discuss', null, 'v.', 'A1', 'আলোচনা করা', 'Let''s discuss the plan.', 'চলো পরিকল্পনাটি নিয়ে আলোচনা করি।', 210),
    ('dish', null, 'n.', 'A1', 'থালা; পদ (খাবার)', 'This is a tasty dish.', 'এটি একটি সুস্বাদু পদ।', 211),
    ('do', null, 'auxiliary v., v.', 'A1', 'করা', 'What do you do?', 'তুমি কী করো?', 212),
    ('doctor', null, 'n.', 'A1', 'ডাক্তার; চিকিৎসক', 'The doctor is very kind.', 'ডাক্তার খুব দয়ালু।', 213),
    ('dog', null, 'n.', 'A1', 'কুকুর', 'The dog is barking.', 'কুকুরটি ঘেউ ঘেউ করছে।', 214),
    ('dollar', null, 'n.', 'A1', 'ডলার', 'It costs ten dollars.', 'এর দাম দশ ডলার।', 215),
    ('door', null, 'n.', 'A1', 'দরজা', 'Please close the door.', 'দয়া করে দরজাটি বন্ধ করো।', 216),
    ('down', null, 'prep., adv.', 'A1', 'নিচে; নিচের দিকে', 'Sit down, please.', 'দয়া করে বসুন।', 217),
    ('downstairs', null, 'adv., adj.', 'A1', 'নিচতলায়; নিচে', 'The kitchen is downstairs.', 'রান্নাঘরটি নিচতলায়।', 218),
    ('draw', null, 'v.', 'A1', 'আঁকা', 'She can draw very well.', 'সে খুব ভালো আঁকতে পারে।', 219),
    ('dress', null, 'n., v.', 'A1', 'পোশাক; জামা পরা', 'She wore a red dress.', 'সে একটি লাল জামা পরেছিল।', 220),
    ('drink', null, 'n., v.', 'A1', 'পান করা; পানীয়', 'Please drink some water.', 'দয়া করে একটু পানি পান করো।', 221),
    ('drive', null, 'n., v.', 'A1', 'গাড়ি চালানো', 'He can drive a car.', 'সে গাড়ি চালাতে পারে।', 222),
    ('driver', null, 'n.', 'A1', 'চালক; ড্রাইভার', 'The bus driver is careful.', 'বাসের চালক সতর্ক।', 223),
    ('during', null, 'prep.', 'A1', 'চলাকালীন; সময়ে', 'Do not talk during the movie.', 'সিনেমা চলাকালীন কথা বলো না।', 224),
    ('DVD', null, 'n.', 'A1', 'ডিভিডি', 'We watched a DVD last night.', 'গত রাতে আমরা একটি ডিভিডি দেখেছি।', 225),
    ('each', null, 'pron., det., adv.', 'A1', 'প্রত্যেক; প্রতিটি', 'Each student has a book.', 'প্রত্যেক ছাত্রের একটি বই আছে।', 226),
    ('ear', null, 'n.', 'A1', 'কান', 'I have a pain in my ear.', 'আমার কানে ব্যথা।', 227),
    ('early', null, 'adv., adj.', 'A1', 'তাড়াতাড়ি; আগেভাগে', 'I wake up early.', 'আমি তাড়াতাড়ি ঘুম থেকে উঠি।', 228),
    ('east', null, 'adv., adj., n.', 'A1', 'পূর্ব; পূর্ব দিক', 'The sun rises in the east.', 'সূর্য পূর্ব দিকে ওঠে।', 229),
    ('easy', null, 'adj.', 'A1', 'সহজ', 'This lesson is easy.', 'এই পাঠটি সহজ।', 230),
    ('eat', null, 'v.', 'A1', 'খাওয়া', 'I eat rice every day.', 'আমি প্রতিদিন ভাত খাই।', 231),
    ('egg', null, 'n.', 'A1', 'ডিম', 'I had an egg for breakfast.', 'আমি নাস্তায় একটি ডিম খেয়েছি।', 232),
    ('eight', null, 'number', 'A1', 'আট (৮)', 'There are eight chairs.', 'আটটি চেয়ার আছে।', 233),
    ('eighteen', null, 'number', 'A1', 'আঠারো (১৮)', 'She is eighteen years old.', 'তার বয়স আঠারো বছর।', 234),
    ('eighty', null, 'number', 'A1', 'আশি (৮০)', 'My grandfather is eighty.', 'আমার দাদার বয়স আশি।', 235),
    ('elephant', null, 'n.', 'A1', 'হাতি', 'The elephant is very big.', 'হাতিটি খুব বড়।', 236),
    ('eleven', null, 'number', 'A1', 'এগারো (১১)', 'The team has eleven players.', 'দলে এগারো জন খেলোয়াড় আছে।', 237),
    ('else', null, 'adv.', 'A1', 'আর; অন্য কিছু', 'Do you want anything else?', 'তুমি কি আর কিছু চাও?', 238),
    ('email', null, 'n., v.', 'A1', 'ইমেইল', 'I sent you an email.', 'আমি তোমাকে একটি ইমেইল পাঠিয়েছি।', 239),
    ('end', null, 'n., v.', 'A1', 'শেষ; সমাপ্তি', 'The story has a happy end.', 'গল্পটির একটি সুখী সমাপ্তি আছে।', 240),
    ('enjoy', null, 'v.', 'A1', 'উপভোগ করা', 'I enjoy music.', 'আমি গান উপভোগ করি।', 241),
    ('enough', null, 'pron., det., adv.', 'A1', 'যথেষ্ট', 'We have enough food.', 'আমাদের কাছে যথেষ্ট খাবার আছে।', 242),
    ('euro', null, 'n.', 'A1', 'ইউরো (মুদ্রা)', 'It costs twenty euros.', 'এর দাম বিশ ইউরো।', 243),
    ('even', null, 'adv., adj.', 'A1', 'এমনকি', 'Even a child knows this.', 'এমনকি একটি শিশুও এটা জানে।', 244),
    ('evening', null, 'n.', 'A1', 'সন্ধ্যা', 'Good evening, everyone.', 'সবাইকে শুভ সন্ধ্যা।', 245),
    ('event', null, 'n.', 'A1', 'ঘটনা; অনুষ্ঠান', 'The event starts at noon.', 'অনুষ্ঠানটি দুপুরে শুরু হয়।', 246),
    ('ever', null, 'adv.', 'A1', 'কখনও', 'Have you ever been to India?', 'তুমি কি কখনও ভারতে গিয়েছ?', 247),
    ('every', null, 'det.', 'A1', 'প্রতিটি; প্রত্যেক', 'I read every day.', 'আমি প্রতিদিন পড়ি।', 248),
    ('everybody', null, 'pron.', 'A1', 'সবাই', 'Everybody likes her.', 'সবাই তাকে পছন্দ করে।', 249),
    ('everyone', null, 'pron.', 'A1', 'সবাই; প্রত্যেকে', 'Everyone is here.', 'সবাই এখানে।', 250),
    ('everything', null, 'pron.', 'A1', 'সবকিছু', 'Everything is fine.', 'সবকিছু ঠিক আছে।', 251),
    ('exam', null, 'n.', 'A1', 'পরীক্ষা', 'I have an exam tomorrow.', 'আমার আগামীকাল একটি পরীক্ষা আছে।', 252),
    ('example', null, 'n.', 'A1', 'উদাহরণ', 'Give me an example.', 'আমাকে একটি উদাহরণ দাও।', 253),
    ('excited', null, 'adj.', 'A1', 'উত্তেজিত; রোমাঞ্চিত', 'The children are excited.', 'বাচ্চারা রোমাঞ্চিত।', 254),
    ('exciting', null, 'adj.', 'A1', 'রোমাঞ্চকর', 'It was an exciting game.', 'এটি একটি রোমাঞ্চকর খেলা ছিল।', 255),
    ('exercise', null, 'n., v.', 'A1', 'ব্যায়াম; অনুশীলন', 'I do exercise every morning.', 'আমি প্রতিদিন সকালে ব্যায়াম করি।', 256),
    ('expensive', null, 'adj.', 'A1', 'দামি; ব্যয়বহুল', 'This phone is expensive.', 'এই ফোনটি দামি।', 257),
    ('explain', null, 'v.', 'A1', 'ব্যাখ্যা করা; বোঝানো', 'Please explain this word.', 'দয়া করে এই শব্দটি বুঝিয়ে দাও।', 258),
    ('extra', null, 'adv., adj., n.', 'A1', 'অতিরিক্ত; বাড়তি', 'I need extra time.', 'আমার বাড়তি সময় দরকার।', 259),
    ('eye', null, 'n.', 'A1', 'চোখ', 'She has big eyes.', 'তার বড় বড় চোখ।', 260),
    ('face', null, 'n., v.', 'A1', 'মুখ; মুখমণ্ডল', 'Wash your face.', 'তোমার মুখ ধুয়ে নাও।', 261),
    ('fact', null, 'n.', 'A1', 'সত্য; ঘটনা', 'That is a well-known fact.', 'সেটি একটি সুপরিচিত সত্য।', 262),
    ('fall', null, 'n., v.', 'A1', 'পড়ে যাওয়া; পতন', 'Leaves fall in autumn.', 'শরৎকালে পাতা ঝরে পড়ে।', 263),
    ('false', null, 'adj.', 'A1', 'মিথ্যা; ভুল', 'This statement is false.', 'এই বক্তব্যটি ভুল।', 264),
    ('family', null, 'adj., n.', 'A1', 'পরিবার', 'I love my family.', 'আমি আমার পরিবারকে ভালোবাসি।', 265),
    ('famous', null, 'adj.', 'A1', 'বিখ্যাত', 'He is a famous singer.', 'সে একজন বিখ্যাত গায়ক।', 266),
    ('fantastic', null, 'adj.', 'A1', 'চমৎকার; দুর্দান্ত', 'The food was fantastic.', 'খাবারটা চমৎকার ছিল।', 267),
    ('far', null, 'adv., adj.', 'A1', 'দূরে', 'The school is not far.', 'স্কুলটি দূরে নয়।', 268),
    ('farm', null, 'n., v.', 'A1', 'খামার', 'They live on a farm.', 'তারা একটি খামারে থাকে।', 269),
    ('farmer', null, 'n.', 'A1', 'কৃষক', 'The farmer grows rice.', 'কৃষক ধান চাষ করে।', 270),
    ('fast', null, 'adv., adj.', 'A1', 'দ্রুত; তাড়াতাড়ি', 'He runs very fast.', 'সে খুব দ্রুত দৌড়ায়।', 271),
    ('fat', null, 'adj., n.', 'A1', 'মোটা; চর্বি', 'The cat is fat.', 'বিড়ালটি মোটা।', 272),
    ('father', null, 'n.', 'A1', 'বাবা; পিতা', 'My father works hard.', 'আমার বাবা কঠোর পরিশ্রম করেন।', 273),
    ('favorite', null, 'adj., n.', 'A1', 'প্রিয়; পছন্দের', 'Blue is my favorite color.', 'নীল আমার প্রিয় রঙ।', 274),
    ('February', null, 'n.', 'A1', 'ফেব্রুয়ারি (মাস)', 'February is a short month.', 'ফেব্রুয়ারি একটি ছোট মাস।', 275),
    ('feel', null, 'n., v.', 'A1', 'অনুভব করা', 'I feel happy today.', 'আমি আজ খুশি অনুভব করছি।', 276),
    ('feeling', null, 'n.', 'A1', 'অনুভূতি', 'It is a nice feeling.', 'এটি একটি সুন্দর অনুভূতি।', 277),
    ('festival', null, 'n.', 'A1', 'উৎসব; পার্বণ', 'Eid is a big festival.', 'ঈদ একটি বড় উৎসব।', 278),
    ('few', null, 'pron., det., adj.', 'A1', 'অল্প; কয়েকটি', 'I have a few friends.', 'আমার কয়েকজন বন্ধু আছে।', 279),
    ('fifteen', null, 'number', 'A1', 'পনেরো (১৫)', 'Wait for fifteen minutes.', 'পনেরো মিনিট অপেক্ষা করো।', 280),
    ('fifth', null, 'number', 'A1', 'পঞ্চম', 'This is my fifth visit.', 'এটি আমার পঞ্চম বার আসা।', 281),
    ('fifty', null, 'number', 'A1', 'পঞ্চাশ (৫০)', 'He is fifty years old.', 'তার বয়স পঞ্চাশ বছর।', 282),
    ('fill', null, 'v.', 'A1', 'পূর্ণ করা; ভরা', 'Fill the glass with water.', 'গ্লাসটি পানি দিয়ে ভরো।', 283),
    ('final', null, 'adj., n.', 'A1', 'চূড়ান্ত; শেষ', 'This is my final answer.', 'এটি আমার চূড়ান্ত উত্তর।', 284),
    ('find', null, 'v.', 'A1', 'খুঁজে পাওয়া', 'I cannot find my keys.', 'আমি আমার চাবি খুঁজে পাচ্ছি না।', 285),
    ('fine', null, 'adj.', 'A1', 'ভালো; সুন্দর', 'I am fine, thank you.', 'আমি ভালো আছি, ধন্যবাদ।', 286),
    ('finish', null, 'n., v.', 'A1', 'শেষ করা', 'Finish your homework.', 'তোমার বাড়ির কাজ শেষ করো।', 287),
    ('fire', null, 'n., v.', 'A1', 'আগুন', 'The fire is very hot.', 'আগুনটি খুব গরম।', 288),
    ('first', null, 'number, det., adv., n.', 'A1', 'প্রথম', 'She came first in the race.', 'সে দৌড়ে প্রথম হয়েছে।', 289),
    ('fish', null, 'n., v.', 'A1', 'মাছ', 'We eat fish and rice.', 'আমরা মাছ-ভাত খাই।', 290),
    ('five', null, 'number', 'A1', 'পাঁচ (৫)', 'I have five books.', 'আমার পাঁচটি বই আছে।', 291),
    ('flight', null, 'n.', 'A1', 'উড়ান; বিমানযাত্রা', 'My flight is at noon.', 'আমার ফ্লাইট দুপুরে।', 292),
    ('floor', null, 'n.', 'A1', 'মেঝে; তলা', 'The keys are on the floor.', 'চাবিগুলো মেঝেতে।', 293),
    ('flower', null, 'n.', 'A1', 'ফুল', 'This flower smells nice.', 'এই ফুলটির সুন্দর গন্ধ।', 294),
    ('fly', null, 'n., v.', 'A1', 'ওড়া; মাছি', 'Birds can fly.', 'পাখিরা উড়তে পারে।', 295),
    ('follow', null, 'v.', 'A1', 'অনুসরণ করা', 'Follow me, please.', 'দয়া করে আমাকে অনুসরণ করো।', 296),
    ('food', null, 'n.', 'A1', 'খাবার; খাদ্য', 'The food is ready.', 'খাবার তৈরি।', 297),
    ('foot', null, 'n.', 'A1', 'পা; পায়ের পাতা', 'My foot hurts.', 'আমার পায়ে ব্যথা।', 298),
    ('football', null, 'n.', 'A1', 'ফুটবল', 'They play football together.', 'তারা একসাথে ফুটবল খেলে।', 299),
    ('for', null, 'prep.', 'A1', 'জন্য', 'This gift is for you.', 'এই উপহারটি তোমার জন্য।', 300),
    ('forget', null, 'v.', 'A1', 'ভুলে যাওয়া', 'Do not forget your keys.', 'তোমার চাবি ভুলে যেয়ো না।', 301),
    ('form', null, 'n., v.', 'A1', 'ফরম; রূপ; গঠন করা', 'Please fill out this form.', 'দয়া করে এই ফরমটি পূরণ করুন।', 302),
    ('forty', null, 'number', 'A1', 'চল্লিশ (৪০)', 'There are forty students.', 'চল্লিশ জন ছাত্র আছে।', 303),
    ('four', null, 'number', 'A1', 'চার (৪)', 'A table has four legs.', 'একটি টেবিলের চারটি পা থাকে।', 304),
    ('fourteen', null, 'number', 'A1', 'চৌদ্দ (১৪)', 'She is fourteen years old.', 'তার বয়স চৌদ্দ বছর।', 305),
    ('fourth', null, 'number', 'A1', 'চতুর্থ', 'This is the fourth chapter.', 'এটি চতুর্থ অধ্যায়।', 306),
    ('free', null, 'adv., adj., v.', 'A1', 'মুক্ত; বিনামূল্যে', 'Entry is free for children.', 'শিশুদের জন্য প্রবেশ বিনামূল্যে।', 307),
    ('Friday', null, 'n.', 'A1', 'শুক্রবার', 'We have a holiday on Friday.', 'শুক্রবারে আমাদের ছুটি।', 308),
    ('friend', null, 'n.', 'A1', 'বন্ধু', 'He is my best friend.', 'সে আমার সবচেয়ে ভালো বন্ধু।', 309),
    ('friendly', null, 'adj.', 'A1', 'বন্ধুত্বপূর্ণ; মিশুক', 'Our neighbors are friendly.', 'আমাদের প্রতিবেশীরা মিশুক।', 310),
    ('from', null, 'prep.', 'A1', 'থেকে; হতে', 'I am from Bangladesh.', 'আমি বাংলাদেশ থেকে এসেছি।', 311),
    ('front', null, 'adj., n.', 'A1', 'সামনের অংশ; সম্মুখ', 'Sit in the front row.', 'সামনের সারিতে বসো।', 312),
    ('fruit', null, 'n.', 'A1', 'ফল', 'Eat fresh fruit every day.', 'প্রতিদিন তাজা ফল খাও।', 313),
    ('full', null, 'adj.', 'A1', 'পূর্ণ; ভরা', 'The glass is full.', 'গ্লাসটি ভরা।', 314),
    ('fun', null, 'adj., n.', 'A1', 'মজা; আনন্দ', 'We had a lot of fun.', 'আমরা অনেক মজা করেছি।', 315),
    ('funny', null, 'adj.', 'A1', 'মজার; হাস্যকর', 'That is a funny story.', 'এটি একটি মজার গল্প।', 316),
    ('future', null, 'adj., n.', 'A1', 'ভবিষ্যৎ', 'Think about your future.', 'তোমার ভবিষ্যৎ নিয়ে ভাবো।', 317),
    ('game', null, 'n.', 'A1', 'খেলা', 'Let''s play a game.', 'চলো একটা খেলা খেলি।', 318),
    ('garden', null, 'n.', 'A1', 'বাগান', 'There are roses in the garden.', 'বাগানে গোলাপ ফুল আছে।', 319),
    ('geography', null, 'n.', 'A1', 'ভূগোল', 'I like studying geography.', 'আমি ভূগোল পড়তে পছন্দ করি।', 320),
    ('get', null, 'v.', 'A1', 'পাওয়া; হওয়া', 'I get up at six.', 'আমি ছয়টায় ঘুম থেকে উঠি।', 321),
    ('girl', null, 'n.', 'A1', 'মেয়ে', 'The girl is reading a book.', 'মেয়েটি একটি বই পড়ছে।', 322),
    ('girlfriend', null, 'n.', 'A1', 'প্রেমিকা; গার্লফ্রেন্ড', 'His girlfriend is a doctor.', 'তার গার্লফ্রেন্ড একজন ডাক্তার।', 323),
    ('give', null, 'v.', 'A1', 'দেওয়া', 'Give me the book, please.', 'দয়া করে আমাকে বইটি দাও।', 324),
    ('glass', null, 'n.', 'A1', 'কাচ; গ্লাস', 'I broke a glass.', 'আমি একটি গ্লাস ভেঙে ফেলেছি।', 325),
    ('go', null, 'n., v.', 'A1', 'যাওয়া', 'I go to school by bus.', 'আমি বাসে করে স্কুলে যাই।', 326),
    ('good', null, 'adj., n.', 'A1', 'ভালো', 'This is a good idea.', 'এটি একটি ভালো ধারণা।', 327),
    ('goodbye', null, 'exclam., n.', 'A1', 'বিদায়', 'Goodbye, see you soon.', 'বিদায়, শীঘ্রই দেখা হবে।', 328),
    ('grandfather', null, 'n.', 'A1', 'দাদা; নানা', 'My grandfather tells stories.', 'আমার দাদা গল্প বলেন।', 329),
    ('grandmother', null, 'n.', 'A1', 'দাদি; নানি', 'My grandmother cooks well.', 'আমার দাদি ভালো রান্না করেন।', 330),
    ('grandparent', null, 'n.', 'A1', 'দাদা-দাদি; নানা-নানি', 'My grandparents live in a village.', 'আমার দাদা-দাদি গ্রামে থাকেন।', 331),
    ('gray', null, 'adj., n.', 'A1', 'ধূসর; ছাই রঙ', 'The sky is gray today.', 'আজ আকাশ ধূসর।', 332),
    ('great', null, 'adj.', 'A1', 'দুর্দান্ত; মহান', 'You did a great job.', 'তুমি দুর্দান্ত কাজ করেছ।', 333),
    ('green', null, 'adj., n.', 'A1', 'সবুজ', 'The grass is green.', 'ঘাস সবুজ।', 334),
    ('group', null, 'n.', 'A1', 'দল; গোষ্ঠী', 'We work in a group.', 'আমরা দলবদ্ধভাবে কাজ করি।', 335),
    ('grow', null, 'v.', 'A1', 'বৃদ্ধি পাওয়া; জন্মানো', 'Plants grow in the sun.', 'গাছপালা রোদে বেড়ে ওঠে।', 336),
    ('guess', null, 'n., v.', 'A1', 'অনুমান করা', 'Guess my age.', 'আমার বয়স অনুমান করো।', 337),
    ('guitar', null, 'n.', 'A1', 'গিটার', 'He plays the guitar.', 'সে গিটার বাজায়।', 338),
    ('gym', null, 'n.', 'A1', 'ব্যায়ামাগার; জিম', 'I go to the gym on Mondays.', 'আমি সোমবারে জিমে যাই।', 339),
    ('hair', null, 'n.', 'A1', 'চুল', 'She has long hair.', 'তার লম্বা চুল।', 340),
    ('half', null, 'pron., det., adv., n.', 'A1', 'অর্ধেক', 'I ate half of the cake.', 'আমি কেকের অর্ধেক খেয়েছি।', 341),
    ('hand', null, 'n., v.', 'A1', 'হাত', 'Raise your hand.', 'তোমার হাত তোলো।', 342),
    ('happen', null, 'v.', 'A1', 'ঘটা; হওয়া', 'What happened here?', 'এখানে কী ঘটেছে?', 343),
    ('happy', null, 'adj.', 'A1', 'খুশি; সুখী', 'I am very happy today.', 'আমি আজ খুব খুশি।', 344),
    ('hard', null, 'adv., adj.', 'A1', 'কঠিন; শক্ত; কঠোর', 'He works very hard.', 'সে খুব কঠোর পরিশ্রম করে।', 345),
    ('hat', null, 'n.', 'A1', 'টুপি', 'He is wearing a black hat.', 'সে একটি কালো টুপি পরেছে।', 346),
    ('hate', null, 'n., v.', 'A1', 'ঘৃণা করা; অপছন্দ করা', 'I hate lies.', 'আমি মিথ্যা ঘৃণা করি।', 347),
    ('have', null, 'auxiliary v., v.', 'A1', 'থাকা; আছে; খাওয়া', 'I have two brothers.', 'আমার দুই ভাই আছে।', 348),
    ('have to', null, 'modal v., v.', 'A1', 'করতে হওয়া (বাধ্যবাধকতা)', 'I have to go now.', 'আমাকে এখন যেতে হবে।', 349),
    ('he', null, 'pron.', 'A1', 'সে (পুরুষ); তিনি', 'He is my teacher.', 'তিনি আমার শিক্ষক।', 350),
    ('head', null, 'n., v.', 'A1', 'মাথা', 'My head hurts.', 'আমার মাথা ব্যথা করছে।', 351),
    ('health', null, 'n.', 'A1', 'স্বাস্থ্য', 'Good health is important.', 'সুস্বাস্থ্য গুরুত্বপূর্ণ।', 352),
    ('healthy', null, 'adj.', 'A1', 'স্বাস্থ্যকর; সুস্থ', 'Fruit is a healthy food.', 'ফল একটি স্বাস্থ্যকর খাবার।', 353),
    ('hear', null, 'v.', 'A1', 'শোনা', 'I can hear music.', 'আমি গান শুনতে পাচ্ছি।', 354),
    ('hello', null, 'exclam., n.', 'A1', 'হ্যালো; নমস্কার', 'Hello, how are you?', 'হ্যালো, কেমন আছো?', 355),
    ('help', null, 'n., v.', 'A1', 'সাহায্য করা', 'Can you help me?', 'তুমি কি আমাকে সাহায্য করতে পারবে?', 356),
    ('her', null, 'pron., det.', 'A1', 'তার; তাকে (স্ত্রী)', 'This is her book.', 'এটি তার বই।', 357),
    ('here', null, 'adv.', 'A1', 'এখানে', 'Come here, please.', 'দয়া করে এখানে এসো।', 358),
    ('hey', null, 'exclam.', 'A1', 'এই; আরে (ডাক)', 'Hey, wait for me!', 'আরে, আমার জন্য অপেক্ষা করো!', 359),
    ('hi', null, 'exclam.', 'A1', 'হাই; সালাম', 'Hi, nice to meet you.', 'হাই, তোমার সাথে পরিচিত হয়ে ভালো লাগল।', 360),
    ('high', null, 'adv., adj., n.', 'A1', 'উঁচু; উচ্চ', 'The wall is very high.', 'দেয়ালটি খুব উঁচু।', 361),
    ('him', null, 'pron.', 'A1', 'তাকে; তাঁকে (পুরুষ)', 'I gave him a gift.', 'আমি তাকে একটি উপহার দিয়েছি।', 362),
    ('his', null, 'pron., det.', 'A1', 'তার; তাঁর (পুরুষ)', 'This is his car.', 'এটি তার গাড়ি।', 363),
    ('history', null, 'n.', 'A1', 'ইতিহাস', 'I like reading history.', 'আমি ইতিহাস পড়তে পছন্দ করি।', 364),
    ('hobby', null, 'n.', 'A1', 'শখ', 'My hobby is painting.', 'আমার শখ ছবি আঁকা।', 365),
    ('home', null, 'adv., adj., n.', 'A1', 'বাড়ি; ঘর', 'I am going home.', 'আমি বাড়ি যাচ্ছি।', 366),
    ('homework', null, 'n.', 'A1', 'বাড়ির কাজ; হোমওয়ার্ক', 'Do your homework now.', 'এখনই তোমার বাড়ির কাজ করো।', 367),
    ('hope', null, 'n., v.', 'A1', 'আশা করা', 'I hope you feel better.', 'আশা করি তুমি ভালো বোধ করবে।', 368),
    ('horse', null, 'n.', 'A1', 'ঘোড়া', 'The horse runs fast.', 'ঘোড়াটি দ্রুত দৌড়ায়।', 369),
    ('hospital', null, 'n.', 'A1', 'হাসপাতাল', 'She works in a hospital.', 'সে একটি হাসপাতালে কাজ করে।', 370),
    ('hot', null, 'adj.', 'A1', 'গরম; উষ্ণ', 'The tea is very hot.', 'চা টা খুব গরম।', 371),
    ('hotel', null, 'n.', 'A1', 'হোটেল', 'We stayed in a hotel.', 'আমরা একটি হোটেলে ছিলাম।', 372),
    ('hour', null, 'n.', 'A1', 'ঘণ্টা', 'I waited for an hour.', 'আমি এক ঘণ্টা অপেক্ষা করেছি।', 373),
    ('house', null, 'n., v.', 'A1', 'বাড়ি; গৃহ', 'They have a big house.', 'তাদের একটি বড় বাড়ি আছে।', 374),
    ('how', null, 'adv.', 'A1', 'কীভাবে; কেমন', 'How are you?', 'তুমি কেমন আছো?', 375),
    ('however', null, 'adv.', 'A1', 'তবে; যাইহোক', 'It is small; however, it is nice.', 'এটি ছোট; তবে এটি সুন্দর।', 376),
    ('hundred', null, 'number', 'A1', 'একশত (১০০)', 'There are a hundred pages.', 'একশত পৃষ্ঠা আছে।', 377),
    ('hungry', null, 'adj.', 'A1', 'ক্ষুধার্ত', 'I am very hungry.', 'আমি খুব ক্ষুধার্ত।', 378),
    ('husband', null, 'n.', 'A1', 'স্বামী', 'Her husband is a teacher.', 'তার স্বামী একজন শিক্ষক।', 379),
    ('I', null, 'pron.', 'A1', 'আমি', 'I am a student.', 'আমি একজন ছাত্র।', 380),
    ('ice', null, 'n.', 'A1', 'বরফ', 'There is ice in my drink.', 'আমার পানীয়তে বরফ আছে।', 381),
    ('ice cream', null, 'n.', 'A1', 'আইসক্রিম', 'The children love ice cream.', 'বাচ্চারা আইসক্রিম খুব ভালোবাসে।', 382),
    ('idea', null, 'n.', 'A1', 'ধারণা; ভাবনা', 'That is a great idea.', 'এটি একটি দুর্দান্ত ধারণা।', 383),
    ('if', null, 'conj.', 'A1', 'যদি', 'Call me if you need help.', 'সাহায্য লাগলে আমাকে ফোন করো।', 384),
    ('imagine', null, 'v.', 'A1', 'কল্পনা করা', 'Imagine a quiet beach.', 'একটি নিরিবিলি সৈকত কল্পনা করো।', 385),
    ('important', null, 'adj.', 'A1', 'গুরুত্বপূর্ণ', 'This is an important meeting.', 'এটি একটি গুরুত্বপূর্ণ বৈঠক।', 386),
    ('improve', null, 'v.', 'A1', 'উন্নতি করা; উন্নত করা', 'I want to improve my English.', 'আমি আমার ইংরেজি উন্নত করতে চাই।', 387),
    ('in', null, 'prep., adv.', 'A1', 'ভিতরে; -এ', 'The keys are in the bag.', 'চাবিগুলো ব্যাগের ভিতরে।', 388),
    ('include', null, 'v.', 'A1', 'অন্তর্ভুক্ত করা', 'The price includes breakfast.', 'দামের মধ্যে সকালের নাস্তা অন্তর্ভুক্ত।', 389),
    ('information', null, 'n.', 'A1', 'তথ্য', 'I need more information.', 'আমার আরও তথ্য দরকার।', 390),
    ('interest', null, 'n., v.', 'A1', 'আগ্রহ; সুদ', 'She has an interest in music.', 'সঙ্গীতে তার আগ্রহ আছে।', 391),
    ('interested', null, 'adj.', 'A1', 'আগ্রহী', 'I am interested in art.', 'আমি শিল্পে আগ্রহী।', 392),
    ('interesting', null, 'adj.', 'A1', 'আকর্ষণীয়; মজার', 'This book is interesting.', 'এই বইটি আকর্ষণীয়।', 393),
    ('internet', null, 'n.', 'A1', 'ইন্টারনেট', 'I use the internet every day.', 'আমি প্রতিদিন ইন্টারনেট ব্যবহার করি।', 394),
    ('interview', null, 'n., v.', 'A1', 'সাক্ষাৎকার', 'He has a job interview today.', 'তার আজ একটি চাকরির সাক্ষাৎকার আছে।', 395),
    ('into', null, 'prep.', 'A1', 'ভিতরে; মধ্যে', 'She went into the room.', 'সে ঘরের ভিতরে গেল।', 396),
    ('introduce', null, 'v.', 'A1', 'পরিচয় করিয়ে দেওয়া', 'Let me introduce my friend.', 'আমার বন্ধুর সাথে পরিচয় করিয়ে দিই।', 397),
    ('island', null, 'n.', 'A1', 'দ্বীপ', 'They live on a small island.', 'তারা একটি ছোট দ্বীপে থাকে।', 398),
    ('it', null, 'pron.', 'A1', 'এটি; এটা; ইহা', 'It is raining.', 'বৃষ্টি হচ্ছে।', 399),
    ('its', null, 'det.', 'A1', 'এর; তার (প্রাণহীন)', 'The dog wags its tail.', 'কুকুরটি তার লেজ নাড়ায়।', 400),
    ('jacket', null, 'n.', 'A1', 'জ্যাকেট', 'Put on your jacket.', 'তোমার জ্যাকেটটি পরো।', 401),
    ('January', null, 'n.', 'A1', 'জানুয়ারি (মাস)', 'The year starts in January.', 'বছর জানুয়ারিতে শুরু হয়।', 402),
    ('jeans', null, 'n.', 'A1', 'জিন্স (প্যান্ট)', 'He is wearing blue jeans.', 'সে নীল জিন্স পরেছে।', 403),
    ('job', null, 'n.', 'A1', 'চাকরি; কাজ', 'She has a new job.', 'তার একটি নতুন চাকরি হয়েছে।', 404),
    ('join', null, 'v.', 'A1', 'যোগ দেওয়া', 'Come and join us.', 'এসো, আমাদের সাথে যোগ দাও।', 405),
    ('juice', null, 'n.', 'A1', 'রস; জুস', 'I drink orange juice.', 'আমি কমলার রস পান করি।', 406),
    ('July', null, 'n.', 'A1', 'জুলাই (মাস)', 'It rains a lot in July.', 'জুলাই মাসে অনেক বৃষ্টি হয়।', 407),
    ('June', null, 'n.', 'A1', 'জুন (মাস)', 'School closes in June.', 'জুন মাসে স্কুল বন্ধ হয়।', 408),
    ('just', null, 'adv.', 'A1', 'শুধু; এইমাত্র', 'I just arrived home.', 'আমি এইমাত্র বাড়ি পৌঁছেছি।', 409),
    ('keep', null, 'v.', 'A1', 'রাখা; ধরে রাখা', 'Keep the door open.', 'দরজাটি খোলা রাখো।', 410),
    ('key', null, 'adj., n., v.', 'A1', 'চাবি', 'I lost my house key.', 'আমি আমার বাড়ির চাবি হারিয়ে ফেলেছি।', 411),
    ('kind', 'type', 'n.', 'A1', 'ধরন; প্রকার', 'What kind of music do you like?', 'তুমি কোন ধরনের গান পছন্দ করো?', 412),
    ('kitchen', null, 'n.', 'A1', 'রান্নাঘর', 'Mom is in the kitchen.', 'মা রান্নাঘরে আছেন।', 413),
    ('know', null, 'v.', 'A1', 'জানা; চেনা', 'I know the answer.', 'আমি উত্তরটি জানি।', 414),
    ('land', null, 'n., v.', 'A1', 'জমি; ভূমি; অবতরণ করা', 'The plane will land soon.', 'বিমানটি শীঘ্রই অবতরণ করবে।', 415),
    ('language', null, 'n.', 'A1', 'ভাষা', 'Bengali is my first language.', 'বাংলা আমার প্রথম ভাষা।', 416),
    ('large', null, 'adj.', 'A1', 'বড়; বৃহৎ', 'They have a large family.', 'তাদের একটি বড় পরিবার।', 417),
    ('last', 'final', 'det., adv., n.', 'A1', 'শেষ; সর্বশেষ', 'This is the last page.', 'এটি শেষ পৃষ্ঠা।', 418),
    ('late', null, 'adv., adj.', 'A1', 'দেরি; বিলম্বিত', 'Do not be late.', 'দেরি করো না।', 419),
    ('later', null, 'adv., adj.', 'A1', 'পরে', 'I will call you later.', 'আমি তোমাকে পরে ফোন করব।', 420),
    ('laugh', null, 'n., v.', 'A1', 'হাসা; হাসি', 'The joke made me laugh.', 'রসিকতাটি আমাকে হাসাল।', 421),
    ('learn', null, 'v.', 'A1', 'শেখা', 'I want to learn English.', 'আমি ইংরেজি শিখতে চাই।', 422),
    ('leave', null, 'n., v.', 'A1', 'চলে যাওয়া; ছেড়ে যাওয়া', 'We leave at nine.', 'আমরা নয়টায় রওনা হই।', 423),
    ('left', null, 'adv., adj., n.', 'A1', 'বাম; বাঁ দিক', 'Turn left at the corner.', 'কোণে গিয়ে বাঁ দিকে ঘুরো।', 424),
    ('leg', null, 'n.', 'A1', 'পা; ঠ্যাং', 'He broke his leg.', 'সে তার পা ভেঙে ফেলেছে।', 425),
    ('lesson', null, 'n.', 'A1', 'পাঠ; শিক্ষা', 'Today''s lesson is easy.', 'আজকের পাঠটি সহজ।', 426),
    ('let', null, 'v.', 'A1', 'অনুমতি দেওয়া; দেওয়া', 'Let me help you.', 'আমাকে তোমাকে সাহায্য করতে দাও।', 427),
    ('letter', null, 'n.', 'A1', 'চিঠি; অক্ষর', 'I wrote a letter to my friend.', 'আমি আমার বন্ধুকে একটি চিঠি লিখেছি।', 428),
    ('library', null, 'n.', 'A1', 'গ্রন্থাগার; লাইব্রেরি', 'The library is very quiet.', 'লাইব্রেরিটি খুব শান্ত।', 429),
    ('lie', null, 'v.', 'A1', 'শুয়ে থাকা', 'I like to lie on the grass.', 'আমি ঘাসের উপর শুয়ে থাকতে পছন্দ করি।', 430),
    ('life', null, 'n.', 'A1', 'জীবন', 'Life is beautiful.', 'জীবন সুন্দর।', 431),
    ('light', 'from the sun/a lamp', 'n., adj., v.', 'A1', 'আলো', 'Please turn on the light.', 'দয়া করে আলোটি জ্বালাও।', 432),
    ('like', 'find sb/sth pleasant', 'v.', 'A1', 'পছন্দ করা', 'I like tea.', 'আমি চা পছন্দ করি।', 433),
    ('like', 'similar', 'prep.', 'A1', 'মতো; সদৃশ', 'She sings like a bird.', 'সে পাখির মতো গান গায়।', 434),
    ('line', null, 'n., v.', 'A1', 'রেখা; লাইন; সারি', 'Draw a straight line.', 'একটি সোজা রেখা আঁকো।', 435),
    ('lion', null, 'n.', 'A1', 'সিংহ', 'The lion is a strong animal.', 'সিংহ একটি শক্তিশালী প্রাণী।', 436),
    ('lip', null, 'n.', 'A1', 'ঠোঁট', 'Her lips are dry.', 'তার ঠোঁট শুকনো।', 437),
    ('list', null, 'n., v.', 'A1', 'তালিকা', 'Make a list of your books.', 'তোমার বইয়ের একটি তালিকা বানাও।', 438),
    ('listen', null, 'v.', 'A1', 'শোনা; মনোযোগ দিয়ে শোনা', 'Listen to the teacher.', 'শিক্ষকের কথা শোনো।', 439),
    ('little', null, 'pron., det., adv., adj.', 'A1', 'ছোট; অল্প', 'I have a little money.', 'আমার কাছে অল্প টাকা আছে।', 440),
    ('live', null, 'v.', 'A1', 'বাস করা; বেঁচে থাকা', 'I live in Dhaka.', 'আমি ঢাকায় থাকি।', 441),
    ('local', null, 'adj., n.', 'A1', 'স্থানীয়', 'We shop at the local market.', 'আমরা স্থানীয় বাজারে কেনাকাটা করি।', 442),
    ('long', null, 'adv., adj.', 'A1', 'লম্বা; দীর্ঘ', 'It is a long river.', 'এটি একটি দীর্ঘ নদী।', 443),
    ('look', null, 'n., v.', 'A1', 'দেখা; তাকানো', 'Look at the sky.', 'আকাশের দিকে তাকাও।', 444),
    ('lose', null, 'v.', 'A1', 'হারানো; হেরে যাওয়া', 'Do not lose your ticket.', 'তোমার টিকিটটি হারিয়ো না।', 445),
    ('lot', null, 'pron., det., adv.', 'A1', 'অনেক; প্রচুর', 'I have a lot of work.', 'আমার অনেক কাজ আছে।', 446),
    ('love', null, 'n., v.', 'A1', 'ভালোবাসা; ভালোবাসা', 'I love my country.', 'আমি আমার দেশকে ভালোবাসি।', 447),
    ('lunch', null, 'n.', 'A1', 'দুপুরের খাবার', 'We have lunch at one.', 'আমরা একটায় দুপুরের খাবার খাই।', 448),
    ('machine', null, 'n.', 'A1', 'যন্ত্র; মেশিন', 'This machine is very old.', 'এই মেশিনটি খুব পুরনো।', 449),
    ('magazine', null, 'n.', 'A1', 'পত্রিকা; ম্যাগাজিন', 'She reads a fashion magazine.', 'সে একটি ফ্যাশন পত্রিকা পড়ে।', 450),
    ('main', null, 'adj.', 'A1', 'প্রধান; মুখ্য', 'This is the main road.', 'এটি প্রধান সড়ক।', 451),
    ('make', null, 'n., v.', 'A1', 'তৈরি করা; বানানো', 'Can you make tea?', 'তুমি কি চা বানাতে পারো?', 452),
    ('mall', null, 'n.', 'A1', 'শপিং মল', 'We went shopping at the mall.', 'আমরা মলে কেনাকাটা করতে গিয়েছিলাম।', 453),
    ('man', null, 'n.', 'A1', 'পুরুষ; লোক', 'That man is my uncle.', 'ওই লোকটি আমার চাচা।', 454),
    ('many', null, 'pron., det.', 'A1', 'অনেক; বহু', 'There are many people here.', 'এখানে অনেক মানুষ আছে।', 455),
    ('map', null, 'n., v.', 'A1', 'মানচিত্র; ম্যাপ', 'Look at the map.', 'মানচিত্রটি দেখো।', 456),
    ('March', null, 'n.', 'A1', 'মার্চ (মাস)', 'Spring begins in March.', 'মার্চ মাসে বসন্ত শুরু হয়।', 457),
    ('market', null, 'n., v.', 'A1', 'বাজার', 'I buy fish at the market.', 'আমি বাজারে মাছ কিনি।', 458),
    ('married', null, 'adj.', 'A1', 'বিবাহিত', 'My sister is married.', 'আমার বোন বিবাহিত।', 459),
    ('May', null, 'n.', 'A1', 'মে (মাস)', 'It is warm in May.', 'মে মাসে গরম থাকে।', 460),
    ('maybe', null, 'adv.', 'A1', 'হয়তো; সম্ভবত', 'Maybe it will rain today.', 'হয়তো আজ বৃষ্টি হবে।', 461),
    ('me', null, 'pron.', 'A1', 'আমাকে; আমায়', 'Please give it to me.', 'দয়া করে এটি আমাকে দাও।', 462),
    ('meal', null, 'n.', 'A1', 'খাবার (এক বেলার)', 'This is a healthy meal.', 'এটি একটি স্বাস্থ্যকর খাবার।', 463),
    ('mean', null, 'v.', 'A1', 'অর্থ বোঝানো; মানে হওয়া', 'What does this word mean?', 'এই শব্দটির অর্থ কী?', 464),
    ('meaning', null, 'n.', 'A1', 'অর্থ; মানে', 'I know the meaning of the word.', 'আমি শব্দটির অর্থ জানি।', 465),
    ('meat', null, 'n.', 'A1', 'মাংস', 'He does not eat meat.', 'সে মাংস খায় না।', 466),
    ('meet', null, 'v.', 'A1', 'সাক্ষাৎ করা; দেখা করা', 'Let''s meet at the cafe.', 'চলো ক্যাফেতে দেখা করি।', 467),
    ('meeting', null, 'n.', 'A1', 'সভা; বৈঠক', 'The meeting is at ten.', 'সভাটি দশটায়।', 468),
    ('member', null, 'n.', 'A1', 'সদস্য', 'She is a club member.', 'সে একজন ক্লাব সদস্য।', 469),
    ('menu', null, 'n.', 'A1', 'মেনু; খাবারের তালিকা', 'Can I see the menu?', 'আমি কি মেনুটি দেখতে পারি?', 470),
    ('message', null, 'n.', 'A1', 'বার্তা; মেসেজ', 'I sent her a message.', 'আমি তাকে একটি বার্তা পাঠিয়েছি।', 471),
    ('meter', null, 'n.', 'A1', 'মিটার', 'The room is five meters long.', 'ঘরটি পাঁচ মিটার লম্বা।', 472),
    ('midnight', null, 'n.', 'A1', 'মধ্যরাত', 'The train leaves at midnight.', 'ট্রেনটি মধ্যরাতে ছাড়ে।', 473),
    ('mile', null, 'n.', 'A1', 'মাইল', 'We walked two miles.', 'আমরা দুই মাইল হেঁটেছি।', 474),
    ('milk', null, 'n.', 'A1', 'দুধ', 'I drink milk every day.', 'আমি প্রতিদিন দুধ পান করি।', 475),
    ('million', null, 'number', 'A1', 'দশ লক্ষ; মিলিয়ন', 'The city has two million people.', 'শহরটিতে বিশ লক্ষ মানুষ আছে।', 476),
    ('minute', null, 'n.', 'A1', 'মিনিট', 'Wait a minute, please.', 'দয়া করে এক মিনিট অপেক্ষা করো।', 477),
    ('miss', null, 'v.', 'A1', 'মিস করা; অভাব বোধ করা', 'I miss my family.', 'আমি আমার পরিবারকে মিস করি।', 478),
    ('mistake', null, 'n., v.', 'A1', 'ভুল', 'Everyone makes mistakes.', 'সবাই ভুল করে।', 479),
    ('model', null, 'n., v.', 'A1', 'মডেল; নমুনা', 'This is a new car model.', 'এটি একটি নতুন গাড়ির মডেল।', 480),
    ('modern', null, 'adj.', 'A1', 'আধুনিক', 'They live in a modern house.', 'তারা একটি আধুনিক বাড়িতে থাকে।', 481),
    ('mom', null, 'n.', 'A1', 'মা', 'My mom is cooking.', 'আমার মা রান্না করছেন।', 482),
    ('moment', null, 'n.', 'A1', 'মুহূর্ত; ক্ষণ', 'Please wait a moment.', 'দয়া করে এক মুহূর্ত অপেক্ষা করো।', 483),
    ('Monday', null, 'n.', 'A1', 'সোমবার', 'School starts on Monday.', 'সোমবারে স্কুল শুরু হয়।', 484),
    ('money', null, 'n.', 'A1', 'টাকা; অর্থ', 'I do not have much money.', 'আমার কাছে বেশি টাকা নেই।', 485),
    ('month', null, 'n.', 'A1', 'মাস', 'There are twelve months in a year.', 'এক বছরে বারো মাস থাকে।', 486),
    ('more', null, 'pron., det., adv.', 'A1', 'আরও; বেশি', 'I want more rice.', 'আমি আরও ভাত চাই।', 487),
    ('morning', null, 'n.', 'A1', 'সকাল', 'Good morning, everyone.', 'সবাইকে শুভ সকাল।', 488),
    ('most', null, 'pron., det., adv.', 'A1', 'অধিকাংশ; সবচেয়ে বেশি', 'Most students passed the exam.', 'অধিকাংশ ছাত্র পরীক্ষায় পাস করেছে।', 489),
    ('mother', null, 'n.', 'A1', 'মা; জননী', 'My mother is very kind.', 'আমার মা খুব দয়ালু।', 490),
    ('mountain', null, 'n.', 'A1', 'পাহাড়; পর্বত', 'The mountain is very tall.', 'পর্বতটি খুব উঁচু।', 491),
    ('mouse', null, 'n.', 'A1', 'ইঁদুর; মাউস', 'A mouse ran across the floor.', 'একটি ইঁদুর মেঝে দিয়ে দৌড়ে গেল।', 492),
    ('mouth', null, 'n.', 'A1', 'মুখ; মুখগহ্বর', 'Open your mouth.', 'তোমার মুখ খোলো।', 493),
    ('move', null, 'n., v.', 'A1', 'নড়া; সরানো; স্থানান্তর', 'Please move your car.', 'দয়া করে তোমার গাড়ি সরাও।', 494),
    ('movie', null, 'n.', 'A1', 'সিনেমা; চলচ্চিত্র', 'Let''s watch a movie.', 'চলো একটা সিনেমা দেখি।', 495),
    ('much', null, 'pron., det., adv.', 'A1', 'অনেক; বেশি', 'How much is this?', 'এটার দাম কত?', 496),
    ('museum', null, 'n.', 'A1', 'জাদুঘর', 'We visited a museum.', 'আমরা একটি জাদুঘর দেখতে গিয়েছিলাম।', 497),
    ('music', null, 'n.', 'A1', 'সঙ্গীত; গান', 'I love listening to music.', 'আমি গান শুনতে ভালোবাসি।', 498),
    ('must', null, 'modal v., v.', 'A1', 'অবশ্যই করতে হবে', 'You must wear a seatbelt.', 'তোমাকে অবশ্যই সিটবেল্ট পরতে হবে।', 499),
    ('my', null, 'det.', 'A1', 'আমার', 'This is my book.', 'এটি আমার বই।', 500),
    ('name', null, 'n., v.', 'A1', 'নাম', 'What is your name?', 'তোমার নাম কী?', 501),
    ('natural', null, 'adj.', 'A1', 'প্রাকৃতিক; স্বাভাবিক', 'This is a natural lake.', 'এটি একটি প্রাকৃতিক হ্রদ।', 502),
    ('near', null, 'prep., adv., adj.', 'A1', 'কাছে; নিকটে', 'The shop is near my house.', 'দোকানটি আমার বাড়ির কাছে।', 503),
    ('need', null, 'modal v., n., v.', 'A1', 'প্রয়োজন হওয়া; দরকার', 'I need some help.', 'আমার কিছু সাহায্য দরকার।', 504),
    ('negative', null, 'adj., n.', 'A1', 'নেতিবাচক; ঋণাত্মক', 'Do not be so negative.', 'এত নেতিবাচক হয়ো না।', 505),
    ('neighbor', null, 'n.', 'A1', 'প্রতিবেশী', 'My neighbor is very helpful.', 'আমার প্রতিবেশী খুব সাহায্যপরায়ণ।', 506),
    ('neighborhood', null, 'n.', 'A1', 'পাড়া; আশপাশ', 'This is a quiet neighborhood.', 'এটি একটি শান্ত পাড়া।', 507),
    ('never', null, 'adv.', 'A1', 'কখনও না', 'I never drink coffee.', 'আমি কখনও কফি পান করি না।', 508),
    ('new', null, 'adj.', 'A1', 'নতুন', 'I bought a new phone.', 'আমি একটি নতুন ফোন কিনেছি।', 509),
    ('news', null, 'n.', 'A1', 'খবর; সংবাদ', 'I watch the news at night.', 'আমি রাতে খবর দেখি।', 510),
    ('newspaper', null, 'n.', 'A1', 'সংবাদপত্র; খবরের কাগজ', 'He reads the newspaper daily.', 'সে প্রতিদিন খবরের কাগজ পড়ে।', 511),
    ('next', null, 'adv., adj., n.', 'A1', 'পরবর্তী; পরের', 'See you next week.', 'আগামী সপ্তাহে দেখা হবে।', 512),
    ('next to', null, 'prep.', 'A1', 'পাশে; নিকটে', 'The bank is next to the school.', 'ব্যাংকটি স্কুলের পাশে।', 513),
    ('nice', null, 'adj.', 'A1', 'চমৎকার; ভালো', 'Have a nice day.', 'শুভ দিন কাটুক।', 514),
    ('night', null, 'n.', 'A1', 'রাত', 'Good night, sleep well.', 'শুভ রাত্রি, ভালো করে ঘুমাও।', 515),
    ('nine', null, 'number', 'A1', 'নয় (৯)', 'There are nine players.', 'নয় জন খেলোয়াড় আছে।', 516),
    ('nineteen', null, 'number', 'A1', 'ঊনিশ (১৯)', 'She is nineteen years old.', 'তার বয়স ঊনিশ বছর।', 517),
    ('ninety', null, 'number', 'A1', 'নব্বই (৯০)', 'My great-grandmother is ninety.', 'আমার বড়-দাদির বয়স নব্বই।', 518),
    ('no', null, 'exclam., det.', 'A1', 'না; কোনো নয়', 'No, thank you.', 'না, ধন্যবাদ।', 519),
    ('no one', null, 'pron.', 'A1', 'কেউ না', 'No one was at home.', 'বাড়িতে কেউ ছিল না।', 520),
    ('nobody', null, 'pron.', 'A1', 'কেউ না', 'Nobody knows the answer.', 'কেউ উত্তরটি জানে না।', 521),
    ('north', null, 'adv., adj., n.', 'A1', 'উত্তর; উত্তর দিক', 'The birds fly north.', 'পাখিরা উত্তর দিকে ওড়ে।', 522),
    ('nose', null, 'n.', 'A1', 'নাক', 'The rabbit has a small nose.', 'খরগোশের একটি ছোট নাক আছে।', 523),
    ('not', null, 'adv.', 'A1', 'না; নয়', 'I am not tired.', 'আমি ক্লান্ত নই।', 524),
    ('note', null, 'n., v.', 'A1', 'টুকে রাখা; নোট', 'I wrote a quick note.', 'আমি একটি দ্রুত নোট লিখেছি।', 525),
    ('nothing', null, 'pron.', 'A1', 'কিছু না; কিছুই না', 'There is nothing in the box.', 'বাক্সে কিছুই নেই।', 526),
    ('November', null, 'n.', 'A1', 'নভেম্বর (মাস)', 'It gets cold in November.', 'নভেম্বরে ঠান্ডা পড়ে।', 527),
    ('now', null, 'conj., adv.', 'A1', 'এখন', 'I am busy now.', 'আমি এখন ব্যস্ত।', 528),
    ('nurse', null, 'n.', 'A1', 'নার্স; সেবিকা', 'The nurse is very kind.', 'নার্সটি খুব দয়ালু।', 529),
    ('object', null, 'n., v.', 'A1', 'বস্তু; জিনিস', 'What is this object?', 'এই বস্তুটি কী?', 530),
    ('ocean', null, 'n.', 'A1', 'মহাসাগর', 'The ocean is very deep.', 'মহাসাগর খুব গভীর।', 531),
    ('October', null, 'n.', 'A1', 'অক্টোবর (মাস)', 'My exam is in October.', 'আমার পরীক্ষা অক্টোবরে।', 532),
    ('of', null, 'prep.', 'A1', '-এর; থেকে', 'He is a friend of mine.', 'সে আমার একজন বন্ধু।', 533),
    ('off', null, 'prep., adv.', 'A1', 'বন্ধ; দূরে; থেকে', 'Please turn off the light.', 'দয়া করে আলোটি বন্ধ করো।', 534),
    ('office', null, 'n.', 'A1', 'অফিস; কার্যালয়', 'She works in an office.', 'সে একটি অফিসে কাজ করে।', 535),
    ('often', null, 'adv.', 'A1', 'প্রায়ই; প্রায়শই', 'I often go for a walk.', 'আমি প্রায়ই হাঁটতে যাই।', 536),
    ('oh', null, 'exclam.', 'A1', 'ওহ; আহা (বিস্ময়)', 'Oh, that is wonderful!', 'ওহ, এটা তো দারুণ!', 537),
    ('OK', null, 'exclam., adv., adj.', 'A1', 'ঠিক আছে; আচ্ছা', 'OK, let''s go.', 'ঠিক আছে, চলো যাই।', 538),
    ('old', null, 'adj.', 'A1', 'পুরনো; বৃদ্ধ', 'This is an old house.', 'এটি একটি পুরনো বাড়ি।', 539),
    ('on', null, 'prep., adv.', 'A1', 'উপরে; -এর উপর', 'The book is on the table.', 'বইটি টেবিলের উপর।', 540),
    ('once', null, 'conj., adv.', 'A1', 'একবার', 'I met him once.', 'আমি তার সাথে একবার দেখা করেছি।', 541),
    ('one', null, 'number, pron., det.', 'A1', 'এক (১)', 'I have one sister.', 'আমার একটি বোন আছে।', 542),
    ('onion', null, 'n.', 'A1', 'পেঁয়াজ', 'Cut the onion into pieces.', 'পেঁয়াজটি টুকরো করে কাটো।', 543),
    ('online', null, 'adv., adj.', 'A1', 'অনলাইনে', 'I bought this book online.', 'আমি এই বইটি অনলাইনে কিনেছি।', 544),
    ('only', null, 'adv., adj.', 'A1', 'শুধু; কেবল', 'I have only one pen.', 'আমার কাছে শুধু একটি কলম আছে।', 545),
    ('open', null, 'adj., v.', 'A1', 'খোলা; খোলা', 'The shop is open.', 'দোকানটি খোলা।', 546),
    ('opinion', null, 'n.', 'A1', 'মতামত; অভিমত', 'What is your opinion?', 'তোমার মতামত কী?', 547),
    ('opposite', null, 'prep., adv., adj., n.', 'A1', 'বিপরীত', 'The park is opposite the bank.', 'পার্কটি ব্যাংকের বিপরীত দিকে।', 548),
    ('or', null, 'conj.', 'A1', 'অথবা; কিংবা', 'Tea or coffee?', 'চা নাকি কফি?', 549),
    ('orange', null, 'adj., n.', 'A1', 'কমলা; কমলা রঙ', 'I like orange juice.', 'আমি কমলার রস পছন্দ করি।', 550),
    ('order', null, 'n., v.', 'A1', 'আদেশ; ফরমায়েশ; ক্রম', 'May I take your order?', 'আমি কি আপনার অর্ডার নিতে পারি?', 551),
    ('other', null, 'pron., adj.', 'A1', 'অন্য; অপর', 'Where is the other shoe?', 'অন্য জুতোটি কোথায়?', 552),
    ('our', null, 'det.', 'A1', 'আমাদের', 'This is our school.', 'এটি আমাদের স্কুল।', 553),
    ('out', null, 'prep., adv.', 'A1', 'বাইরে', 'He went out for a walk.', 'সে হাঁটতে বাইরে গেল।', 554),
    ('outside', null, 'prep., adv.', 'A1', 'বাইরে; বাইরের দিকে', 'The children are playing outside.', 'বাচ্চারা বাইরে খেলছে।', 555),
    ('over', null, 'prep., adv.', 'A1', 'উপরে; শেষ; পার', 'The bridge is over the river.', 'সেতুটি নদীর উপর দিয়ে গেছে।', 556),
    ('own', null, 'pron., adj., v.', 'A1', 'নিজের; মালিক হওয়া', 'I have my own room.', 'আমার নিজের একটি ঘর আছে।', 557),
    ('o’clock', null, 'adv.', 'A1', 'টা (সময় নির্দেশক)', 'It is five o''clock.', 'এখন পাঁচটা বাজে।', 558),
    ('page', null, 'n.', 'A1', 'পৃষ্ঠা', 'Open your book to page ten.', 'তোমার বইয়ের দশ নম্বর পৃষ্ঠা খোলো।', 559),
    ('paint', null, 'n., v.', 'A1', 'রং; রং করা; আঁকা', 'They paint the wall blue.', 'তারা দেয়ালটি নীল রং করে।', 560),
    ('painting', null, 'n.', 'A1', 'চিত্রকর্ম; ছবি', 'This painting is beautiful.', 'এই চিত্রকর্মটি সুন্দর।', 561),
    ('pair', null, 'n.', 'A1', 'জোড়া', 'I bought a pair of shoes.', 'আমি এক জোড়া জুতো কিনেছি।', 562),
    ('pants', null, 'n.', 'A1', 'প্যান্ট; পাতলুন', 'He is wearing black pants.', 'সে কালো প্যান্ট পরেছে।', 563),
    ('paper', null, 'n.', 'A1', 'কাগজ', 'Write your name on the paper.', 'কাগজে তোমার নাম লেখো।', 564),
    ('paragraph', null, 'n.', 'A1', 'অনুচ্ছেদ; প্যারাগ্রাফ', 'Read the first paragraph.', 'প্রথম অনুচ্ছেদটি পড়ো।', 565),
    ('parent', null, 'n.', 'A1', 'পিতা বা মাতা; অভিভাবক', 'My parents love me.', 'আমার বাবা-মা আমাকে ভালোবাসেন।', 566),
    ('park', null, 'n., v.', 'A1', 'পার্ক; উদ্যান; গাড়ি রাখা', 'We play in the park.', 'আমরা পার্কে খেলি।', 567),
    ('part', null, 'n.', 'A1', 'অংশ; ভাগ', 'This is the best part.', 'এটি সবচেয়ে ভালো অংশ।', 568),
    ('partner', null, 'n.', 'A1', 'সঙ্গী; অংশীদার', 'Work with a partner.', 'একজন সঙ্গীর সাথে কাজ করো।', 569),
    ('party', null, 'n.', 'A1', 'পার্টি; অনুষ্ঠান', 'We had a birthday party.', 'আমরা একটি জন্মদিনের পার্টি করেছি।', 570),
    ('passport', null, 'n.', 'A1', 'পাসপোর্ট', 'Show me your passport, please.', 'দয়া করে আপনার পাসপোর্ট দেখান।', 571),
    ('past', null, 'prep., adv., adj., n.', 'A1', 'অতীত; গত', 'Do not think about the past.', 'অতীত নিয়ে ভেবো না।', 572),
    ('pay', null, 'n., v.', 'A1', 'টাকা দেওয়া; পরিশোধ করা', 'I will pay for the food.', 'আমি খাবারের দাম দেব।', 573),
    ('pen', null, 'n.', 'A1', 'কলম', 'Write with a blue pen.', 'নীল কলম দিয়ে লেখো।', 574),
    ('pencil', null, 'n.', 'A1', 'পেন্সিল', 'My pencil is broken.', 'আমার পেন্সিলটি ভাঙা।', 575),
    ('people', null, 'n.', 'A1', 'মানুষ; লোকজন', 'Many people came to the party.', 'অনেক মানুষ পার্টিতে এসেছিল।', 576),
    ('pepper', null, 'n.', 'A1', 'মরিচ; গোলমরিচ', 'Add some pepper to the soup.', 'স্যুপে একটু মরিচ দাও।', 577),
    ('perfect', null, 'adj.', 'A1', 'নিখুঁত; পারফেক্ট', 'The weather is perfect today.', 'আজ আবহাওয়া চমৎকার।', 578),
    ('period', null, 'n.', 'A1', 'সময়কাল; পিরিয়ড', 'We have a long rest period.', 'আমাদের একটি দীর্ঘ বিশ্রামের সময় আছে।', 579),
    ('person', null, 'n.', 'A1', 'ব্যক্তি; মানুষ', 'She is a kind person.', 'সে একজন দয়ালু মানুষ।', 580),
    ('personal', null, 'adj.', 'A1', 'ব্যক্তিগত', 'This is my personal diary.', 'এটি আমার ব্যক্তিগত ডায়েরি।', 581),
    ('phone', null, 'n., v.', 'A1', 'ফোন; টেলিফোন', 'My phone is ringing.', 'আমার ফোন বাজছে।', 582),
    ('photo', null, 'n.', 'A1', 'ছবি; ফটো', 'Let''s take a photo.', 'চলো একটা ছবি তুলি।', 583),
    ('photograph', null, 'n., v.', 'A1', 'আলোকচিত্র; ছবি তোলা', 'This is an old photograph.', 'এটি একটি পুরনো ছবি।', 584),
    ('phrase', null, 'n.', 'A1', 'বাক্যাংশ; শব্দগুচ্ছ', 'Learn this useful phrase.', 'এই দরকারি বাক্যাংশটি শেখো।', 585),
    ('piano', null, 'n.', 'A1', 'পিয়ানো', 'She plays the piano well.', 'সে ভালো পিয়ানো বাজায়।', 586),
    ('picture', null, 'n., v.', 'A1', 'ছবি; চিত্র', 'Draw a picture of your house.', 'তোমার বাড়ির একটি ছবি আঁকো।', 587),
    ('piece', null, 'n.', 'A1', 'টুকরা; খণ্ড', 'Give me a piece of cake.', 'আমাকে এক টুকরো কেক দাও।', 588),
    ('pig', null, 'n.', 'A1', 'শূকর; শুয়োর', 'The pig is in the mud.', 'শূকরটি কাদায় আছে।', 589),
    ('pink', null, 'adj., n.', 'A1', 'গোলাপি', 'She has a pink bag.', 'তার একটি গোলাপি ব্যাগ আছে।', 590),
    ('place', null, 'n., v.', 'A1', 'স্থান; জায়গা', 'This is a nice place.', 'এটি একটি সুন্দর জায়গা।', 591),
    ('plan', null, 'n., v.', 'A1', 'পরিকল্পনা', 'What is your plan for today?', 'আজকের জন্য তোমার পরিকল্পনা কী?', 592),
    ('plane', null, 'n.', 'A1', 'উড়োজাহাজ; বিমান', 'The plane is in the sky.', 'বিমানটি আকাশে।', 593),
    ('plant', null, 'n., v.', 'A1', 'গাছ; চারা; রোপণ করা', 'Water the plant every day.', 'প্রতিদিন গাছটিতে পানি দাও।', 594),
    ('play', null, 'n., v.', 'A1', 'খেলা; অভিনয় করা; বাজানো', 'The children play in the yard.', 'বাচ্চারা উঠোনে খেলে।', 595),
    ('player', null, 'n.', 'A1', 'খেলোয়াড়', 'He is a good football player.', 'সে একজন ভালো ফুটবল খেলোয়াড়।', 596),
    ('please', null, 'exclam., v.', 'A1', 'দয়া করে; অনুগ্রহ করে', 'Please sit down.', 'দয়া করে বসুন।', 597),
    ('point', null, 'n., v.', 'A1', 'বিন্দু; পয়েন্ট; নির্দেশ করা', 'That is a good point.', 'এটি একটি ভালো পয়েন্ট।', 598),
    ('police', null, 'n.', 'A1', 'পুলিশ', 'Call the police.', 'পুলিশ ডাকো।', 599),
    ('policeman', null, 'n.', 'A1', 'পুলিশ কর্মকর্তা; পুলিশ', 'The policeman helped us.', 'পুলিশটি আমাদের সাহায্য করলেন।', 600),
    ('pool', null, 'n.', 'A1', 'পুকুর; সুইমিং পুল', 'They swim in the pool.', 'তারা পুলে সাঁতার কাটে।', 601),
    ('poor', null, 'adj.', 'A1', 'গরিব; দরিদ্র', 'He helps poor people.', 'সে গরিব মানুষদের সাহায্য করে।', 602),
    ('popular', null, 'adj.', 'A1', 'জনপ্রিয়', 'This song is very popular.', 'এই গানটি খুব জনপ্রিয়।', 603),
    ('positive', null, 'adj., n.', 'A1', 'ইতিবাচক; ধনাত্মক', 'Stay positive.', 'ইতিবাচক থাকো।', 604),
    ('possible', null, 'adj.', 'A1', 'সম্ভব', 'Is it possible to finish today?', 'আজ শেষ করা কি সম্ভব?', 605),
    ('post', null, 'n., v.', 'A1', 'ডাক; পোস্ট করা', 'I will post the letter today.', 'আমি আজ চিঠিটি ডাকে দেব।', 606),
    ('potato', null, 'n.', 'A1', 'আলু', 'I like fried potato.', 'আমি ভাজা আলু পছন্দ করি।', 607),
    ('pound', null, 'n.', 'A1', 'পাউন্ড (মুদ্রা/ওজন)', 'It costs five pounds.', 'এর দাম পাঁচ পাউন্ড।', 608),
    ('practice', null, 'n., v.', 'A1', 'অনুশীলন; চর্চা করা', 'Practice makes perfect.', 'অনুশীলনে সবকিছু নিখুঁত হয়।', 609),
    ('prefer', null, 'v.', 'A1', 'বেশি পছন্দ করা', 'I prefer tea to coffee.', 'আমি কফির চেয়ে চা বেশি পছন্দ করি।', 610),
    ('prepare', null, 'v.', 'A1', 'প্রস্তুত করা; তৈরি করা', 'She is preparing dinner.', 'সে রাতের খাবার তৈরি করছে।', 611),
    ('present', null, 'adj., n., v.', 'A1', 'উপহার; উপস্থিত; বর্তমান', 'I got a nice present.', 'আমি একটি সুন্দর উপহার পেয়েছি।', 612),
    ('pretty', null, 'adv., adj.', 'A1', 'সুন্দর; বেশ', 'She has a pretty smile.', 'তার একটি সুন্দর হাসি আছে।', 613),
    ('price', null, 'n., v.', 'A1', 'দাম; মূল্য', 'What is the price of this?', 'এটার দাম কত?', 614),
    ('probably', null, 'adv.', 'A1', 'সম্ভবত', 'He is probably at home.', 'সে সম্ভবত বাড়িতে আছে।', 615),
    ('problem', null, 'n.', 'A1', 'সমস্যা', 'We have a small problem.', 'আমাদের একটি ছোট সমস্যা আছে।', 616),
    ('product', null, 'n.', 'A1', 'পণ্য; উৎপাদন', 'This product is very good.', 'এই পণ্যটি খুব ভালো।', 617),
    ('program', null, 'n., v.', 'A1', 'অনুষ্ঠান; কর্মসূচি; প্রোগ্রাম', 'I watched a TV program.', 'আমি একটি টিভি অনুষ্ঠান দেখেছি।', 618),
    ('project', null, 'n., v.', 'A1', 'প্রকল্প; প্রজেক্ট', 'We are working on a project.', 'আমরা একটি প্রকল্পে কাজ করছি।', 619),
    ('purple', null, 'adj., n.', 'A1', 'বেগুনি', 'She wore a purple dress.', 'সে একটি বেগুনি জামা পরেছিল।', 620),
    ('put', null, 'v.', 'A1', 'রাখা; রাখা', 'Put the book on the shelf.', 'বইটি তাকের উপর রাখো।', 621),
    ('quarter', null, 'n.', 'A1', 'এক-চতুর্থাংশ; সিকি', 'It is a quarter past three.', 'এখন সোয়া তিনটা বাজে।', 622),
    ('question', null, 'n., v.', 'A1', 'প্রশ্ন', 'May I ask a question?', 'আমি কি একটি প্রশ্ন করতে পারি?', 623),
    ('quick', null, 'adj.', 'A1', 'দ্রুত; ঝটপট', 'Let''s have a quick lunch.', 'চলো ঝটপট দুপুরের খাবার খেয়ে নিই।', 624),
    ('quickly', null, 'adv.', 'A1', 'দ্রুত; তাড়াতাড়ি', 'Come here quickly.', 'তাড়াতাড়ি এখানে এসো।', 625),
    ('quiet', null, 'adj.', 'A1', 'শান্ত; নীরব', 'Please be quiet.', 'দয়া করে চুপ করো।', 626),
    ('quite', null, 'adv.', 'A1', 'বেশ; যথেষ্ট', 'It is quite cold today.', 'আজ বেশ ঠান্ডা।', 627),
    ('radio', null, 'n.', 'A1', 'রেডিও', 'I listen to the radio.', 'আমি রেডিও শুনি।', 628),
    ('rain', null, 'n., v.', 'A1', 'বৃষ্টি', 'It will rain tonight.', 'আজ রাতে বৃষ্টি হবে।', 629),
    ('read', null, 'v.', 'A1', 'পড়া', 'I read a book every night.', 'আমি প্রতি রাতে একটি বই পড়ি।', 630),
    ('reader', null, 'n.', 'A1', 'পাঠক', 'She is a fast reader.', 'সে দ্রুত পড়তে পারে।', 631),
    ('reading', null, 'n.', 'A1', 'পড়া; পাঠ', 'Reading is good for you.', 'পড়া তোমার জন্য ভালো।', 632),
    ('ready', null, 'adj.', 'A1', 'প্রস্তুত; তৈরি', 'Are you ready to go?', 'তুমি কি যেতে প্রস্তুত?', 633),
    ('real', null, 'adj.', 'A1', 'আসল; বাস্তব', 'Is this a real diamond?', 'এটি কি আসল হীরা?', 634),
    ('really', null, 'adv.', 'A1', 'সত্যিই; আসলে', 'I really like this song.', 'আমি সত্যিই এই গানটি পছন্দ করি।', 635),
    ('reason', null, 'n.', 'A1', 'কারণ', 'What is the reason?', 'কারণটা কী?', 636),
    ('red', null, 'adj., n.', 'A1', 'লাল', 'She has a red car.', 'তার একটি লাল গাড়ি আছে।', 637),
    ('relax', null, 'v.', 'A1', 'বিশ্রাম নেওয়া; আরাম করা', 'Relax and enjoy the music.', 'আরাম করো আর গান উপভোগ করো।', 638),
    ('remember', null, 'v.', 'A1', 'মনে রাখা; স্মরণ করা', 'I remember your name.', 'আমি তোমার নাম মনে রেখেছি।', 639),
    ('repeat', null, 'n., v.', 'A1', 'পুনরাবৃত্তি করা; আবার বলা', 'Please repeat the word.', 'দয়া করে শব্দটি আবার বলো।', 640),
    ('report', null, 'n., v.', 'A1', 'প্রতিবেদন; রিপোর্ট', 'I wrote a report.', 'আমি একটি প্রতিবেদন লিখেছি।', 641),
    ('restaurant', null, 'n.', 'A1', 'রেস্তোরাঁ', 'We ate at a nice restaurant.', 'আমরা একটি সুন্দর রেস্তোরাঁয় খেয়েছি।', 642),
    ('result', null, 'n., v.', 'A1', 'ফলাফল; ফল', 'The exam result is good.', 'পরীক্ষার ফলাফল ভালো।', 643),
    ('return', null, 'n., v.', 'A1', 'ফিরে আসা; ফেরত দেওয়া', 'Please return my book.', 'দয়া করে আমার বইটি ফেরত দাও।', 644),
    ('rice', null, 'n.', 'A1', 'ভাত; চাল', 'We eat rice every day.', 'আমরা প্রতিদিন ভাত খাই।', 645),
    ('rich', null, 'adj.', 'A1', 'ধনী; সম্পদশালী', 'He is a rich man.', 'সে একজন ধনী লোক।', 646),
    ('ride', null, 'n., v.', 'A1', 'চড়া; সওয়ার হওয়া', 'I ride my bike to school.', 'আমি সাইকেলে চড়ে স্কুলে যাই।', 647),
    ('right', null, 'adv., adj., n.', 'A1', 'সঠিক; ডান; অধিকার', 'Turn right at the light.', 'বাতির কাছে ডানে ঘুরো।', 648),
    ('river', null, 'n.', 'A1', 'নদী', 'The river is very wide.', 'নদীটি খুব চওড়া।', 649),
    ('road', null, 'n.', 'A1', 'রাস্তা; সড়ক', 'This road is very busy.', 'এই রাস্তাটি খুব ব্যস্ত।', 650),
    ('room', null, 'n.', 'A1', 'ঘর; কক্ষ', 'My room is clean.', 'আমার ঘরটি পরিষ্কার।', 651),
    ('routine', null, 'adj., n.', 'A1', 'রুটিন; নিত্যকর্ম', 'Exercise is part of my routine.', 'ব্যায়াম আমার রুটিনের অংশ।', 652),
    ('rule', null, 'n., v.', 'A1', 'নিয়ম; শাসন করা', 'Follow the rules of the game.', 'খেলার নিয়ম মেনে চলো।', 653),
    ('run', null, 'n., v.', 'A1', 'দৌড়ানো; চালানো', 'I run every morning.', 'আমি প্রতিদিন সকালে দৌড়াই।', 654),
    ('sad', null, 'adj.', 'A1', 'দুঃখিত; বিষণ্ণ', 'Why are you sad?', 'তুমি কেন দুঃখিত?', 655),
    ('salad', null, 'n.', 'A1', 'সালাদ', 'I made a fresh salad.', 'আমি একটি তাজা সালাদ বানিয়েছি।', 656),
    ('salt', null, 'n.', 'A1', 'লবণ; নুন', 'Add a little salt.', 'একটু লবণ যোগ করো।', 657),
    ('same', null, 'pron., adv., adj.', 'A1', 'একই; সমান', 'We have the same bag.', 'আমাদের একই ব্যাগ।', 658),
    ('sandwich', null, 'n.', 'A1', 'স্যান্ডউইচ', 'I had a cheese sandwich.', 'আমি একটি চিজ স্যান্ডউইচ খেয়েছি।', 659),
    ('Saturday', null, 'n.', 'A1', 'শনিবার', 'We rest on Saturday.', 'শনিবারে আমরা বিশ্রাম করি।', 660),
    ('say', null, 'v.', 'A1', 'বলা', 'What did you say?', 'তুমি কী বললে?', 661),
    ('school', null, 'n.', 'A1', 'বিদ্যালয়; স্কুল', 'I go to school every day.', 'আমি প্রতিদিন স্কুলে যাই।', 662),
    ('science', null, 'n.', 'A1', 'বিজ্ঞান', 'Science is my favorite subject.', 'বিজ্ঞান আমার প্রিয় বিষয়।', 663),
    ('scientist', null, 'n.', 'A1', 'বিজ্ঞানী', 'She wants to be a scientist.', 'সে একজন বিজ্ঞানী হতে চায়।', 664),
    ('second', 'next after the first', 'det., adv., n.', 'A1', 'দ্বিতীয়', 'This is my second cup of tea.', 'এটি আমার দ্বিতীয় কাপ চা।', 665),
    ('second', 'unit of time', 'n.', 'A1', 'সেকেন্ড (সময়)', 'Wait a second, please.', 'দয়া করে এক সেকেন্ড অপেক্ষা করো।', 666),
    ('section', null, 'n.', 'A1', 'বিভাগ; অংশ', 'Read the next section.', 'পরবর্তী অংশটি পড়ো।', 667),
    ('see', null, 'v.', 'A1', 'দেখা', 'I can see the moon.', 'আমি চাঁদ দেখতে পাচ্ছি।', 668),
    ('sell', null, 'v.', 'A1', 'বিক্রি করা', 'They sell fresh fruit.', 'তারা তাজা ফল বিক্রি করে।', 669),
    ('send', null, 'v.', 'A1', 'পাঠানো', 'Send me a message.', 'আমাকে একটি বার্তা পাঠাও।', 670),
    ('sentence', null, 'n., v.', 'A1', 'বাক্য', 'Write a short sentence.', 'একটি ছোট বাক্য লেখো।', 671),
    ('September', null, 'n.', 'A1', 'সেপ্টেম্বর (মাস)', 'School reopens in September.', 'সেপ্টেম্বরে স্কুল আবার খোলে।', 672),
    ('seven', null, 'number', 'A1', 'সাত (৭)', 'There are seven days in a week.', 'সপ্তাহে সাত দিন থাকে।', 673),
    ('seventeen', null, 'number', 'A1', 'সতেরো (১৭)', 'He is seventeen years old.', 'তার বয়স সতেরো বছর।', 674),
    ('seventy', null, 'number', 'A1', 'সত্তর (৭০)', 'My grandmother is seventy.', 'আমার দাদির বয়স সত্তর।', 675),
    ('share', null, 'n., v.', 'A1', 'ভাগ করা; শেয়ার করা', 'Please share your food.', 'দয়া করে তোমার খাবার ভাগ করো।', 676),
    ('she', null, 'pron.', 'A1', 'সে (স্ত্রী); তিনি', 'She is my sister.', 'সে আমার বোন।', 677),
    ('sheep', null, 'n.', 'A1', 'ভেড়া', 'The sheep are in the field.', 'ভেড়াগুলো মাঠে আছে।', 678),
    ('shirt', null, 'n.', 'A1', 'শার্ট; জামা', 'He is wearing a white shirt.', 'সে একটি সাদা শার্ট পরেছে।', 679),
    ('shoe', null, 'n.', 'A1', 'জুতা', 'My shoe is dirty.', 'আমার জুতোটি নোংরা।', 680),
    ('shop', null, 'n., v.', 'A1', 'দোকান; কেনাকাটা করা', 'The shop is closed today.', 'দোকানটি আজ বন্ধ।', 681),
    ('shopping', null, 'n.', 'A1', 'কেনাকাটা', 'I go shopping on weekends.', 'আমি সপ্তাহান্তে কেনাকাটা করি।', 682),
    ('short', null, 'adj.', 'A1', 'খাটো; ছোট', 'He is short and thin.', 'সে খাটো ও পাতলা।', 683),
    ('should', null, 'modal v., v.', 'A1', 'উচিত', 'You should sleep early.', 'তোমার তাড়াতাড়ি ঘুমানো উচিত।', 684),
    ('show', null, 'n., v.', 'A1', 'দেখানো; অনুষ্ঠান', 'Show me your homework.', 'তোমার বাড়ির কাজ আমাকে দেখাও।', 685),
    ('shower', null, 'n.', 'A1', 'ঝরনা; গোসল', 'I take a shower every morning.', 'আমি প্রতিদিন সকালে গোসল করি।', 686),
    ('sick', null, 'adj.', 'A1', 'অসুস্থ; পীড়িত', 'She is sick today.', 'সে আজ অসুস্থ।', 687),
    ('similar', null, 'adj.', 'A1', 'একই রকম; সদৃশ', 'These two bags are similar.', 'এই দুটো ব্যাগ একই রকম।', 688),
    ('sing', null, 'v.', 'A1', 'গান গাওয়া', 'She can sing very well.', 'সে খুব ভালো গান গাইতে পারে।', 689),
    ('singer', null, 'n.', 'A1', 'গায়ক; গায়িকা', 'He is a famous singer.', 'সে একজন বিখ্যাত গায়ক।', 690),
    ('sister', null, 'n.', 'A1', 'বোন', 'My sister is a nurse.', 'আমার বোন একজন নার্স।', 691),
    ('sit', null, 'v.', 'A1', 'বসা', 'Please sit here.', 'দয়া করে এখানে বসো।', 692),
    ('situation', null, 'n.', 'A1', 'পরিস্থিতি; অবস্থা', 'It is a difficult situation.', 'এটি একটি কঠিন পরিস্থিতি।', 693),
    ('six', null, 'number', 'A1', 'ছয় (৬)', 'I wake up at six.', 'আমি ছয়টায় ঘুম থেকে উঠি।', 694),
    ('sixteen', null, 'number', 'A1', 'ষোলো (১৬)', 'She is sixteen years old.', 'তার বয়স ষোলো বছর।', 695),
    ('sixty', null, 'number', 'A1', 'ষাট (৬০)', 'There are sixty minutes in an hour.', 'এক ঘণ্টায় ষাট মিনিট থাকে।', 696),
    ('skill', null, 'n.', 'A1', 'দক্ষতা; কৌশল', 'Cooking is a useful skill.', 'রান্না একটি দরকারি দক্ষতা।', 697),
    ('skirt', null, 'n.', 'A1', 'স্কার্ট; ঘাগরা', 'She wore a long skirt.', 'সে একটি লম্বা স্কার্ট পরেছিল।', 698),
    ('sleep', null, 'n., v.', 'A1', 'ঘুম; ঘুমানো', 'The baby is sleeping.', 'বাচ্চাটি ঘুমাচ্ছে।', 699),
    ('slow', null, 'adj., v.', 'A1', 'ধীর; মন্থর', 'The turtle is slow.', 'কচ্ছপটি ধীর।', 700),
    ('small', null, 'adj.', 'A1', 'ছোট', 'This is a small room.', 'এটি একটি ছোট ঘর।', 701),
    ('smart', null, 'adj.', 'A1', 'চালাক; বুদ্ধিমান', 'She is a smart student.', 'সে একজন বুদ্ধিমান ছাত্রী।', 702),
    ('snake', null, 'n.', 'A1', 'সাপ', 'The snake is dangerous.', 'সাপটি বিপজ্জনক।', 703),
    ('snow', null, 'n., v.', 'A1', 'বরফ; তুষার', 'It does not snow here.', 'এখানে তুষারপাত হয় না।', 704),
    ('so', null, 'conj., adv.', 'A1', 'তাই; এত; সুতরাং', 'I was tired, so I slept.', 'আমি ক্লান্ত ছিলাম, তাই ঘুমিয়ে পড়েছি।', 705),
    ('some', null, 'pron., det.', 'A1', 'কিছু; কয়েকটি', 'I need some water.', 'আমার কিছু পানি দরকার।', 706),
    ('somebody', null, 'pron.', 'A1', 'কেউ একজন', 'Somebody is knocking at the door.', 'কেউ একজন দরজায় কড়া নাড়ছে।', 707),
    ('someone', null, 'pron.', 'A1', 'কেউ একজন', 'Someone left a bag here.', 'কেউ একজন এখানে একটি ব্যাগ রেখে গেছে।', 708),
    ('something', null, 'pron.', 'A1', 'কিছু একটা', 'I want to tell you something.', 'আমি তোমাকে কিছু একটা বলতে চাই।', 709),
    ('sometimes', null, 'adv.', 'A1', 'মাঝে মাঝে; কখনও কখনও', 'Sometimes I walk to work.', 'মাঝে মাঝে আমি হেঁটে কাজে যাই।', 710),
    ('son', null, 'n.', 'A1', 'পুত্র; ছেলে', 'They have one son.', 'তাদের একটি ছেলে আছে।', 711),
    ('song', null, 'n.', 'A1', 'গান', 'This is my favorite song.', 'এটি আমার প্রিয় গান।', 712),
    ('soon', null, 'adv.', 'A1', 'শীঘ্রই; তাড়াতাড়ি', 'I will be back soon.', 'আমি শীঘ্রই ফিরে আসব।', 713),
    ('sorry', null, 'exclam., adj.', 'A1', 'দুঃখিত', 'I am sorry for being late.', 'দেরি করার জন্য আমি দুঃখিত।', 714),
    ('sound', null, 'n., v.', 'A1', 'শব্দ; আওয়াজ; মনে হওয়া', 'I heard a strange sound.', 'আমি একটি অদ্ভুত শব্দ শুনলাম।', 715),
    ('soup', null, 'n.', 'A1', 'স্যুপ; ঝোল', 'The soup is hot.', 'স্যুপটি গরম।', 716),
    ('south', null, 'adv., adj., n.', 'A1', 'দক্ষিণ; দক্ষিণ দিক', 'They traveled south.', 'তারা দক্ষিণ দিকে ভ্রমণ করল।', 717),
    ('space', null, 'n.', 'A1', 'স্থান; জায়গা; মহাকাশ', 'There is no space here.', 'এখানে কোনো জায়গা নেই।', 718),
    ('speak', null, 'v.', 'A1', 'কথা বলা', 'Can you speak English?', 'তুমি কি ইংরেজি বলতে পারো?', 719),
    ('special', null, 'adj.', 'A1', 'বিশেষ', 'Today is a special day.', 'আজ একটি বিশেষ দিন।', 720),
    ('spell', null, 'v.', 'A1', 'বানান করা', 'How do you spell your name?', 'তোমার নামের বানান কী?', 721),
    ('spelling', null, 'n.', 'A1', 'বানান', 'Check the spelling of this word.', 'এই শব্দটির বানান যাচাই করো।', 722),
    ('spend', null, 'v.', 'A1', 'খরচ করা; ব্যয় করা (সময়/অর্থ)', 'I spend time with my family.', 'আমি আমার পরিবারের সাথে সময় কাটাই।', 723),
    ('sport', null, 'n.', 'A1', 'খেলাধুলা; ক্রীড়া', 'My favorite sport is cricket.', 'আমার প্রিয় খেলা ক্রিকেট।', 724),
    ('spring', null, 'n., v.', 'A1', 'বসন্তকাল', 'Flowers bloom in spring.', 'বসন্তে ফুল ফোটে।', 725),
    ('stand', null, 'n., v.', 'A1', 'দাঁড়ানো', 'Please stand up.', 'দয়া করে উঠে দাঁড়াও।', 726),
    ('star', null, 'n., v.', 'A1', 'তারা; নক্ষত্র', 'The stars are bright tonight.', 'আজ রাতে তারাগুলো উজ্জ্বল।', 727),
    ('start', null, 'n., v.', 'A1', 'শুরু করা', 'Let''s start the lesson.', 'চলো পাঠটি শুরু করি।', 728),
    ('statement', null, 'n.', 'A1', 'বিবৃতি; বক্তব্য', 'Is this statement true?', 'এই বিবৃতিটি কি সত্য?', 729),
    ('station', null, 'n.', 'A1', 'স্টেশন', 'The train station is near.', 'ট্রেন স্টেশনটি কাছেই।', 730),
    ('stay', null, 'n., v.', 'A1', 'থাকা; অবস্থান করা', 'Please stay here.', 'দয়া করে এখানে থাকো।', 731),
    ('still', null, 'adv., adj.', 'A1', 'এখনও; স্থির', 'He is still sleeping.', 'সে এখনও ঘুমাচ্ছে।', 732),
    ('stop', null, 'n., v.', 'A1', 'থামা; বন্ধ করা', 'Please stop the car.', 'দয়া করে গাড়িটি থামাও।', 733),
    ('store', null, 'n., v.', 'A1', 'দোকান; সংরক্ষণ করা', 'The store opens at nine.', 'দোকানটি নয়টায় খোলে।', 734),
    ('story', null, 'n.', 'A1', 'গল্প; কাহিনী', 'Tell me a story.', 'আমাকে একটি গল্প বলো।', 735),
    ('street', null, 'n.', 'A1', 'রাস্তা; সড়ক', 'The street is very quiet.', 'রাস্তাটি খুব শান্ত।', 736),
    ('strong', null, 'adj.', 'A1', 'শক্তিশালী; মজবুত', 'He is very strong.', 'সে খুব শক্তিশালী।', 737),
    ('student', null, 'n.', 'A1', 'ছাত্র; ছাত্রী; শিক্ষার্থী', 'She is a good student.', 'সে একজন ভালো ছাত্রী।', 738),
    ('study', null, 'n., v.', 'A1', 'পড়াশোনা করা; অধ্যয়ন', 'I study every evening.', 'আমি প্রতি সন্ধ্যায় পড়াশোনা করি।', 739),
    ('style', null, 'n.', 'A1', 'ধরন; শৈলী; স্টাইল', 'I like her style.', 'আমি তার স্টাইল পছন্দ করি।', 740),
    ('subject', null, 'adj., n.', 'A1', 'বিষয়; পাঠ্যবিষয়', 'Math is a hard subject.', 'গণিত একটি কঠিন বিষয়।', 741),
    ('success', null, 'n.', 'A1', 'সাফল্য; সফলতা', 'Hard work brings success.', 'কঠোর পরিশ্রম সাফল্য এনে দেয়।', 742),
    ('sugar', null, 'n.', 'A1', 'চিনি', 'I take sugar in my tea.', 'আমি চায়ে চিনি নিই।', 743),
    ('summer', null, 'n.', 'A1', 'গ্রীষ্মকাল', 'It is hot in summer.', 'গ্রীষ্মকালে গরম থাকে।', 744),
    ('sun', null, 'n.', 'A1', 'সূর্য', 'The sun is very bright.', 'সূর্য খুব উজ্জ্বল।', 745),
    ('Sunday', null, 'n.', 'A1', 'রবিবার', 'We visit family on Sunday.', 'আমরা রবিবারে পরিবারের সাথে দেখা করি।', 746),
    ('supermarket', null, 'n.', 'A1', 'সুপারমার্কেট', 'I buy food at the supermarket.', 'আমি সুপারমার্কেটে খাবার কিনি।', 747),
    ('sure', null, 'adv., adj.', 'A1', 'নিশ্চিত', 'Are you sure about this?', 'তুমি কি এই বিষয়ে নিশ্চিত?', 748),
    ('sweater', null, 'n.', 'A1', 'সোয়েটার', 'Wear a sweater in winter.', 'শীতে সোয়েটার পরো।', 749),
    ('swim', null, 'n., v.', 'A1', 'সাঁতার কাটা', 'I can swim in the river.', 'আমি নদীতে সাঁতার কাটতে পারি।', 750),
    ('swimming', null, 'n.', 'A1', 'সাঁতার', 'Swimming is good exercise.', 'সাঁতার একটি ভালো ব্যায়াম।', 751),
    ('T-shirt', null, 'n.', 'A1', 'টি-শার্ট', 'He wears a blue T-shirt.', 'সে একটি নীল টি-শার্ট পরে।', 752),
    ('table', null, 'n.', 'A1', 'টেবিল', 'The food is on the table.', 'খাবার টেবিলের উপর।', 753),
    ('take', null, 'v.', 'A1', 'নেওয়া; গ্রহণ করা', 'Take an umbrella with you.', 'তোমার সাথে একটি ছাতা নাও।', 754),
    ('talk', null, 'n., v.', 'A1', 'কথা বলা; আলাপ', 'Let''s talk after class.', 'চলো ক্লাসের পরে কথা বলি।', 755),
    ('tall', null, 'adj.', 'A1', 'লম্বা; উঁচু', 'He is very tall.', 'সে খুব লম্বা।', 756),
    ('taxi', null, 'n.', 'A1', 'ট্যাক্সি', 'Let''s take a taxi.', 'চলো একটা ট্যাক্সি নিই।', 757),
    ('tea', null, 'n.', 'A1', 'চা', 'I drink tea in the morning.', 'আমি সকালে চা পান করি।', 758),
    ('teach', null, 'v.', 'A1', 'শেখানো; পড়ানো', 'She teaches English.', 'তিনি ইংরেজি পড়ান।', 759),
    ('teacher', null, 'n.', 'A1', 'শিক্ষক; শিক্ষিকা', 'My teacher is very kind.', 'আমার শিক্ষক খুব দয়ালু।', 760),
    ('team', null, 'n.', 'A1', 'দল; টিম', 'Our team won the game.', 'আমাদের দল খেলায় জিতেছে।', 761),
    ('teenager', null, 'n.', 'A1', 'কিশোর-কিশোরী', 'My brother is a teenager.', 'আমার ভাই একজন কিশোর।', 762),
    ('telephone', null, 'n., v.', 'A1', 'টেলিফোন; ফোন', 'The telephone is ringing.', 'টেলিফোনটি বাজছে।', 763),
    ('television', null, 'n.', 'A1', 'টেলিভিশন', 'We watch television at night.', 'আমরা রাতে টেলিভিশন দেখি।', 764),
    ('tell', null, 'v.', 'A1', 'বলা; জানানো', 'Tell me the truth.', 'আমাকে সত্যি কথা বলো।', 765),
    ('ten', null, 'number', 'A1', 'দশ (১০)', 'I have ten fingers.', 'আমার দশটি আঙুল আছে।', 766),
    ('tennis', null, 'n.', 'A1', 'টেনিস', 'They play tennis on Sundays.', 'তারা রবিবারে টেনিস খেলে।', 767),
    ('terrible', null, 'adj.', 'A1', 'ভয়ানক; ভীষণ খারাপ', 'The weather is terrible.', 'আবহাওয়া ভীষণ খারাপ।', 768),
    ('test', null, 'n., v.', 'A1', 'পরীক্ষা; যাচাই', 'We have a test tomorrow.', 'আমাদের আগামীকাল একটি পরীক্ষা আছে।', 769),
    ('text', null, 'n., v.', 'A1', 'লেখা; পাঠ্য; বার্তা পাঠানো', 'Read the text carefully.', 'লেখাটি মন দিয়ে পড়ো।', 770),
    ('than', null, 'conj.', 'A1', 'চেয়ে; তুলনায়', 'She is taller than me.', 'সে আমার চেয়ে লম্বা।', 771),
    ('thank', null, 'v.', 'A1', 'ধন্যবাদ দেওয়া', 'I want to thank you.', 'আমি তোমাকে ধন্যবাদ দিতে চাই।', 772),
    ('thanks', null, 'exclam., n.', 'A1', 'ধন্যবাদ', 'Thanks for your help.', 'তোমার সাহায্যের জন্য ধন্যবাদ।', 773),
    ('that', null, 'pron., conj., det., adv.', 'A1', 'ওটা; সেটি; যে', 'That is my house.', 'ওটা আমার বাড়ি।', 774),
    ('the', null, 'definite article', 'A1', 'টি; টা (নির্দিষ্ট)', 'The book is on the table.', 'বইটি টেবিলের উপর।', 775),
    ('theater', null, 'n.', 'A1', 'থিয়েটার; নাট্যশালা', 'We went to the theater.', 'আমরা থিয়েটারে গিয়েছিলাম।', 776),
    ('their', null, 'det.', 'A1', 'তাদের', 'This is their car.', 'এটি তাদের গাড়ি।', 777),
    ('them', null, 'pron.', 'A1', 'তাদের; তাদেরকে', 'I gave them the books.', 'আমি তাদের বইগুলো দিয়েছি।', 778),
    ('then', null, 'adv.', 'A1', 'তারপর; তখন', 'We ate, then we left.', 'আমরা খেলাম, তারপর চলে গেলাম।', 779),
    ('there', null, 'adv.', 'A1', 'সেখানে; ওখানে', 'Put it over there.', 'ওটা ওখানে রাখো।', 780),
    ('they', null, 'pron.', 'A1', 'তারা; তাঁরা', 'They are my friends.', 'তারা আমার বন্ধু।', 781),
    ('thing', null, 'n.', 'A1', 'জিনিস; বস্তু', 'What is that thing?', 'ওই জিনিসটা কী?', 782),
    ('think', null, 'v.', 'A1', 'চিন্তা করা; ভাবা', 'I think you are right.', 'আমি মনে করি তুমি ঠিক।', 783),
    ('third', null, 'number, n.', 'A1', 'তৃতীয়', 'This is my third try.', 'এটি আমার তৃতীয় চেষ্টা।', 784),
    ('thirsty', null, 'adj.', 'A1', 'তৃষ্ণার্ত; পিপাসার্ত', 'I am very thirsty.', 'আমি খুব তৃষ্ণার্ত।', 785),
    ('thirteen', null, 'number', 'A1', 'তেরো (১৩)', 'She is thirteen years old.', 'তার বয়স তেরো বছর।', 786),
    ('thirty', null, 'number', 'A1', 'ত্রিশ (৩০)', 'There are thirty days in April.', 'এপ্রিলে ত্রিশ দিন থাকে।', 787),
    ('this', null, 'pron., det., adv.', 'A1', 'এটি; এটা; এই', 'This is my book.', 'এটি আমার বই।', 788),
    ('thousand', null, 'number', 'A1', 'হাজার (১০০০)', 'It costs a thousand taka.', 'এর দাম এক হাজার টাকা।', 789),
    ('three', null, 'number', 'A1', 'তিন (৩)', 'I have three pens.', 'আমার তিনটি কলম আছে।', 790),
    ('through', null, 'prep., adv.', 'A1', 'ভিতর দিয়ে; মধ্য দিয়ে', 'We walked through the park.', 'আমরা পার্কের ভিতর দিয়ে হাঁটলাম।', 791),
    ('Thursday', null, 'n.', 'A1', 'বৃহস্পতিবার', 'The meeting is on Thursday.', 'সভাটি বৃহস্পতিবারে।', 792),
    ('ticket', null, 'n.', 'A1', 'টিকিট', 'I bought two tickets.', 'আমি দুটি টিকিট কিনেছি।', 793),
    ('time', null, 'n., v.', 'A1', 'সময়', 'What time is it?', 'এখন কয়টা বাজে?', 794),
    ('tired', null, 'adj.', 'A1', 'ক্লান্ত', 'I am tired after work.', 'কাজের পর আমি ক্লান্ত।', 795),
    ('title', null, 'n., v.', 'A1', 'শিরোনাম; উপাধি', 'What is the title of the book?', 'বইটির শিরোনাম কী?', 796),
    ('to', null, 'prep.', 'A1', 'প্রতি; -এর দিকে; -তে', 'I am going to school.', 'আমি স্কুলে যাচ্ছি।', 797),
    ('today', null, 'adv., n.', 'A1', 'আজ', 'Today is a holiday.', 'আজ ছুটির দিন।', 798),
    ('together', null, 'adv.', 'A1', 'একসাথে; একত্রে', 'We study together.', 'আমরা একসাথে পড়াশোনা করি।', 799),
    ('toilet', null, 'n.', 'A1', 'শৌচাগার; টয়লেট', 'Where is the toilet?', 'টয়লেট কোথায়?', 800),
    ('tomato', null, 'n.', 'A1', 'টমেটো', 'I put tomato in the salad.', 'আমি সালাদে টমেটো দিলাম।', 801),
    ('tomorrow', null, 'adv., n.', 'A1', 'আগামীকাল', 'See you tomorrow.', 'আগামীকাল দেখা হবে।', 802),
    ('tonight', null, 'adv., n.', 'A1', 'আজ রাতে', 'We will meet tonight.', 'আমরা আজ রাতে দেখা করব।', 803),
    ('too', null, 'adv.', 'A1', '-ও; খুব বেশি', 'I want to come too.', 'আমিও আসতে চাই।', 804),
    ('tooth', null, 'n.', 'A1', 'দাঁত', 'Brush your teeth every day.', 'প্রতিদিন তোমার দাঁত ব্রাশ করো।', 805),
    ('topic', null, 'n.', 'A1', 'বিষয়; প্রসঙ্গ', 'Choose a topic for your essay.', 'তোমার রচনার জন্য একটি বিষয় বেছে নাও।', 806),
    ('tourist', null, 'n.', 'A1', 'পর্যটক', 'Many tourists visit the beach.', 'অনেক পর্যটক সৈকতে আসে।', 807),
    ('town', null, 'n.', 'A1', 'শহর; নগর', 'I live in a small town.', 'আমি একটি ছোট শহরে থাকি।', 808),
    ('traffic', null, 'n.', 'A1', 'যানজট; ট্রাফিক', 'There is heavy traffic today.', 'আজ প্রচণ্ড যানজট।', 809),
    ('train', null, 'n., v.', 'A1', 'ট্রেন; প্রশিক্ষণ দেওয়া', 'The train is late.', 'ট্রেনটি দেরি করছে।', 810),
    ('travel', null, 'n., v.', 'A1', 'ভ্রমণ করা', 'I love to travel.', 'আমি ভ্রমণ করতে ভালোবাসি।', 811),
    ('tree', null, 'n.', 'A1', 'গাছ; বৃক্ষ', 'There is a big tree in the yard.', 'উঠোনে একটি বড় গাছ আছে।', 812),
    ('trip', null, 'n., v.', 'A1', 'ভ্রমণ; সফর', 'We took a trip to the hills.', 'আমরা পাহাড়ে একটি ভ্রমণে গিয়েছিলাম।', 813),
    ('truck', null, 'n.', 'A1', 'ট্রাক', 'The truck carries goods.', 'ট্রাকটি মালামাল বহন করে।', 814),
    ('true', null, 'adj.', 'A1', 'সত্য; সঠিক', 'Is this story true?', 'এই গল্পটি কি সত্য?', 815),
    ('try', null, 'n., v.', 'A1', 'চেষ্টা করা', 'Try again, please.', 'দয়া করে আবার চেষ্টা করো।', 816),
    ('Tuesday', null, 'n.', 'A1', 'মঙ্গলবার', 'I have a class on Tuesday.', 'আমার মঙ্গলবারে একটি ক্লাস আছে।', 817),
    ('turn', null, 'n., v.', 'A1', 'ঘোরা; মোড়; পালা', 'It is your turn now.', 'এখন তোমার পালা।', 818),
    ('TV', null, 'n.', 'A1', 'টিভি; টেলিভিশন', 'Turn off the TV.', 'টিভিটি বন্ধ করো।', 819),
    ('twelve', null, 'number', 'A1', 'বারো (১২)', 'There are twelve months.', 'বারো মাস আছে।', 820),
    ('twenty', null, 'number', 'A1', 'বিশ (২০)', 'She is twenty years old.', 'তার বয়স বিশ বছর।', 821),
    ('twice', null, 'adv.', 'A1', 'দুইবার', 'I brush my teeth twice a day.', 'আমি দিনে দুইবার দাঁত ব্রাশ করি।', 822),
    ('two', null, 'number', 'A1', 'দুই (২)', 'I have two hands.', 'আমার দুটি হাত আছে।', 823),
    ('type', null, 'n., v.', 'A1', 'ধরন; টাইপ করা', 'Please type your name.', 'দয়া করে তোমার নাম টাইপ করো।', 824),
    ('umbrella', null, 'n.', 'A1', 'ছাতা', 'Take an umbrella; it may rain.', 'একটি ছাতা নাও; বৃষ্টি হতে পারে।', 825),
    ('uncle', null, 'n.', 'A1', 'চাচা; মামা; কাকা', 'My uncle lives in the city.', 'আমার চাচা শহরে থাকেন।', 826),
    ('under', null, 'prep., adv.', 'A1', 'নিচে; তলায়', 'The cat is under the table.', 'বিড়ালটি টেবিলের নিচে।', 827),
    ('understand', null, 'v.', 'A1', 'বোঝা', 'I understand the lesson.', 'আমি পাঠটি বুঝি।', 828),
    ('university', null, 'n.', 'A1', 'বিশ্ববিদ্যালয়', 'She studies at a university.', 'সে একটি বিশ্ববিদ্যালয়ে পড়ে।', 829),
    ('until', null, 'prep., conj.', 'A1', 'পর্যন্ত; যতক্ষণ না', 'Wait until I come back.', 'আমি ফিরে না আসা পর্যন্ত অপেক্ষা করো।', 830),
    ('up', null, 'prep., adv.', 'A1', 'উপরে; উপরের দিকে', 'Look up at the sky.', 'আকাশের দিকে উপরে তাকাও।', 831),
    ('upstairs', null, 'adv., adj.', 'A1', 'উপরতলায়; উপরে', 'My room is upstairs.', 'আমার ঘরটি উপরতলায়।', 832),
    ('us', null, 'pron.', 'A1', 'আমাদের; আমাদেরকে', 'Come with us.', 'আমাদের সাথে এসো।', 833),
    ('use', null, 'n., v.', 'A1', 'ব্যবহার করা', 'Can I use your pen?', 'আমি কি তোমার কলমটি ব্যবহার করতে পারি?', 834),
    ('useful', null, 'adj.', 'A1', 'উপযোগী; দরকারি', 'This is a useful book.', 'এটি একটি দরকারি বই।', 835),
    ('usually', null, 'adv.', 'A1', 'সাধারণত', 'I usually wake up early.', 'আমি সাধারণত তাড়াতাড়ি উঠি।', 836),
    ('vacation', null, 'n.', 'A1', 'ছুটি; অবকাশ', 'We are on vacation.', 'আমরা ছুটিতে আছি।', 837),
    ('vegetable', null, 'n.', 'A1', 'সবজি; শাকসবজি', 'Eat more vegetables.', 'বেশি করে সবজি খাও।', 838),
    ('very', null, 'adv., adj.', 'A1', 'খুব; অত্যন্ত', 'It is very hot today.', 'আজ খুব গরম।', 839),
    ('video', null, 'n.', 'A1', 'ভিডিও', 'I watched a funny video.', 'আমি একটি মজার ভিডিও দেখেছি।', 840),
    ('visit', null, 'n., v.', 'A1', 'সাক্ষাৎ; ভ্রমণ করা', 'I will visit my grandmother.', 'আমি আমার দাদির সাথে দেখা করতে যাব।', 841),
    ('visitor', null, 'n.', 'A1', 'অতিথি; দর্শনার্থী', 'We have a visitor today.', 'আজ আমাদের একজন অতিথি আছেন।', 842),
    ('wait', null, 'n., v.', 'A1', 'অপেক্ষা করা', 'Please wait for me.', 'দয়া করে আমার জন্য অপেক্ষা করো।', 843),
    ('waiter', null, 'n.', 'A1', 'পরিবেশক; ওয়েটার', 'The waiter brought the food.', 'ওয়েটার খাবার নিয়ে এলেন।', 844),
    ('wake', null, 'v.', 'A1', 'জেগে ওঠা; জাগানো', 'I wake up at six.', 'আমি ছয়টায় জেগে উঠি।', 845),
    ('walk', null, 'n., v.', 'A1', 'হাঁটা', 'Let''s go for a walk.', 'চলো হাঁটতে যাই।', 846),
    ('wall', null, 'n.', 'A1', 'দেয়াল; প্রাচীর', 'There is a clock on the wall.', 'দেয়ালে একটি ঘড়ি আছে।', 847),
    ('want', null, 'v.', 'A1', 'চাওয়া', 'I want a glass of water.', 'আমি এক গ্লাস পানি চাই।', 848),
    ('warm', null, 'adj., v.', 'A1', 'উষ্ণ; গরম', 'The water is warm.', 'পানি উষ্ণ।', 849),
    ('wash', null, 'n., v.', 'A1', 'ধোয়া', 'Wash your hands before eating.', 'খাওয়ার আগে হাত ধুয়ে নাও।', 850),
    ('watch', null, 'n., v.', 'A1', 'দেখা; ঘড়ি (হাতের)', 'I watch TV in the evening.', 'আমি সন্ধ্যায় টিভি দেখি।', 851),
    ('water', null, 'n., v.', 'A1', 'পানি; জল', 'Please give me some water.', 'দয়া করে আমাকে একটু পানি দাও।', 852),
    ('way', null, 'adv., n.', 'A1', 'পথ; উপায়', 'Can you show me the way?', 'তুমি কি আমাকে পথটি দেখাতে পারবে?', 853),
    ('we', null, 'pron.', 'A1', 'আমরা', 'We are good friends.', 'আমরা ভালো বন্ধু।', 854),
    ('wear', null, 'v.', 'A1', 'পরা (পোশাক)', 'She wears glasses.', 'সে চশমা পরে।', 855),
    ('weather', null, 'n.', 'A1', 'আবহাওয়া', 'The weather is nice today.', 'আজ আবহাওয়া সুন্দর।', 856),
    ('website', null, 'n.', 'A1', 'ওয়েবসাইট', 'Visit our website.', 'আমাদের ওয়েবসাইটে যান।', 857),
    ('Wednesday', null, 'n.', 'A1', 'বুধবার', 'We have a test on Wednesday.', 'আমাদের বুধবারে একটি পরীক্ষা আছে।', 858),
    ('week', null, 'n.', 'A1', 'সপ্তাহ', 'There are seven days in a week.', 'এক সপ্তাহে সাত দিন থাকে।', 859),
    ('weekend', null, 'n.', 'A1', 'সপ্তাহান্ত; ছুটির দিন', 'What do you do on the weekend?', 'তুমি সপ্তাহান্তে কী করো?', 860),
    ('welcome', null, 'exclam., adj., n., v.', 'A1', 'স্বাগতম', 'Welcome to our home.', 'আমাদের বাড়িতে স্বাগতম।', 861),
    ('well', null, 'exclam., adv., adj.', 'A1', 'ভালোভাবে; বেশ', 'She sings very well.', 'সে খুব ভালো গান গায়।', 862),
    ('west', null, 'adv., adj., n.', 'A1', 'পশ্চিম; পশ্চিম দিক', 'The sun sets in the west.', 'সূর্য পশ্চিমে অস্ত যায়।', 863),
    ('what', null, 'pron., det.', 'A1', 'কী; কি', 'What is your name?', 'তোমার নাম কী?', 864),
    ('when', null, 'pron., conj., adv.', 'A1', 'কখন; যখন', 'When will you come?', 'তুমি কখন আসবে?', 865),
    ('where', null, 'conj., adv.', 'A1', 'কোথায়; যেখানে', 'Where do you live?', 'তুমি কোথায় থাকো?', 866),
    ('which', null, 'pron., det.', 'A1', 'কোনটি; যেটি', 'Which color do you like?', 'তুমি কোন রঙ পছন্দ করো?', 867),
    ('white', null, 'adj., n.', 'A1', 'সাদা', 'She wore a white dress.', 'সে একটি সাদা জামা পরেছিল।', 868),
    ('who', null, 'pron.', 'A1', 'কে; যিনি', 'Who is at the door?', 'দরজায় কে?', 869),
    ('why', null, 'adv.', 'A1', 'কেন', 'Why are you late?', 'তুমি কেন দেরি করলে?', 870),
    ('wife', null, 'n.', 'A1', 'স্ত্রী; বউ', 'His wife is a teacher.', 'তার স্ত্রী একজন শিক্ষিকা।', 871),
    ('will', null, 'modal v., n., v.', 'A1', 'করবে (ভবিষ্যৎ)', 'I will call you tomorrow.', 'আমি আগামীকাল তোমাকে ফোন করব।', 872),
    ('win', null, 'n., v.', 'A1', 'জেতা; জয়ী হওয়া', 'I hope we win.', 'আশা করি আমরা জিতব।', 873),
    ('window', null, 'n.', 'A1', 'জানালা', 'Please open the window.', 'দয়া করে জানালাটি খোলো।', 874),
    ('wine', null, 'n.', 'A1', 'মদ; ওয়াইন', 'They served red wine.', 'তারা লাল ওয়াইন পরিবেশন করল।', 875),
    ('winter', null, 'n.', 'A1', 'শীতকাল', 'It is cold in winter.', 'শীতকালে ঠান্ডা থাকে।', 876),
    ('with', null, 'prep.', 'A1', 'সাথে; সঙ্গে', 'Come with me.', 'আমার সাথে এসো।', 877),
    ('without', null, 'prep.', 'A1', 'ছাড়া; ব্যতীত', 'I cannot see without glasses.', 'চশমা ছাড়া আমি দেখতে পাই না।', 878),
    ('woman', null, 'n.', 'A1', 'নারী; মহিলা', 'That woman is a doctor.', 'ওই মহিলা একজন ডাক্তার।', 879),
    ('wonderful', null, 'adj.', 'A1', 'বিস্ময়কর; চমৎকার', 'We had a wonderful time.', 'আমরা একটি চমৎকার সময় কাটিয়েছি।', 880),
    ('word', null, 'n.', 'A1', 'শব্দ', 'I learned a new word today.', 'আমি আজ একটি নতুন শব্দ শিখেছি।', 881),
    ('work', null, 'n., v.', 'A1', 'কাজ; কাজ করা', 'I work in an office.', 'আমি একটি অফিসে কাজ করি।', 882),
    ('worker', null, 'n.', 'A1', 'শ্রমিক; কর্মী', 'He is a hard worker.', 'সে একজন পরিশ্রমী কর্মী।', 883),
    ('world', null, 'n.', 'A1', 'পৃথিবী; বিশ্ব', 'English is spoken around the world.', 'সারা বিশ্বে ইংরেজি বলা হয়।', 884),
    ('would', null, 'modal v., v.', 'A1', 'করত; চাইবে (ভদ্র অনুরোধ)', 'Would you like some tea?', 'তুমি কি একটু চা খাবে?', 885),
    ('write', null, 'v.', 'A1', 'লেখা', 'Write your name here.', 'এখানে তোমার নাম লেখো।', 886),
    ('writer', null, 'n.', 'A1', 'লেখক; লেখিকা', 'She is a famous writer.', 'সে একজন বিখ্যাত লেখিকা।', 887),
    ('writing', null, 'n.', 'A1', 'লেখা; লেখনী', 'Your writing is very neat.', 'তোমার হাতের লেখা খুব সুন্দর।', 888),
    ('wrong', null, 'adv., adj., n.', 'A1', 'ভুল; অন্যায়', 'This answer is wrong.', 'এই উত্তরটি ভুল।', 889),
    ('yard', null, 'n.', 'A1', 'উঠোন; আঙিনা', 'The children play in the yard.', 'বাচ্চারা উঠোনে খেলে।', 890),
    ('yeah', null, 'exclam.', 'A1', 'হ্যাঁ (অনানুষ্ঠানিক)', 'Yeah, that sounds good.', 'হ্যাঁ, শুনতে ভালোই লাগছে।', 891),
    ('year', null, 'n.', 'A1', 'বছর', 'I will travel next year.', 'আমি আগামী বছর ভ্রমণ করব।', 892),
    ('yellow', null, 'adj., n.', 'A1', 'হলুদ', 'The sun looks yellow.', 'সূর্যকে হলুদ দেখায়।', 893),
    ('yes', null, 'exclam.', 'A1', 'হ্যাঁ', 'Yes, I agree.', 'হ্যাঁ, আমি একমত।', 894),
    ('yesterday', null, 'adv., n.', 'A1', 'গতকাল', 'I saw her yesterday.', 'আমি গতকাল তাকে দেখেছি।', 895),
    ('you', null, 'pron.', 'A1', 'তুমি; আপনি; তোমরা', 'How are you?', 'তুমি কেমন আছো?', 896),
    ('young', null, 'adj., n.', 'A1', 'তরুণ; অল্পবয়সী', 'She is a young girl.', 'সে একটি অল্পবয়সী মেয়ে।', 897),
    ('your', null, 'det.', 'A1', 'তোমার; আপনার', 'Is this your bag?', 'এটি কি তোমার ব্যাগ?', 898),
    ('yourself', null, 'pron.', 'A1', 'নিজে; তুমি নিজে', 'Take care of yourself.', 'নিজের যত্ন নিও।', 899);
