-- V13 — seed vocabulary: Oxford 3000 (American English) A2 band, 801 headwords.
-- Generated from authored Bengali glosses + bilingual examples (scratchpad/a2_chunk_*.json).
-- Standalone reference data; see V11 for the table.

insert into vocabulary
    (headword, sense_label, part_of_speech, cefr_level, bn_gloss, example_en, example_bn, ordinal)
values
    ('ability', null, 'n.', 'A2', 'সক্ষমতা; দক্ষতা', 'She has the ability to lead.', 'তার নেতৃত্ব দেওয়ার সক্ষমতা আছে।', 1),
    ('able', null, 'adj.', 'A2', 'সক্ষম; সমর্থ', 'I am able to help you.', 'আমি তোমাকে সাহায্য করতে সক্ষম।', 2),
    ('accept', null, 'v.', 'A2', 'গ্রহণ করা; মেনে নেওয়া', 'Please accept my gift.', 'দয়া করে আমার উপহারটি গ্রহণ করো।', 3),
    ('accident', null, 'n.', 'A2', 'দুর্ঘটনা', 'There was a car accident.', 'একটি গাড়ি দুর্ঘটনা ঘটেছিল।', 4),
    ('according to', null, 'prep.', 'A2', 'অনুসারে; মতে', 'According to the map, we turn left.', 'মানচিত্র অনুসারে, আমরা বাঁয়ে ঘুরব।', 5),
    ('achieve', null, 'v.', 'A2', 'অর্জন করা; সাধন করা', 'You can achieve your goals.', 'তুমি তোমার লক্ষ্য অর্জন করতে পারো।', 6),
    ('act', null, 'n., v.', 'A2', 'কাজ; অভিনয় করা', 'He acts in movies.', 'সে সিনেমায় অভিনয় করে।', 7),
    ('active', null, 'adj.', 'A2', 'সক্রিয়; কর্মঠ', 'She lives an active life.', 'সে একটি সক্রিয় জীবনযাপন করে।', 8),
    ('actually', null, 'adv.', 'A2', 'আসলে; প্রকৃতপক্ষে', 'Actually, I disagree.', 'আসলে, আমি একমত নই।', 9),
    ('advantage', null, 'n.', 'A2', 'সুবিধা; সুযোগ', 'Speed is a big advantage.', 'গতি একটি বড় সুবিধা।', 10),
    ('adventure', null, 'n.', 'A2', 'রোমাঞ্চ; অভিযান', 'The trip was a great adventure.', 'ভ্রমণটি একটি দারুণ অভিযান ছিল।', 11),
    ('advertise', null, 'v.', 'A2', 'বিজ্ঞাপন দেওয়া', 'They advertise on TV.', 'তারা টিভিতে বিজ্ঞাপন দেয়।', 12),
    ('advertisement', null, 'n.', 'A2', 'বিজ্ঞাপন', 'I saw an advertisement for shoes.', 'আমি জুতোর একটি বিজ্ঞাপন দেখলাম।', 13),
    ('advertising', null, 'n.', 'A2', 'বিজ্ঞাপন প্রচার', 'She works in advertising.', 'সে বিজ্ঞাপন প্রচারের কাজ করে।', 14),
    ('affect', null, 'v.', 'A2', 'প্রভাবিত করা', 'Rain can affect the game.', 'বৃষ্টি খেলাকে প্রভাবিত করতে পারে।', 15),
    ('against', null, 'prep.', 'A2', 'বিরুদ্ধে; বিপক্ষে', 'They played against our team.', 'তারা আমাদের দলের বিপক্ষে খেলল।', 16),
    ('ah', null, 'exclam.', 'A2', 'আহ (অনুভূতি প্রকাশ)', 'Ah, now I understand.', 'আহ, এখন আমি বুঝলাম।', 17),
    ('airline', null, 'n.', 'A2', 'বিমান সংস্থা', 'This airline is very good.', 'এই বিমান সংস্থাটি খুব ভালো।', 18),
    ('alive', null, 'adj.', 'A2', 'জীবিত; বেঁচে থাকা', 'The fish is still alive.', 'মাছটি এখনও জীবিত।', 19),
    ('all right', null, 'adv., adj.', 'A2', 'ঠিক আছে; ভালো', 'Don''t worry, it''s all right.', 'চিন্তা করো না, সব ঠিক আছে।', 20),
    ('allow', null, 'v.', 'A2', 'অনুমতি দেওয়া', 'They do not allow pets here.', 'এখানে পোষা প্রাণী রাখার অনুমতি নেই।', 21),
    ('almost', null, 'adv.', 'A2', 'প্রায়', 'I am almost ready.', 'আমি প্রায় প্রস্তুত।', 22),
    ('alone', null, 'adv., adj.', 'A2', 'একা; একাকী', 'She lives alone.', 'সে একা থাকে।', 23),
    ('along', null, 'prep., adv.', 'A2', 'বরাবর; ধরে', 'We walked along the river.', 'আমরা নদী ধরে হাঁটলাম।', 24),
    ('already', null, 'adv.', 'A2', 'ইতিমধ্যে; এরই মধ্যে', 'I have already eaten.', 'আমি ইতিমধ্যে খেয়ে ফেলেছি।', 25),
    ('alternative', null, 'adj., n.', 'A2', 'বিকল্প', 'Is there an alternative plan?', 'কি কোনো বিকল্প পরিকল্পনা আছে?', 26),
    ('although', null, 'conj.', 'A2', 'যদিও', 'Although it rained, we went out.', 'যদিও বৃষ্টি হয়েছিল, আমরা বেরিয়েছিলাম।', 27),
    ('among', null, 'prep.', 'A2', 'মধ্যে; মাঝে (অনেকের)', 'She is popular among students.', 'সে ছাত্রদের মধ্যে জনপ্রিয়।', 28),
    ('amount', null, 'n., v.', 'A2', 'পরিমাণ', 'A large amount of water was wasted.', 'প্রচুর পরিমাণ পানি নষ্ট হলো।', 29),
    ('analyze', null, 'v.', 'A2', 'বিশ্লেষণ করা', 'We will analyze the results.', 'আমরা ফলাফল বিশ্লেষণ করব।', 30),
    ('ancient', null, 'adj.', 'A2', 'প্রাচীন', 'They visited an ancient temple.', 'তারা একটি প্রাচীন মন্দির দেখতে গেল।', 31),
    ('ankle', null, 'n.', 'A2', 'গোড়ালি', 'I hurt my ankle.', 'আমি আমার গোড়ালিতে ব্যথা পেয়েছি।', 32),
    ('anybody', null, 'pron.', 'A2', 'যে কেউ; কেউ', 'Is anybody there?', 'সেখানে কি কেউ আছে?', 33),
    ('anymore', null, 'adv.', 'A2', 'আর (নেতিবাচক অর্থে)', 'I don''t live there anymore.', 'আমি আর সেখানে থাকি না।', 34),
    ('anyway', null, 'adv.', 'A2', 'যাইহোক; তবুও', 'It''s late, but let''s go anyway.', 'দেরি হয়ে গেছে, তবুও চলো যাই।', 35),
    ('anywhere', null, 'pron., adv.', 'A2', 'যেকোনো জায়গায়; কোথাও', 'I can''t find it anywhere.', 'আমি এটি কোথাও খুঁজে পাচ্ছি না।', 36),
    ('app', null, 'n.', 'A2', 'অ্যাপ; অ্যাপ্লিকেশন', 'I downloaded a new app.', 'আমি একটি নতুন অ্যাপ ডাউনলোড করেছি।', 37),
    ('appear', null, 'v.', 'A2', 'আবির্ভূত হওয়া; মনে হওয়া', 'A star appeared in the sky.', 'আকাশে একটি তারা দেখা দিল।', 38),
    ('appearance', null, 'n.', 'A2', 'চেহারা; উপস্থিতি', 'She cares about her appearance.', 'সে তার চেহারা নিয়ে যত্নশীল।', 39),
    ('apply', null, 'v.', 'A2', 'আবেদন করা; প্রয়োগ করা', 'I want to apply for the job.', 'আমি চাকরিটির জন্য আবেদন করতে চাই।', 40),
    ('architect', null, 'n.', 'A2', 'স্থপতি; আর্কিটেক্ট', 'The architect designed the house.', 'স্থপতি বাড়িটির নকশা করলেন।', 41),
    ('architecture', null, 'n.', 'A2', 'স্থাপত্য', 'I love old architecture.', 'আমি প্রাচীন স্থাপত্য ভালোবাসি।', 42),
    ('argue', null, 'v.', 'A2', 'তর্ক করা; যুক্তি দেওয়া', 'They often argue about money.', 'তারা প্রায়ই টাকা নিয়ে তর্ক করে।', 43),
    ('argument', null, 'n.', 'A2', 'তর্ক; যুক্তি', 'They had a big argument.', 'তাদের মধ্যে একটি বড় তর্ক হলো।', 44),
    ('army', null, 'n.', 'A2', 'সেনাবাহিনী', 'He joined the army.', 'সে সেনাবাহিনীতে যোগ দিল।', 45),
    ('arrange', null, 'v.', 'A2', 'সাজানো; আয়োজন করা', 'Let''s arrange a meeting.', 'চলো একটি বৈঠকের আয়োজন করি।', 46),
    ('arrangement', null, 'n.', 'A2', 'ব্যবস্থা; আয়োজন', 'We made all the arrangements.', 'আমরা সব ব্যবস্থা করে ফেলেছি।', 47),
    ('asleep', null, 'adj.', 'A2', 'ঘুমন্ত; ঘুমিয়ে', 'The baby is asleep.', 'বাচ্চাটি ঘুমিয়ে আছে।', 48),
    ('assistant', null, 'adj., n.', 'A2', 'সহকারী', 'She is my new assistant.', 'সে আমার নতুন সহকারী।', 49),
    ('athlete', null, 'n.', 'A2', 'ক্রীড়াবিদ; খেলোয়াড়', 'He is a famous athlete.', 'সে একজন বিখ্যাত ক্রীড়াবিদ।', 50),
    ('attack', null, 'n., v.', 'A2', 'আক্রমণ করা', 'The dog did not attack.', 'কুকুরটি আক্রমণ করেনি।', 51),
    ('attend', null, 'v.', 'A2', 'উপস্থিত থাকা; যোগ দেওয়া', 'I will attend the class.', 'আমি ক্লাসে উপস্থিত থাকব।', 52),
    ('attention', null, 'n.', 'A2', 'মনোযোগ; নজর', 'Please pay attention.', 'দয়া করে মনোযোগ দাও।', 53),
    ('attractive', null, 'adj.', 'A2', 'আকর্ষণীয়', 'It is an attractive offer.', 'এটি একটি আকর্ষণীয় প্রস্তাব।', 54),
    ('audience', null, 'n.', 'A2', 'দর্শক; শ্রোতা', 'The audience clapped loudly.', 'দর্শকরা জোরে হাততালি দিল।', 55),
    ('author', null, 'n.', 'A2', 'লেখক; রচয়িতা', 'Who is the author of this book?', 'এই বইটির লেখক কে?', 56),
    ('available', null, 'adj.', 'A2', 'উপলব্ধ; পাওয়া যায়', 'Is this seat available?', 'এই আসনটি কি খালি আছে?', 57),
    ('average', null, 'adj., n., v.', 'A2', 'গড়; সাধারণ', 'His grades are above average.', 'তার নম্বর গড়ের চেয়ে বেশি।', 58),
    ('avoid', null, 'v.', 'A2', 'এড়িয়ে চলা', 'Try to avoid mistakes.', 'ভুল এড়ানোর চেষ্টা করো।', 59),
    ('award', null, 'n., v.', 'A2', 'পুরস্কার', 'She won an award.', 'সে একটি পুরস্কার জিতল।', 60),
    ('awful', null, 'adj.', 'A2', 'ভয়ানক; বাজে', 'The food tasted awful.', 'খাবারটির স্বাদ বাজে ছিল।', 61),
    ('background', null, 'n.', 'A2', 'পটভূমি; পশ্চাৎপট', 'There are hills in the background.', 'পটভূমিতে পাহাড় আছে।', 62),
    ('badly', null, 'adv.', 'A2', 'খারাপভাবে; ভীষণভাবে', 'He plays badly.', 'সে খারাপভাবে খেলে।', 63),
    ('based', null, 'adj.', 'A2', 'ভিত্তি করে; অবস্থিত', 'The movie is based on a book.', 'সিনেমাটি একটি বইয়ের উপর ভিত্তি করে তৈরি।', 64),
    ('bean', null, 'n.', 'A2', 'শিম; বিন', 'I like green beans.', 'আমি সবুজ শিম পছন্দ করি।', 65),
    ('bear', 'animal', 'n.', 'A2', 'ভালুক', 'A bear lives in the forest.', 'একটি ভালুক বনে বাস করে।', 66),
    ('beat', null, 'n., v.', 'A2', 'পরাজিত করা; আঘাত করা', 'Our team beat theirs.', 'আমাদের দল তাদের হারিয়ে দিল।', 67),
    ('beef', null, 'n.', 'A2', 'গরুর মাংস', 'We ate beef curry.', 'আমরা গরুর মাংসের তরকারি খেলাম।', 68),
    ('behave', null, 'v.', 'A2', 'আচরণ করা', 'The children behaved well.', 'বাচ্চারা ভালো আচরণ করল।', 69),
    ('behavior', null, 'n.', 'A2', 'আচরণ; ব্যবহার', 'His behavior was strange.', 'তার আচরণ অদ্ভুত ছিল।', 70),
    ('belong', null, 'v.', 'A2', 'অধিকারভুক্ত হওয়া; অন্তর্গত হওয়া', 'This book belongs to me.', 'এই বইটি আমার।', 71),
    ('belt', null, 'n.', 'A2', 'বেল্ট; কোমরবন্ধ', 'He wears a leather belt.', 'সে একটি চামড়ার বেল্ট পরে।', 72),
    ('benefit', null, 'n., v.', 'A2', 'উপকার; সুবিধা', 'Exercise has many benefits.', 'ব্যায়ামের অনেক উপকার আছে।', 73),
    ('billion', null, 'number', 'A2', 'একশত কোটি; বিলিয়ন', 'The company earned a billion dollars.', 'কোম্পানিটি একশ কোটি ডলার আয় করল।', 74),
    ('biology', null, 'n.', 'A2', 'জীববিজ্ঞান', 'Biology is the study of life.', 'জীববিজ্ঞান হলো জীবনের অধ্যয়ন।', 75),
    ('birth', null, 'n.', 'A2', 'জন্ম', 'What is your date of birth?', 'তোমার জন্ম তারিখ কী?', 76),
    ('bit', null, 'n.', 'A2', 'একটু; সামান্য অংশ', 'I am a bit tired.', 'আমি একটু ক্লান্ত।', 77),
    ('blank', null, 'adj., n.', 'A2', 'খালি; ফাঁকা', 'Fill in the blank.', 'শূন্যস্থান পূরণ করো।', 78),
    ('block', null, 'n., v.', 'A2', 'বাধা দেওয়া; খণ্ড; ব্লক', 'A tree blocked the road.', 'একটি গাছ রাস্তা আটকে দিল।', 79),
    ('blood', null, 'n.', 'A2', 'রক্ত', 'He gave blood at the hospital.', 'সে হাসপাতালে রক্ত দিল।', 80),
    ('blow', null, 'v.', 'A2', 'বইয়ে দেওয়া; ফুঁ দেওয়া', 'The wind is blowing hard.', 'বাতাস জোরে বইছে।', 81),
    ('board', null, 'n., v.', 'A2', 'বোর্ড; তক্তা; ওঠা', 'Write it on the board.', 'এটি বোর্ডে লেখো।', 82),
    ('boil', null, 'v.', 'A2', 'ফোটানো; সিদ্ধ করা', 'Boil the water first.', 'প্রথমে পানি ফুটাও।', 83),
    ('bone', null, 'n.', 'A2', 'হাড়', 'The dog has a bone.', 'কুকুরটির কাছে একটি হাড় আছে।', 84),
    ('borrow', null, 'v.', 'A2', 'ধার নেওয়া', 'Can I borrow your pen?', 'আমি কি তোমার কলমটি ধার নিতে পারি?', 85),
    ('boss', null, 'n.', 'A2', 'মালিক; বস', 'My boss is very kind.', 'আমার বস খুব দয়ালু।', 86),
    ('bottom', null, 'adj., n.', 'A2', 'তলা; নিচের অংশ', 'Look at the bottom of the page.', 'পৃষ্ঠার নিচের অংশে দেখো।', 87),
    ('bowl', null, 'n.', 'A2', 'বাটি; পাত্র', 'I ate a bowl of rice.', 'আমি এক বাটি ভাত খেলাম।', 88),
    ('brain', null, 'n.', 'A2', 'মস্তিষ্ক; মগজ', 'The brain controls the body.', 'মস্তিষ্ক শরীরকে নিয়ন্ত্রণ করে।', 89),
    ('bridge', null, 'n.', 'A2', 'সেতু; পুল', 'We crossed a long bridge.', 'আমরা একটি দীর্ঘ সেতু পার হলাম।', 90),
    ('bright', null, 'adj.', 'A2', 'উজ্জ্বল; ঝলমলে', 'The sun is very bright.', 'সূর্য খুব উজ্জ্বল।', 91),
    ('brilliant', null, 'adj.', 'A2', 'অসাধারণ; মেধাবী', 'That is a brilliant idea.', 'এটি একটি অসাধারণ ধারণা।', 92),
    ('broken', null, 'adj.', 'A2', 'ভাঙা; নষ্ট', 'The chair is broken.', 'চেয়ারটি ভাঙা।', 93),
    ('brush', null, 'n., v.', 'A2', 'ব্রাশ; মাজা', 'Brush your teeth twice a day.', 'দিনে দুইবার দাঁত ব্রাশ করো।', 94),
    ('burn', null, 'n., v.', 'A2', 'পোড়া; জ্বলা', 'Be careful, the stove can burn you.', 'সাবধান, চুলা তোমাকে পুড়িয়ে দিতে পারে।', 95),
    ('businessman', null, 'n.', 'A2', 'ব্যবসায়ী', 'He is a rich businessman.', 'সে একজন ধনী ব্যবসায়ী।', 96),
    ('button', null, 'n.', 'A2', 'বোতাম', 'Press the red button.', 'লাল বোতামটি চাপো।', 97),
    ('camp', null, 'n., v.', 'A2', 'শিবির; ক্যাম্প', 'We set up a camp near the river.', 'আমরা নদীর কাছে একটি ক্যাম্প বসালাম।', 98),
    ('camping', null, 'n.', 'A2', 'শিবির স্থাপন; ক্যাম্পিং', 'We went camping last weekend.', 'আমরা গত সপ্তাহান্তে ক্যাম্পিংয়ে গিয়েছিলাম।', 99),
    ('campus', null, 'n.', 'A2', 'ক্যাম্পাস; বিদ্যায়তন', 'The campus is very big.', 'ক্যাম্পাসটি খুব বড়।', 100),
    ('can', null, 'n.', 'A2', 'টিন; ক্যান', 'I bought a can of soup.', 'আমি এক ক্যান স্যুপ কিনলাম।', 101),
    ('candy', null, 'n.', 'A2', 'মিষ্টি; ক্যান্ডি; চকলেট', 'The child wants some candy.', 'শিশুটি কিছু মিষ্টি চায়।', 102),
    ('care', null, 'n., v.', 'A2', 'যত্ন; পরোয়া করা', 'Take care of your health.', 'তোমার স্বাস্থ্যের যত্ন নাও।', 103),
    ('careful', null, 'adj.', 'A2', 'সতর্ক; সাবধানী', 'Be careful on the road.', 'রাস্তায় সতর্ক থেকো।', 104),
    ('carefully', null, 'adv.', 'A2', 'সাবধানে; যত্নসহকারে', 'Read the question carefully.', 'প্রশ্নটি মন দিয়ে পড়ো।', 105),
    ('carpet', null, 'n.', 'A2', 'কার্পেট; গালিচা', 'There is a soft carpet on the floor.', 'মেঝেতে একটি নরম কার্পেট আছে।', 106),
    ('cartoon', null, 'n.', 'A2', 'কার্টুন', 'Children love cartoons.', 'বাচ্চারা কার্টুন খুব ভালোবাসে।', 107),
    ('case', null, 'n.', 'A2', 'ক্ষেত্র; মামলা; বাক্স', 'In that case, we will wait.', 'সেক্ষেত্রে, আমরা অপেক্ষা করব।', 108),
    ('cash', null, 'n.', 'A2', 'নগদ টাকা', 'I paid in cash.', 'আমি নগদ টাকায় পরিশোধ করলাম।', 109),
    ('catch', null, 'n., v.', 'A2', 'ধরা; লুফে নেওয়া', 'Catch the ball!', 'বলটি ধরো!', 110),
    ('cause', null, 'n., v.', 'A2', 'কারণ; ঘটানো', 'Rain can cause floods.', 'বৃষ্টি বন্যা ঘটাতে পারে।', 111),
    ('celebrate', null, 'v.', 'A2', 'উদযাপন করা', 'We celebrate Eid together.', 'আমরা একসাথে ঈদ উদযাপন করি।', 112),
    ('celebrity', null, 'n.', 'A2', 'তারকা; খ্যাতিমান ব্যক্তি', 'She is a famous celebrity.', 'সে একজন বিখ্যাত তারকা।', 113),
    ('cell', null, 'n.', 'A2', 'কোষ; কুঠুরি', 'The body has many cells.', 'শরীরে অনেক কোষ আছে।', 114),
    ('century', null, 'n.', 'A2', 'শতাব্দী; শতক', 'This castle is a century old.', 'এই দুর্গটি একশ বছরের পুরনো।', 115),
    ('certain', null, 'adj.', 'A2', 'নিশ্চিত; কোনো একটি', 'I am certain about the answer.', 'আমি উত্তরটি সম্পর্কে নিশ্চিত।', 116),
    ('certainly', null, 'adv.', 'A2', 'অবশ্যই; নিশ্চিতভাবে', 'I will certainly help you.', 'আমি অবশ্যই তোমাকে সাহায্য করব।', 117),
    ('chance', null, 'n.', 'A2', 'সুযোগ; সম্ভাবনা', 'Give me one more chance.', 'আমাকে আরও একটি সুযোগ দাও।', 118),
    ('character', null, 'n.', 'A2', 'চরিত্র', 'My favorite character is the hero.', 'আমার প্রিয় চরিত্র হলো নায়ক।', 119),
    ('charity', null, 'n.', 'A2', 'দাতব্য; দান', 'They gave money to charity.', 'তারা দাতব্য কাজে টাকা দিল।', 120),
    ('chat', null, 'n., v.', 'A2', 'আড্ডা; গল্প করা', 'We chatted for an hour.', 'আমরা এক ঘণ্টা আড্ডা দিলাম।', 121),
    ('chef', null, 'n.', 'A2', 'রাঁধুনি; শেফ', 'The chef made a great meal.', 'শেফ একটি দারুণ খাবার বানালেন।', 122),
    ('chemistry', null, 'n.', 'A2', 'রসায়ন', 'Chemistry is an interesting subject.', 'রসায়ন একটি আকর্ষণীয় বিষয়।', 123),
    ('chip', null, 'n.', 'A2', 'চিপ; ভাজা আলু', 'He ate a bag of chips.', 'সে এক প্যাকেট চিপস খেল।', 124),
    ('choice', null, 'n.', 'A2', 'পছন্দ; নির্বাচন', 'It was a good choice.', 'এটি একটি ভালো পছন্দ ছিল।', 125),
    ('church', null, 'n.', 'A2', 'গির্জা', 'They go to church on Sunday.', 'তারা রবিবারে গির্জায় যায়।', 126),
    ('cigarette', null, 'n.', 'A2', 'সিগারেট', 'Smoking cigarettes is harmful.', 'সিগারেট খাওয়া ক্ষতিকর।', 127),
    ('circle', null, 'n., v.', 'A2', 'বৃত্ত; গোল', 'Draw a circle here.', 'এখানে একটি বৃত্ত আঁকো।', 128),
    ('classical', null, 'adj.', 'A2', 'শাস্ত্রীয়; ধ্রুপদী', 'She likes classical music.', 'সে শাস্ত্রীয় সঙ্গীত পছন্দ করে।', 129),
    ('clear', null, 'adj., v.', 'A2', 'পরিষ্কার; স্পষ্ট', 'The sky is clear today.', 'আজ আকাশ পরিষ্কার।', 130),
    ('clearly', null, 'adv.', 'A2', 'স্পষ্টভাবে', 'Please speak clearly.', 'দয়া করে স্পষ্টভাবে কথা বলো।', 131),
    ('clerk', null, 'n.', 'A2', 'কেরানি; বিক্রয়কর্মী', 'The clerk helped me.', 'কেরানিটি আমাকে সাহায্য করল।', 132),
    ('climate', null, 'n.', 'A2', 'জলবায়ু', 'The climate here is warm.', 'এখানকার জলবায়ু উষ্ণ।', 133),
    ('close', 'near', 'adv., adj.', 'A2', 'কাছাকাছি; নিকটবর্তী', 'The station is close to my home.', 'স্টেশনটি আমার বাড়ির কাছাকাছি।', 134),
    ('closed', null, 'adj.', 'A2', 'বন্ধ', 'The shop is closed today.', 'দোকানটি আজ বন্ধ।', 135),
    ('closet', null, 'n.', 'A2', 'আলমারি; দেয়াল-আলমারি', 'Her clothes are in the closet.', 'তার জামাকাপড় আলমারিতে আছে।', 136),
    ('clothing', null, 'n.', 'A2', 'পোশাক; বস্ত্র', 'They sell winter clothing.', 'তারা শীতের পোশাক বিক্রি করে।', 137),
    ('cloud', null, 'n.', 'A2', 'মেঘ', 'There are dark clouds in the sky.', 'আকাশে কালো মেঘ আছে।', 138),
    ('coach', null, 'n., v.', 'A2', 'প্রশিক্ষক; কোচ', 'The coach trained the team.', 'কোচ দলটিকে প্রশিক্ষণ দিলেন।', 139),
    ('coast', null, 'n.', 'A2', 'উপকূল; সমুদ্রতট', 'We drove along the coast.', 'আমরা উপকূল ধরে গাড়ি চালালাম।', 140),
    ('code', null, 'n.', 'A2', 'সংকেত; কোড', 'Enter your secret code.', 'তোমার গোপন কোডটি লেখো।', 141),
    ('colleague', null, 'n.', 'A2', 'সহকর্মী', 'She is my colleague at work.', 'সে কর্মক্ষেত্রে আমার সহকর্মী।', 142),
    ('collect', null, 'v.', 'A2', 'সংগ্রহ করা', 'He collects old coins.', 'সে পুরনো মুদ্রা সংগ্রহ করে।', 143),
    ('column', null, 'n.', 'A2', 'স্তম্ভ; কলাম', 'Add up the numbers in this column.', 'এই কলামের সংখ্যাগুলো যোগ করো।', 144),
    ('comedy', null, 'n.', 'A2', 'কমেডি; হাস্যরস', 'We watched a funny comedy.', 'আমরা একটি মজার কমেডি দেখলাম।', 145),
    ('comfortable', null, 'adj.', 'A2', 'আরামদায়ক', 'This chair is very comfortable.', 'এই চেয়ারটি খুব আরামদায়ক।', 146),
    ('comment', null, 'n., v.', 'A2', 'মন্তব্য', 'She made a kind comment.', 'সে একটি দয়ালু মন্তব্য করল।', 147),
    ('communicate', null, 'v.', 'A2', 'যোগাযোগ করা; ভাব বিনিময় করা', 'We communicate by email.', 'আমরা ইমেইলে যোগাযোগ করি।', 148),
    ('community', null, 'n.', 'A2', 'সম্প্রদায়; সমাজ', 'Our community is very friendly.', 'আমাদের সম্প্রদায় খুব বন্ধুত্বপূর্ণ।', 149),
    ('compete', null, 'v.', 'A2', 'প্রতিযোগিতা করা', 'Ten teams will compete.', 'দশটি দল প্রতিযোগিতা করবে।', 150),
    ('competition', null, 'n.', 'A2', 'প্রতিযোগিতা', 'She won the singing competition.', 'সে গানের প্রতিযোগিতায় জিতল।', 151),
    ('complain', null, 'v.', 'A2', 'অভিযোগ করা', 'He complained about the noise.', 'সে শব্দ নিয়ে অভিযোগ করল।', 152),
    ('completely', null, 'adv.', 'A2', 'সম্পূর্ণরূপে; পুরোপুরি', 'I completely agree.', 'আমি পুরোপুরি একমত।', 153),
    ('condition', null, 'n.', 'A2', 'অবস্থা; শর্ত', 'The car is in good condition.', 'গাড়িটি ভালো অবস্থায় আছে।', 154),
    ('conference', null, 'n.', 'A2', 'সম্মেলন; সভা', 'He spoke at the conference.', 'তিনি সম্মেলনে বক্তব্য দিলেন।', 155),
    ('connect', null, 'v.', 'A2', 'সংযোগ করা; যুক্ত করা', 'Connect the printer to the computer.', 'প্রিন্টারটি কম্পিউটারের সাথে যুক্ত করো।', 156),
    ('connected', null, 'adj.', 'A2', 'সংযুক্ত', 'My phone is connected to the internet.', 'আমার ফোন ইন্টারনেটের সাথে সংযুক্ত।', 157),
    ('consider', null, 'v.', 'A2', 'বিবেচনা করা', 'Please consider my request.', 'দয়া করে আমার অনুরোধটি বিবেচনা করো।', 158),
    ('contain', null, 'v.', 'A2', 'ধারণ করা; থাকা', 'This box contains books.', 'এই বাক্সে বই আছে।', 159),
    ('context', null, 'n.', 'A2', 'প্রসঙ্গ; পরিপ্রেক্ষিত', 'Guess the meaning from the context.', 'প্রসঙ্গ থেকে অর্থ অনুমান করো।', 160),
    ('continent', null, 'n.', 'A2', 'মহাদেশ', 'Asia is the largest continent.', 'এশিয়া সবচেয়ে বড় মহাদেশ।', 161),
    ('continue', null, 'v.', 'A2', 'চালিয়ে যাওয়া; অব্যাহত রাখা', 'Please continue reading.', 'দয়া করে পড়া চালিয়ে যাও।', 162),
    ('control', null, 'n., v.', 'A2', 'নিয়ন্ত্রণ করা', 'He cannot control his anger.', 'সে তার রাগ নিয়ন্ত্রণ করতে পারে না।', 163),
    ('cookie', null, 'n.', 'A2', 'কুকি; বিস্কুট', 'She baked chocolate cookies.', 'সে চকলেট কুকি বানাল।', 164),
    ('copy', null, 'n., v.', 'A2', 'অনুলিপি; নকল করা', 'Make a copy of this page.', 'এই পৃষ্ঠার একটি অনুলিপি বানাও।', 165),
    ('corner', null, 'n.', 'A2', 'কোণ; মোড়', 'The shop is on the corner.', 'দোকানটি মোড়ের উপর।', 166),
    ('correctly', null, 'adv.', 'A2', 'সঠিকভাবে; শুদ্ধভাবে', 'Answer the question correctly.', 'প্রশ্নটির সঠিক উত্তর দাও।', 167),
    ('count', null, 'n., v.', 'A2', 'গণনা করা; গোনা', 'Count from one to ten.', 'এক থেকে দশ পর্যন্ত গোনো।', 168),
    ('couple', null, 'n.', 'A2', 'জোড়া; দম্পতি', 'A young couple lives next door.', 'একটি তরুণ দম্পতি পাশের বাড়িতে থাকে।', 169),
    ('cover', null, 'n., v.', 'A2', 'ঢাকা; আবরণ', 'Cover the pot with a lid.', 'পাত্রটি ঢাকনা দিয়ে ঢেকে দাও।', 170),
    ('crazy', null, 'adj.', 'A2', 'পাগল; উন্মাদ', 'That is a crazy idea.', 'এটি একটি পাগলাটে ধারণা।', 171),
    ('creative', null, 'adj.', 'A2', 'সৃজনশীল', 'She is a creative artist.', 'সে একজন সৃজনশীল শিল্পী।', 172),
    ('credit', null, 'n., v.', 'A2', 'ধার; ক্রেডিট; কৃতিত্ব', 'I paid with a credit card.', 'আমি ক্রেডিট কার্ড দিয়ে পরিশোধ করলাম।', 173),
    ('crime', null, 'n.', 'A2', 'অপরাধ', 'Stealing is a crime.', 'চুরি করা একটি অপরাধ।', 174),
    ('criminal', null, 'adj., n.', 'A2', 'অপরাধী', 'The police caught the criminal.', 'পুলিশ অপরাধীটিকে ধরল।', 175),
    ('cross', null, 'n., v.', 'A2', 'অতিক্রম করা; পার হওয়া', 'Cross the road carefully.', 'সাবধানে রাস্তা পার হও।', 176),
    ('crowd', null, 'n.', 'A2', 'ভিড়; জনতা', 'A big crowd gathered.', 'একটি বড় ভিড় জমল।', 177),
    ('crowded', null, 'adj.', 'A2', 'ভিড়ে ঠাসা; জনাকীর্ণ', 'The bus was very crowded.', 'বাসটি খুব ভিড়ে ঠাসা ছিল।', 178),
    ('cry', null, 'n., v.', 'A2', 'কাঁদা; কান্না', 'The baby began to cry.', 'বাচ্চাটি কাঁদতে শুরু করল।', 179),
    ('curly', null, 'adj.', 'A2', 'কোঁকড়া', 'She has curly hair.', 'তার কোঁকড়া চুল।', 180),
    ('cycle', null, 'n., v.', 'A2', 'চক্র; সাইকেল চালানো', 'I cycle to work every day.', 'আমি প্রতিদিন সাইকেল চালিয়ে কাজে যাই।', 181),
    ('daily', null, 'adv., adj.', 'A2', 'দৈনিক; প্রতিদিনের', 'Reading is part of my daily routine.', 'পড়া আমার দৈনিক রুটিনের অংশ।', 182),
    ('danger', null, 'n.', 'A2', 'বিপদ', 'The sign warns of danger.', 'চিহ্নটি বিপদের সতর্কবার্তা দেয়।', 183),
    ('data', null, 'n.', 'A2', 'তথ্য; উপাত্ত', 'We collected a lot of data.', 'আমরা অনেক তথ্য সংগ্রহ করলাম।', 184),
    ('dead', null, 'adj.', 'A2', 'মৃত', 'The plant is dead.', 'গাছটি মৃত।', 185),
    ('deal', null, 'n., v.', 'A2', 'চুক্তি; মোকাবিলা করা', 'We made a good deal.', 'আমরা একটি ভালো চুক্তি করলাম।', 186),
    ('death', null, 'n.', 'A2', 'মৃত্যু', 'His death made everyone sad.', 'তার মৃত্যুতে সবাই শোকাহত হলো।', 187),
    ('decision', null, 'n.', 'A2', 'সিদ্ধান্ত', 'It was a hard decision.', 'এটি একটি কঠিন সিদ্ধান্ত ছিল।', 188),
    ('deep', null, 'adv., adj.', 'A2', 'গভীর', 'The lake is very deep.', 'হ্রদটি খুব গভীর।', 189),
    ('definitely', null, 'adv.', 'A2', 'নিশ্চিতভাবে; অবশ্যই', 'I will definitely come.', 'আমি অবশ্যই আসব।', 190),
    ('degree', null, 'n.', 'A2', 'ডিগ্রি; মাত্রা', 'It is thirty degrees today.', 'আজ তাপমাত্রা ত্রিশ ডিগ্রি।', 191),
    ('dentist', null, 'n.', 'A2', 'দন্তচিকিৎসক', 'I visit the dentist twice a year.', 'আমি বছরে দুইবার দন্তচিকিৎসকের কাছে যাই।', 192),
    ('department', null, 'n.', 'A2', 'বিভাগ; দপ্তর', 'She works in the sales department.', 'সে বিক্রয় বিভাগে কাজ করে।', 193),
    ('depend', null, 'v.', 'A2', 'নির্ভর করা', 'It depends on the weather.', 'এটি আবহাওয়ার উপর নির্ভর করে।', 194),
    ('desert', null, 'n., v.', 'A2', 'মরুভূমি', 'Camels live in the desert.', 'উট মরুভূমিতে বাস করে।', 195),
    ('designer', null, 'n.', 'A2', 'নকশাকার; ডিজাইনার', 'She is a fashion designer.', 'সে একজন ফ্যাশন ডিজাইনার।', 196),
    ('dessert', null, 'n.', 'A2', 'মিষ্টান্ন (খাবারের শেষে)', 'We had ice cream for dessert.', 'আমরা মিষ্টান্ন হিসেবে আইসক্রিম খেলাম।', 197),
    ('destroy', null, 'v.', 'A2', 'ধ্বংস করা', 'The storm destroyed the house.', 'ঝড়টি বাড়িটি ধ্বংস করে দিল।', 198),
    ('detective', null, 'n.', 'A2', 'গোয়েন্দা', 'The detective solved the case.', 'গোয়েন্দাটি রহস্যটির সমাধান করল।', 199),
    ('develop', null, 'v.', 'A2', 'উন্নয়ন করা; বিকশিত করা', 'They want to develop the area.', 'তারা এলাকাটির উন্নয়ন করতে চায়।', 200),
    ('device', null, 'n.', 'A2', 'যন্ত্র; ডিভাইস', 'This is a useful device.', 'এটি একটি দরকারি যন্ত্র।', 201),
    ('diary', null, 'n.', 'A2', 'দিনলিপি; ডায়েরি', 'She writes in her diary daily.', 'সে প্রতিদিন তার ডায়েরিতে লেখে।', 202),
    ('differently', null, 'adv.', 'A2', 'ভিন্নভাবে', 'He thinks differently.', 'সে ভিন্নভাবে চিন্তা করে।', 203),
    ('digital', null, 'adj.', 'A2', 'ডিজিটাল', 'I bought a digital watch.', 'আমি একটি ডিজিটাল ঘড়ি কিনলাম।', 204),
    ('direct', null, 'adv., adj., v.', 'A2', 'সরাসরি; সোজা; পরিচালনা করা', 'This is a direct flight.', 'এটি একটি সরাসরি ফ্লাইট।', 205),
    ('direction', null, 'n.', 'A2', 'দিক; নির্দেশনা', 'Which direction is the station?', 'স্টেশনটি কোন দিকে?', 206),
    ('director', null, 'n.', 'A2', 'পরিচালক', 'He is a movie director.', 'সে একজন সিনেমা পরিচালক।', 207),
    ('disagree', null, 'v.', 'A2', 'দ্বিমত পোষণ করা', 'I disagree with that plan.', 'আমি সেই পরিকল্পনার সাথে দ্বিমত পোষণ করি।', 208),
    ('disappear', null, 'v.', 'A2', 'অদৃশ্য হওয়া; উধাও হওয়া', 'The sun disappeared behind a cloud.', 'সূর্য একটি মেঘের আড়ালে অদৃশ্য হয়ে গেল।', 209),
    ('disaster', null, 'n.', 'A2', 'দুর্যোগ; বিপর্যয়', 'The flood was a disaster.', 'বন্যাটি একটি দুর্যোগ ছিল।', 210),
    ('discover', null, 'v.', 'A2', 'আবিষ্কার করা; খুঁজে পাওয়া', 'They discovered a new island.', 'তারা একটি নতুন দ্বীপ আবিষ্কার করল।', 211),
    ('discovery', null, 'n.', 'A2', 'আবিষ্কার', 'It was an important discovery.', 'এটি একটি গুরুত্বপূর্ণ আবিষ্কার ছিল।', 212),
    ('discussion', null, 'n.', 'A2', 'আলোচনা', 'We had a long discussion.', 'আমাদের একটি দীর্ঘ আলোচনা হলো।', 213),
    ('disease', null, 'n.', 'A2', 'রোগ; ব্যাধি', 'This disease is rare.', 'এই রোগটি বিরল।', 214),
    ('distance', null, 'n.', 'A2', 'দূরত্ব', 'What is the distance to the city?', 'শহরটির দূরত্ব কত?', 215),
    ('divorced', null, 'adj.', 'A2', 'তালাকপ্রাপ্ত; বিবাহবিচ্ছিন্ন', 'Her parents are divorced.', 'তার বাবা-মা বিবাহবিচ্ছিন্ন।', 216),
    ('document', null, 'n., v.', 'A2', 'নথি; দলিল', 'Sign this document, please.', 'দয়া করে এই নথিতে স্বাক্ষর করুন।', 217),
    ('double', null, 'pron., det., adv., adj., v.', 'A2', 'দ্বিগুণ; জোড়া', 'I need a double room.', 'আমার একটি ডাবল রুম দরকার।', 218),
    ('download', null, 'n., v.', 'A2', 'ডাউনলোড করা', 'Download the file here.', 'ফাইলটি এখানে ডাউনলোড করো।', 219),
    ('downtown', null, 'adv., adj., n.', 'A2', 'শহরের কেন্দ্র; ডাউনটাউন', 'We went downtown for shopping.', 'আমরা কেনাকাটার জন্য শহরের কেন্দ্রে গেলাম।', 220),
    ('drama', null, 'n.', 'A2', 'নাটক', 'She studies drama at college.', 'সে কলেজে নাটক নিয়ে পড়াশোনা করে।', 221),
    ('drawing', null, 'n.', 'A2', 'অঙ্কন; ছবি আঁকা', 'This is a nice drawing.', 'এটি একটি সুন্দর অঙ্কন।', 222),
    ('dream', null, 'n., v.', 'A2', 'স্বপ্ন', 'I had a strange dream.', 'আমি একটি অদ্ভুত স্বপ্ন দেখলাম।', 223),
    ('driving', null, 'n.', 'A2', 'গাড়ি চালানো', 'Driving at night is hard.', 'রাতে গাড়ি চালানো কঠিন।', 224),
    ('drop', null, 'n., v.', 'A2', 'ফোঁটা; ফেলে দেওয়া; পড়া', 'Do not drop the glass.', 'গ্লাসটি ফেলে দিও না।', 225),
    ('drug', null, 'n.', 'A2', 'ওষুধ; মাদক', 'The doctor gave me a drug.', 'ডাক্তার আমাকে একটি ওষুধ দিলেন।', 226),
    ('dry', null, 'adj., v.', 'A2', 'শুকনো; শুকানো', 'The towel is dry.', 'তোয়ালেটি শুকনো।', 227),
    ('earn', null, 'v.', 'A2', 'উপার্জন করা; রোজগার করা', 'She earns a good salary.', 'সে ভালো বেতন উপার্জন করে।', 228),
    ('earth', null, 'n.', 'A2', 'পৃথিবী; মাটি', 'The earth moves around the sun.', 'পৃথিবী সূর্যের চারদিকে ঘোরে।', 229),
    ('easily', null, 'adv.', 'A2', 'সহজে', 'He solved it easily.', 'সে এটি সহজে সমাধান করল।', 230),
    ('education', null, 'n.', 'A2', 'শিক্ষা', 'Education is very important.', 'শিক্ষা খুব গুরুত্বপূর্ণ।', 231),
    ('effect', null, 'n.', 'A2', 'প্রভাব; ফলাফল', 'The medicine had a good effect.', 'ওষুধটির ভালো প্রভাব পড়ল।', 232),
    ('either', null, 'pron., det., adv.', 'A2', 'দুটির যেকোনো একটি; কোনোটিও (না)', 'You can take either book.', 'তুমি দুটোর যেকোনো বই নিতে পারো।', 233),
    ('electric', null, 'adj.', 'A2', 'বৈদ্যুতিক', 'This is an electric car.', 'এটি একটি বৈদ্যুতিক গাড়ি।', 234),
    ('electrical', null, 'adj.', 'A2', 'বিদ্যুৎ সংক্রান্ত', 'He is an electrical engineer.', 'সে একজন বৈদ্যুতিক প্রকৌশলী।', 235),
    ('electricity', null, 'n.', 'A2', 'বিদ্যুৎ', 'There is no electricity now.', 'এখন বিদ্যুৎ নেই।', 236),
    ('electronic', null, 'adj.', 'A2', 'ইলেকট্রনিক', 'They sell electronic goods.', 'তারা ইলেকট্রনিক পণ্য বিক্রি করে।', 237),
    ('elevator', null, 'n.', 'A2', 'লিফট; উত্তোলক', 'Take the elevator to the fifth floor.', 'পাঁচতলায় যেতে লিফট নাও।', 238),
    ('employ', null, 'v.', 'A2', 'নিয়োগ করা; চাকরি দেওয়া', 'The factory employs many people.', 'কারখানাটি অনেক লোককে নিয়োগ করে।', 239),
    ('employee', null, 'n.', 'A2', 'কর্মচারী', 'She is a hard-working employee.', 'সে একজন পরিশ্রমী কর্মচারী।', 240),
    ('employer', null, 'n.', 'A2', 'নিয়োগকর্তা; মালিক', 'My employer is very fair.', 'আমার নিয়োগকর্তা খুব ন্যায়পরায়ণ।', 241),
    ('empty', null, 'adj., v.', 'A2', 'খালি; শূন্য', 'The bottle is empty.', 'বোতলটি খালি।', 242),
    ('ending', null, 'n.', 'A2', 'সমাপ্তি; শেষাংশ', 'The movie has a happy ending.', 'সিনেমাটির একটি সুখী সমাপ্তি আছে।', 243),
    ('energy', null, 'n.', 'A2', 'শক্তি; কর্মশক্তি', 'Children have a lot of energy.', 'বাচ্চাদের অনেক কর্মশক্তি থাকে।', 244),
    ('engine', null, 'n.', 'A2', 'ইঞ্জিন; যন্ত্র', 'The car engine is broken.', 'গাড়ির ইঞ্জিনটি নষ্ট।', 245),
    ('engineer', null, 'n.', 'A2', 'প্রকৌশলী; ইঞ্জিনিয়ার', 'My father is an engineer.', 'আমার বাবা একজন প্রকৌশলী।', 246),
    ('enormous', null, 'adj.', 'A2', 'বিশাল; প্রকাণ্ড', 'The building is enormous.', 'ভবনটি বিশাল।', 247),
    ('enter', null, 'v.', 'A2', 'প্রবেশ করা; ঢোকা', 'Please enter the room quietly.', 'দয়া করে চুপচাপ ঘরে প্রবেশ করো।', 248),
    ('environment', null, 'n.', 'A2', 'পরিবেশ', 'We must protect the environment.', 'আমাদের পরিবেশ রক্ষা করতে হবে।', 249),
    ('equipment', null, 'n.', 'A2', 'সরঞ্জাম; যন্ত্রপাতি', 'The gym has new equipment.', 'জিমে নতুন সরঞ্জাম আছে।', 250),
    ('error', null, 'n.', 'A2', 'ভুল; ত্রুটি', 'There is an error in the report.', 'প্রতিবেদনে একটি ত্রুটি আছে।', 251),
    ('especially', null, 'adv.', 'A2', 'বিশেষত; বিশেষ করে', 'I love fruit, especially mangoes.', 'আমি ফল ভালোবাসি, বিশেষ করে আম।', 252),
    ('essay', null, 'n.', 'A2', 'প্রবন্ধ; রচনা', 'I wrote an essay about my city.', 'আমি আমার শহর নিয়ে একটি রচনা লিখলাম।', 253),
    ('everyday', null, 'adj.', 'A2', 'প্রাত্যহিক; দৈনন্দিন', 'These are everyday problems.', 'এগুলো দৈনন্দিন সমস্যা।', 254),
    ('everywhere', null, 'adv.', 'A2', 'সর্বত্র; সব জায়গায়', 'I looked everywhere for my keys.', 'আমি আমার চাবি সব জায়গায় খুঁজলাম।', 255),
    ('evidence', null, 'n.', 'A2', 'প্রমাণ; সাক্ষ্য', 'There is no evidence of this.', 'এর কোনো প্রমাণ নেই।', 256),
    ('exact', null, 'adj.', 'A2', 'সঠিক; হুবহু', 'What is the exact time?', 'সঠিক সময় কত?', 257),
    ('exactly', null, 'adv.', 'A2', 'ঠিক; হুবহু', 'That is exactly what I meant.', 'আমি ঠিক এটাই বোঝাতে চেয়েছিলাম।', 258),
    ('excellent', null, 'adj.', 'A2', 'চমৎকার; উৎকৃষ্ট', 'Your work is excellent.', 'তোমার কাজ চমৎকার।', 259),
    ('except', null, 'prep., conj.', 'A2', 'ছাড়া; ব্যতীত', 'Everyone came except Ali.', 'আলি ছাড়া সবাই এসেছিল।', 260),
    ('exist', null, 'v.', 'A2', 'অস্তিত্ব থাকা; বিদ্যমান থাকা', 'Do ghosts exist?', 'ভূত কি সত্যিই আছে?', 261),
    ('expect', null, 'v.', 'A2', 'আশা করা; প্রত্যাশা করা', 'I expect good news.', 'আমি ভালো খবর আশা করছি।', 262),
    ('experience', null, 'n., v.', 'A2', 'অভিজ্ঞতা', 'She has teaching experience.', 'তার শিক্ষকতার অভিজ্ঞতা আছে।', 263),
    ('experiment', null, 'n., v.', 'A2', 'পরীক্ষা-নিরীক্ষা', 'We did a science experiment.', 'আমরা একটি বিজ্ঞান পরীক্ষা করলাম।', 264),
    ('expert', null, 'adj., n.', 'A2', 'বিশেষজ্ঞ', 'He is a computer expert.', 'সে একজন কম্পিউটার বিশেষজ্ঞ।', 265),
    ('explanation', null, 'n.', 'A2', 'ব্যাখ্যা', 'Thanks for the clear explanation.', 'স্পষ্ট ব্যাখ্যার জন্য ধন্যবাদ।', 266),
    ('express', null, 'v.', 'A2', 'প্রকাশ করা; ব্যক্ত করা', 'She expressed her thanks.', 'সে তার কৃতজ্ঞতা প্রকাশ করল।', 267),
    ('expression', null, 'n.', 'A2', 'অভিব্যক্তি; প্রকাশভঙ্গি', 'He had a happy expression.', 'তার মুখে খুশির অভিব্যক্তি ছিল।', 268),
    ('extreme', null, 'adj., n.', 'A2', 'চরম; অত্যধিক', 'The desert has extreme heat.', 'মরুভূমিতে চরম গরম থাকে।', 269),
    ('extremely', null, 'adv.', 'A2', 'অত্যন্ত; ভীষণভাবে', 'It is extremely cold today.', 'আজ ভীষণ ঠান্ডা।', 270),
    ('factor', null, 'n.', 'A2', 'উপাদান; কারণ', 'Price is an important factor.', 'দাম একটি গুরুত্বপূর্ণ উপাদান।', 271),
    ('factory', null, 'n.', 'A2', 'কারখানা', 'He works in a car factory.', 'সে একটি গাড়ির কারখানায় কাজ করে।', 272),
    ('fail', null, 'v.', 'A2', 'ব্যর্থ হওয়া; ফেল করা', 'Do not be afraid to fail.', 'ব্যর্থ হতে ভয় পেয়ো না।', 273),
    ('fair', null, 'adj.', 'A2', 'ন্যায্য; সুষ্ঠু', 'That is not a fair decision.', 'এটি একটি ন্যায্য সিদ্ধান্ত নয়।', 274),
    ('fan', null, 'n.', 'A2', 'পাখা; ভক্ত', 'Turn on the fan, please.', 'দয়া করে পাখাটি চালু করো।', 275),
    ('farming', null, 'n.', 'A2', 'কৃষিকাজ; চাষবাস', 'Farming is hard work.', 'কৃষিকাজ কঠোর পরিশ্রমের কাজ।', 276),
    ('fashion', null, 'n.', 'A2', 'ফ্যাশন; হাল-চাল', 'She follows the latest fashion.', 'সে সর্বশেষ ফ্যাশন অনুসরণ করে।', 277),
    ('fear', null, 'n., v.', 'A2', 'ভয়; ভীতি', 'He has a fear of heights.', 'তার উচ্চতার ভয় আছে।', 278),
    ('feature', null, 'n., v.', 'A2', 'বৈশিষ্ট্য', 'This phone has a new feature.', 'এই ফোনটিতে একটি নতুন বৈশিষ্ট্য আছে।', 279),
    ('feed', null, 'n., v.', 'A2', 'খাওয়ানো', 'I feed my cat every morning.', 'আমি প্রতিদিন সকালে আমার বিড়ালকে খাওয়াই।', 280),
    ('female', null, 'adj., n.', 'A2', 'স্ত্রী; নারী', 'A female lion is called a lioness.', 'স্ত্রী সিংহকে সিংহী বলা হয়।', 281),
    ('fever', null, 'n.', 'A2', 'জ্বর', 'She has a high fever.', 'তার প্রচণ্ড জ্বর।', 282),
    ('fiction', null, 'n.', 'A2', 'কল্পকাহিনী; কথাসাহিত্য', 'I enjoy reading fiction.', 'আমি কল্পকাহিনী পড়তে উপভোগ করি।', 283),
    ('field', null, 'n.', 'A2', 'মাঠ; ক্ষেত্র', 'The cows are in the field.', 'গরুগুলো মাঠে আছে।', 284),
    ('fight', null, 'n., v.', 'A2', 'লড়াই; মারামারি করা', 'The boys had a fight.', 'ছেলেরা মারামারি করল।', 285),
    ('figure', null, 'n., v.', 'A2', 'সংখ্যা; আকৃতি; মূর্তি', 'Write the figure in words.', 'সংখ্যাটি কথায় লেখো।', 286),
    ('film', null, 'n., v.', 'A2', 'চলচ্চিত্র; ফিল্ম', 'We saw a good film.', 'আমরা একটি ভালো ফিল্ম দেখলাম।', 287),
    ('finally', null, 'adv.', 'A2', 'অবশেষে; শেষ পর্যন্ত', 'Finally, the bus arrived.', 'অবশেষে, বাসটি এল।', 288),
    ('finger', null, 'n.', 'A2', 'আঙুল', 'She hurt her finger.', 'সে তার আঙুলে ব্যথা পেল।', 289),
    ('fishing', null, 'n.', 'A2', 'মাছ ধরা', 'My uncle likes fishing.', 'আমার চাচা মাছ ধরতে পছন্দ করেন।', 290),
    ('fit', null, 'adj., v.', 'A2', 'মানানসই; সুস্থ; মাপসই হওয়া', 'This shirt does not fit me.', 'এই শার্টটি আমার গায়ে হয় না।', 291),
    ('fix', null, 'n., v.', 'A2', 'মেরামত করা; ঠিক করা', 'Can you fix my bike?', 'তুমি কি আমার সাইকেলটি ঠিক করতে পারবে?', 292),
    ('flat', null, 'adj.', 'A2', 'সমতল; চ্যাপ্টা', 'The land here is flat.', 'এখানকার জমি সমতল।', 293),
    ('flu', null, 'n.', 'A2', 'ফ্লু; সর্দি-জ্বর', 'He is in bed with the flu.', 'সে ফ্লুতে আক্রান্ত হয়ে বিছানায় আছে।', 294),
    ('flying', null, 'adj., n.', 'A2', 'উড়ন্ত; ওড়া', 'I am afraid of flying.', 'আমি বিমানে ওড়াকে ভয় পাই।', 295),
    ('focus', null, 'n., v.', 'A2', 'মনোনিবেশ করা; কেন্দ্রীভূত করা', 'Focus on your studies.', 'তোমার পড়াশোনায় মনোনিবেশ করো।', 296),
    ('following', null, 'prep., adj., n.', 'A2', 'নিম্নলিখিত; পরবর্তী', 'Answer the following questions.', 'নিম্নলিখিত প্রশ্নগুলোর উত্তর দাও।', 297),
    ('foreign', null, 'adj.', 'A2', 'বিদেশি', 'She speaks a foreign language.', 'সে একটি বিদেশি ভাষায় কথা বলে।', 298),
    ('forest', null, 'n.', 'A2', 'বন; জঙ্গল', 'Many animals live in the forest.', 'অনেক প্রাণী বনে বাস করে।', 299),
    ('fork', null, 'n.', 'A2', 'কাঁটাচামচ', 'Eat the cake with a fork.', 'কাঁটাচামচ দিয়ে কেকটি খাও।', 300),
    ('formal', null, 'adj.', 'A2', 'আনুষ্ঠানিক; ফরমাল', 'He wore formal clothes.', 'সে আনুষ্ঠানিক পোশাক পরেছিল।', 301),
    ('fortunately', null, 'adv.', 'A2', 'সৌভাগ্যক্রমে', 'Fortunately, no one was hurt.', 'সৌভাগ্যক্রমে, কেউ আহত হয়নি।', 302),
    ('forward', null, 'adv., adj.', 'A2', 'সামনের দিকে; অগ্রসর', 'Please move forward.', 'দয়া করে সামনের দিকে এগোও।', 303),
    ('fresh', null, 'adj.', 'A2', 'তাজা; সতেজ', 'I bought fresh vegetables.', 'আমি তাজা সবজি কিনলাম।', 304),
    ('frog', null, 'n.', 'A2', 'ব্যাঙ', 'A frog jumped into the pond.', 'একটি ব্যাঙ পুকুরে লাফ দিল।', 305),
    ('furniture', null, 'n.', 'A2', 'আসবাবপত্র', 'They bought new furniture.', 'তারা নতুন আসবাবপত্র কিনল।', 306),
    ('further', null, 'adv., adj.', 'A2', 'আরও দূরে; অতিরিক্ত', 'We walked further into the woods.', 'আমরা বনের আরও গভীরে হাঁটলাম।', 307),
    ('gallery', null, 'n.', 'A2', 'চিত্রশালা; গ্যালারি', 'We visited an art gallery.', 'আমরা একটি চিত্রশালা দেখতে গেলাম।', 308),
    ('gap', null, 'n.', 'A2', 'ফাঁক; ব্যবধান', 'There is a gap in the fence.', 'বেড়ায় একটি ফাঁক আছে।', 309),
    ('garbage', null, 'n.', 'A2', 'আবর্জনা; ময়লা', 'Please take out the garbage.', 'দয়া করে আবর্জনা বাইরে ফেলো।', 310),
    ('gas', null, 'n.', 'A2', 'গ্যাস; জ্বালানি', 'We cook with gas.', 'আমরা গ্যাসে রান্না করি।', 311),
    ('gate', null, 'n.', 'A2', 'ফটক; দরজা', 'Close the gate, please.', 'দয়া করে ফটকটি বন্ধ করো।', 312),
    ('general', null, 'adj.', 'A2', 'সাধারণ; ব্যাপক', 'This is general information.', 'এটি সাধারণ তথ্য।', 313),
    ('gift', null, 'n.', 'A2', 'উপহার', 'I bought a gift for my mother.', 'আমি আমার মায়ের জন্য একটি উপহার কিনলাম।', 314),
    ('goal', null, 'n.', 'A2', 'লক্ষ্য; গোল', 'My goal is to learn English.', 'আমার লক্ষ্য ইংরেজি শেখা।', 315),
    ('god', null, 'n.', 'A2', 'ঈশ্বর; দেবতা', 'They believe in one god.', 'তারা এক ঈশ্বরে বিশ্বাস করে।', 316),
    ('gold', null, 'adj., n.', 'A2', 'সোনা; স্বর্ণ', 'She wears a gold ring.', 'সে একটি সোনার আংটি পরে।', 317),
    ('golf', null, 'n.', 'A2', 'গলফ', 'He plays golf on weekends.', 'সে সপ্তাহান্তে গলফ খেলে।', 318),
    ('government', null, 'n.', 'A2', 'সরকার', 'The government built a new road.', 'সরকার একটি নতুন রাস্তা বানাল।', 319),
    ('grass', null, 'n.', 'A2', 'ঘাস', 'The children sat on the grass.', 'বাচ্চারা ঘাসের উপর বসল।', 320),
    ('greet', null, 'v.', 'A2', 'অভিবাদন করা; স্বাগত জানানো', 'She greeted us warmly.', 'সে আমাদের উষ্ণভাবে স্বাগত জানাল।', 321),
    ('grocery', null, 'n.', 'A2', 'মুদি; মুদিখানার জিনিস', 'I need to buy some groceries.', 'আমার কিছু মুদিখানার জিনিস কিনতে হবে।', 322),
    ('ground', null, 'n.', 'A2', 'মাটি; ভূমি', 'The ball fell on the ground.', 'বলটি মাটিতে পড়ল।', 323),
    ('guest', null, 'n.', 'A2', 'অতিথি; মেহমান', 'We have guests tonight.', 'আজ রাতে আমাদের অতিথি আছেন।', 324),
    ('guide', null, 'n., v.', 'A2', 'পথপ্রদর্শক; গাইড; পথ দেখানো', 'The guide showed us the museum.', 'গাইড আমাদের জাদুঘরটি দেখালেন।', 325),
    ('gun', null, 'n.', 'A2', 'বন্দুক', 'The police officer has a gun.', 'পুলিশ কর্মকর্তার কাছে একটি বন্দুক আছে।', 326),
    ('guy', null, 'n.', 'A2', 'লোক; ছেলে (অনানুষ্ঠানিক)', 'He is a nice guy.', 'সে একজন ভালো লোক।', 327),
    ('habit', null, 'n.', 'A2', 'অভ্যাস', 'Reading is a good habit.', 'পড়া একটি ভালো অভ্যাস।', 328),
    ('hall', null, 'n.', 'A2', 'হলঘর; বড় কক্ষ', 'The meeting is in the main hall.', 'বৈঠকটি প্রধান হলঘরে।', 329),
    ('happily', null, 'adv.', 'A2', 'সুখে; আনন্দের সাথে', 'They lived happily.', 'তারা সুখে বসবাস করল।', 330),
    ('headache', null, 'n.', 'A2', 'মাথাব্যথা', 'I have a bad headache.', 'আমার প্রচণ্ড মাথাব্যথা।', 331),
    ('heart', null, 'n.', 'A2', 'হৃদয়; হৃৎপিণ্ড', 'Exercise is good for your heart.', 'ব্যায়াম তোমার হৃদয়ের জন্য ভালো।', 332),
    ('heat', null, 'n., v.', 'A2', 'তাপ; গরম করা', 'Heat the milk, please.', 'দয়া করে দুধটি গরম করো।', 333),
    ('heavy', null, 'adj.', 'A2', 'ভারী', 'This box is too heavy.', 'এই বাক্সটি খুব ভারী।', 334),
    ('height', null, 'n.', 'A2', 'উচ্চতা', 'What is your height?', 'তোমার উচ্চতা কত?', 335),
    ('helpful', null, 'adj.', 'A2', 'সহায়ক; উপকারী', 'The staff were very helpful.', 'কর্মীরা খুব সহায়ক ছিল।', 336),
    ('hero', null, 'n.', 'A2', 'বীর; নায়ক', 'He is a national hero.', 'সে একজন জাতীয় বীর।', 337),
    ('hers', null, 'pron.', 'A2', 'তার (স্ত্রী-মালিকানা)', 'This bag is hers.', 'এই ব্যাগটি তার।', 338),
    ('herself', null, 'pron.', 'A2', 'সে নিজে (স্ত্রী)', 'She made it herself.', 'সে নিজে এটি বানিয়েছে।', 339),
    ('hide', null, 'v.', 'A2', 'লুকানো; লুকিয়ে থাকা', 'The cat hid under the bed.', 'বিড়ালটি বিছানার নিচে লুকাল।', 340),
    ('hill', null, 'n.', 'A2', 'পাহাড়; টিলা', 'Their house is on a hill.', 'তাদের বাড়িটি একটি পাহাড়ের উপর।', 341),
    ('himself', null, 'pron.', 'A2', 'সে নিজে (পুরুষ)', 'He cut himself while cooking.', 'রান্না করার সময় সে নিজেকে কেটে ফেলল।', 342),
    ('hit', null, 'n., v.', 'A2', 'আঘাত করা; মারা', 'The ball hit the window.', 'বলটি জানালায় আঘাত করল।', 343),
    ('hockey', null, 'n.', 'A2', 'হকি', 'They play hockey in winter.', 'তারা শীতকালে হকি খেলে।', 344),
    ('hold', null, 'n., v.', 'A2', 'ধরা; ধরে রাখা', 'Hold my hand.', 'আমার হাতটি ধরো।', 345),
    ('hole', null, 'n.', 'A2', 'গর্ত; ছিদ্র', 'There is a hole in my sock.', 'আমার মোজায় একটি ছিদ্র আছে।', 346),
    ('holiday', null, 'n.', 'A2', 'ছুটি; উৎসবের দিন', 'Tomorrow is a holiday.', 'আগামীকাল ছুটির দিন।', 347),
    ('huge', null, 'adj.', 'A2', 'বিশাল; প্রকাণ্ড', 'They live in a huge house.', 'তারা একটি বিশাল বাড়িতে থাকে।', 348),
    ('human', null, 'adj., n.', 'A2', 'মানুষ; মানবিক', 'Every human needs water.', 'প্রত্যেক মানুষের পানি প্রয়োজন।', 349),
    ('hurt', null, 'adj., n., v.', 'A2', 'আঘাত করা; ব্যথা পাওয়া', 'My leg hurts.', 'আমার পায়ে ব্যথা করছে।', 350),
    ('ideal', null, 'adj., n.', 'A2', 'আদর্শ; উত্তম', 'This is an ideal place to rest.', 'এটি বিশ্রামের জন্য একটি আদর্শ জায়গা।', 351),
    ('identify', null, 'v.', 'A2', 'শনাক্ত করা; চিহ্নিত করা', 'Can you identify this plant?', 'তুমি কি এই গাছটি শনাক্ত করতে পারো?', 352),
    ('ill', null, 'adj.', 'A2', 'অসুস্থ', 'She has been ill for a week.', 'সে এক সপ্তাহ ধরে অসুস্থ।', 353),
    ('illness', null, 'n.', 'A2', 'অসুস্থতা; রোগ', 'He recovered from his illness.', 'সে তার অসুস্থতা থেকে সেরে উঠল।', 354),
    ('image', null, 'n.', 'A2', 'চিত্র; প্রতিমূর্তি', 'The image is very clear.', 'চিত্রটি খুব স্পষ্ট।', 355),
    ('immediately', null, 'adv.', 'A2', 'অবিলম্বে; তৎক্ষণাৎ', 'Come here immediately.', 'অবিলম্বে এখানে এসো।', 356),
    ('impossible', null, 'adj.', 'A2', 'অসম্ভব', 'Nothing is impossible.', 'কোনো কিছুই অসম্ভব নয়।', 357),
    ('included', null, 'adj.', 'A2', 'অন্তর্ভুক্ত', 'Breakfast is included in the price.', 'দামের মধ্যে সকালের নাস্তা অন্তর্ভুক্ত।', 358),
    ('including', null, 'prep.', 'A2', 'সহ; অন্তর্ভুক্ত করে', 'Everyone came, including the teacher.', 'শিক্ষকসহ সবাই এল।', 359),
    ('increase', null, 'n., v.', 'A2', 'বৃদ্ধি করা; বাড়ানো', 'Prices increase every year.', 'প্রতি বছর দাম বাড়ে।', 360),
    ('incredible', null, 'adj.', 'A2', 'অবিশ্বাস্য; অসাধারণ', 'The view was incredible.', 'দৃশ্যটি অবিশ্বাস্য ছিল।', 361),
    ('independent', null, 'adj.', 'A2', 'স্বাধীন; স্বনির্ভর', 'She is very independent.', 'সে খুব স্বনির্ভর।', 362),
    ('individual', null, 'adj., n.', 'A2', 'ব্যক্তি; একক', 'Each individual is important.', 'প্রত্যেক ব্যক্তি গুরুত্বপূর্ণ।', 363),
    ('industry', null, 'n.', 'A2', 'শিল্প; কারখানা-ব্যবস্থা', 'The tourism industry is growing.', 'পর্যটন শিল্প বাড়ছে।', 364),
    ('informal', null, 'adj.', 'A2', 'অনানুষ্ঠানিক; ঘরোয়া', 'It was an informal meeting.', 'এটি একটি অনানুষ্ঠানিক বৈঠক ছিল।', 365),
    ('injury', null, 'n.', 'A2', 'আঘাত; জখম', 'He has a knee injury.', 'তার হাঁটুতে আঘাত লেগেছে।', 366),
    ('insect', null, 'n.', 'A2', 'পোকা; কীটপতঙ্গ', 'An insect landed on the flower.', 'একটি পোকা ফুলের উপর বসল।', 367),
    ('inside', null, 'prep., adv., adj., n.', 'A2', 'ভিতরে; অভ্যন্তরে', 'Let''s go inside.', 'চলো ভিতরে যাই।', 368),
    ('instead', null, 'adv.', 'A2', 'পরিবর্তে; বদলে', 'I drank tea instead of coffee.', 'আমি কফির বদলে চা পান করলাম।', 369),
    ('instruction', null, 'n.', 'A2', 'নির্দেশ; নির্দেশনা', 'Follow the instructions carefully.', 'নির্দেশনাগুলো মন দিয়ে অনুসরণ করো।', 370),
    ('instructor', null, 'n.', 'A2', 'প্রশিক্ষক', 'Our driving instructor is patient.', 'আমাদের ড্রাইভিং প্রশিক্ষক ধৈর্যশীল।', 371),
    ('instrument', null, 'n.', 'A2', 'যন্ত্র; বাদ্যযন্ত্র', 'The guitar is my favorite instrument.', 'গিটার আমার প্রিয় বাদ্যযন্ত্র।', 372),
    ('intelligent', null, 'adj.', 'A2', 'বুদ্ধিমান; মেধাবী', 'She is a very intelligent girl.', 'সে একটি খুব বুদ্ধিমতী মেয়ে।', 373),
    ('international', null, 'adj.', 'A2', 'আন্তর্জাতিক', 'It is an international airport.', 'এটি একটি আন্তর্জাতিক বিমানবন্দর।', 374),
    ('introduction', null, 'n.', 'A2', 'পরিচিতি; ভূমিকা', 'The book has a short introduction.', 'বইটিতে একটি সংক্ষিপ্ত ভূমিকা আছে।', 375),
    ('invent', null, 'v.', 'A2', 'উদ্ভাবন করা; আবিষ্কার করা', 'Who invented the telephone?', 'টেলিফোন কে উদ্ভাবন করেছিলেন?', 376),
    ('invention', null, 'n.', 'A2', 'উদ্ভাবন; আবিষ্কার', 'The wheel was a great invention.', 'চাকা একটি মহান আবিষ্কার ছিল।', 377),
    ('invitation', null, 'n.', 'A2', 'নিমন্ত্রণ; আমন্ত্রণ', 'Thank you for the invitation.', 'আমন্ত্রণের জন্য ধন্যবাদ।', 378),
    ('invite', null, 'v.', 'A2', 'আমন্ত্রণ জানানো; নিমন্ত্রণ করা', 'I want to invite you to dinner.', 'আমি তোমাকে রাতের খাবারে আমন্ত্রণ জানাতে চাই।', 379),
    ('involve', null, 'v.', 'A2', 'জড়িত করা; সম্পৃক্ত করা', 'The job involves a lot of travel.', 'চাকরিটিতে অনেক ভ্রমণ জড়িত।', 380),
    ('item', null, 'n.', 'A2', 'বস্তু; জিনিস (তালিকার)', 'There are ten items on the list.', 'তালিকায় দশটি জিনিস আছে।', 381),
    ('itself', null, 'pron.', 'A2', 'এটি নিজে; স্বয়ং', 'The cat cleaned itself.', 'বিড়ালটি নিজে নিজেকে পরিষ্কার করল।', 382),
    ('jam', null, 'n.', 'A2', 'জ্যাম; ফলের মোরব্বা', 'I like jam on my bread.', 'আমি রুটিতে জ্যাম পছন্দ করি।', 383),
    ('jazz', null, 'n.', 'A2', 'জ্যাজ (সঙ্গীত)', 'He plays jazz on the piano.', 'সে পিয়ানোতে জ্যাজ বাজায়।', 384),
    ('jewelry', null, 'n.', 'A2', 'গহনা; অলংকার', 'She wears beautiful jewelry.', 'সে সুন্দর গহনা পরে।', 385),
    ('joke', null, 'n., v.', 'A2', 'রসিকতা; কৌতুক', 'He told a funny joke.', 'সে একটি মজার কৌতুক বলল।', 386),
    ('journalist', null, 'n.', 'A2', 'সাংবাদিক', 'The journalist wrote a report.', 'সাংবাদিক একটি প্রতিবেদন লিখলেন।', 387),
    ('jump', null, 'n., v.', 'A2', 'লাফানো; ঝাঁপ দেওয়া', 'The cat jumped onto the table.', 'বিড়ালটি টেবিলের উপর লাফ দিল।', 388),
    ('kid', null, 'n.', 'A2', 'বাচ্চা; ছেলেমেয়ে', 'The kids are playing outside.', 'বাচ্চারা বাইরে খেলছে।', 389),
    ('kill', null, 'v.', 'A2', 'হত্যা করা; মারা', 'The frost killed the plants.', 'তুষার গাছগুলো মেরে ফেলল।', 390),
    ('kilometer', null, 'n.', 'A2', 'কিলোমিটার', 'The school is two kilometers away.', 'স্কুলটি দুই কিলোমিটার দূরে।', 391),
    ('king', null, 'n.', 'A2', 'রাজা', 'The king lived in a big palace.', 'রাজা একটি বড় প্রাসাদে থাকতেন।', 392),
    ('knee', null, 'n.', 'A2', 'হাঁটু', 'He fell and hurt his knee.', 'সে পড়ে গিয়ে হাঁটুতে ব্যথা পেল।', 393),
    ('knife', null, 'n.', 'A2', 'ছুরি; চাকু', 'Cut the fruit with a knife.', 'ছুরি দিয়ে ফলটি কাটো।', 394),
    ('knock', null, 'n., v.', 'A2', 'কড়া নাড়া; টোকা দেওয়া', 'Someone is knocking at the door.', 'কেউ দরজায় কড়া নাড়ছে।', 395),
    ('knowledge', null, 'n.', 'A2', 'জ্ঞান', 'She has a lot of knowledge.', 'তার অনেক জ্ঞান আছে।', 396),
    ('lab', null, 'n.', 'A2', 'পরীক্ষাগার; ল্যাব', 'We did the test in the lab.', 'আমরা ল্যাবে পরীক্ষাটি করলাম।', 397),
    ('lady', null, 'n.', 'A2', 'ভদ্রমহিলা; মহিলা', 'An old lady sat near me.', 'একজন বৃদ্ধা মহিলা আমার কাছে বসলেন।', 398),
    ('lake', null, 'n.', 'A2', 'হ্রদ; বিল', 'We swam in the lake.', 'আমরা হ্রদে সাঁতার কাটলাম।', 399),
    ('lamp', null, 'n.', 'A2', 'বাতি; প্রদীপ', 'Turn on the lamp, please.', 'দয়া করে বাতিটি জ্বালাও।', 400),
    ('laptop', null, 'n.', 'A2', 'ল্যাপটপ', 'I work on my laptop.', 'আমি আমার ল্যাপটপে কাজ করি।', 401),
    ('last', 'taking time', 'v.', 'A2', 'স্থায়ী হওয়া; টেকা', 'The movie lasts two hours.', 'সিনেমাটি দুই ঘণ্টা ধরে চলে।', 402),
    ('laughter', null, 'n.', 'A2', 'হাসি', 'The room was full of laughter.', 'ঘরটি হাসিতে ভরে গেল।', 403),
    ('law', null, 'n.', 'A2', 'আইন', 'We must obey the law.', 'আমাদের আইন মানতে হবে।', 404),
    ('lawyer', null, 'n.', 'A2', 'আইনজীবী; উকিল', 'She is a good lawyer.', 'সে একজন ভালো আইনজীবী।', 405),
    ('lazy', null, 'adj.', 'A2', 'অলস; কুঁড়ে', 'He is too lazy to work.', 'সে কাজ করতে খুব অলস।', 406),
    ('lead', null, 'n., v.', 'A2', 'নেতৃত্ব দেওয়া; পথ দেখানো', 'She will lead the team.', 'সে দলটির নেতৃত্ব দেবে।', 407),
    ('leader', null, 'n.', 'A2', 'নেতা', 'He is a strong leader.', 'সে একজন শক্তিশালী নেতা।', 408),
    ('learning', null, 'n.', 'A2', 'শেখা; শিক্ষা', 'Learning a language takes time.', 'একটি ভাষা শেখা সময়সাপেক্ষ।', 409),
    ('least', null, 'pron., det., adv.', 'A2', 'সর্বনিম্ন; কমপক্ষে', 'This is the least expensive one.', 'এটি সবচেয়ে কম দামি।', 410),
    ('lecture', null, 'n., v.', 'A2', 'বক্তৃতা; ভাষণ', 'The lecture was very interesting.', 'বক্তৃতাটি খুব আকর্ষণীয় ছিল।', 411),
    ('lemon', null, 'n.', 'A2', 'লেবু', 'Add some lemon to the tea.', 'চায়ে একটু লেবু দাও।', 412),
    ('lend', null, 'v.', 'A2', 'ধার দেওয়া', 'Can you lend me some money?', 'তুমি কি আমাকে কিছু টাকা ধার দিতে পারবে?', 413),
    ('less', null, 'pron., det., adv.', 'A2', 'কম; অল্প', 'Eat less sugar.', 'কম চিনি খাও।', 414),
    ('level', null, 'adj., n., v.', 'A2', 'স্তর; মাত্রা; সমতল', 'She is at an advanced level.', 'সে একটি উন্নত স্তরে আছে।', 415),
    ('lifestyle', null, 'n.', 'A2', 'জীবনযাত্রা; জীবনধারা', 'He has a healthy lifestyle.', 'তার একটি স্বাস্থ্যকর জীবনযাত্রা আছে।', 416),
    ('lift', null, 'v.', 'A2', 'তোলা; উঠানো', 'Lift the box carefully.', 'বাক্সটি সাবধানে তোলো।', 417),
    ('light', 'not heavy', 'adj.', 'A2', 'হালকা', 'This bag is very light.', 'এই ব্যাগটি খুব হালকা।', 418),
    ('likely', null, 'adj.', 'A2', 'সম্ভাব্য; সম্ভাবনাময়', 'It is likely to rain.', 'বৃষ্টি হওয়ার সম্ভাবনা আছে।', 419),
    ('link', null, 'n., v.', 'A2', 'সংযোগ; লিংক', 'Click on this link.', 'এই লিংকে ক্লিক করো।', 420),
    ('listener', null, 'n.', 'A2', 'শ্রোতা', 'She is a good listener.', 'সে একজন ভালো শ্রোতা।', 421),
    ('lock', null, 'n., v.', 'A2', 'তালা; তালা দেওয়া', 'Lock the door before you leave.', 'বের হওয়ার আগে দরজায় তালা দাও।', 422),
    ('lost', null, 'adj.', 'A2', 'হারানো; পথহারা', 'I am lost; can you help me?', 'আমি পথ হারিয়ে ফেলেছি; তুমি কি সাহায্য করতে পারবে?', 423),
    ('loud', null, 'adv., adj.', 'A2', 'জোরে; উচ্চস্বর', 'The music is too loud.', 'গানটি খুব জোরে।', 424),
    ('loudly', null, 'adv.', 'A2', 'জোরে; উচ্চস্বরে', 'He spoke loudly.', 'সে জোরে কথা বলল।', 425),
    ('low', null, 'adv., adj., n.', 'A2', 'নিচু; কম', 'The prices are very low.', 'দামগুলো খুব কম।', 426),
    ('luck', null, 'n.', 'A2', 'ভাগ্য; কপাল', 'Good luck on your exam!', 'তোমার পরীক্ষার জন্য শুভকামনা!', 427),
    ('lucky', null, 'adj.', 'A2', 'ভাগ্যবান', 'You are very lucky.', 'তুমি খুব ভাগ্যবান।', 428),
    ('mail', null, 'n., v.', 'A2', 'ডাক; চিঠিপত্র', 'I got mail from my friend.', 'আমি আমার বন্ধুর কাছ থেকে চিঠি পেলাম।', 429),
    ('major', null, 'adj., n.', 'A2', 'প্রধান; বড়', 'This is a major problem.', 'এটি একটি বড় সমস্যা।', 430),
    ('male', null, 'adj., n.', 'A2', 'পুরুষ', 'A male bird has bright colors.', 'পুরুষ পাখির উজ্জ্বল রঙ থাকে।', 431),
    ('manage', null, 'v.', 'A2', 'পরিচালনা করা; সামলানো', 'She manages a big team.', 'সে একটি বড় দল পরিচালনা করে।', 432),
    ('manager', null, 'n.', 'A2', 'ব্যবস্থাপক; ম্যানেজার', 'The manager is in a meeting.', 'ম্যানেজার একটি বৈঠকে আছেন।', 433),
    ('manner', null, 'n.', 'A2', 'ধরন; আচরণ', 'He spoke in a polite manner.', 'সে ভদ্রভাবে কথা বলল।', 434),
    ('mark', null, 'n., v.', 'A2', 'চিহ্ন; নম্বর; দাগ দেওয়া', 'She got full marks.', 'সে পূর্ণ নম্বর পেল।', 435),
    ('marry', null, 'v.', 'A2', 'বিয়ে করা', 'They will marry next month.', 'তারা আগামী মাসে বিয়ে করবে।', 436),
    ('match', 'contest/correspond', 'n., v.', 'A2', 'খেলা; মিল হওয়া', 'We watched a cricket match.', 'আমরা একটি ক্রিকেট খেলা দেখলাম।', 437),
    ('material', null, 'adj., n.', 'A2', 'উপাদান; কাপড়; সামগ্রী', 'This material is very soft.', 'এই কাপড়টি খুব নরম।', 438),
    ('math', null, 'n.', 'A2', 'গণিত', 'Math is my favorite subject.', 'গণিত আমার প্রিয় বিষয়।', 439),
    ('mathematics', null, 'n.', 'A2', 'গণিত', 'She teaches mathematics.', 'তিনি গণিত পড়ান।', 440),
    ('matter', null, 'n., v.', 'A2', 'বিষয়; গুরুত্বপূর্ণ হওয়া', 'It does not matter.', 'এতে কিছু আসে যায় না।', 441),
    ('may', null, 'modal v., v.', 'A2', 'হতে পারে; অনুমতি (ভদ্র)', 'May I come in?', 'আমি কি ভিতরে আসতে পারি?', 442),
    ('mayor', null, 'n.', 'A2', 'মেয়র; নগরপ্রধান', 'The mayor visited our school.', 'মেয়র আমাদের স্কুল পরিদর্শন করলেন।', 443),
    ('media', null, 'n.', 'A2', 'গণমাধ্যম', 'The story was in the media.', 'খবরটি গণমাধ্যমে এসেছিল।', 444),
    ('medical', null, 'adj.', 'A2', 'চিকিৎসা সংক্রান্ত; মেডিকেল', 'He needs medical help.', 'তার চিকিৎসা সাহায্য দরকার।', 445),
    ('medicine', null, 'n.', 'A2', 'ওষুধ; চিকিৎসাশাস্ত্র', 'Take this medicine after meals.', 'খাওয়ার পর এই ওষুধটি খেয়ো।', 446),
    ('memory', null, 'n.', 'A2', 'স্মৃতি; স্মরণশক্তি', 'I have a happy memory of that day.', 'সেই দিনের একটি সুখী স্মৃতি আমার আছে।', 447),
    ('mention', null, 'n., v.', 'A2', 'উল্লেখ করা', 'She mentioned your name.', 'সে তোমার নাম উল্লেখ করল।', 448),
    ('metal', null, 'n.', 'A2', 'ধাতু', 'Iron is a strong metal.', 'লোহা একটি শক্ত ধাতু।', 449),
    ('method', null, 'n.', 'A2', 'পদ্ধতি; উপায়', 'This is a simple method.', 'এটি একটি সহজ পদ্ধতি।', 450),
    ('middle', null, 'adj., n.', 'A2', 'মধ্য; মাঝখান', 'Stand in the middle.', 'মাঝখানে দাঁড়াও।', 451),
    ('might', null, 'modal v., v.', 'A2', 'হয়তো; হতে পারে', 'It might rain later.', 'পরে হয়তো বৃষ্টি হতে পারে।', 452),
    ('mind', null, 'n., v.', 'A2', 'মন; আপত্তি করা', 'Do you mind if I sit here?', 'আমি এখানে বসলে কি তোমার আপত্তি আছে?', 453),
    ('mine', 'belongs to me', 'pron.', 'A2', 'আমার', 'That book is mine.', 'ওই বইটি আমার।', 454),
    ('mirror', null, 'n.', 'A2', 'আয়না; দর্পণ', 'She looked in the mirror.', 'সে আয়নায় তাকাল।', 455),
    ('missing', null, 'adj.', 'A2', 'নিখোঁজ; অনুপস্থিত', 'One book is missing.', 'একটি বই নিখোঁজ।', 456),
    ('monkey', null, 'n.', 'A2', 'বানর', 'The monkey climbed the tree.', 'বানরটি গাছে উঠল।', 457),
    ('moon', null, 'n.', 'A2', 'চাঁদ', 'The moon is bright tonight.', 'আজ রাতে চাঁদ উজ্জ্বল।', 458),
    ('mostly', null, 'adv.', 'A2', 'বেশিরভাগ; প্রধানত', 'I mostly drink water.', 'আমি বেশিরভাগ সময় পানি পান করি।', 459),
    ('motorcycle', null, 'n.', 'A2', 'মোটরসাইকেল', 'He rides a motorcycle.', 'সে একটি মোটরসাইকেল চালায়।', 460),
    ('movement', null, 'n.', 'A2', 'চলাচল; আন্দোলন', 'I saw a movement in the bushes.', 'আমি ঝোপে কিছু নড়াচড়া দেখলাম।', 461),
    ('musical', null, 'adj., n.', 'A2', 'সাংগীতিক; সুরেলা', 'She has a musical voice.', 'তার একটি সুরেলা কণ্ঠ আছে।', 462),
    ('musician', null, 'n.', 'A2', 'সঙ্গীতশিল্পী; বাদক', 'He is a talented musician.', 'সে একজন প্রতিভাবান সঙ্গীতশিল্পী।', 463),
    ('myself', null, 'pron.', 'A2', 'আমি নিজে', 'I made this cake myself.', 'আমি নিজে এই কেকটি বানিয়েছি।', 464),
    ('narrow', null, 'adj., v.', 'A2', 'সরু; সংকীর্ণ', 'This is a narrow street.', 'এটি একটি সরু রাস্তা।', 465),
    ('national', null, 'adj., n.', 'A2', 'জাতীয়', 'Today is a national holiday.', 'আজ একটি জাতীয় ছুটির দিন।', 466),
    ('nature', null, 'n.', 'A2', 'প্রকৃতি; স্বভাব', 'I love the beauty of nature.', 'আমি প্রকৃতির সৌন্দর্য ভালোবাসি।', 467),
    ('nearly', null, 'adv.', 'A2', 'প্রায়; কাছাকাছি', 'It is nearly midnight.', 'প্রায় মধ্যরাত হয়ে গেছে।', 468),
    ('necessary', null, 'adj.', 'A2', 'প্রয়োজনীয়; দরকারি', 'Sleep is necessary for health.', 'স্বাস্থ্যের জন্য ঘুম প্রয়োজনীয়।', 469),
    ('neck', null, 'n.', 'A2', 'ঘাড়; গলা', 'The giraffe has a long neck.', 'জিরাফের একটি লম্বা ঘাড় আছে।', 470),
    ('neither', null, 'pron., det., adv.', 'A2', 'কোনোটিই না (দুটির)', 'Neither answer is correct.', 'দুটো উত্তরের কোনোটিই সঠিক নয়।', 471),
    ('nervous', null, 'adj.', 'A2', 'উদ্বিগ্ন; ঘাবড়ানো', 'I am nervous before exams.', 'পরীক্ষার আগে আমি ঘাবড়ে যাই।', 472),
    ('network', null, 'n.', 'A2', 'নেটওয়ার্ক; জালব্যবস্থা', 'The phone network is down.', 'ফোন নেটওয়ার্ক বন্ধ আছে।', 473),
    ('noise', null, 'n.', 'A2', 'শব্দ; আওয়াজ; হইচই', 'Please do not make noise.', 'দয়া করে শব্দ করো না।', 474),
    ('noisy', null, 'adj.', 'A2', 'শোরগোলপূর্ণ; হইচইপূর্ণ', 'The classroom is very noisy.', 'শ্রেণিকক্ষটি খুব হইচইপূর্ণ।', 475),
    ('none', null, 'pron.', 'A2', 'কোনোটিই না; একটিও না', 'None of them came.', 'তাদের একজনও আসেনি।', 476),
    ('normal', null, 'adj., n.', 'A2', 'স্বাভাবিক; সাধারণ', 'His temperature is normal.', 'তার তাপমাত্রা স্বাভাবিক।', 477),
    ('normally', null, 'adv.', 'A2', 'সাধারণত; স্বাভাবিকভাবে', 'I normally sleep at ten.', 'আমি সাধারণত দশটায় ঘুমাই।', 478),
    ('notice', null, 'n., v.', 'A2', 'লক্ষ্য করা; বিজ্ঞপ্তি', 'Did you notice the change?', 'তুমি কি পরিবর্তনটি লক্ষ্য করেছ?', 479),
    ('novel', null, 'n.', 'A2', 'উপন্যাস', 'She is writing a novel.', 'সে একটি উপন্যাস লিখছে।', 480),
    ('nowhere', null, 'adv.', 'A2', 'কোথাও না', 'There is nowhere to sit.', 'বসার কোনো জায়গা নেই।', 481),
    ('nut', null, 'n.', 'A2', 'বাদাম; বাদাম জাতীয় ফল', 'I like nuts in my salad.', 'আমি সালাদে বাদাম পছন্দ করি।', 482),
    ('observe', null, 'v.', 'A2', 'পর্যবেক্ষণ করা; লক্ষ্য করা', 'We observed the birds quietly.', 'আমরা চুপচাপ পাখিদের পর্যবেক্ষণ করলাম।', 483),
    ('offer', null, 'n., v.', 'A2', 'প্রস্তাব দেওয়া; অফার', 'They offered me a job.', 'তারা আমাকে একটি চাকরির প্রস্তাব দিল।', 484),
    ('officer', null, 'n.', 'A2', 'কর্মকর্তা; অফিসার', 'A police officer helped us.', 'একজন পুলিশ কর্মকর্তা আমাদের সাহায্য করলেন।', 485),
    ('oil', null, 'n.', 'A2', 'তেল', 'Cook the fish in oil.', 'তেলে মাছটি রান্না করো।', 486),
    ('onto', null, 'prep.', 'A2', 'উপরে (গতির দিকে)', 'The cat jumped onto the roof.', 'বিড়ালটি ছাদের উপর লাফ দিল।', 487),
    ('opportunity', null, 'n.', 'A2', 'সুযোগ', 'This is a great opportunity.', 'এটি একটি দারুণ সুযোগ।', 488),
    ('option', null, 'n.', 'A2', 'বিকল্প; পছন্দ', 'You have three options.', 'তোমার কাছে তিনটি বিকল্প আছে।', 489),
    ('ordinary', null, 'adj.', 'A2', 'সাধারণ; মামুলি', 'It was an ordinary day.', 'এটি একটি সাধারণ দিন ছিল।', 490),
    ('organization', null, 'n.', 'A2', 'সংগঠন; প্রতিষ্ঠান', 'She works for a charity organization.', 'সে একটি দাতব্য সংগঠনের হয়ে কাজ করে।', 491),
    ('organize', null, 'v.', 'A2', 'আয়োজন করা; সংগঠিত করা', 'They organized a party.', 'তারা একটি পার্টির আয়োজন করল।', 492),
    ('original', null, 'adj., n.', 'A2', 'মৌলিক; আসল', 'This is the original painting.', 'এটি আসল চিত্রকর্ম।', 493),
    ('ourselves', null, 'pron.', 'A2', 'আমরা নিজেরা', 'We cooked the meal ourselves.', 'আমরা নিজেরাই খাবারটি রান্না করলাম।', 494),
    ('oven', null, 'n.', 'A2', 'চুলা; ওভেন', 'Put the cake in the oven.', 'কেকটি ওভেনে রাখো।', 495),
    ('overseas', null, 'adv., adj.', 'A2', 'বিদেশে; সমুদ্রপারে', 'He studies overseas.', 'সে বিদেশে পড়াশোনা করে।', 496),
    ('owner', null, 'n.', 'A2', 'মালিক', 'Who is the owner of this shop?', 'এই দোকানের মালিক কে?', 497),
    ('pack', null, 'n., v.', 'A2', 'প্যাক করা; গোছানো', 'Pack your bags tonight.', 'আজ রাতে তোমার ব্যাগ গোছাও।', 498),
    ('pain', null, 'n.', 'A2', 'ব্যথা; যন্ত্রণা', 'I feel a pain in my back.', 'আমার পিঠে ব্যথা অনুভব করছি।', 499),
    ('painter', null, 'n.', 'A2', 'চিত্রকর; রং মিস্ত্রি', 'The painter finished the wall.', 'রং মিস্ত্রি দেয়ালটি শেষ করল।', 500),
    ('palace', null, 'n.', 'A2', 'প্রাসাদ; রাজপ্রাসাদ', 'The queen lives in a palace.', 'রানি একটি প্রাসাদে থাকেন।', 501),
    ('parking', null, 'n.', 'A2', 'পার্কিং; গাড়ি রাখার জায়গা', 'There is no parking here.', 'এখানে গাড়ি রাখার জায়গা নেই।', 502),
    ('particular', null, 'adj.', 'A2', 'নির্দিষ্ট; বিশেষ', 'Is there a particular book you want?', 'তুমি কি কোনো নির্দিষ্ট বই চাও?', 503),
    ('pass', null, 'n., v.', 'A2', 'পাস করা; অতিক্রম করা; এগিয়ে দেওয়া', 'Please pass the salt.', 'দয়া করে লবণটি এগিয়ে দাও।', 504),
    ('passenger', null, 'n.', 'A2', 'যাত্রী', 'The bus was full of passengers.', 'বাসটি যাত্রীতে পূর্ণ ছিল।', 505),
    ('patient', null, 'adj., n.', 'A2', 'রোগী; ধৈর্যশীল', 'The doctor sees ten patients a day.', 'ডাক্তার দিনে দশজন রোগী দেখেন।', 506),
    ('pattern', null, 'n.', 'A2', 'নকশা; ছাঁদ; ধরন', 'The cloth has a nice pattern.', 'কাপড়টিতে একটি সুন্দর নকশা আছে।', 507),
    ('peace', null, 'n.', 'A2', 'শান্তি', 'Everyone wants peace.', 'সবাই শান্তি চায়।', 508),
    ('penny', null, 'n.', 'A2', 'পেনি (মুদ্রা)', 'I do not have a penny.', 'আমার কাছে একটি পেনিও নেই।', 509),
    ('per', null, 'prep.', 'A2', 'প্রতি; প্রতিটির জন্য', 'The car goes sixty miles per hour.', 'গাড়িটি ঘণ্টায় ষাট মাইল চলে।', 510),
    ('percent', null, 'n., adv., adj.', 'A2', 'শতাংশ; পার্সেন্ট', 'Ninety percent of students passed.', 'নব্বই শতাংশ ছাত্র পাস করেছে।', 511),
    ('perform', null, 'v.', 'A2', 'সম্পাদন করা; অভিনয়/পরিবেশন করা', 'The band will perform tonight.', 'ব্যান্ডটি আজ রাতে পরিবেশন করবে।', 512),
    ('perhaps', null, 'adv.', 'A2', 'সম্ভবত; হয়তো', 'Perhaps we can meet tomorrow.', 'হয়তো আমরা আগামীকাল দেখা করতে পারি।', 513),
    ('permission', null, 'n.', 'A2', 'অনুমতি', 'You need permission to enter.', 'ভিতরে ঢুকতে তোমার অনুমতি লাগবে।', 514),
    ('personality', null, 'n.', 'A2', 'ব্যক্তিত্ব', 'She has a friendly personality.', 'তার একটি বন্ধুত্বপূর্ণ ব্যক্তিত্ব আছে।', 515),
    ('pet', null, 'n.', 'A2', 'পোষা প্রাণী', 'They have a pet dog.', 'তাদের একটি পোষা কুকুর আছে।', 516),
    ('physical', null, 'adj.', 'A2', 'শারীরিক; ভৌত', 'Physical exercise keeps you fit.', 'শারীরিক ব্যায়াম তোমাকে সুস্থ রাখে।', 517),
    ('physics', null, 'n.', 'A2', 'পদার্থবিজ্ঞান', 'He is studying physics.', 'সে পদার্থবিজ্ঞান পড়ছে।', 518),
    ('pick', null, 'n., v.', 'A2', 'বেছে নেওয়া; তোলা', 'Pick a card, any card.', 'একটি তাস বেছে নাও, যেকোনো তাস।', 519),
    ('pilot', null, 'n.', 'A2', 'বৈমানিক; পাইলট', 'The pilot flew the plane safely.', 'পাইলট বিমানটি নিরাপদে চালালেন।', 520),
    ('planet', null, 'n.', 'A2', 'গ্রহ', 'Earth is our planet.', 'পৃথিবী আমাদের গ্রহ।', 521),
    ('plastic', null, 'adj., n.', 'A2', 'প্লাস্টিক', 'Do not use plastic bags.', 'প্লাস্টিকের ব্যাগ ব্যবহার করো না।', 522),
    ('plate', null, 'n.', 'A2', 'প্লেট; থালা', 'Put the food on the plate.', 'খাবারটি প্লেটে রাখো।', 523),
    ('platform', null, 'n.', 'A2', 'প্ল্যাটফর্ম; মঞ্চ', 'The train is at platform two.', 'ট্রেনটি দুই নম্বর প্ল্যাটফর্মে।', 524),
    ('pleased', null, 'adj.', 'A2', 'খুশি; সন্তুষ্ট', 'I am pleased to meet you.', 'তোমার সাথে পরিচিত হয়ে আমি খুশি।', 525),
    ('pocket', null, 'n.', 'A2', 'পকেট', 'The keys are in my pocket.', 'চাবিগুলো আমার পকেটে।', 526),
    ('polite', null, 'adj.', 'A2', 'ভদ্র; নম্র', 'He is always polite.', 'সে সবসময় ভদ্র।', 527),
    ('pollution', null, 'n.', 'A2', 'দূষণ', 'Air pollution is a big problem.', 'বায়ু দূষণ একটি বড় সমস্যা।', 528),
    ('pop', null, 'adj., n.', 'A2', 'পপ (সঙ্গীত); জনপ্রিয় ধরনের', 'She loves pop music.', 'সে পপ সঙ্গীত খুব ভালোবাসে।', 529),
    ('population', null, 'n.', 'A2', 'জনসংখ্যা', 'The population is growing fast.', 'জনসংখ্যা দ্রুত বাড়ছে।', 530),
    ('position', null, 'n., v.', 'A2', 'অবস্থান; পদ', 'He has a high position at work.', 'কর্মক্ষেত্রে তার একটি উঁচু পদ আছে।', 531),
    ('possession', null, 'n.', 'A2', 'অধিকার; সম্পত্তি', 'The house is his most valued possession.', 'বাড়িটি তার সবচেয়ে মূল্যবান সম্পত্তি।', 532),
    ('possibility', null, 'n.', 'A2', 'সম্ভাবনা', 'There is a possibility of rain.', 'বৃষ্টির সম্ভাবনা আছে।', 533),
    ('poster', null, 'n.', 'A2', 'পোস্টার', 'There is a movie poster on the wall.', 'দেয়ালে একটি সিনেমার পোস্টার আছে।', 534),
    ('power', null, 'n., v.', 'A2', 'শক্তি; ক্ষমতা', 'Knowledge is power.', 'জ্ঞানই শক্তি।', 535),
    ('predict', null, 'v.', 'A2', 'ভবিষ্যদ্বাণী করা; আগে থেকে বলা', 'Can you predict the weather?', 'তুমি কি আবহাওয়ার পূর্বাভাস দিতে পারো?', 536),
    ('president', null, 'n.', 'A2', 'রাষ্ট্রপতি; সভাপতি', 'The president gave a speech.', 'রাষ্ট্রপতি একটি ভাষণ দিলেন।', 537),
    ('prevent', null, 'v.', 'A2', 'প্রতিরোধ করা; বাধা দেওয়া', 'Wash your hands to prevent illness.', 'অসুস্থতা প্রতিরোধ করতে হাত ধুয়ে নাও।', 538),
    ('print', null, 'n., v.', 'A2', 'মুদ্রণ; ছাপা', 'Please print this page.', 'দয়া করে এই পৃষ্ঠাটি ছাপাও।', 539),
    ('printer', null, 'n.', 'A2', 'প্রিন্টার; মুদ্রণযন্ত্র', 'The printer is out of ink.', 'প্রিন্টারে কালি ফুরিয়ে গেছে।', 540),
    ('prison', null, 'n.', 'A2', 'কারাগার, জেল', 'He spent two years in prison.', 'তিনি দুই বছর কারাগারে কাটিয়েছেন।', 541),
    ('prize', null, 'n.', 'A2', 'পুরস্কার', 'She won first prize in the contest.', 'সে প্রতিযোগিতায় প্রথম পুরস্কার জিতেছে।', 542),
    ('process', null, 'n., v.', 'A2', 'প্রক্রিয়া; প্রক্রিয়াজাত করা', 'Learning a language is a slow process.', 'ভাষা শেখা একটি ধীর প্রক্রিয়া।', 543),
    ('produce', null, 'v.', 'A2', 'উৎপাদন করা, তৈরি করা', 'This factory produces cars.', 'এই কারখানা গাড়ি উৎপাদন করে।', 544),
    ('professional', null, 'adj., n.', 'A2', 'পেশাদার', 'She is a professional dancer.', 'সে একজন পেশাদার নৃত্যশিল্পী।', 545),
    ('professor', null, 'n.', 'A2', 'অধ্যাপক', 'The professor teaches history.', 'অধ্যাপক ইতিহাস পড়ান।', 546),
    ('profile', null, 'n.', 'A2', 'পরিচিতি, প্রোফাইল', 'Please update your online profile.', 'অনুগ্রহ করে আপনার অনলাইন প্রোফাইল হালনাগাদ করুন।', 547),
    ('progress', null, 'n., v.', 'A2', 'অগ্রগতি; এগিয়ে যাওয়া', 'You are making good progress.', 'তুমি ভালো অগ্রগতি করছ।', 548),
    ('promise', null, 'n., v.', 'A2', 'প্রতিশ্রুতি; প্রতিশ্রুতি দেওয়া', 'I promise to help you.', 'আমি তোমাকে সাহায্য করার প্রতিশ্রুতি দিচ্ছি।', 549),
    ('pronounce', null, 'v.', 'A2', 'উচ্চারণ করা', 'How do you pronounce this word?', 'তুমি এই শব্দটি কীভাবে উচ্চারণ কর?', 550),
    ('protect', null, 'v.', 'A2', 'রক্ষা করা', 'We must protect the environment.', 'আমাদের পরিবেশ রক্ষা করতে হবে।', 551),
    ('provide', null, 'v.', 'A2', 'সরবরাহ করা, জোগানো', 'The school provides free books.', 'স্কুল বিনামূল্যে বই সরবরাহ করে।', 552),
    ('public', null, 'adj., n.', 'A2', 'সর্বজনীন; জনসাধারণ', 'This is a public park.', 'এটি একটি সর্বজনীন উদ্যান।', 553),
    ('publish', null, 'v.', 'A2', 'প্রকাশ করা', 'He wants to publish a book.', 'তিনি একটি বই প্রকাশ করতে চান।', 554),
    ('pull', null, 'n., v.', 'A2', 'টান; টানা', 'Pull the door to open it.', 'দরজাটি খুলতে টানো।', 555),
    ('purpose', null, 'n.', 'A2', 'উদ্দেশ্য', 'What is the purpose of this trip?', 'এই ভ্রমণের উদ্দেশ্য কী?', 556),
    ('push', null, 'n., v.', 'A2', 'ধাক্কা; ধাক্কা দেওয়া', 'Push the button to start.', 'শুরু করতে বোতামটি চাপো।', 557),
    ('quality', null, 'n.', 'A2', 'গুণমান', 'This shirt is of good quality.', 'এই শার্টটির গুণমান ভালো।', 558),
    ('quantity', null, 'n.', 'A2', 'পরিমাণ', 'We need a large quantity of water.', 'আমাদের প্রচুর পরিমাণে পানি দরকার।', 559),
    ('queen', null, 'n.', 'A2', 'রানি', 'The queen lives in a palace.', 'রানি একটি প্রাসাদে থাকেন।', 560),
    ('quietly', null, 'adv.', 'A2', 'চুপচাপ, নিঃশব্দে', 'She closed the door quietly.', 'সে চুপচাপ দরজাটি বন্ধ করল।', 561),
    ('race', 'competition', 'n., v.', 'A2', 'দৌড় প্রতিযোগিতা; দৌড়ানো', 'He won the running race.', 'সে দৌড় প্রতিযোগিতায় জিতেছে।', 562),
    ('railroad', null, 'n.', 'A2', 'রেলপথ', 'The railroad connects two cities.', 'রেলপথটি দুটি শহরকে যুক্ত করে।', 563),
    ('raise', null, 'n., v.', 'A2', 'বৃদ্ধি; তোলা, উত্থাপন করা', 'Raise your hand to answer.', 'উত্তর দিতে হাত তোলো।', 564),
    ('rate', null, 'n., v.', 'A2', 'হার; মূল্যায়ন করা', 'The success rate is very high.', 'সাফল্যের হার খুব বেশি।', 565),
    ('rather', null, 'adv.', 'A2', 'বরং, কিছুটা', 'It is rather cold today.', 'আজ কিছুটা ঠান্ডা।', 566),
    ('reach', null, 'n., v.', 'A2', 'পৌঁছানো', 'We reached home late at night.', 'আমরা রাত করে বাড়িতে পৌঁছেছি।', 567),
    ('react', null, 'v.', 'A2', 'প্রতিক্রিয়া দেখানো', 'How did she react to the news?', 'খবরটির প্রতি সে কীভাবে প্রতিক্রিয়া দেখাল?', 568),
    ('realize', null, 'v.', 'A2', 'উপলব্ধি করা, বুঝতে পারা', 'I did not realize it was so late.', 'আমি বুঝতে পারিনি এত দেরি হয়ে গেছে।', 569),
    ('receive', null, 'v.', 'A2', 'গ্রহণ করা, পাওয়া', 'I received your letter yesterday.', 'আমি গতকাল তোমার চিঠি পেয়েছি।', 570),
    ('recent', null, 'adj.', 'A2', 'সাম্প্রতিক', 'This is a recent photo of us.', 'এটি আমাদের একটি সাম্প্রতিক ছবি।', 571),
    ('recently', null, 'adv.', 'A2', 'সম্প্রতি', 'They recently moved to a new house.', 'তারা সম্প্রতি একটি নতুন বাড়িতে উঠেছে।', 572),
    ('reception', null, 'n.', 'A2', 'অভ্যর্থনা; অভ্যর্থনা কক্ষ', 'Please wait at the reception.', 'অনুগ্রহ করে অভ্যর্থনা কক্ষে অপেক্ষা করুন।', 573),
    ('recipe', null, 'n.', 'A2', 'রন্ধনপ্রণালী, রেসিপি', 'This is my mother''s recipe.', 'এটি আমার মায়ের রেসিপি।', 574),
    ('recognize', null, 'v.', 'A2', 'চিনতে পারা', 'I did not recognize you at first.', 'আমি প্রথমে তোমাকে চিনতে পারিনি।', 575),
    ('recommend', null, 'v.', 'A2', 'সুপারিশ করা, পরামর্শ দেওয়া', 'Can you recommend a good book?', 'তুমি কি একটি ভালো বইয়ের সুপারিশ করতে পার?', 576),
    ('record', null, 'n., v.', 'A2', 'রেকর্ড, নথি; রেকর্ড করা', 'She broke the world record.', 'সে বিশ্ব রেকর্ড ভেঙেছে।', 577),
    ('recording', null, 'n.', 'A2', 'রেকর্ডিং, ধারণকৃত রূপ', 'I listened to the recording twice.', 'আমি রেকর্ডিংটি দুইবার শুনেছি।', 578),
    ('recycle', null, 'v.', 'A2', 'পুনর্ব্যবহার করা', 'We should recycle plastic bottles.', 'আমাদের প্লাস্টিকের বোতল পুনর্ব্যবহার করা উচিত।', 579),
    ('reduce', null, 'v.', 'A2', 'কমানো', 'Try to reduce your screen time.', 'তোমার স্ক্রিনে সময় কমানোর চেষ্টা কর।', 580),
    ('refer', null, 'v.', 'A2', 'উল্লেখ করা, নির্দেশ করা', 'The teacher referred to an old story.', 'শিক্ষক একটি পুরনো গল্পের উল্লেখ করলেন।', 581),
    ('refrigerator', null, 'n.', 'A2', 'হিমাগার, ফ্রিজ', 'Keep the milk in the refrigerator.', 'দুধ ফ্রিজে রাখো।', 582),
    ('refuse', null, 'v.', 'A2', 'প্রত্যাখ্যান করা, অস্বীকার করা', 'He refused to help us.', 'সে আমাদের সাহায্য করতে অস্বীকার করল।', 583),
    ('region', null, 'n.', 'A2', 'অঞ্চল', 'This region is famous for tea.', 'এই অঞ্চলটি চায়ের জন্য বিখ্যাত।', 584),
    ('regular', null, 'adj.', 'A2', 'নিয়মিত', 'He is a regular customer here.', 'তিনি এখানকার একজন নিয়মিত ক্রেতা।', 585),
    ('relationship', null, 'n.', 'A2', 'সম্পর্ক', 'They have a close relationship.', 'তাদের মধ্যে ঘনিষ্ঠ সম্পর্ক আছে।', 586),
    ('remove', null, 'v.', 'A2', 'সরানো, অপসারণ করা', 'Please remove your shoes here.', 'অনুগ্রহ করে এখানে জুতা খুলে রাখুন।', 587),
    ('repair', null, 'n., v.', 'A2', 'মেরামত; মেরামত করা', 'He can repair the broken bike.', 'সে ভাঙা সাইকেলটি মেরামত করতে পারে।', 588),
    ('replace', null, 'v.', 'A2', 'প্রতিস্থাপন করা, বদলানো', 'We need to replace the old battery.', 'আমাদের পুরনো ব্যাটারিটি বদলাতে হবে।', 589),
    ('reply', null, 'n., v.', 'A2', 'উত্তর; উত্তর দেওয়া', 'She did not reply to my message.', 'সে আমার বার্তার উত্তর দেয়নি।', 590),
    ('reporter', null, 'n.', 'A2', 'সংবাদদাতা, প্রতিবেদক', 'The reporter asked many questions.', 'প্রতিবেদক অনেক প্রশ্ন করলেন।', 591),
    ('request', null, 'n., v.', 'A2', 'অনুরোধ; অনুরোধ করা', 'I have a small request for you.', 'তোমার কাছে আমার একটি ছোট অনুরোধ আছে।', 592),
    ('research', null, 'n., v.', 'A2', 'গবেষণা; গবেষণা করা', 'She does research on plants.', 'সে গাছপালা নিয়ে গবেষণা করে।', 593),
    ('researcher', null, 'n.', 'A2', 'গবেষক', 'He is a researcher at the university.', 'তিনি বিশ্ববিদ্যালয়ের একজন গবেষক।', 594),
    ('respond', null, 'v.', 'A2', 'সাড়া দেওয়া, উত্তর দেওয়া', 'Please respond to the email soon.', 'অনুগ্রহ করে শীঘ্রই ইমেইলের উত্তর দিন।', 595),
    ('response', null, 'n.', 'A2', 'সাড়া, প্রতিক্রিয়া', 'We got a quick response from them.', 'আমরা তাদের কাছ থেকে দ্রুত সাড়া পেয়েছি।', 596),
    ('rest', 'remaining part', 'n.', 'A2', 'বাকি অংশ', 'I will do the rest of the work tomorrow.', 'বাকি কাজটা আমি কাল করব।', 597),
    ('rest', 'sleep/relax', 'n., v.', 'A2', 'বিশ্রাম; বিশ্রাম নেওয়া', 'You should rest after the long trip.', 'দীর্ঘ ভ্রমণের পর তোমার বিশ্রাম নেওয়া উচিত।', 598),
    ('review', null, 'n., v.', 'A2', 'পর্যালোচনা; পর্যালোচনা করা', 'I wrote a review of the movie.', 'আমি সিনেমাটির একটি পর্যালোচনা লিখেছি।', 599),
    ('ring', 'jewelry', 'n.', 'A2', 'আংটি', 'She wears a gold ring.', 'সে একটি সোনার আংটি পরে।', 600),
    ('ring', 'sound/call', 'n., v.', 'A2', 'ঘণ্টাধ্বনি; বেজে ওঠা, ফোন করা', 'The phone began to ring.', 'ফোনটি বেজে উঠতে শুরু করল।', 601),
    ('rise', null, 'n., v.', 'A2', 'উত্থান; ওঠা, বৃদ্ধি পাওয়া', 'The sun rises in the east.', 'সূর্য পূর্ব দিকে ওঠে।', 602),
    ('rock', 'music', 'n.', 'A2', 'রক সংগীত', 'He loves rock music.', 'সে রক সংগীত ভালোবাসে।', 603),
    ('rock', 'stone', 'n.', 'A2', 'পাথর, শিলা', 'The children sat on a big rock.', 'শিশুরা একটি বড় পাথরের উপর বসল।', 604),
    ('role', null, 'n.', 'A2', 'ভূমিকা', 'She played an important role in the team.', 'সে দলে একটি গুরুত্বপূর্ণ ভূমিকা পালন করেছে।', 605),
    ('roof', null, 'n.', 'A2', 'ছাদ', 'A bird sat on the roof.', 'একটি পাখি ছাদে বসল।', 606),
    ('round', null, 'prep., adv., adj., n.', 'A2', 'গোল; চারদিকে; পর্ব', 'The Earth is round.', 'পৃথিবী গোলাকার।', 607),
    ('route', null, 'n.', 'A2', 'পথ, রুট', 'This is the shortest route to school.', 'এটি স্কুলে যাওয়ার সবচেয়ে ছোট পথ।', 608),
    ('rude', null, 'adj.', 'A2', 'অভদ্র, রূঢ়', 'It is rude to interrupt people.', 'মানুষের কথার মাঝে বাধা দেওয়া অভদ্রতা।', 609),
    ('runner', null, 'n.', 'A2', 'দৌড়বিদ', 'She is the fastest runner in class.', 'সে ক্লাসের সবচেয়ে দ্রুত দৌড়বিদ।', 610),
    ('running', null, 'n.', 'A2', 'দৌড়ানো', 'Running is good for your health.', 'দৌড়ানো তোমার স্বাস্থ্যের জন্য ভালো।', 611),
    ('sadly', null, 'adv.', 'A2', 'দুঃখজনকভাবে', 'Sadly, the shop was closed.', 'দুঃখজনকভাবে, দোকানটি বন্ধ ছিল।', 612),
    ('safe', null, 'adj.', 'A2', 'নিরাপদ', 'This place is safe for children.', 'এই জায়গাটি শিশুদের জন্য নিরাপদ।', 613),
    ('sail', null, 'n., v.', 'A2', 'পাল; জাহাজে যাত্রা করা', 'The boat will sail at dawn.', 'নৌকাটি ভোরে যাত্রা করবে।', 614),
    ('sailing', null, 'n.', 'A2', 'নৌযাত্রা, পাল তোলা', 'We went sailing on the lake.', 'আমরা হ্রদে নৌযাত্রায় গিয়েছিলাম।', 615),
    ('salary', null, 'n.', 'A2', 'বেতন', 'He gets his salary every month.', 'তিনি প্রতি মাসে বেতন পান।', 616),
    ('sale', null, 'n.', 'A2', 'বিক্রয়', 'The house is for sale.', 'বাড়িটি বিক্রয়ের জন্য।', 617),
    ('sauce', null, 'n.', 'A2', 'সস, ঝোল', 'Add some tomato sauce to the pasta.', 'পাস্তায় কিছুটা টমেটো সস দাও।', 618),
    ('save', null, 'v.', 'A2', 'বাঁচানো; সঞ্চয় করা', 'I want to save money for a trip.', 'আমি একটি ভ্রমণের জন্য টাকা সঞ্চয় করতে চাই।', 619),
    ('scared', null, 'adj.', 'A2', 'ভীত, ভয় পাওয়া', 'The child was scared of the dog.', 'শিশুটি কুকুরটিকে ভয় পেয়েছিল।', 620),
    ('scary', null, 'adj.', 'A2', 'ভয়ংকর, ভীতিকর', 'We watched a scary movie.', 'আমরা একটি ভীতিকর সিনেমা দেখেছি।', 621),
    ('scene', null, 'n.', 'A2', 'দৃশ্য', 'The last scene of the film was sad.', 'সিনেমার শেষ দৃশ্যটি বিষণ্ণ ছিল।', 622),
    ('schedule', null, 'n., v.', 'A2', 'সময়সূচি; সময় নির্ধারণ করা', 'Check the train schedule first.', 'প্রথমে ট্রেনের সময়সূচি দেখে নাও।', 623),
    ('score', null, 'n., v.', 'A2', 'স্কোর, নম্বর; নম্বর করা', 'What was the final score?', 'চূড়ান্ত স্কোর কত ছিল?', 624),
    ('screen', null, 'n., v.', 'A2', 'পর্দা, স্ক্রিন', 'The screen of my phone is broken.', 'আমার ফোনের স্ক্রিন ভাঙা।', 625),
    ('sea', null, 'n.', 'A2', 'সমুদ্র', 'We swam in the sea.', 'আমরা সমুদ্রে সাঁতার কেটেছি।', 626),
    ('search', null, 'n., v.', 'A2', 'অনুসন্ধান; খোঁজা', 'They are searching for the lost dog.', 'তারা হারানো কুকুরটি খুঁজছে।', 627),
    ('season', null, 'n.', 'A2', 'ঋতু, মৌসুম', 'Winter is my favorite season.', 'শীত আমার প্রিয় ঋতু।', 628),
    ('seat', null, 'n., v.', 'A2', 'আসন, সিট; বসানো', 'Please take your seat.', 'অনুগ্রহ করে আপনার আসনে বসুন।', 629),
    ('secret', null, 'adj., n.', 'A2', 'গোপন; গোপন কথা', 'Can you keep a secret?', 'তুমি কি একটি গোপন কথা রাখতে পারবে?', 630),
    ('secretary', null, 'n.', 'A2', 'সচিব, সেক্রেটারি', 'The secretary answered the phone.', 'সেক্রেটারি ফোনটি ধরলেন।', 631),
    ('seem', null, 'v.', 'A2', 'মনে হওয়া', 'You seem tired today.', 'তোমাকে আজ ক্লান্ত মনে হচ্ছে।', 632),
    ('sense', null, 'n., v.', 'A2', 'অনুভূতি, বোধ; অনুভব করা', 'She has a good sense of humor.', 'তার রসবোধ ভালো।', 633),
    ('separate', null, 'adj., v.', 'A2', 'পৃথক; আলাদা করা', 'Keep these two files separate.', 'এই দুটি ফাইল আলাদা রাখো।', 634),
    ('series', null, 'n.', 'A2', 'ধারাবাহিক, সিরিজ', 'I am watching a new TV series.', 'আমি একটি নতুন টিভি সিরিজ দেখছি।', 635),
    ('serious', null, 'adj.', 'A2', 'গুরুতর; গম্ভীর', 'This is a serious problem.', 'এটি একটি গুরুতর সমস্যা।', 636),
    ('serve', null, 'v.', 'A2', 'পরিবেশন করা; সেবা করা', 'They serve lunch at noon.', 'তারা দুপুরে মধ্যাহ্নভোজ পরিবেশন করে।', 637),
    ('service', null, 'n.', 'A2', 'সেবা', 'The hotel has good service.', 'হোটেলটির সেবা ভালো।', 638),
    ('several', null, 'pron., det.', 'A2', 'কয়েকটি, বেশ কয়েক', 'I have visited this city several times.', 'আমি এই শহরে কয়েকবার এসেছি।', 639),
    ('shake', null, 'n., v.', 'A2', 'ঝাঁকুনি; নাড়ানো, কাঁপা', 'Shake the bottle before you drink.', 'পান করার আগে বোতলটি ঝাঁকাও।', 640),
    ('shape', null, 'n., v.', 'A2', 'আকৃতি; আকার দেওয়া', 'The cake has a round shape.', 'কেকটির আকৃতি গোল।', 641),
    ('sheet', null, 'n.', 'A2', 'চাদর; পাতা', 'Write your name on this sheet.', 'এই পাতায় তোমার নাম লেখো।', 642),
    ('ship', null, 'n., v.', 'A2', 'জাহাজ; পাঠানো', 'The ship crossed the ocean.', 'জাহাজটি সমুদ্র পার হলো।', 643),
    ('shoulder', null, 'n.', 'A2', 'কাঁধ', 'He carried the bag on his shoulder.', 'সে ব্যাগটি কাঁধে বহন করল।', 644),
    ('shout', null, 'n., v.', 'A2', 'চিৎকার; চিৎকার করা', 'Please do not shout in the library.', 'অনুগ্রহ করে গ্রন্থাগারে চিৎকার করো না।', 645),
    ('shut', null, 'adj., v.', 'A2', 'বন্ধ; বন্ধ করা', 'Please shut the window.', 'অনুগ্রহ করে জানালাটি বন্ধ করো।', 646),
    ('side', null, 'n.', 'A2', 'পাশ, দিক', 'Write on both sides of the paper.', 'কাগজের দুই পাশেই লেখো।', 647),
    ('sign', null, 'n., v.', 'A2', 'চিহ্ন, সাইন; স্বাক্ষর করা', 'Please sign here.', 'অনুগ্রহ করে এখানে স্বাক্ষর করুন।', 648),
    ('silver', null, 'adj., n.', 'A2', 'রূপা; রুপালি', 'She wore a silver necklace.', 'সে একটি রুপালি হার পরেছিল।', 649),
    ('simple', null, 'adj.', 'A2', 'সহজ, সরল', 'This is a very simple question.', 'এটি একটি খুব সহজ প্রশ্ন।', 650),
    ('since', null, 'prep., conj., adv.', 'A2', 'থেকে; যেহেতু', 'I have lived here since 2010.', 'আমি ২০১০ সাল থেকে এখানে বাস করছি।', 651),
    ('singing', null, 'n.', 'A2', 'গান গাওয়া', 'Her singing made everyone happy.', 'তার গান সবাইকে খুশি করল।', 652),
    ('single', null, 'adj., n.', 'A2', 'একক, একমাত্র; অবিবাহিত', 'There is a single tree in the field.', 'মাঠে একটিমাত্র গাছ আছে।', 653),
    ('sir', null, 'n.', 'A2', 'স্যার, মহাশয়', 'Excuse me, sir, is this seat free?', 'মাফ করবেন স্যার, এই আসনটি কি খালি?', 654),
    ('site', null, 'n.', 'A2', 'স্থান; ওয়েবসাইট', 'They are building a house on this site.', 'তারা এই স্থানে একটি বাড়ি বানাচ্ছে।', 655),
    ('size', null, 'n.', 'A2', 'আকার, মাপ', 'What size shoes do you wear?', 'তুমি কোন মাপের জুতা পরো?', 656),
    ('ski', null, 'n., v.', 'A2', 'স্কি; স্কি করা', 'They learned to ski in the mountains.', 'তারা পাহাড়ে স্কি করা শিখেছিল।', 657),
    ('skiing', null, 'n.', 'A2', 'স্কিইং, স্কি খেলা', 'Skiing is popular in winter.', 'শীতকালে স্কিইং জনপ্রিয়।', 658),
    ('skin', null, 'n.', 'A2', 'ত্বক, চামড়া', 'Protect your skin from the sun.', 'রোদ থেকে তোমার ত্বক রক্ষা কর।', 659),
    ('sky', null, 'n.', 'A2', 'আকাশ', 'The sky is clear and blue.', 'আকাশ পরিষ্কার ও নীল।', 660),
    ('slowly', null, 'adv.', 'A2', 'ধীরে', 'Please speak more slowly.', 'অনুগ্রহ করে আরও ধীরে কথা বলুন।', 661),
    ('smartphone', null, 'n.', 'A2', 'স্মার্টফোন', 'She bought a new smartphone.', 'সে একটি নতুন স্মার্টফোন কিনেছে।', 662),
    ('smell', null, 'n., v.', 'A2', 'গন্ধ; গন্ধ পাওয়া', 'I can smell fresh bread.', 'আমি তাজা রুটির গন্ধ পাচ্ছি।', 663),
    ('smile', null, 'n., v.', 'A2', 'হাসি; হাসা', 'She gave me a warm smile.', 'সে আমাকে একটি উষ্ণ হাসি দিল।', 664),
    ('smoke', null, 'n., v.', 'A2', 'ধোঁয়া; ধূমপান করা', 'Smoke was coming from the kitchen.', 'রান্নাঘর থেকে ধোঁয়া আসছিল।', 665),
    ('smoking', null, 'n.', 'A2', 'ধূমপান', 'Smoking is not allowed here.', 'এখানে ধূমপান নিষিদ্ধ।', 666),
    ('sneaker', null, 'n.', 'A2', 'কেডস, স্নিকার', 'He bought white sneakers.', 'সে সাদা স্নিকার কিনেছে।', 667),
    ('soap', null, 'n.', 'A2', 'সাবান', 'Wash your hands with soap.', 'সাবান দিয়ে হাত ধোও।', 668),
    ('soccer', null, 'n.', 'A2', 'ফুটবল', 'The boys are playing soccer.', 'ছেলেরা ফুটবল খেলছে।', 669),
    ('social', null, 'adj.', 'A2', 'সামাজিক', 'He has a busy social life.', 'তার সামাজিক জীবন ব্যস্ত।', 670),
    ('society', null, 'n.', 'A2', 'সমাজ', 'Education helps improve society.', 'শিক্ষা সমাজের উন্নতিতে সাহায্য করে।', 671),
    ('sock', null, 'n.', 'A2', 'মোজা', 'I cannot find my other sock.', 'আমি আমার অন্য মোজাটি খুঁজে পাচ্ছি না।', 672),
    ('soft', null, 'adj.', 'A2', 'নরম', 'The pillow is very soft.', 'বালিশটি খুব নরম।', 673),
    ('soldier', null, 'n.', 'A2', 'সৈনিক', 'The soldier stood at the gate.', 'সৈনিকটি ফটকে দাঁড়িয়ে ছিল।', 674),
    ('solution', null, 'n.', 'A2', 'সমাধান', 'We found a simple solution.', 'আমরা একটি সহজ সমাধান পেয়েছি।', 675),
    ('solve', null, 'v.', 'A2', 'সমাধান করা', 'Can you solve this problem?', 'তুমি কি এই সমস্যাটি সমাধান করতে পার?', 676),
    ('somewhere', null, 'pron., adv.', 'A2', 'কোথাও', 'I left my keys somewhere.', 'আমি আমার চাবি কোথাও রেখে দিয়েছি।', 677),
    ('sort', null, 'n., v.', 'A2', 'ধরন; সাজানো, বাছাই করা', 'What sort of music do you like?', 'তুমি কোন ধরনের সংগীত পছন্দ কর?', 678),
    ('source', null, 'n.', 'A2', 'উৎস', 'The sun is a source of energy.', 'সূর্য শক্তির একটি উৎস।', 679),
    ('speaker', null, 'n.', 'A2', 'বক্তা; স্পিকার', 'The speaker gave a short talk.', 'বক্তা একটি সংক্ষিপ্ত বক্তৃতা দিলেন।', 680),
    ('specific', null, 'adj.', 'A2', 'নির্দিষ্ট', 'Give me a specific example.', 'আমাকে একটি নির্দিষ্ট উদাহরণ দাও।', 681),
    ('speech', null, 'n.', 'A2', 'বক্তৃতা, ভাষণ', 'He gave a wonderful speech.', 'তিনি একটি চমৎকার বক্তৃতা দিলেন।', 682),
    ('speed', null, 'n., v.', 'A2', 'গতি; দ্রুত চলা', 'The car moved at high speed.', 'গাড়িটি দ্রুত গতিতে চলল।', 683),
    ('spider', null, 'n.', 'A2', 'মাকড়সা', 'A spider made a web in the corner.', 'একটি মাকড়সা কোণে জাল বুনল।', 684),
    ('spoon', null, 'n.', 'A2', 'চামচ', 'Eat the soup with a spoon.', 'চামচ দিয়ে স্যুপ খাও।', 685),
    ('square', null, 'adj., n.', 'A2', 'বর্গাকার; চত্বর', 'The table has a square shape.', 'টেবিলটির আকৃতি বর্গাকার।', 686),
    ('stage', null, 'n., v.', 'A2', 'মঞ্চ; পর্যায়', 'The singer walked onto the stage.', 'গায়ক মঞ্চে উঠলেন।', 687),
    ('stair', null, 'n.', 'A2', 'সিঁড়ির ধাপ', 'She sat on the bottom stair.', 'সে সিঁড়ির নিচের ধাপে বসল।', 688),
    ('stamp', null, 'n.', 'A2', 'ডাকটিকিট; সিলমোহর', 'He put a stamp on the letter.', 'সে চিঠিতে একটি ডাকটিকিট লাগাল।', 689),
    ('state', null, 'adj., n., v.', 'A2', 'অবস্থা; রাজ্য; বিবৃত করা', 'Please state your name clearly.', 'অনুগ্রহ করে আপনার নাম স্পষ্টভাবে বলুন।', 690),
    ('steal', null, 'v.', 'A2', 'চুরি করা', 'Someone tried to steal my bag.', 'কেউ আমার ব্যাগ চুরি করার চেষ্টা করেছিল।', 691),
    ('step', null, 'n., v.', 'A2', 'পদক্ষেপ; পা ফেলা', 'Follow each step carefully.', 'প্রতিটি পদক্ষেপ সাবধানে অনুসরণ কর।', 692),
    ('stomach', null, 'n.', 'A2', 'পেট, উদর', 'My stomach hurts.', 'আমার পেট ব্যথা করছে।', 693),
    ('stone', null, 'n.', 'A2', 'পাথর', 'He threw a stone into the river.', 'সে নদীতে একটি পাথর ছুড়ল।', 694),
    ('storm', null, 'n.', 'A2', 'ঝড়', 'A big storm is coming tonight.', 'আজ রাতে একটি বড় ঝড় আসছে।', 695),
    ('stove', null, 'n.', 'A2', 'চুলা', 'The pot is on the stove.', 'পাত্রটি চুলার উপর আছে।', 696),
    ('straight', null, 'adv., adj.', 'A2', 'সোজা', 'Go straight and turn left.', 'সোজা যাও এবং বাঁ দিকে ঘোরো।', 697),
    ('strange', null, 'adj.', 'A2', 'অদ্ভুত, অচেনা', 'I heard a strange noise.', 'আমি একটি অদ্ভুত শব্দ শুনলাম।', 698),
    ('strategy', null, 'n.', 'A2', 'কৌশল, রণকৌশল', 'We need a new strategy to win.', 'জিততে আমাদের একটি নতুন কৌশল দরকার।', 699),
    ('stress', null, 'n., v.', 'A2', 'চাপ, মানসিক চাপ; জোর দেওয়া', 'Too much work causes stress.', 'অতিরিক্ত কাজ মানসিক চাপ সৃষ্টি করে।', 700),
    ('structure', null, 'n., v.', 'A2', 'কাঠামো; গঠন করা', 'The building has a strong structure.', 'ভবনটির কাঠামো মজবুত।', 701),
    ('stupid', null, 'adj.', 'A2', 'বোকা, নির্বোধ', 'That was a stupid mistake.', 'ওটা একটি বোকা ভুল ছিল।', 702),
    ('subway', null, 'n.', 'A2', 'পাতাল রেল', 'We took the subway to work.', 'আমরা কাজে যেতে পাতাল রেল নিলাম।', 703),
    ('succeed', null, 'v.', 'A2', 'সফল হওয়া', 'She worked hard to succeed.', 'সে সফল হতে কঠোর পরিশ্রম করেছে।', 704),
    ('successful', null, 'adj.', 'A2', 'সফল', 'He is a successful businessman.', 'তিনি একজন সফল ব্যবসায়ী।', 705),
    ('such', null, 'pron., det.', 'A2', 'এমন, এরূপ', 'I have never seen such a big dog.', 'আমি এত বড় কুকুর কখনো দেখিনি।', 706),
    ('suddenly', null, 'adv.', 'A2', 'হঠাৎ', 'Suddenly, the lights went out.', 'হঠাৎ, আলো নিভে গেল।', 707),
    ('suggest', null, 'v.', 'A2', 'পরামর্শ দেওয়া, প্রস্তাব করা', 'I suggest we start early.', 'আমি পরামর্শ দিচ্ছি আমরা তাড়াতাড়ি শুরু করি।', 708),
    ('suggestion', null, 'n.', 'A2', 'পরামর্শ, প্রস্তাব', 'That is a good suggestion.', 'এটি একটি ভালো পরামর্শ।', 709),
    ('suit', null, 'n., v.', 'A2', 'স্যুট, পোশাক; মানানসই হওয়া', 'This color suits you well.', 'এই রঙটি তোমাকে ভালো মানায়।', 710),
    ('support', null, 'n., v.', 'A2', 'সমর্থন; সমর্থন করা', 'Thank you for your support.', 'তোমার সমর্থনের জন্য ধন্যবাদ।', 711),
    ('suppose', null, 'v.', 'A2', 'ধরে নেওয়া, অনুমান করা', 'I suppose you are right.', 'আমার ধারণা তুমি ঠিক বলছ।', 712),
    ('surprise', null, 'n., v.', 'A2', 'বিস্ময়, চমক; অবাক করা', 'The gift was a big surprise.', 'উপহারটি একটি বড় চমক ছিল।', 713),
    ('surprised', null, 'adj.', 'A2', 'অবাক, বিস্মিত', 'I was surprised to see her.', 'তাকে দেখে আমি অবাক হয়েছিলাম।', 714),
    ('surprising', null, 'adj.', 'A2', 'বিস্ময়কর', 'The result was quite surprising.', 'ফলাফলটি বেশ বিস্ময়কর ছিল।', 715),
    ('survey', null, 'n., v.', 'A2', 'জরিপ; জরিপ করা', 'They did a survey of the students.', 'তারা শিক্ষার্থীদের নিয়ে একটি জরিপ করল।', 716),
    ('sweet', null, 'adj.', 'A2', 'মিষ্টি', 'This mango is very sweet.', 'এই আমটি খুব মিষ্টি।', 717),
    ('symbol', null, 'n.', 'A2', 'প্রতীক', 'A dove is a symbol of peace.', 'পায়রা শান্তির প্রতীক।', 718),
    ('system', null, 'n.', 'A2', 'ব্যবস্থা, পদ্ধতি', 'The school has a new grading system.', 'স্কুলে একটি নতুন গ্রেডিং ব্যবস্থা আছে।', 719),
    ('tablet', null, 'n.', 'A2', 'ট্যাবলেট; বড়ি', 'She reads books on her tablet.', 'সে তার ট্যাবলেটে বই পড়ে।', 720),
    ('target', null, 'n., v.', 'A2', 'লক্ষ্য; লক্ষ্য করা', 'Our target is to finish by June.', 'আমাদের লক্ষ্য জুনের মধ্যে শেষ করা।', 721),
    ('task', null, 'n.', 'A2', 'কাজ, দায়িত্ব', 'This task is easy to complete.', 'এই কাজটি শেষ করা সহজ।', 722),
    ('taste', null, 'n., v.', 'A2', 'স্বাদ; স্বাদ নেওয়া', 'The soup has a nice taste.', 'স্যুপটির স্বাদ চমৎকার।', 723),
    ('teaching', null, 'n.', 'A2', 'শিক্ষকতা, পাঠদান', 'She enjoys teaching children.', 'সে শিশুদের পড়াতে ভালোবাসে।', 724),
    ('technology', null, 'n.', 'A2', 'প্রযুক্তি', 'Technology has changed our lives.', 'প্রযুক্তি আমাদের জীবন বদলে দিয়েছে।', 725),
    ('teenage', null, 'adj.', 'A2', 'কিশোর বয়সের', 'They have two teenage daughters.', 'তাদের দুটি কিশোরী মেয়ে আছে।', 726),
    ('temperature', null, 'n.', 'A2', 'তাপমাত্রা', 'The temperature is very high today.', 'আজ তাপমাত্রা খুব বেশি।', 727),
    ('term', null, 'n., v.', 'A2', 'পরিভাষা; মেয়াদ, সেমিস্টার', 'The new term starts in September.', 'নতুন সেমিস্টার সেপ্টেম্বরে শুরু হয়।', 728),
    ('themselves', null, 'pron.', 'A2', 'তারা নিজেরা', 'The children made the cake themselves.', 'শিশুরা নিজেরাই কেকটি বানিয়েছে।', 729),
    ('thick', null, 'adj.', 'A2', 'পুরু, ঘন', 'He wore a thick coat.', 'সে একটি পুরু কোট পরেছিল।', 730),
    ('thief', null, 'n.', 'A2', 'চোর', 'The police caught the thief.', 'পুলিশ চোরটিকে ধরল।', 731),
    ('thin', null, 'adj.', 'A2', 'পাতলা; রোগা', 'Cut the bread into thin slices.', 'রুটিটি পাতলা টুকরো করে কাটো।', 732),
    ('thinking', null, 'n.', 'A2', 'চিন্তা, ভাবনা', 'Good thinking led to the answer.', 'ভালো চিন্তা উত্তরের দিকে নিয়ে গেল।', 733),
    ('thought', null, 'n.', 'A2', 'চিন্তা, ভাবনা', 'A sudden thought came to my mind.', 'হঠাৎ একটি চিন্তা আমার মনে এল।', 734),
    ('throw', null, 'v.', 'A2', 'ছোড়া, নিক্ষেপ করা', 'Throw the ball to me.', 'বলটি আমার দিকে ছোড়ো।', 735),
    ('tie', null, 'n., v.', 'A2', 'টাই; বাঁধা', 'He wore a blue tie to the office.', 'সে অফিসে একটি নীল টাই পরল।', 736),
    ('tip', null, 'n., v.', 'A2', 'পরামর্শ; বকশিশ; আগা', 'Here is a useful tip for you.', 'তোমার জন্য এখানে একটি দরকারি পরামর্শ।', 737),
    ('tool', null, 'n.', 'A2', 'যন্ত্র, হাতিয়ার', 'A hammer is a useful tool.', 'হাতুড়ি একটি দরকারি যন্ত্র।', 738),
    ('top', null, 'adj., n.', 'A2', 'উপরের অংশ, শীর্ষ', 'The book is on top of the shelf.', 'বইটি তাকের উপরে আছে।', 739),
    ('touch', null, 'n., v.', 'A2', 'স্পর্শ; স্পর্শ করা', 'Do not touch the hot stove.', 'গরম চুলা স্পর্শ করো না।', 740),
    ('tour', null, 'n., v.', 'A2', 'ভ্রমণ, সফর', 'We went on a city tour.', 'আমরা একটি শহর ভ্রমণে গিয়েছিলাম।', 741),
    ('tourism', null, 'n.', 'A2', 'পর্যটন', 'Tourism is important for this town.', 'এই শহরের জন্য পর্যটন গুরুত্বপূর্ণ।', 742),
    ('toward', null, 'prep.', 'A2', 'দিকে, অভিমুখে', 'She walked toward the door.', 'সে দরজার দিকে হাঁটল।', 743),
    ('towel', null, 'n.', 'A2', 'তোয়ালে, গামছা', 'Dry your hands with a towel.', 'তোয়ালে দিয়ে হাত শুকাও।', 744),
    ('tower', null, 'n.', 'A2', 'মিনার, টাওয়ার', 'We climbed to the top of the tower.', 'আমরা টাওয়ারের চূড়ায় উঠলাম।', 745),
    ('toy', null, 'adj., n.', 'A2', 'খেলনা', 'The baby played with a toy car.', 'শিশুটি একটি খেলনা গাড়ি নিয়ে খেলল।', 746),
    ('track', null, 'n., v.', 'A2', 'পথ, ট্র্যাক; অনুসরণ করা', 'The train left the track.', 'ট্রেনটি লাইনচ্যুত হলো।', 747),
    ('tradition', null, 'n.', 'A2', 'ঐতিহ্য, প্রথা', 'This is an old family tradition.', 'এটি একটি পুরনো পারিবারিক ঐতিহ্য।', 748),
    ('traditional', null, 'adj.', 'A2', 'ঐতিহ্যবাহী', 'She wore a traditional dress.', 'সে একটি ঐতিহ্যবাহী পোশাক পরেছিল।', 749),
    ('training', null, 'n.', 'A2', 'প্রশিক্ষণ', 'The new staff need some training.', 'নতুন কর্মীদের কিছু প্রশিক্ষণ দরকার।', 750),
    ('transportation', null, 'n.', 'A2', 'পরিবহন', 'Buses are cheap transportation.', 'বাস সস্তা পরিবহন।', 751),
    ('trash', null, 'n.', 'A2', 'আবর্জনা', 'Please throw the trash in the bin.', 'অনুগ্রহ করে আবর্জনা ঝুড়িতে ফেলো।', 752),
    ('traveler', null, 'n.', 'A2', 'ভ্রমণকারী, পর্যটক', 'The traveler asked for directions.', 'ভ্রমণকারী পথের নির্দেশ চাইলেন।', 753),
    ('trouble', null, 'n., v.', 'A2', 'সমস্যা, ঝামেলা; বিরক্ত করা', 'He is in trouble with his teacher.', 'সে তার শিক্ষকের সঙ্গে ঝামেলায় আছে।', 754),
    ('twin', null, 'adj., n.', 'A2', 'যমজ', 'She has a twin sister.', 'তার একটি যমজ বোন আছে।', 755),
    ('typical', null, 'adj.', 'A2', 'সাধারণ, বৈশিষ্ট্যপূর্ণ', 'This is a typical winter day.', 'এটি একটি সাধারণ শীতের দিন।', 756),
    ('underground', null, 'adv., adj.', 'A2', 'ভূগর্ভস্থ, মাটির নিচে', 'The trains run underground.', 'ট্রেনগুলো মাটির নিচে চলে।', 757),
    ('understanding', null, 'n.', 'A2', 'বোঝাপড়া, উপলব্ধি', 'They reached a good understanding.', 'তারা একটি ভালো বোঝাপড়ায় পৌঁছাল।', 758),
    ('unfortunately', null, 'adv.', 'A2', 'দুর্ভাগ্যবশত', 'Unfortunately, we missed the bus.', 'দুর্ভাগ্যবশত, আমরা বাসটি মিস করলাম।', 759),
    ('unhappy', null, 'adj.', 'A2', 'অসুখী, বিষণ্ণ', 'She looked unhappy this morning.', 'আজ সকালে তাকে অসুখী দেখাল।', 760),
    ('uniform', null, 'n.', 'A2', 'ইউনিফর্ম, পোশাক', 'Students wear a school uniform.', 'শিক্ষার্থীরা স্কুলের পোশাক পরে।', 761),
    ('unit', null, 'n.', 'A2', 'একক; অধ্যায়', 'We finished the first unit today.', 'আমরা আজ প্রথম অধ্যায় শেষ করেছি।', 762),
    ('united', null, 'adj.', 'A2', 'ঐক্যবদ্ধ, সংযুক্ত', 'The team stayed united.', 'দলটি ঐক্যবদ্ধ থাকল।', 763),
    ('unusual', null, 'adj.', 'A2', 'অস্বাভাবিক, অসাধারণ', 'It is unusual for him to be late.', 'তার দেরি করাটা অস্বাভাবিক।', 764),
    ('used to', null, 'modal v., v.', 'A2', 'আগে করতাম (অভ্যাস বোঝায়)', 'I used to play cricket every day.', 'আমি আগে প্রতিদিন ক্রিকেট খেলতাম।', 765),
    ('user', null, 'n.', 'A2', 'ব্যবহারকারী', 'The app has millions of users.', 'অ্যাপটির লক্ষ লক্ষ ব্যবহারকারী আছে।', 766),
    ('usual', null, 'adj.', 'A2', 'স্বাভাবিক, প্রচলিত', 'We met at the usual place.', 'আমরা চেনা জায়গায় দেখা করলাম।', 767),
    ('valley', null, 'n.', 'A2', 'উপত্যকা', 'A river flows through the valley.', 'উপত্যকার ভেতর দিয়ে একটি নদী বয়ে যায়।', 768),
    ('variety', null, 'n.', 'A2', 'বৈচিত্র্য, নানা রকম', 'The shop sells a variety of fruits.', 'দোকানটি নানা রকমের ফল বিক্রি করে।', 769),
    ('vehicle', null, 'n.', 'A2', 'যানবাহন', 'No vehicles are allowed here.', 'এখানে কোনো যানবাহন প্রবেশ নিষেধ।', 770),
    ('view', null, 'n., v.', 'A2', 'দৃশ্য; মত; দেখা', 'The room has a lovely view.', 'ঘরটি থেকে সুন্দর দৃশ্য দেখা যায়।', 771),
    ('village', null, 'n.', 'A2', 'গ্রাম', 'My grandparents live in a village.', 'আমার দাদা-দাদি একটি গ্রামে থাকেন।', 772),
    ('virus', null, 'n.', 'A2', 'ভাইরাস', 'A virus made him ill.', 'একটি ভাইরাস তাকে অসুস্থ করে দিল।', 773),
    ('voice', null, 'n.', 'A2', 'কণ্ঠস্বর', 'She has a beautiful voice.', 'তার কণ্ঠস্বর সুন্দর।', 774),
    ('war', null, 'n.', 'A2', 'যুদ্ধ', 'Many people suffer during a war.', 'যুদ্ধের সময় অনেক মানুষ কষ্ট পায়।', 775),
    ('washing', null, 'n.', 'A2', 'ধোয়ার কাজ, কাচা কাপড়', 'She hung the washing outside.', 'সে কাচা কাপড় বাইরে মেলে দিল।', 776),
    ('wave', null, 'n., v.', 'A2', 'ঢেউ; হাত নাড়া', 'She waved goodbye to us.', 'সে আমাদের বিদায় জানিয়ে হাত নাড়ল।', 777),
    ('weak', null, 'adj.', 'A2', 'দুর্বল', 'He felt weak after the illness.', 'অসুস্থতার পর সে দুর্বল বোধ করল।', 778),
    ('web', null, 'n.', 'A2', 'জাল; ওয়েব', 'I found the recipe on the web.', 'আমি ওয়েবে রেসিপিটি পেয়েছি।', 779),
    ('wedding', null, 'n.', 'A2', 'বিয়ে, বিবাহ অনুষ্ঠান', 'We are invited to their wedding.', 'আমরা তাদের বিয়েতে আমন্ত্রিত।', 780),
    ('weight', null, 'n.', 'A2', 'ওজন, ভার', 'What is the weight of this box?', 'এই বাক্সের ওজন কত?', 781),
    ('wet', null, 'adj.', 'A2', 'ভেজা, সিক্ত', 'The grass is still wet.', 'ঘাস এখনো ভেজা।', 782),
    ('wheel', null, 'n.', 'A2', 'চাকা', 'One wheel of the car is flat.', 'গাড়ির একটি চাকা পাংচার হয়ে গেছে।', 783),
    ('while', null, 'conj., n.', 'A2', 'যখন, সময়কাল; কিছুক্ষণ', 'Please wait here for a while.', 'অনুগ্রহ করে এখানে কিছুক্ষণ অপেক্ষা কর।', 784),
    ('whole', null, 'adj., n.', 'A2', 'সম্পূর্ণ, গোটা', 'He ate the whole cake.', 'সে গোটা কেকটি খেয়ে ফেলল।', 785),
    ('whose', null, 'pron., det.', 'A2', 'কার, যার', 'Whose bag is this?', 'এটি কার ব্যাগ?', 786),
    ('wide', null, 'adj.', 'A2', 'চওড়া, প্রশস্ত', 'This is a wide road.', 'এটি একটি চওড়া রাস্তা।', 787),
    ('wild', null, 'adj.', 'A2', 'বন্য, জংলি', 'Wild animals live in the forest.', 'বন্য প্রাণীরা বনে বাস করে।', 788),
    ('wind', null, 'n.', 'A2', 'বাতাস, হাওয়া', 'A cold wind is blowing.', 'একটি ঠান্ডা বাতাস বইছে।', 789),
    ('winner', null, 'n.', 'A2', 'বিজয়ী', 'She is the winner of the contest.', 'সে প্রতিযোগিতার বিজয়ী।', 790),
    ('wish', null, 'n., v.', 'A2', 'ইচ্ছা, শুভকামনা; কামনা করা', 'I wish you good luck.', 'আমি তোমার শুভকামনা করি।', 791),
    ('wood', null, 'n.', 'A2', 'কাঠ', 'The table is made of wood.', 'টেবিলটি কাঠের তৈরি।', 792),
    ('wooden', null, 'adj.', 'A2', 'কাঠের তৈরি', 'She has a wooden chair.', 'তার একটি কাঠের চেয়ার আছে।', 793),
    ('working', null, 'adj.', 'A2', 'কর্মরত; সচল', 'She is a working mother.', 'সে একজন কর্মজীবী মা।', 794),
    ('worried', null, 'adj.', 'A2', 'চিন্তিত, উদ্বিগ্ন', 'I am worried about the exam.', 'আমি পরীক্ষা নিয়ে চিন্তিত।', 795),
    ('worry', null, 'n., v.', 'A2', 'দুশ্চিন্তা; চিন্তা করা', 'Do not worry about small things.', 'ছোট বিষয় নিয়ে দুশ্চিন্তা করো না।', 796),
    ('worse', null, 'adv., adj., n.', 'A2', 'আরও খারাপ', 'The weather got worse in the evening.', 'সন্ধ্যায় আবহাওয়া আরও খারাপ হলো।', 797),
    ('worst', null, 'adv., adj., n.', 'A2', 'সবচেয়ে খারাপ', 'It was the worst day of my life.', 'এটি আমার জীবনের সবচেয়ে খারাপ দিন ছিল।', 798),
    ('wow', null, 'exclam.', 'A2', 'বাহ! (বিস্ময়সূচক)', 'Wow, what a beautiful view!', 'বাহ, কী সুন্দর দৃশ্য!', 799),
    ('yet', null, 'conj., adv.', 'A2', 'এখনো; তবুও', 'I have not finished my work yet.', 'আমি এখনো আমার কাজ শেষ করিনি।', 800),
    ('yours', null, 'pron.', 'A2', 'তোমার, আপনার', 'Is this book yours?', 'এই বইটি কি তোমার?', 801);
