-- V14 — seed vocabulary: Oxford 3000 (American English) B1 band, 699 headwords.
-- Generated from authored Bengali glosses + bilingual examples (scratchpad/b1_chunk_*.json).
-- Standalone reference data; see V11 for the table.

insert into vocabulary
    (headword, sense_label, part_of_speech, cefr_level, bn_gloss, example_en, example_bn, ordinal)
values
    ('absolutely', null, 'adv.', 'B1', 'একেবারে, সম্পূর্ণভাবে', 'You are absolutely right.', 'তুমি একেবারে ঠিক বলেছ।', 1),
    ('academic', null, 'adj.', 'B1', 'শিক্ষা-সংক্রান্ত, একাডেমিক', 'She has a strong academic record.', 'তার একাডেমিক ফলাফল খুব ভালো।', 2),
    ('access', null, 'n., v.', 'B1', 'প্রবেশাধিকার; প্রবেশ করা', 'Students have access to the library.', 'শিক্ষার্থীদের গ্রন্থাগারে প্রবেশাধিকার আছে।', 3),
    ('account', null, 'n., v.', 'B1', 'হিসাব; অ্যাকাউন্ট', 'I opened a bank account.', 'আমি একটি ব্যাংক অ্যাকাউন্ট খুলেছি।', 4),
    ('achievement', null, 'n.', 'B1', 'অর্জন, সাফল্য', 'Winning the prize was a great achievement.', 'পুরস্কার জেতা ছিল একটি বড় অর্জন।', 5),
    ('ad', null, 'n.', 'B1', 'বিজ্ঞাপন', 'I saw the ad on television.', 'আমি টেলিভিশনে বিজ্ঞাপনটি দেখেছি।', 6),
    ('addition', null, 'n.', 'B1', 'যোগ; সংযোজন', 'In addition, we need more time.', 'তাছাড়া, আমাদের আরও সময় দরকার।', 7),
    ('administration', null, 'n.', 'B1', 'প্রশাসন, পরিচালনা', 'She works in the school administration.', 'সে স্কুল প্রশাসনে কাজ করে।', 8),
    ('admire', null, 'v.', 'B1', 'প্রশংসা করা, মুগ্ধ হওয়া', 'I admire her courage.', 'আমি তার সাহসের প্রশংসা করি।', 9),
    ('admit', null, 'v.', 'B1', 'স্বীকার করা', 'He admitted his mistake.', 'সে তার ভুল স্বীকার করল।', 10),
    ('advanced', null, 'adj.', 'B1', 'উন্নত, অগ্রসর', 'This is an advanced English class.', 'এটি একটি উন্নত স্তরের ইংরেজি ক্লাস।', 11),
    ('advise', null, 'v.', 'B1', 'পরামর্শ দেওয়া', 'The doctor advised me to rest.', 'ডাক্তার আমাকে বিশ্রাম নিতে পরামর্শ দিলেন।', 12),
    ('afford', null, 'v.', 'B1', 'সামর্থ্য থাকা, বহন করতে পারা', 'I cannot afford a new car.', 'আমি একটি নতুন গাড়ি কেনার সামর্থ্য রাখি না।', 13),
    ('agent', null, 'n.', 'B1', 'প্রতিনিধি, এজেন্ট', 'A travel agent booked our tickets.', 'একজন ট্রাভেল এজেন্ট আমাদের টিকিট বুক করলেন।', 14),
    ('agreement', null, 'n.', 'B1', 'চুক্তি, সম্মতি', 'The two sides reached an agreement.', 'দুই পক্ষ একটি চুক্তিতে পৌঁছাল।', 15),
    ('ahead', null, 'adv.', 'B1', 'সামনে, অগ্রে', 'The road ahead is closed.', 'সামনের রাস্তাটি বন্ধ।', 16),
    ('aim', null, 'n., v.', 'B1', 'লক্ষ্য; লক্ষ্য করা', 'Our aim is to help students.', 'আমাদের লক্ষ্য শিক্ষার্থীদের সাহায্য করা।', 17),
    ('alarm', null, 'n., v.', 'B1', 'সতর্কধ্বনি, অ্যালার্ম; আতঙ্কিত করা', 'The fire alarm rang loudly.', 'অগ্নি-সংকেত জোরে বেজে উঠল।', 18),
    ('album', null, 'n.', 'B1', 'অ্যালবাম, সংকলন', 'The band released a new album.', 'ব্যান্ডটি একটি নতুন অ্যালবাম প্রকাশ করল।', 19),
    ('alcohol', null, 'n.', 'B1', 'মদ, অ্যালকোহল', 'He does not drink alcohol.', 'সে মদ পান করে না।', 20),
    ('alcoholic', null, 'adj.', 'B1', 'মদজাত, অ্যালকোহলযুক্ত', 'They do not serve alcoholic drinks.', 'তারা মদজাত পানীয় পরিবেশন করে না।', 21),
    ('amazed', null, 'adj.', 'B1', 'বিস্মিত, হতবাক', 'I was amazed by the magic show.', 'জাদু প্রদর্শনী দেখে আমি হতবাক হয়ে গেলাম।', 22),
    ('ambition', null, 'n.', 'B1', 'উচ্চাকাঙ্ক্ষা, স্বপ্ন', 'Her ambition is to become a doctor.', 'তার স্বপ্ন একজন ডাক্তার হওয়া।', 23),
    ('analysis', null, 'n.', 'B1', 'বিশ্লেষণ', 'The report gives a clear analysis.', 'প্রতিবেদনটি একটি স্পষ্ট বিশ্লেষণ দেয়।', 24),
    ('announce', null, 'v.', 'B1', 'ঘোষণা করা', 'They announced the winner.', 'তারা বিজয়ীর নাম ঘোষণা করল।', 25),
    ('announcement', null, 'n.', 'B1', 'ঘোষণা', 'Please listen to the announcement.', 'অনুগ্রহ করে ঘোষণাটি শুনুন।', 26),
    ('annoy', null, 'v.', 'B1', 'বিরক্ত করা', 'The loud music annoyed the neighbors.', 'জোরে বাজানো গান প্রতিবেশীদের বিরক্ত করল।', 27),
    ('annoyed', null, 'adj.', 'B1', 'বিরক্ত', 'She was annoyed by the delay.', 'দেরির কারণে সে বিরক্ত হয়েছিল।', 28),
    ('annoying', null, 'adj.', 'B1', 'বিরক্তিকর', 'That noise is really annoying.', 'ওই শব্দটা সত্যিই বিরক্তিকর।', 29),
    ('apart', null, 'adv.', 'B1', 'পৃথকভাবে, আলাদা', 'The two houses are far apart.', 'বাড়ি দুটি একে অপর থেকে অনেক দূরে।', 30),
    ('apologize', null, 'v.', 'B1', 'ক্ষমা চাওয়া', 'He apologized for being late.', 'দেরি করার জন্য সে ক্ষমা চাইল।', 31),
    ('application', null, 'n.', 'B1', 'আবেদন; প্রয়োগ', 'I sent my job application today.', 'আমি আজ আমার চাকরির আবেদন পাঠিয়েছি।', 32),
    ('appointment', null, 'n.', 'B1', 'সাক্ষাৎকারের সময়, অ্যাপয়েন্টমেন্ট', 'I have a doctor''s appointment at five.', 'আমার পাঁচটায় ডাক্তারের অ্যাপয়েন্টমেন্ট আছে।', 33),
    ('appreciate', null, 'v.', 'B1', 'কদর করা, কৃতজ্ঞ হওয়া', 'I appreciate your help.', 'আমি তোমার সাহায্যের জন্য কৃতজ্ঞ।', 34),
    ('approximately', null, 'adv.', 'B1', 'আনুমানিক, প্রায়', 'The trip takes approximately two hours.', 'যাত্রাটি আনুমানিক দুই ঘণ্টা সময় নেয়।', 35),
    ('arrest', null, 'n., v.', 'B1', 'গ্রেপ্তার; গ্রেপ্তার করা', 'The police arrested the thief.', 'পুলিশ চোরটিকে গ্রেপ্তার করল।', 36),
    ('arrival', null, 'n.', 'B1', 'আগমন', 'We waited for their arrival.', 'আমরা তাদের আগমনের জন্য অপেক্ষা করলাম।', 37),
    ('assignment', null, 'n.', 'B1', 'নির্ধারিত কাজ, অ্যাসাইনমেন্ট', 'I must finish my assignment tonight.', 'আমাকে আজ রাতেই আমার অ্যাসাইনমেন্ট শেষ করতে হবে।', 38),
    ('assist', null, 'v.', 'B1', 'সাহায্য করা', 'A nurse assisted the doctor.', 'একজন নার্স ডাক্তারকে সাহায্য করলেন।', 39),
    ('atmosphere', null, 'n.', 'B1', 'পরিবেশ; বায়ুমণ্ডল', 'The cafe has a friendly atmosphere.', 'ক্যাফেটির পরিবেশ বন্ধুত্বপূর্ণ।', 40),
    ('attach', null, 'v.', 'B1', 'সংযুক্ত করা, জুড়ে দেওয়া', 'Please attach the file to the email.', 'অনুগ্রহ করে ফাইলটি ইমেইলে সংযুক্ত করুন।', 41),
    ('attitude', null, 'n.', 'B1', 'মনোভাব', 'She has a positive attitude.', 'তার একটি ইতিবাচক মনোভাব আছে।', 42),
    ('attract', null, 'v.', 'B1', 'আকর্ষণ করা', 'Flowers attract bees.', 'ফুল মৌমাছিদের আকর্ষণ করে।', 43),
    ('attraction', null, 'n.', 'B1', 'আকর্ষণ', 'The zoo is a popular attraction.', 'চিড়িয়াখানাটি একটি জনপ্রিয় আকর্ষণ।', 44),
    ('authority', null, 'n.', 'B1', 'কর্তৃপক্ষ; ক্ষমতা', 'The local authority runs the schools.', 'স্থানীয় কর্তৃপক্ষ স্কুলগুলো পরিচালনা করে।', 45),
    ('automatic', null, 'adj.', 'B1', 'স্বয়ংক্রিয়', 'The door is automatic.', 'দরজাটি স্বয়ংক্রিয়।', 46),
    ('automatically', null, 'adv.', 'B1', 'স্বয়ংক্রিয়ভাবে', 'The lights turn on automatically.', 'আলোগুলো স্বয়ংক্রিয়ভাবে জ্বলে ওঠে।', 47),
    ('aware', null, 'adj.', 'B1', 'সচেতন, অবগত', 'Are you aware of the rules?', 'তুমি কি নিয়মগুলো সম্পর্কে অবগত?', 48),
    ('backward', null, 'adv.', 'B1', 'পেছনের দিকে', 'He took a step backward.', 'সে পেছনের দিকে এক পা ফেলল।', 49),
    ('bake', null, 'v.', 'B1', 'সেঁকা, বেক করা', 'She likes to bake bread.', 'সে রুটি বেক করতে ভালোবাসে।', 50),
    ('balance', null, 'n., v.', 'B1', 'ভারসাম্য; ভারসাম্য রাখা', 'Try to keep your balance.', 'তোমার ভারসাম্য রাখার চেষ্টা কর।', 51),
    ('ban', null, 'n., v.', 'B1', 'নিষেধাজ্ঞা; নিষিদ্ধ করা', 'The city banned smoking in parks.', 'শহরটি উদ্যানে ধূমপান নিষিদ্ধ করল।', 52),
    ('bank', 'river', 'n.', 'B1', 'নদীর তীর', 'We sat on the river bank.', 'আমরা নদীর তীরে বসলাম।', 53),
    ('base', null, 'n., v.', 'B1', 'ভিত্তি; ভিত্তি করা', 'The story is based on real events.', 'গল্পটি সত্য ঘটনার ভিত্তিতে রচিত।', 54),
    ('basic', null, 'adj.', 'B1', 'মৌলিক, প্রাথমিক', 'We learned some basic rules.', 'আমরা কিছু মৌলিক নিয়ম শিখলাম।', 55),
    ('basis', null, 'n.', 'B1', 'ভিত্তি', 'We meet on a weekly basis.', 'আমরা সাপ্তাহিক ভিত্তিতে দেখা করি।', 56),
    ('battery', null, 'n.', 'B1', 'ব্যাটারি', 'My phone battery is low.', 'আমার ফোনের ব্যাটারি কম।', 57),
    ('battle', null, 'n., v.', 'B1', 'যুদ্ধ, লড়াই; লড়াই করা', 'They won the final battle.', 'তারা চূড়ান্ত যুদ্ধে জয়ী হলো।', 58),
    ('beauty', null, 'n.', 'B1', 'সৌন্দর্য', 'The beauty of the mountains amazed us.', 'পাহাড়ের সৌন্দর্য আমাদের মুগ্ধ করল।', 59),
    ('bee', null, 'n.', 'B1', 'মৌমাছি', 'A bee landed on the flower.', 'একটি মৌমাছি ফুলের উপর বসল।', 60),
    ('belief', null, 'n.', 'B1', 'বিশ্বাস', 'It is my belief that hard work pays off.', 'আমার বিশ্বাস পরিশ্রমের ফল মেলে।', 61),
    ('bell', null, 'n.', 'B1', 'ঘণ্টা', 'The school bell rang at eight.', 'স্কুলের ঘণ্টা আটটায় বাজল।', 62),
    ('bend', null, 'n., v.', 'B1', 'বাঁক; বাঁকানো', 'Bend your knees slowly.', 'ধীরে ধীরে তোমার হাঁটু বাঁকাও।', 63),
    ('bite', null, 'n., v.', 'B1', 'কামড়; কামড়ানো', 'The dog might bite you.', 'কুকুরটি তোমাকে কামড়াতে পারে।', 64),
    ('bomb', null, 'n., v.', 'B1', 'বোমা; বোমা ফেলা', 'The old bomb was found in a field.', 'পুরনো বোমাটি একটি মাঠে পাওয়া গেল।', 65),
    ('border', null, 'n., v.', 'B1', 'সীমান্ত; সীমা নির্ধারণ করা', 'They crossed the border by train.', 'তারা ট্রেনে করে সীমান্ত পার হলো।', 66),
    ('bother', null, 'v.', 'B1', 'বিরক্ত করা, বিব্রত করা', 'Sorry to bother you.', 'তোমাকে বিরক্ত করার জন্য দুঃখিত।', 67),
    ('branch', null, 'n.', 'B1', 'শাখা, ডাল', 'A bird sat on the branch.', 'একটি পাখি ডালে বসল।', 68),
    ('brand', null, 'n., v.', 'B1', 'ব্র্যান্ড, পণ্যচিহ্ন', 'This is a well-known brand.', 'এটি একটি সুপরিচিত ব্র্যান্ড।', 69),
    ('brave', null, 'adj.', 'B1', 'সাহসী', 'The brave boy saved the child.', 'সাহসী ছেলেটি শিশুটিকে বাঁচাল।', 70),
    ('breath', null, 'n.', 'B1', 'নিঃশ্বাস', 'Take a deep breath.', 'একটি গভীর নিঃশ্বাস নাও।', 71),
    ('breathe', null, 'v.', 'B1', 'শ্বাস নেওয়া', 'It is hard to breathe up here.', 'এখানে উপরে শ্বাস নেওয়া কঠিন।', 72),
    ('breathing', null, 'n.', 'B1', 'শ্বাসপ্রশ্বাস', 'Her breathing was slow and calm.', 'তার শ্বাসপ্রশ্বাস ধীর ও শান্ত ছিল।', 73),
    ('bride', null, 'n.', 'B1', 'কনে, নববধূ', 'The bride wore a red dress.', 'কনে একটি লাল পোশাক পরেছিল।', 74),
    ('bubble', null, 'n.', 'B1', 'বুদবুদ', 'The child blew a soap bubble.', 'শিশুটি একটি সাবানের বুদবুদ ফুঁ দিল।', 75),
    ('bury', null, 'v.', 'B1', 'কবর দেওয়া, পুঁতে রাখা', 'The dog buried its bone.', 'কুকুরটি তার হাড় পুঁতে রাখল।', 76),
    ('cable', null, 'n.', 'B1', 'তার, ক্যাবল', 'Connect the cable to the screen.', 'ক্যাবলটি স্ক্রিনের সঙ্গে যুক্ত কর।', 77),
    ('calm', null, 'adj., n., v.', 'B1', 'শান্ত; শান্ত করা', 'Stay calm and think clearly.', 'শান্ত থাকো এবং স্পষ্টভাবে ভাবো।', 78),
    ('campaign', null, 'n., v.', 'B1', 'অভিযান, প্রচারাভিযান', 'They started a clean-water campaign.', 'তারা একটি বিশুদ্ধ পানির অভিযান শুরু করল।', 79),
    ('candidate', null, 'n.', 'B1', 'প্রার্থী', 'She is the best candidate for the job.', 'সে চাকরিটির জন্য সেরা প্রার্থী।', 80),
    ('cap', null, 'n.', 'B1', 'টুপি; ঢাকনা', 'He wore a blue cap.', 'সে একটি নীল টুপি পরেছিল।', 81),
    ('captain', null, 'n.', 'B1', 'অধিনায়ক, ক্যাপ্টেন', 'She is the captain of the team.', 'সে দলের অধিনায়ক।', 82),
    ('careless', null, 'adj.', 'B1', 'অসাবধান, অযত্নশীল', 'A careless driver caused the accident.', 'একজন অসাবধান চালক দুর্ঘটনাটি ঘটাল।', 83),
    ('category', null, 'n.', 'B1', 'শ্রেণি, বিভাগ', 'Books are sorted by category.', 'বইগুলো বিভাগ অনুযায়ী সাজানো।', 84),
    ('ceiling', null, 'n.', 'B1', 'ছাদ, সিলিং', 'A lamp hangs from the ceiling.', 'সিলিং থেকে একটি বাতি ঝুলছে।', 85),
    ('celebration', null, 'n.', 'B1', 'উদযাপন, উৎসব', 'The whole village joined the celebration.', 'পুরো গ্রাম উৎসবে যোগ দিল।', 86),
    ('central', null, 'adj.', 'B1', 'কেন্দ্রীয়', 'The hotel is in a central location.', 'হোটেলটি একটি কেন্দ্রীয় স্থানে অবস্থিত।', 87),
    ('ceremony', null, 'n.', 'B1', 'অনুষ্ঠান, উৎসব', 'The wedding ceremony was beautiful.', 'বিয়ের অনুষ্ঠানটি সুন্দর ছিল।', 88),
    ('chain', null, 'n., v.', 'B1', 'শিকল, চেইন; বেঁধে রাখা', 'The gate was closed with a chain.', 'ফটকটি একটি শিকল দিয়ে বন্ধ ছিল।', 89),
    ('challenge', null, 'n., v.', 'B1', 'চ্যালেঞ্জ, প্রতিদ্বন্দ্বিতা; চ্যালেঞ্জ করা', 'Learning a new language is a challenge.', 'একটি নতুন ভাষা শেখা একটি চ্যালেঞ্জ।', 90),
    ('champion', null, 'n.', 'B1', 'চ্যাম্পিয়ন, বিজয়ী', 'He is the national champion.', 'তিনি জাতীয় চ্যাম্পিয়ন।', 91),
    ('channel', null, 'n.', 'B1', 'চ্যানেল; প্রণালী', 'Please change the TV channel.', 'অনুগ্রহ করে টিভি চ্যানেলটি বদলাও।', 92),
    ('chapter', null, 'n.', 'B1', 'অধ্যায়', 'Read the first chapter tonight.', 'আজ রাতে প্রথম অধ্যায়টি পড়ো।', 93),
    ('charge', null, 'n., v.', 'B1', 'মূল্য, চার্জ; চার্জ করা, দায়িত্ব দেওয়া', 'There is no charge for children.', 'শিশুদের জন্য কোনো মূল্য নেই।', 94),
    ('cheat', null, 'n., v.', 'B1', 'প্রতারণা; প্রতারণা করা, নকল করা', 'Do not cheat in the exam.', 'পরীক্ষায় নকল করো না।', 95),
    ('cheerful', null, 'adj.', 'B1', 'প্রফুল্ল, হাসিখুশি', 'She has a cheerful smile.', 'তার একটি হাসিখুশি হাসি আছে।', 96),
    ('chemical', null, 'adj., n.', 'B1', 'রাসায়নিক; রাসায়নিক পদার্থ', 'These chemicals are dangerous.', 'এই রাসায়নিক পদার্থগুলো বিপজ্জনক।', 97),
    ('chest', null, 'n.', 'B1', 'বুক, বক্ষ; সিন্দুক', 'He felt a pain in his chest.', 'সে তার বুকে ব্যথা অনুভব করল।', 98),
    ('childhood', null, 'n.', 'B1', 'শৈশব', 'She had a happy childhood.', 'তার একটি সুখী শৈশব ছিল।', 99),
    ('claim', null, 'n., v.', 'B1', 'দাবি; দাবি করা', 'He claims to know the answer.', 'সে উত্তরটি জানে বলে দাবি করে।', 100),
    ('clause', null, 'n.', 'B1', 'খণ্ডবাক্য; ধারা', 'This sentence has two clauses.', 'এই বাক্যে দুটি খণ্ডবাক্য আছে।', 101),
    ('clever', null, 'adj.', 'B1', 'চতুর, বুদ্ধিমান', 'That was a clever idea.', 'ওটা একটি বুদ্ধিমান ভাবনা ছিল।', 102),
    ('click', null, 'n., v.', 'B1', 'ক্লিক; ক্লিক করা', 'Click the button to continue.', 'চালিয়ে যেতে বোতামে ক্লিক কর।', 103),
    ('client', null, 'n.', 'B1', 'মক্কেল, গ্রাহক', 'The lawyer met her client.', 'আইনজীবী তার মক্কেলের সঙ্গে দেখা করলেন।', 104),
    ('cloth', null, 'n.', 'B1', 'কাপড়', 'Wipe the table with a clean cloth.', 'একটি পরিষ্কার কাপড় দিয়ে টেবিলটি মোছো।', 105),
    ('clue', null, 'n.', 'B1', 'সূত্র, ইঙ্গিত', 'The police found an important clue.', 'পুলিশ একটি গুরুত্বপূর্ণ সূত্র পেল।', 106),
    ('coal', null, 'n.', 'B1', 'কয়লা', 'The train once ran on coal.', 'ট্রেনটি একসময় কয়লায় চলত।', 107),
    ('coin', null, 'n.', 'B1', 'মুদ্রা, কয়েন', 'She dropped a coin on the floor.', 'সে মেঝেতে একটি মুদ্রা ফেলে দিল।', 108),
    ('collection', null, 'n.', 'B1', 'সংগ্রহ', 'He has a large stamp collection.', 'তার একটি বড় ডাকটিকিট সংগ্রহ আছে।', 109),
    ('colored', null, 'adj.', 'B1', 'রঙিন', 'She drew with colored pencils.', 'সে রঙিন পেন্সিল দিয়ে আঁকল।', 110),
    ('combine', null, 'v.', 'B1', 'একত্র করা, মেশানো', 'Combine the flour and sugar.', 'ময়দা ও চিনি একত্র কর।', 111),
    ('commercial', null, 'adj., n.', 'B1', 'বাণিজ্যিক; বিজ্ঞাপন', 'This is a commercial district.', 'এটি একটি বাণিজ্যিক এলাকা।', 112),
    ('commit', null, 'v.', 'B1', 'সংঘটিত করা; প্রতিশ্রুতিবদ্ধ হওয়া', 'He did not commit the crime.', 'সে অপরাধটি করেনি।', 113),
    ('communication', null, 'n.', 'B1', 'যোগাযোগ', 'Good communication is important.', 'ভালো যোগাযোগ গুরুত্বপূর্ণ।', 114),
    ('comparison', null, 'n.', 'B1', 'তুলনা', 'There is no comparison between them.', 'তাদের মধ্যে কোনো তুলনা হয় না।', 115),
    ('competitive', null, 'adj.', 'B1', 'প্রতিযোগিতামূলক', 'He is very competitive in sports.', 'সে খেলায় খুব প্রতিযোগিতামূলক।', 116),
    ('competitor', null, 'n.', 'B1', 'প্রতিযোগী', 'She beat all her competitors.', 'সে তার সব প্রতিযোগীকে হারাল।', 117),
    ('complaint', null, 'n.', 'B1', 'অভিযোগ', 'The customer made a complaint.', 'ক্রেতা একটি অভিযোগ করলেন।', 118),
    ('complex', null, 'adj., n.', 'B1', 'জটিল; সমষ্টি', 'This is a complex problem.', 'এটি একটি জটিল সমস্যা।', 119),
    ('concentrate', null, 'v.', 'B1', 'মনোযোগ দেওয়া, একাগ্র হওয়া', 'I cannot concentrate with this noise.', 'এই শব্দে আমি মনোযোগ দিতে পারছি না।', 120),
    ('conclude', null, 'v.', 'B1', 'উপসংহারে আসা, শেষ করা', 'She concluded her speech with a joke.', 'সে একটি রসিকতা দিয়ে তার বক্তৃতা শেষ করল।', 121),
    ('conclusion', null, 'n.', 'B1', 'উপসংহার, সিদ্ধান্ত', 'What is your conclusion?', 'তোমার সিদ্ধান্ত কী?', 122),
    ('confident', null, 'adj.', 'B1', 'আত্মবিশ্বাসী', 'She is confident about the test.', 'সে পরীক্ষা নিয়ে আত্মবিশ্বাসী।', 123),
    ('confirm', null, 'v.', 'B1', 'নিশ্চিত করা', 'Please confirm your booking.', 'অনুগ্রহ করে আপনার বুকিং নিশ্চিত করুন।', 124),
    ('confuse', null, 'v.', 'B1', 'বিভ্রান্ত করা, গুলিয়ে ফেলা', 'The map confused me.', 'মানচিত্রটি আমাকে বিভ্রান্ত করল।', 125),
    ('confused', null, 'adj.', 'B1', 'বিভ্রান্ত, দ্বিধাগ্রস্ত', 'I was confused by the question.', 'প্রশ্নটি নিয়ে আমি বিভ্রান্ত ছিলাম।', 126),
    ('connection', null, 'n.', 'B1', 'সংযোগ, সম্পর্ক', 'The internet connection is slow.', 'ইন্টারনেট সংযোগটি ধীর।', 127),
    ('consequence', null, 'n.', 'B1', 'পরিণতি, ফলাফল', 'Every choice has a consequence.', 'প্রতিটি সিদ্ধান্তের একটি পরিণতি আছে।', 128),
    ('consist', null, 'v.', 'B1', 'গঠিত হওয়া, নিয়ে গঠিত', 'The team consists of five players.', 'দলটি পাঁচজন খেলোয়াড় নিয়ে গঠিত।', 129),
    ('consume', null, 'v.', 'B1', 'গ্রহণ করা, ভোগ করা', 'We consume too much sugar.', 'আমরা অতিরিক্ত চিনি গ্রহণ করি।', 130),
    ('consumer', null, 'n.', 'B1', 'ভোক্তা, ক্রেতা', 'Consumers want low prices.', 'ভোক্তারা কম দাম চায়।', 131),
    ('contact', null, 'n., v.', 'B1', 'যোগাযোগ; যোগাযোগ করা', 'Please contact me tomorrow.', 'অনুগ্রহ করে আগামীকাল আমার সঙ্গে যোগাযোগ করুন।', 132),
    ('container', null, 'n.', 'B1', 'পাত্র, ধারক', 'Keep the rice in a container.', 'ভাত একটি পাত্রে রাখো।', 133),
    ('content', null, 'n.', 'B1', 'বিষয়বস্তু', 'The content of the book is useful.', 'বইটির বিষয়বস্তু দরকারি।', 134),
    ('continuous', null, 'adj.', 'B1', 'অবিরাম, একটানা', 'There was continuous rain all day.', 'সারাদিন একটানা বৃষ্টি হয়েছিল।', 135),
    ('contrast', null, 'n., v.', 'B1', 'বৈসাদৃশ্য, পার্থক্য; তুলনা করা', 'There is a clear contrast between them.', 'তাদের মধ্যে একটি স্পষ্ট পার্থক্য আছে।', 136),
    ('convenient', null, 'adj.', 'B1', 'সুবিধাজনক', 'Is this a convenient time to talk?', 'কথা বলার জন্য এটি কি সুবিধাজনক সময়?', 137),
    ('convince', null, 'v.', 'B1', 'বোঝানো, রাজি করানো', 'He convinced me to go.', 'সে আমাকে যেতে রাজি করাল।', 138),
    ('corn', null, 'n.', 'B1', 'ভুট্টা', 'The farmer grows corn.', 'কৃষকটি ভুট্টা চাষ করেন।', 139),
    ('costume', null, 'n.', 'B1', 'পোশাক, সাজপোশাক', 'She wore a lion costume.', 'সে একটি সিংহের পোশাক পরল।', 140),
    ('cotton', null, 'n.', 'B1', 'তুলা, সুতি', 'This shirt is made of cotton.', 'এই শার্টটি সুতির তৈরি।', 141),
    ('countryside', null, 'n.', 'B1', 'গ্রামাঞ্চল', 'We spent the weekend in the countryside.', 'আমরা সপ্তাহান্ত গ্রামাঞ্চলে কাটালাম।', 142),
    ('court', null, 'n.', 'B1', 'আদালত; খেলার কোর্ট', 'The case went to court.', 'মামলাটি আদালতে গেল।', 143),
    ('covered', null, 'adj.', 'B1', 'আচ্ছাদিত, ঢাকা', 'The ground was covered with snow.', 'মাটি বরফে ঢাকা ছিল।', 144),
    ('cruel', null, 'adj.', 'B1', 'নিষ্ঠুর', 'It is cruel to hurt animals.', 'প্রাণীদের কষ্ট দেওয়া নিষ্ঠুরতা।', 145),
    ('cultural', null, 'adj.', 'B1', 'সাংস্কৃতিক', 'We attended a cultural event.', 'আমরা একটি সাংস্কৃতিক অনুষ্ঠানে যোগ দিলাম।', 146),
    ('cupboard', null, 'n.', 'B1', 'আলমারি, তাক', 'The cups are in the cupboard.', 'কাপগুলো আলমারিতে আছে।', 147),
    ('currency', null, 'n.', 'B1', 'মুদ্রা, প্রচলিত অর্থ', 'The taka is the currency of Bangladesh.', 'টাকা বাংলাদেশের মুদ্রা।', 148),
    ('current', null, 'adj., n.', 'B1', 'বর্তমান; স্রোত, তড়িৎপ্রবাহ', 'What is the current situation?', 'বর্তমান পরিস্থিতি কী?', 149),
    ('currently', null, 'adv.', 'B1', 'বর্তমানে', 'She is currently living abroad.', 'সে বর্তমানে বিদেশে বাস করছে।', 150),
    ('curtain', null, 'n.', 'B1', 'পর্দা', 'Please open the curtains.', 'অনুগ্রহ করে পর্দাগুলো খোলো।', 151),
    ('custom', null, 'n.', 'B1', 'প্রথা, রীতি', 'Shaking hands is a common custom.', 'করমর্দন একটি সাধারণ প্রথা।', 152),
    ('damage', null, 'n., v.', 'B1', 'ক্ষতি; ক্ষতি করা', 'The storm caused a lot of damage.', 'ঝড়টি অনেক ক্ষতি করল।', 153),
    ('decade', null, 'n.', 'B1', 'দশক', 'They lived here for a decade.', 'তারা এখানে এক দশক ধরে বাস করেছিল।', 154),
    ('define', null, 'v.', 'B1', 'সংজ্ঞা দেওয়া', 'Can you define this word?', 'তুমি কি এই শব্দটির সংজ্ঞা দিতে পার?', 155),
    ('definite', null, 'adj.', 'B1', 'নিশ্চিত, সুনির্দিষ্ট', 'We need a definite answer.', 'আমাদের একটি নিশ্চিত উত্তর দরকার।', 156),
    ('definition', null, 'n.', 'B1', 'সংজ্ঞা', 'Look up the definition in a dictionary.', 'অভিধানে সংজ্ঞাটি খুঁজে দেখো।', 157),
    ('deliver', null, 'v.', 'B1', 'পৌঁছে দেওয়া, বিতরণ করা', 'They deliver food to your home.', 'তারা তোমার বাড়িতে খাবার পৌঁছে দেয়।', 158),
    ('departure', null, 'n.', 'B1', 'প্রস্থান, রওনা', 'The departure time is nine o''clock.', 'রওনার সময় নয়টা।', 159),
    ('despite', null, 'prep.', 'B1', 'সত্ত্বেও', 'We went out despite the rain.', 'বৃষ্টি সত্ত্বেও আমরা বাইরে গেলাম।', 160),
    ('destination', null, 'n.', 'B1', 'গন্তব্য', 'Our final destination is the beach.', 'আমাদের চূড়ান্ত গন্তব্য সমুদ্রসৈকত।', 161),
    ('determine', null, 'v.', 'B1', 'নির্ধারণ করা, স্থির করা', 'The judges will determine the winner.', 'বিচারকরা বিজয়ী নির্ধারণ করবেন।', 162),
    ('determined', null, 'adj.', 'B1', 'দৃঢ়প্রতিজ্ঞ', 'She is determined to succeed.', 'সে সফল হতে দৃঢ়প্রতিজ্ঞ।', 163),
    ('development', null, 'n.', 'B1', 'উন্নয়ন, বিকাশ', 'The city has seen rapid development.', 'শহরটি দ্রুত উন্নয়ন দেখেছে।', 164),
    ('diagram', null, 'n.', 'B1', 'রেখাচিত্র, নকশা', 'The diagram explains the process.', 'রেখাচিত্রটি প্রক্রিয়াটি ব্যাখ্যা করে।', 165),
    ('diamond', null, 'n.', 'B1', 'হীরা', 'She wore a diamond ring.', 'সে একটি হীরার আংটি পরেছিল।', 166),
    ('difficulty', null, 'n.', 'B1', 'অসুবিধা, কষ্ট', 'He had difficulty finding the house.', 'বাড়িটি খুঁজে পেতে তার কষ্ট হয়েছিল।', 167),
    ('directly', null, 'adv.', 'B1', 'সরাসরি', 'Go directly to the office.', 'সরাসরি অফিসে যাও।', 168),
    ('dirt', null, 'n.', 'B1', 'ময়লা, মাটি', 'Wash the dirt off your hands.', 'তোমার হাত থেকে ময়লা ধুয়ে ফেলো।', 169),
    ('disadvantage', null, 'n.', 'B1', 'অসুবিধা, ক্ষতিকর দিক', 'The plan has one disadvantage.', 'পরিকল্পনাটির একটি অসুবিধা আছে।', 170),
    ('disappointed', null, 'adj.', 'B1', 'হতাশ, নিরাশ', 'I was disappointed with the result.', 'ফলাফলে আমি হতাশ হয়েছিলাম।', 171),
    ('disappointing', null, 'adj.', 'B1', 'হতাশাজনক', 'The movie was disappointing.', 'সিনেমাটি হতাশাজনক ছিল।', 172),
    ('discount', null, 'n., v.', 'B1', 'ছাড়, মূল্যহ্রাস', 'They offer a student discount.', 'তারা শিক্ষার্থীদের জন্য ছাড় দেয়।', 173),
    ('dislike', null, 'n., v.', 'B1', 'অপছন্দ; অপছন্দ করা', 'I dislike loud music.', 'আমি জোরে বাজানো গান অপছন্দ করি।', 174),
    ('district', null, 'n.', 'B1', 'জেলা, এলাকা', 'They live in a quiet district.', 'তারা একটি শান্ত এলাকায় থাকে।', 175),
    ('divide', null, 'n., v.', 'B1', 'ভাগ করা', 'Divide the cake into eight pieces.', 'কেকটি আট টুকরায় ভাগ কর।', 176),
    ('documentary', null, 'n.', 'B1', 'প্রামাণ্যচিত্র, ডকুমেন্টারি', 'We watched a documentary about lions.', 'আমরা সিংহ নিয়ে একটি প্রামাণ্যচিত্র দেখলাম।', 177),
    ('donate', null, 'v.', 'B1', 'দান করা', 'They donate money to charity.', 'তারা দাতব্য সংস্থায় অর্থ দান করে।', 178),
    ('doubt', null, 'n., v.', 'B1', 'সন্দেহ; সন্দেহ করা', 'I have no doubt about her honesty.', 'তার সততা নিয়ে আমার কোনো সন্দেহ নেই।', 179),
    ('dressed', null, 'adj.', 'B1', 'পোশাক পরা', 'She was dressed in white.', 'সে সাদা পোশাকে সজ্জিত ছিল।', 180),
    ('drum', null, 'n.', 'B1', 'ঢোল, ড্রাম', 'He plays the drum in a band.', 'সে একটি ব্যান্ডে ড্রাম বাজায়।', 181),
    ('drunk', null, 'adj.', 'B1', 'মাতাল', 'He was too drunk to drive.', 'সে গাড়ি চালানোর মতো অবস্থায় ছিল না, বেশি মাতাল ছিল।', 182),
    ('due', null, 'adj.', 'B1', 'নির্ধারিত, পাওনা', 'The report is due on Monday.', 'প্রতিবেদনটি সোমবারে জমা দেওয়ার কথা।', 183),
    ('dust', null, 'n.', 'B1', 'ধুলা', 'There is dust on the shelf.', 'তাকটিতে ধুলা জমেছে।', 184),
    ('duty', null, 'n.', 'B1', 'কর্তব্য, দায়িত্ব', 'It is my duty to help others.', 'অন্যদের সাহায্য করা আমার কর্তব্য।', 185),
    ('earthquake', null, 'n.', 'B1', 'ভূমিকম্প', 'The earthquake damaged many houses.', 'ভূমিকম্পটি অনেক বাড়ির ক্ষতি করল।', 186),
    ('eastern', null, 'adj.', 'B1', 'পূর্বাঞ্চলীয়, পূর্বদিকের', 'They live in the eastern part of the city.', 'তারা শহরের পূর্বাঞ্চলে থাকে।', 187),
    ('economic', null, 'adj.', 'B1', 'অর্থনৈতিক', 'The country faces economic problems.', 'দেশটি অর্থনৈতিক সমস্যার মুখোমুখি।', 188),
    ('economy', null, 'n.', 'B1', 'অর্থনীতি', 'The economy is growing slowly.', 'অর্থনীতি ধীরে ধীরে বাড়ছে।', 189),
    ('edge', null, 'n.', 'B1', 'কিনারা, প্রান্ত', 'Do not stand near the edge.', 'কিনারার কাছে দাঁড়িও না।', 190),
    ('editor', null, 'n.', 'B1', 'সম্পাদক', 'The editor checked the article.', 'সম্পাদক নিবন্ধটি পরীক্ষা করলেন।', 191),
    ('educate', null, 'v.', 'B1', 'শিক্ষিত করা', 'Schools educate our children.', 'স্কুল আমাদের শিশুদের শিক্ষিত করে।', 192),
    ('educated', null, 'adj.', 'B1', 'শিক্ষিত', 'She is a well-educated woman.', 'সে একজন সুশিক্ষিত নারী।', 193),
    ('educational', null, 'adj.', 'B1', 'শিক্ষামূলক', 'This is an educational game.', 'এটি একটি শিক্ষামূলক খেলা।', 194),
    ('effective', null, 'adj.', 'B1', 'কার্যকর', 'This is an effective medicine.', 'এটি একটি কার্যকর ওষুধ।', 195),
    ('effectively', null, 'adv.', 'B1', 'কার্যকরভাবে', 'She manages her time effectively.', 'সে তার সময় কার্যকরভাবে পরিচালনা করে।', 196),
    ('effort', null, 'n.', 'B1', 'প্রচেষ্টা, চেষ্টা', 'He made a big effort to win.', 'জিততে সে অনেক চেষ্টা করল।', 197),
    ('election', null, 'n.', 'B1', 'নির্বাচন', 'The election is next month.', 'নির্বাচন আগামী মাসে।', 198),
    ('element', null, 'n.', 'B1', 'উপাদান', 'Trust is a key element of friendship.', 'বিশ্বাস বন্ধুত্বের একটি প্রধান উপাদান।', 199),
    ('embarrassed', null, 'adj.', 'B1', 'লজ্জিত, বিব্রত', 'He felt embarrassed by his mistake.', 'তার ভুলের জন্য সে বিব্রত বোধ করল।', 200),
    ('embarrassing', null, 'adj.', 'B1', 'বিব্রতকর, লজ্জাজনক', 'It was an embarrassing moment.', 'এটি একটি বিব্রতকর মুহূর্ত ছিল।', 201),
    ('emergency', null, 'n.', 'B1', 'জরুরি অবস্থা', 'Call this number in an emergency.', 'জরুরি অবস্থায় এই নম্বরে ফোন কর।', 202),
    ('emotion', null, 'n.', 'B1', 'আবেগ, অনুভূতি', 'She could not hide her emotions.', 'সে তার আবেগ লুকাতে পারল না।', 203),
    ('employment', null, 'n.', 'B1', 'কর্মসংস্থান, চাকরি', 'He is looking for employment.', 'সে চাকরি খুঁজছে।', 204),
    ('encourage', null, 'v.', 'B1', 'উৎসাহিত করা', 'My teacher encouraged me to try.', 'আমার শিক্ষক আমাকে চেষ্টা করতে উৎসাহিত করলেন।', 205),
    ('enemy', null, 'n.', 'B1', 'শত্রু', 'He has no enemies.', 'তার কোনো শত্রু নেই।', 206),
    ('engaged', null, 'adj.', 'B1', 'বাগদত্ত; নিযুক্ত, ব্যস্ত', 'They got engaged last year.', 'তারা গত বছর বাগদান করেছিল।', 207),
    ('engineering', null, 'n.', 'B1', 'প্রকৌশল, ইঞ্জিনিয়ারিং', 'He studies engineering.', 'সে প্রকৌশল বিদ্যা পড়ছে।', 208),
    ('entertain', null, 'v.', 'B1', 'বিনোদন দেওয়া, আনন্দ দেওয়া', 'The clown entertained the children.', 'ভাঁড়টি শিশুদের আনন্দ দিল।', 209),
    ('entertainment', null, 'n.', 'B1', 'বিনোদন', 'Music is a form of entertainment.', 'সংগীত এক ধরনের বিনোদন।', 210),
    ('entrance', null, 'n.', 'B1', 'প্রবেশপথ', 'Meet me at the main entrance.', 'প্রধান প্রবেশপথে আমার সঙ্গে দেখা করো।', 211),
    ('entry', null, 'n.', 'B1', 'প্রবেশ; অন্তর্ভুক্তি', 'Entry to the museum is free.', 'জাদুঘরে প্রবেশ বিনামূল্যে।', 212),
    ('environmental', null, 'adj.', 'B1', 'পরিবেশগত', 'We must solve environmental problems.', 'আমাদের পরিবেশগত সমস্যা সমাধান করতে হবে।', 213),
    ('episode', null, 'n.', 'B1', 'পর্ব, কিস্তি', 'I watched the last episode.', 'আমি শেষ পর্বটি দেখেছি।', 214),
    ('equal', null, 'adj., n., v.', 'B1', 'সমান; সমান হওয়া', 'Cut the rope into equal parts.', 'দড়িটি সমান অংশে কাটো।', 215),
    ('equally', null, 'adv.', 'B1', 'সমানভাবে', 'Share the food equally.', 'খাবারটি সমানভাবে ভাগ কর।', 216),
    ('escape', null, 'n., v.', 'B1', 'পলায়ন; পালানো', 'The bird escaped from the cage.', 'পাখিটি খাঁচা থেকে পালাল।', 217),
    ('essential', null, 'adj.', 'B1', 'অপরিহার্য, অত্যাবশ্যক', 'Water is essential for life.', 'জীবনের জন্য পানি অপরিহার্য।', 218),
    ('eventually', null, 'adv.', 'B1', 'অবশেষে, শেষ পর্যন্ত', 'Eventually, they found the way.', 'অবশেষে, তারা পথ খুঁজে পেল।', 219),
    ('examine', null, 'v.', 'B1', 'পরীক্ষা করা, খুঁটিয়ে দেখা', 'The doctor examined the patient.', 'ডাক্তার রোগীকে পরীক্ষা করলেন।', 220),
    ('exchange', null, 'n., v.', 'B1', 'বিনিময়; বিনিময় করা', 'They exchanged phone numbers.', 'তারা ফোন নম্বর বিনিময় করল।', 221),
    ('excitement', null, 'n.', 'B1', 'উত্তেজনা, উদ্দীপনা', 'There was great excitement before the game.', 'খেলার আগে দারুণ উত্তেজনা ছিল।', 222),
    ('exhibition', null, 'n.', 'B1', 'প্রদর্শনী', 'We visited an art exhibition.', 'আমরা একটি চিত্রকলা প্রদর্শনী দেখতে গেলাম।', 223),
    ('exit', null, 'n., v.', 'B1', 'বহির্গমন পথ; বেরিয়ে যাওয়া', 'The emergency exit is on the left.', 'জরুরি বহির্গমন পথ বাঁ দিকে।', 224),
    ('expand', null, 'v.', 'B1', 'সম্প্রসারিত করা, বাড়ানো', 'The company plans to expand.', 'কোম্পানিটি সম্প্রসারণের পরিকল্পনা করছে।', 225),
    ('expected', null, 'adj.', 'B1', 'প্রত্যাশিত', 'The result was as expected.', 'ফলাফলটি প্রত্যাশিত মতোই হলো।', 226),
    ('experienced', null, 'adj.', 'B1', 'অভিজ্ঞ', 'She is an experienced teacher.', 'সে একজন অভিজ্ঞ শিক্ষক।', 227),
    ('explode', null, 'v.', 'B1', 'বিস্ফোরিত হওয়া', 'The old firework did not explode.', 'পুরনো আতশবাজিটি বিস্ফোরিত হলো না।', 228),
    ('explore', null, 'v.', 'B1', 'অন্বেষণ করা, ঘুরে দেখা', 'We want to explore the old town.', 'আমরা পুরনো শহরটি ঘুরে দেখতে চাই।', 229),
    ('explosion', null, 'n.', 'B1', 'বিস্ফোরণ', 'We heard a loud explosion.', 'আমরা একটি জোরে বিস্ফোরণ শুনলাম।', 230),
    ('export', null, 'n., v.', 'B1', 'রপ্তানি; রপ্তানি করা', 'The country exports rice.', 'দেশটি চাল রপ্তানি করে।', 231),
    ('fairly', null, 'adv.', 'B1', 'মোটামুটি; ন্যায্যভাবে', 'The test was fairly easy.', 'পরীক্ষাটি মোটামুটি সহজ ছিল।', 232),
    ('familiar', null, 'adj.', 'B1', 'পরিচিত, চেনা', 'Her face looks familiar.', 'তার মুখটি চেনা মনে হচ্ছে।', 233),
    ('fancy', null, 'adj.', 'B1', 'অভিজাত, কারুকার্যময়', 'They ate at a fancy restaurant.', 'তারা একটি অভিজাত রেস্তোরাঁয় খেল।', 234),
    ('fascinating', null, 'adj.', 'B1', 'চিত্তাকর্ষক, মুগ্ধকর', 'The book is truly fascinating.', 'বইটি সত্যিই চিত্তাকর্ষক।', 235),
    ('fashionable', null, 'adj.', 'B1', 'ফ্যাশনদুরস্ত, চলতি', 'She wears fashionable clothes.', 'সে ফ্যাশনদুরস্ত পোশাক পরে।', 236),
    ('fasten', null, 'v.', 'B1', 'বাঁধা, আটকানো', 'Please fasten your seat belt.', 'অনুগ্রহ করে আপনার সিট বেল্ট বাঁধুন।', 237),
    ('favor', null, 'n., v.', 'B1', 'অনুগ্রহ, উপকার; পক্ষ নেওয়া', 'Can you do me a favor?', 'তুমি কি আমার একটি উপকার করবে?', 238),
    ('federal', null, 'adj.', 'B1', 'কেন্দ্রীয়, যুক্তরাষ্ট্রীয়', 'This is a federal law.', 'এটি একটি কেন্দ্রীয় আইন।', 239),
    ('fence', null, 'n.', 'B1', 'বেড়া', 'There is a wooden fence around the garden.', 'বাগানের চারপাশে একটি কাঠের বেড়া আছে।', 240),
    ('fighting', null, 'n.', 'B1', 'লড়াই, মারামারি', 'The fighting stopped at night.', 'রাতে লড়াই থেমে গেল।', 241),
    ('file', null, 'n., v.', 'B1', 'ফাইল, নথি; নথিভুক্ত করা', 'Save the file on your computer.', 'ফাইলটি তোমার কম্পিউটারে সংরক্ষণ কর।', 242),
    ('financial', null, 'adj.', 'B1', 'আর্থিক', 'They have financial problems.', 'তাদের আর্থিক সমস্যা আছে।', 243),
    ('fitness', null, 'n.', 'B1', 'সুস্থতা, শারীরিক সক্ষমতা', 'Running improves your fitness.', 'দৌড়ানো তোমার শারীরিক সক্ষমতা বাড়ায়।', 244),
    ('fixed', null, 'adj.', 'B1', 'নির্দিষ্ট, স্থির', 'There is a fixed price for tickets.', 'টিকিটের একটি নির্দিষ্ট দাম আছে।', 245),
    ('flag', null, 'n.', 'B1', 'পতাকা', 'The flag waved in the wind.', 'পতাকাটি বাতাসে উড়ছিল।', 246),
    ('flood', null, 'n., v.', 'B1', 'বন্যা; প্লাবিত করা', 'The flood destroyed many homes.', 'বন্যা অনেক বাড়ি ধ্বংস করল।', 247),
    ('flour', null, 'n.', 'B1', 'ময়দা, আটা', 'Add two cups of flour.', 'দুই কাপ ময়দা যোগ কর।', 248),
    ('flow', null, 'n., v.', 'B1', 'প্রবাহ; প্রবাহিত হওয়া', 'The river flows to the sea.', 'নদীটি সমুদ্রের দিকে প্রবাহিত হয়।', 249),
    ('fold', null, 'n., v.', 'B1', 'ভাঁজ; ভাঁজ করা', 'Fold the paper in half.', 'কাগজটি অর্ধেক ভাঁজ কর।', 250),
    ('folk', null, 'adj., n.', 'B1', 'লোকজ; সাধারণ মানুষ', 'I love folk music.', 'আমি লোকসংগীত ভালোবাসি।', 251),
    ('force', null, 'n., v.', 'B1', 'শক্তি, বল; বাধ্য করা', 'Do not force him to eat.', 'তাকে খেতে বাধ্য করো না।', 252),
    ('forever', null, 'adv.', 'B1', 'চিরকাল, সর্বদা', 'Nothing lasts forever.', 'কিছুই চিরকাল টেকে না।', 253),
    ('frame', null, 'n., v.', 'B1', 'কাঠামো, ফ্রেম; ফ্রেমে বাঁধানো', 'She put the photo in a frame.', 'সে ছবিটি একটি ফ্রেমে বাঁধাল।', 254),
    ('freeze', null, 'v.', 'B1', 'জমে যাওয়া, বরফে পরিণত হওয়া', 'Water freezes at zero degrees.', 'পানি শূন্য ডিগ্রিতে জমে যায়।', 255),
    ('frequently', null, 'adv.', 'B1', 'প্রায়ই, ঘন ঘন', 'He frequently visits his parents.', 'সে প্রায়ই তার বাবা-মায়ের কাছে যায়।', 256),
    ('friendship', null, 'n.', 'B1', 'বন্ধুত্ব', 'Their friendship lasted for years.', 'তাদের বন্ধুত্ব বহু বছর টিকেছিল।', 257),
    ('frighten', null, 'v.', 'B1', 'ভয় দেখানো', 'The loud noise frightened the baby.', 'জোরে শব্দটি শিশুটিকে ভয় দেখাল।', 258),
    ('frightened', null, 'adj.', 'B1', 'ভীত, ভয় পাওয়া', 'She was frightened of the dark.', 'সে অন্ধকারকে ভয় পেত।', 259),
    ('frightening', null, 'adj.', 'B1', 'ভয়ংকর, ভীতিকর', 'It was a frightening experience.', 'এটি একটি ভীতিকর অভিজ্ঞতা ছিল।', 260),
    ('frozen', null, 'adj.', 'B1', 'জমাট, হিমায়িত', 'We bought frozen vegetables.', 'আমরা হিমায়িত সবজি কিনলাম।', 261),
    ('fry', null, 'v.', 'B1', 'ভাজা', 'Fry the fish in oil.', 'মাছটি তেলে ভাজো।', 262),
    ('fuel', null, 'n., v.', 'B1', 'জ্বালানি', 'Cars need fuel to run.', 'গাড়ি চলতে জ্বালানি লাগে।', 263),
    ('function', null, 'n., v.', 'B1', 'কাজ, ক্রিয়া; কাজ করা', 'What is the function of this key?', 'এই চাবিটির কাজ কী?', 264),
    ('fur', null, 'n.', 'B1', 'পশম, লোম', 'The cat has soft fur.', 'বিড়ালটির নরম পশম আছে।', 265),
    ('garage', null, 'n.', 'B1', 'গ্যারেজ, গাড়ি রাখার ঘর', 'The car is in the garage.', 'গাড়িটি গ্যারেজে আছে।', 266),
    ('gather', null, 'v.', 'B1', 'জড়ো হওয়া, সংগ্রহ করা', 'People gathered in the square.', 'লোকজন চত্বরে জড়ো হলো।', 267),
    ('generally', null, 'adv.', 'B1', 'সাধারণত', 'I generally wake up early.', 'আমি সাধারণত তাড়াতাড়ি ঘুম থেকে উঠি।', 268),
    ('generation', null, 'n.', 'B1', 'প্রজন্ম', 'This tradition passed down for generations.', 'এই প্রথা প্রজন্মের পর প্রজন্ম ধরে চলে এসেছে।', 269),
    ('generous', null, 'adj.', 'B1', 'উদার, দানশীল', 'She is generous with her time.', 'সে তার সময়ের ব্যাপারে উদার।', 270),
    ('gentle', null, 'adj.', 'B1', 'কোমল, মৃদু', 'He has a gentle voice.', 'তার কণ্ঠস্বর কোমল।', 271),
    ('gentleman', null, 'n.', 'B1', 'ভদ্রলোক', 'He is a true gentleman.', 'তিনি একজন প্রকৃত ভদ্রলোক।', 272),
    ('ghost', null, 'n.', 'B1', 'ভূত, প্রেতাত্মা', 'The children told ghost stories.', 'শিশুরা ভূতের গল্প বলল।', 273),
    ('giant', null, 'adj., n.', 'B1', 'বিশালাকার; দৈত্য', 'A giant wave hit the boat.', 'একটি বিশাল ঢেউ নৌকাটিতে আঘাত করল।', 274),
    ('glad', null, 'adj.', 'B1', 'খুশি, আনন্দিত', 'I am glad to see you.', 'তোমাকে দেখে আমি খুশি।', 275),
    ('global', null, 'adj.', 'B1', 'বিশ্বব্যাপী, বৈশ্বিক', 'Climate change is a global problem.', 'জলবায়ু পরিবর্তন একটি বৈশ্বিক সমস্যা।', 276),
    ('glove', null, 'n.', 'B1', 'দস্তানা, হাতমোজা', 'Wear gloves when it is cold.', 'ঠান্ডার সময় দস্তানা পরো।', 277),
    ('grade', null, 'n., v.', 'B1', 'শ্রেণি, গ্রেড; মূল্যায়ন করা', 'She got a good grade in math.', 'সে গণিতে ভালো গ্রেড পেল।', 278),
    ('graduate', null, 'n., v.', 'B1', 'স্নাতক; স্নাতক হওয়া', 'He will graduate next year.', 'সে আগামী বছর স্নাতক হবে।', 279),
    ('grain', null, 'n.', 'B1', 'শস্য, দানা', 'Rice is an important grain.', 'চাল একটি গুরুত্বপূর্ণ শস্য।', 280),
    ('grateful', null, 'adj.', 'B1', 'কৃতজ্ঞ', 'I am grateful for your kindness.', 'আমি তোমার দয়ার জন্য কৃতজ্ঞ।', 281),
    ('growth', null, 'n.', 'B1', 'বৃদ্ধি, বিকাশ', 'The plant showed rapid growth.', 'গাছটি দ্রুত বৃদ্ধি দেখাল।', 282),
    ('guard', null, 'n., v.', 'B1', 'প্রহরী; পাহারা দেওয়া', 'A guard stood at the gate.', 'একজন প্রহরী ফটকে দাঁড়িয়ে ছিল।', 283),
    ('guilty', null, 'adj.', 'B1', 'দোষী; অপরাধবোধে ভোগা', 'He felt guilty about the lie.', 'মিথ্যা বলার জন্য সে অপরাধবোধে ভুগল।', 284),
    ('hang', null, 'v.', 'B1', 'ঝোলানো, টাঙানো', 'Hang your coat on the hook.', 'তোমার কোট হুকে ঝুলিয়ে রাখো।', 285),
    ('happiness', null, 'n.', 'B1', 'সুখ, আনন্দ', 'Money cannot buy happiness.', 'অর্থ দিয়ে সুখ কেনা যায় না।', 286),
    ('hardly', null, 'adv.', 'B1', 'খুব কমই, প্রায় না', 'I can hardly hear you.', 'আমি তোমাকে প্রায় শুনতেই পাচ্ছি না।', 287),
    ('headline', null, 'n.', 'B1', 'শিরোনাম', 'The news headline shocked everyone.', 'সংবাদ শিরোনামটি সবাইকে হতবাক করল।', 288),
    ('heating', null, 'n.', 'B1', 'তাপ ব্যবস্থা, গরম করার ব্যবস্থা', 'The heating is not working.', 'গরম করার ব্যবস্থাটি কাজ করছে না।', 289),
    ('heavily', null, 'adv.', 'B1', 'ভারীভাবে, প্রবলভাবে', 'It rained heavily last night.', 'গত রাতে প্রবল বৃষ্টি হয়েছিল।', 290),
    ('helicopter', null, 'n.', 'B1', 'হেলিকপ্টার', 'A helicopter flew over the city.', 'একটি হেলিকপ্টার শহরের উপর দিয়ে উড়ে গেল।', 291),
    ('highlight', null, 'n., v.', 'B1', 'গুরুত্বপূর্ণ অংশ; তুলে ধরা', 'Highlight the important words.', 'গুরুত্বপূর্ণ শব্দগুলো চিহ্নিত কর।', 292),
    ('highly', null, 'adv.', 'B1', 'অত্যন্ত, উচ্চমাত্রায়', 'She is highly respected.', 'সে অত্যন্ত সম্মানিত।', 293),
    ('highway', null, 'n.', 'B1', 'মহাসড়ক', 'The highway was very busy.', 'মহাসড়কটি খুব ব্যস্ত ছিল।', 294),
    ('hire', null, 'n., v.', 'B1', 'ভাড়া করা; নিয়োগ করা', 'They hired a new manager.', 'তারা একজন নতুন ব্যবস্থাপক নিয়োগ করল।', 295),
    ('historic', null, 'adj.', 'B1', 'ঐতিহাসিক, স্মরণীয়', 'It was a historic moment.', 'এটি একটি ঐতিহাসিক মুহূর্ত ছিল।', 296),
    ('historical', null, 'adj.', 'B1', 'ইতিহাস-সম্পর্কিত', 'This is a historical building.', 'এটি একটি ঐতিহাসিক ভবন।', 297),
    ('honest', null, 'adj.', 'B1', 'সৎ, সত্যবাদী', 'Please give me an honest answer.', 'অনুগ্রহ করে আমাকে একটি সৎ উত্তর দাও।', 298),
    ('horrible', null, 'adj.', 'B1', 'ভয়ানক, ভয়ংকর', 'The weather was horrible today.', 'আজ আবহাওয়া ভয়ানক ছিল।', 299),
    ('horror', null, 'n.', 'B1', 'আতঙ্ক, ভীতি', 'He does not like horror films.', 'সে ভৌতিক সিনেমা পছন্দ করে না।', 300),
    ('host', null, 'n., v.', 'B1', 'আয়োজক, গৃহকর্তা; আয়োজন করা', 'They will host the party.', 'তারা পার্টির আয়োজন করবে।', 301),
    ('hunt', null, 'n., v.', 'B1', 'শিকার; শিকার করা', 'Lions hunt at night.', 'সিংহ রাতে শিকার করে।', 302),
    ('hurricane', null, 'n.', 'B1', 'ঘূর্ণিঝড়', 'The hurricane hit the coast.', 'ঘূর্ণিঝড়টি উপকূলে আঘাত করল।', 303),
    ('hurry', null, 'n., v.', 'B1', 'তাড়াহুড়া; তাড়াতাড়ি করা', 'Hurry up, we are late.', 'তাড়াতাড়ি কর, আমরা দেরি করে ফেলেছি।', 304),
    ('identity', null, 'n.', 'B1', 'পরিচয়', 'The thief hid his identity.', 'চোরটি তার পরিচয় লুকাল।', 305),
    ('ignore', null, 'v.', 'B1', 'উপেক্ষা করা', 'Do not ignore my advice.', 'আমার পরামর্শ উপেক্ষা করো না।', 306),
    ('illegal', null, 'adj.', 'B1', 'অবৈধ, বেআইনি', 'It is illegal to park here.', 'এখানে গাড়ি রাখা বেআইনি।', 307),
    ('imaginary', null, 'adj.', 'B1', 'কাল্পনিক', 'The child has an imaginary friend.', 'শিশুটির একটি কাল্পনিক বন্ধু আছে।', 308),
    ('immediate', null, 'adj.', 'B1', 'তাৎক্ষণিক, অবিলম্বে', 'We need an immediate answer.', 'আমাদের একটি তাৎক্ষণিক উত্তর দরকার।', 309),
    ('immigrant', null, 'n.', 'B1', 'অভিবাসী', 'Many immigrants came to the city.', 'অনেক অভিবাসী শহরে এল।', 310),
    ('impact', null, 'n., v.', 'B1', 'প্রভাব; প্রভাব ফেলা', 'The news had a big impact.', 'খবরটির বড় প্রভাব পড়ল।', 311),
    ('import', null, 'n., v.', 'B1', 'আমদানি; আমদানি করা', 'We import oil from other countries.', 'আমরা অন্য দেশ থেকে তেল আমদানি করি।', 312),
    ('importance', null, 'n.', 'B1', 'গুরুত্ব', 'He explained the importance of sleep.', 'তিনি ঘুমের গুরুত্ব ব্যাখ্যা করলেন।', 313),
    ('impression', null, 'n.', 'B1', 'ধারণা, প্রভাব', 'She made a good impression.', 'সে একটি ভালো ধারণা তৈরি করল।', 314),
    ('impressive', null, 'adj.', 'B1', 'চিত্তাকর্ষক, প্রশংসনীয়', 'Her results are impressive.', 'তার ফলাফল প্রশংসনীয়।', 315),
    ('improvement', null, 'n.', 'B1', 'উন্নতি', 'There is a big improvement in his work.', 'তার কাজে অনেক উন্নতি হয়েছে।', 316),
    ('incredibly', null, 'adv.', 'B1', 'অবিশ্বাস্যভাবে', 'The food was incredibly good.', 'খাবারটি অবিশ্বাস্যভাবে ভালো ছিল।', 317),
    ('indeed', null, 'adv.', 'B1', 'প্রকৃতপক্ষে, সত্যিই', 'It was indeed a great day.', 'এটি সত্যিই একটি চমৎকার দিন ছিল।', 318),
    ('indicate', null, 'v.', 'B1', 'নির্দেশ করা, ইঙ্গিত দেওয়া', 'The sign indicates the exit.', 'চিহ্নটি বহির্গমন পথ নির্দেশ করে।', 319),
    ('indirect', null, 'adj.', 'B1', 'পরোক্ষ', 'He gave an indirect answer.', 'সে একটি পরোক্ষ উত্তর দিল।', 320),
    ('indoor', null, 'adj.', 'B1', 'অন্দর, ঘরের ভেতরের', 'They played an indoor game.', 'তারা একটি অন্দর খেলা খেলল।', 321),
    ('indoors', null, 'adv.', 'B1', 'ঘরের ভেতরে', 'We stayed indoors during the rain.', 'বৃষ্টির সময় আমরা ঘরের ভেতরে থাকলাম।', 322),
    ('influence', null, 'n., v.', 'B1', 'প্রভাব; প্রভাবিত করা', 'Friends can influence your choices.', 'বন্ধুরা তোমার সিদ্ধান্তকে প্রভাবিত করতে পারে।', 323),
    ('ingredient', null, 'n.', 'B1', 'উপাদান, উপকরণ', 'Flour is the main ingredient.', 'ময়দা প্রধান উপকরণ।', 324),
    ('injure', null, 'v.', 'B1', 'আহত করা, জখম করা', 'He injured his leg while running.', 'দৌড়ানোর সময় সে তার পা জখম করল।', 325),
    ('injured', null, 'adj.', 'B1', 'আহত', 'The injured man was taken to hospital.', 'আহত লোকটিকে হাসপাতালে নেওয়া হলো।', 326),
    ('innocent', null, 'adj.', 'B1', 'নির্দোষ, নিরপরাধ', 'The court found him innocent.', 'আদালত তাকে নির্দোষ ঘোষণা করল।', 327),
    ('intelligence', null, 'n.', 'B1', 'বুদ্ধিমত্তা', 'Dolphins are known for their intelligence.', 'ডলফিন তাদের বুদ্ধিমত্তার জন্য পরিচিত।', 328),
    ('intend', null, 'v.', 'B1', 'ইচ্ছা করা, উদ্দেশ্য করা', 'I intend to study abroad.', 'আমি বিদেশে পড়ার ইচ্ছা করি।', 329),
    ('intention', null, 'n.', 'B1', 'উদ্দেশ্য, অভিপ্রায়', 'She had no intention of leaving.', 'তার চলে যাওয়ার কোনো উদ্দেশ্য ছিল না।', 330),
    ('invest', null, 'v.', 'B1', 'বিনিয়োগ করা', 'They invest money in new businesses.', 'তারা নতুন ব্যবসায় অর্থ বিনিয়োগ করে।', 331),
    ('investigate', null, 'v.', 'B1', 'তদন্ত করা', 'The police will investigate the case.', 'পুলিশ মামলাটি তদন্ত করবে।', 332),
    ('involved', null, 'adj.', 'B1', 'জড়িত, সম্পৃক্ত', 'She is involved in many projects.', 'সে অনেক প্রকল্পে জড়িত।', 333),
    ('iron', null, 'n., v.', 'B1', 'লোহা; ইস্তিরি করা', 'Please iron my shirt.', 'অনুগ্রহ করে আমার শার্টটি ইস্তিরি কর।', 334),
    ('issue', null, 'n., v.', 'B1', 'বিষয়, সমস্যা; জারি করা', 'This is an important issue.', 'এটি একটি গুরুত্বপূর্ণ বিষয়।', 335),
    ('IT', null, 'n.', 'B1', 'তথ্যপ্রযুক্তি', 'He works in the IT department.', 'সে তথ্যপ্রযুক্তি বিভাগে কাজ করে।', 336),
    ('journal', null, 'n.', 'B1', 'পত্রিকা, দিনলিপি', 'She keeps a daily journal.', 'সে প্রতিদিন একটি দিনলিপি লেখে।', 337),
    ('journey', null, 'n.', 'B1', 'যাত্রা, ভ্রমণ', 'The journey took ten hours.', 'যাত্রাটি দশ ঘণ্টা লাগল।', 338),
    ('judge', null, 'n., v.', 'B1', 'বিচারক; বিচার করা', 'Do not judge people by their looks.', 'চেহারা দেখে মানুষকে বিচার করো না।', 339),
    ('keyboard', null, 'n.', 'B1', 'কি-বোর্ড', 'My keyboard has a broken key.', 'আমার কি-বোর্ডে একটি চাবি ভাঙা।', 340),
    ('kick', null, 'n., v.', 'B1', 'লাথি; লাথি মারা', 'He kicked the ball into the goal.', 'সে বলটি গোলে লাথি মারল।', 341),
    ('killing', null, 'n.', 'B1', 'হত্যা', 'The killing shocked the town.', 'হত্যাটি শহরটিকে হতবাক করল।', 342),
    ('kind', 'caring', 'adj.', 'B1', 'দয়ালু', 'She is very kind to animals.', 'সে প্রাণীদের প্রতি খুব দয়ালু।', 343),
    ('kiss', null, 'n., v.', 'B1', 'চুম্বন; চুমু দেওয়া', 'The mother kissed her baby.', 'মা তার শিশুকে চুমু দিল।', 344),
    ('label', null, 'n., v.', 'B1', 'লেবেল, চিহ্ন; লেবেল লাগানো', 'Read the label before you buy.', 'কেনার আগে লেবেলটি পড়ো।', 345),
    ('laboratory', null, 'n.', 'B1', 'গবেষণাগার, ল্যাবরেটরি', 'The students worked in the laboratory.', 'শিক্ষার্থীরা গবেষণাগারে কাজ করল।', 346),
    ('lack', null, 'n., v.', 'B1', 'অভাব; অভাব থাকা', 'There is a lack of clean water.', 'বিশুদ্ধ পানির অভাব রয়েছে।', 347),
    ('latest', null, 'adj., n.', 'B1', 'সর্বশেষ, নবীনতম', 'Have you heard the latest news?', 'তুমি কি সর্বশেষ খবরটি শুনেছ?', 348),
    ('lay', null, 'v.', 'B1', 'রাখা, শোয়ানো; ডিম পাড়া', 'Please lay the books on the table.', 'অনুগ্রহ করে বইগুলো টেবিলে রাখো।', 349),
    ('layer', null, 'n.', 'B1', 'স্তর, পরত', 'There is a layer of dust on it.', 'এর উপর একটি ধুলার স্তর আছে।', 350),
    ('leading', null, 'adj.', 'B1', 'অগ্রণী, শীর্ষস্থানীয়', 'She is a leading scientist.', 'সে একজন অগ্রণী বিজ্ঞানী।', 351),
    ('leaf', null, 'n.', 'B1', 'পাতা', 'A leaf fell from the tree.', 'গাছ থেকে একটি পাতা পড়ল।', 352),
    ('leather', null, 'n.', 'B1', 'চামড়া', 'He bought a leather bag.', 'সে একটি চামড়ার ব্যাগ কিনল।', 353),
    ('legal', null, 'adj.', 'B1', 'আইনি, বৈধ', 'They took legal action.', 'তারা আইনি ব্যবস্থা নিল।', 354),
    ('leisure', null, 'n.', 'B1', 'অবসর, ফুরসত', 'He reads in his leisure time.', 'সে অবসর সময়ে বই পড়ে।', 355),
    ('length', null, 'n.', 'B1', 'দৈর্ঘ্য', 'What is the length of the room?', 'ঘরটির দৈর্ঘ্য কত?', 356),
    ('lie', 'tell a lie', 'n., v.', 'B1', 'মিথ্যা; মিথ্যা বলা', 'Do not tell a lie.', 'মিথ্যা বলো না।', 357),
    ('limit', null, 'n., v.', 'B1', 'সীমা; সীমিত করা', 'There is a speed limit on this road.', 'এই রাস্তায় একটি গতিসীমা আছে।', 358),
    ('liquid', null, 'adj., n.', 'B1', 'তরল', 'Water is a liquid.', 'পানি একটি তরল পদার্থ।', 359),
    ('literature', null, 'n.', 'B1', 'সাহিত্য', 'She loves English literature.', 'সে ইংরেজি সাহিত্য ভালোবাসে।', 360),
    ('live', null, 'adv., adj.', 'B1', 'সরাসরি, লাইভ', 'The match was shown live on TV.', 'খেলাটি টিভিতে সরাসরি দেখানো হলো।', 361),
    ('living', null, 'adj., n.', 'B1', 'জীবিত; জীবিকা', 'He earns his living by writing.', 'সে লেখালেখি করে জীবিকা নির্বাহ করে।', 362),
    ('locate', null, 'v.', 'B1', 'অবস্থান নির্ণয় করা, খুঁজে বের করা', 'Can you locate the village on the map?', 'তুমি কি মানচিত্রে গ্রামটি খুঁজে বের করতে পার?', 363),
    ('located', null, 'adj.', 'B1', 'অবস্থিত', 'The hotel is located near the beach.', 'হোটেলটি সমুদ্রসৈকতের কাছে অবস্থিত।', 364),
    ('location', null, 'n.', 'B1', 'স্থান, অবস্থান', 'This is a good location for a shop.', 'এটি একটি দোকানের জন্য ভালো অবস্থান।', 365),
    ('lonely', null, 'adj.', 'B1', 'একাকী, নিঃসঙ্গ', 'He felt lonely in the new city.', 'নতুন শহরে সে নিঃসঙ্গ বোধ করল।', 366),
    ('loss', null, 'n.', 'B1', 'ক্ষতি, হারানো', 'The team suffered a big loss.', 'দলটি একটি বড় ক্ষতির সম্মুখীন হলো।', 367),
    ('luxury', null, 'n.', 'B1', 'বিলাসিতা', 'A car is a luxury for them.', 'তাদের কাছে গাড়ি একটি বিলাসিতা।', 368),
    ('mad', null, 'adj.', 'B1', 'পাগল; ক্রুদ্ধ', 'He was mad at me for being late.', 'দেরি করার জন্য সে আমার উপর রেগে ছিল।', 369),
    ('magic', null, 'adj., n.', 'B1', 'জাদু; জাদুকরী', 'The children loved the magic show.', 'শিশুরা জাদু প্রদর্শনীটি ভালোবাসল।', 370),
    ('mainly', null, 'adv.', 'B1', 'মূলত, প্রধানত', 'The class is mainly for beginners.', 'ক্লাসটি মূলত নতুনদের জন্য।', 371),
    ('management', null, 'n.', 'B1', 'ব্যবস্থাপনা, পরিচালনা', 'Good time management is useful.', 'ভালো সময় ব্যবস্থাপনা কাজে লাগে।', 372),
    ('marketing', null, 'n.', 'B1', 'বিপণন, মার্কেটিং', 'She works in marketing.', 'সে বিপণন বিভাগে কাজ করে।', 373),
    ('marriage', null, 'n.', 'B1', 'বিবাহ, বিয়ে', 'They have a happy marriage.', 'তাদের একটি সুখী দাম্পত্য জীবন আছে।', 374),
    ('meanwhile', null, 'adv.', 'B1', 'ইতিমধ্যে, এদিকে', 'Meanwhile, I will cook dinner.', 'ইতিমধ্যে, আমি রাতের খাবার রান্না করব।', 375),
    ('measure', null, 'n., v.', 'B1', 'পরিমাপ; মাপা', 'Measure the length of the table.', 'টেবিলটির দৈর্ঘ্য মাপো।', 376),
    ('medium', null, 'adj., n.', 'B1', 'মাঝারি; মাধ্যম', 'I want a medium size shirt.', 'আমি একটি মাঝারি মাপের শার্ট চাই।', 377),
    ('mental', null, 'adj.', 'B1', 'মানসিক', 'Mental health is very important.', 'মানসিক স্বাস্থ্য খুব গুরুত্বপূর্ণ।', 378),
    ('mess', null, 'n., v.', 'B1', 'বিশৃঙ্খলা, নোংরা অবস্থা', 'Please clean up this mess.', 'অনুগ্রহ করে এই বিশৃঙ্খলা পরিষ্কার কর।', 379),
    ('mild', null, 'adj.', 'B1', 'মৃদু, নরম', 'The winter was mild this year.', 'এ বছর শীত মৃদু ছিল।', 380),
    ('mine', 'hole in the ground', 'n.', 'B1', 'খনি', 'They work in a coal mine.', 'তারা একটি কয়লা খনিতে কাজ করে।', 381),
    ('mix', null, 'n., v.', 'B1', 'মিশ্রণ; মেশানো', 'Mix the eggs and sugar.', 'ডিম ও চিনি মেশাও।', 382),
    ('mixture', null, 'n.', 'B1', 'মিশ্রণ', 'This is a mixture of oil and water.', 'এটি তেল ও পানির একটি মিশ্রণ।', 383),
    ('mood', null, 'n.', 'B1', 'মেজাজ, মনের অবস্থা', 'She is in a good mood today.', 'আজ তার মেজাজ ভালো।', 384),
    ('mud', null, 'n.', 'B1', 'কাদা', 'The children played in the mud.', 'শিশুরা কাদায় খেলল।', 385),
    ('murder', null, 'n., v.', 'B1', 'খুন, হত্যা; খুন করা', 'The book is about a murder.', 'বইটি একটি খুন নিয়ে।', 386),
    ('muscle', null, 'n.', 'B1', 'পেশি, মাংসপেশি', 'Exercise makes your muscles strong.', 'ব্যায়াম তোমার পেশি শক্ত করে।', 387),
    ('mystery', null, 'n.', 'B1', 'রহস্য', 'His sudden absence is a mystery.', 'তার হঠাৎ অনুপস্থিতি একটি রহস্য।', 388),
    ('nail', null, 'n.', 'B1', 'পেরেক; নখ', 'He hammered a nail into the wall.', 'সে দেয়ালে একটি পেরেক ঠুকল।', 389),
    ('narrative', null, 'adj., n.', 'B1', 'বর্ণনামূলক; আখ্যান, কাহিনি', 'The film has a simple narrative.', 'সিনেমাটির একটি সরল কাহিনি আছে।', 390),
    ('nation', null, 'n.', 'B1', 'জাতি, দেশ', 'The whole nation celebrated.', 'পুরো জাতি উদযাপন করল।', 391),
    ('native', null, 'adj., n.', 'B1', 'স্থানীয়, জন্মগত; আদিবাসী', 'English is not her native language.', 'ইংরেজি তার মাতৃভাষা নয়।', 392),
    ('naturally', null, 'adv.', 'B1', 'স্বাভাবিকভাবে', 'Naturally, she was happy to win.', 'স্বাভাবিকভাবেই, জিতে সে খুশি হলো।', 393),
    ('neat', null, 'adj.', 'B1', 'পরিপাটি, গোছানো', 'Her desk is always neat.', 'তার ডেস্ক সবসময় পরিপাটি থাকে।', 394),
    ('necessarily', null, 'adv.', 'B1', 'অপরিহার্যভাবে, অবশ্যই', 'That is not necessarily true.', 'সেটা অবশ্যই সত্য নয়।', 395),
    ('needle', null, 'n.', 'B1', 'সুচ', 'She used a needle and thread.', 'সে একটি সুচ ও সুতা ব্যবহার করল।', 396),
    ('net', null, 'n.', 'B1', 'জাল', 'The fisherman threw his net.', 'জেলে তার জাল ছুড়ল।', 397),
    ('nor', null, 'conj., adv.', 'B1', 'না... আবার নাও', 'He can neither read nor write.', 'সে পড়তেও পারে না, লিখতেও পারে না।', 398),
    ('northern', null, 'adj.', 'B1', 'উত্তরাঞ্চলীয়, উত্তরের', 'They live in the northern region.', 'তারা উত্তরাঞ্চলে থাকে।', 399),
    ('nuclear', null, 'adj.', 'B1', 'পারমাণবিক', 'The country has nuclear power.', 'দেশটির পারমাণবিক শক্তি আছে।', 400),
    ('obvious', null, 'adj.', 'B1', 'স্পষ্ট, সুস্পষ্ট', 'The answer is obvious.', 'উত্তরটি স্পষ্ট।', 401),
    ('obviously', null, 'adv.', 'B1', 'স্পষ্টতই', 'Obviously, he was very tired.', 'স্পষ্টতই, সে খুব ক্লান্ত ছিল।', 402),
    ('occasion', null, 'n.', 'B1', 'উপলক্ষ, অনুষ্ঠান', 'We wear these clothes on special occasions.', 'বিশেষ অনুষ্ঠানে আমরা এই পোশাক পরি।', 403),
    ('occur', null, 'v.', 'B1', 'ঘটা, সংঘটিত হওয়া', 'The accident occurred at night.', 'দুর্ঘটনাটি রাতে ঘটেছিল।', 404),
    ('odd', null, 'adj.', 'B1', 'অদ্ভুত; বিজোড়', 'That is an odd thing to say.', 'এটা বলার জন্য একটি অদ্ভুত কথা।', 405),
    ('official', null, 'adj., n.', 'B1', 'সরকারি, দাপ্তরিক; কর্মকর্তা', 'This is the official website.', 'এটি সরকারি ওয়েবসাইট।', 406),
    ('old-fashioned', null, 'adj.', 'B1', 'সেকেলে, পুরনো ধাঁচের', 'He has old-fashioned ideas.', 'তার সেকেলে ধারণা আছে।', 407),
    ('operation', null, 'n.', 'B1', 'অপারেশন, অস্ত্রোপচার; কার্যক্রম', 'She had an operation on her knee.', 'তার হাঁটুতে একটি অপারেশন হয়েছিল।', 408),
    ('organized', null, 'adj.', 'B1', 'সুসংগঠিত, গোছানো', 'She is a well-organized person.', 'সে একজন গোছানো মানুষ।', 409),
    ('organizer', null, 'n.', 'B1', 'আয়োজক, সংগঠক', 'The event organizer welcomed us.', 'অনুষ্ঠানের আয়োজক আমাদের স্বাগত জানালেন।', 410),
    ('originally', null, 'adv.', 'B1', 'মূলত, প্রথমে', 'She originally came from a village.', 'সে মূলত একটি গ্রাম থেকে এসেছিল।', 411),
    ('ought', null, 'modal v., v.', 'B1', 'উচিত', 'You ought to see a doctor.', 'তোমার একজন ডাক্তার দেখানো উচিত।', 412),
    ('ours', null, 'pron.', 'B1', 'আমাদের', 'This house is ours.', 'এই বাড়িটি আমাদের।', 413),
    ('outdoor', null, 'adj.', 'B1', 'বহিরাঙ্গন, খোলা জায়গার', 'They enjoy outdoor sports.', 'তারা বহিরাঙ্গন খেলা উপভোগ করে।', 414),
    ('outdoors', null, 'adv.', 'B1', 'বাইরে, খোলা জায়গায়', 'The children play outdoors.', 'শিশুরা বাইরে খেলে।', 415),
    ('package', null, 'n., v.', 'B1', 'প্যাকেজ, মোড়ক; মোড়কজাত করা', 'The package arrived this morning.', 'প্যাকেজটি আজ সকালে এল।', 416),
    ('painful', null, 'adj.', 'B1', 'যন্ত্রণাদায়ক, বেদনাদায়ক', 'The injury was very painful.', 'আঘাতটি খুব যন্ত্রণাদায়ক ছিল।', 417),
    ('pale', null, 'adj.', 'B1', 'ফ্যাকাশে, বিবর্ণ', 'She looked pale and tired.', 'তাকে ফ্যাকাশে ও ক্লান্ত দেখাল।', 418),
    ('pan', null, 'n.', 'B1', 'কড়াই, প্যান', 'Heat some oil in the pan.', 'প্যানে কিছুটা তেল গরম কর।', 419),
    ('participate', null, 'v.', 'B1', 'অংশগ্রহণ করা', 'All students can participate.', 'সব শিক্ষার্থী অংশগ্রহণ করতে পারে।', 420),
    ('particularly', null, 'adv.', 'B1', 'বিশেষত', 'I particularly like this song.', 'আমি বিশেষত এই গানটি পছন্দ করি।', 421),
    ('passion', null, 'n.', 'B1', 'আবেগ, প্রবল অনুরাগ', 'Music is her passion.', 'সংগীত তার প্রবল অনুরাগ।', 422),
    ('path', null, 'n.', 'B1', 'পথ, রাস্তা', 'A narrow path led to the house.', 'একটি সরু পথ বাড়িটির দিকে গেল।', 423),
    ('payment', null, 'n.', 'B1', 'পরিশোধ, অর্থপ্রদান', 'We accept payment by card.', 'আমরা কার্ডের মাধ্যমে অর্থপ্রদান গ্রহণ করি।', 424),
    ('peaceful', null, 'adj.', 'B1', 'শান্তিপূর্ণ', 'It is a peaceful little village.', 'এটি একটি শান্তিপূর্ণ ছোট গ্রাম।', 425),
    ('percentage', null, 'n.', 'B1', 'শতকরা হার', 'A large percentage of students passed.', 'শিক্ষার্থীদের একটি বড় শতাংশ উত্তীর্ণ হলো।', 426),
    ('perfectly', null, 'adv.', 'B1', 'নিখুঁতভাবে, সম্পূর্ণরূপে', 'The dress fits perfectly.', 'পোশাকটি নিখুঁতভাবে মানানসই।', 427),
    ('performance', null, 'n.', 'B1', 'পরিবেশন, অভিনয়; কর্মদক্ষতা', 'Her performance was excellent.', 'তার পরিবেশন চমৎকার ছিল।', 428),
    ('personally', null, 'adv.', 'B1', 'ব্যক্তিগতভাবে', 'Personally, I prefer tea.', 'ব্যক্তিগতভাবে, আমি চা পছন্দ করি।', 429),
    ('persuade', null, 'v.', 'B1', 'রাজি করানো, প্রবুদ্ধ করা', 'She persuaded him to stay.', 'সে তাকে থাকতে রাজি করাল।', 430),
    ('photographer', null, 'n.', 'B1', 'আলোকচিত্রী, ফটোগ্রাফার', 'The photographer took our picture.', 'ফটোগ্রাফার আমাদের ছবি তুললেন।', 431),
    ('photography', null, 'n.', 'B1', 'আলোকচিত্রবিদ্যা, ফটোগ্রাফি', 'Photography is his hobby.', 'ফটোগ্রাফি তার শখ।', 432),
    ('pin', null, 'n., v.', 'B1', 'পিন, আলপিন; পিন দিয়ে আটকানো', 'Pin the note to the board.', 'নোটটি বোর্ডে পিন দিয়ে আটকাও।', 433),
    ('pipe', null, 'n.', 'B1', 'নল, পাইপ', 'Water flows through the pipe.', 'পাইপের মধ্য দিয়ে পানি প্রবাহিত হয়।', 434),
    ('planning', null, 'n.', 'B1', 'পরিকল্পনা', 'The trip needs careful planning.', 'ভ্রমণটির জন্য সতর্ক পরিকল্পনা দরকার।', 435),
    ('pleasant', null, 'adj.', 'B1', 'মনোরম, সুখকর', 'We had a pleasant evening.', 'আমরা একটি মনোরম সন্ধ্যা কাটালাম।', 436),
    ('pleasure', null, 'n.', 'B1', 'আনন্দ, খুশি', 'It is a pleasure to meet you.', 'তোমার সঙ্গে দেখা করে আনন্দিত হলাম।', 437),
    ('plenty', null, 'pron.', 'B1', 'প্রচুর, যথেষ্ট', 'There is plenty of food for everyone.', 'সবার জন্য প্রচুর খাবার আছে।', 438),
    ('plot', null, 'n., v.', 'B1', 'কাহিনির প্লট; ষড়যন্ত্র করা', 'The movie has an exciting plot.', 'সিনেমাটির একটি রোমাঞ্চকর কাহিনি আছে।', 439),
    ('plus', null, 'prep., conj., adj., n.', 'B1', 'যোগ, এবং', 'Two plus three is five.', 'দুই যোগ তিন সমান পাঁচ।', 440),
    ('poem', null, 'n.', 'B1', 'কবিতা', 'She wrote a poem about spring.', 'সে বসন্ত নিয়ে একটি কবিতা লিখল।', 441),
    ('poet', null, 'n.', 'B1', 'কবি', 'He is a famous poet.', 'তিনি একজন বিখ্যাত কবি।', 442),
    ('poetry', null, 'n.', 'B1', 'কবিতা, কাব্য', 'I enjoy reading poetry.', 'আমি কবিতা পড়তে ভালোবাসি।', 443),
    ('poison', null, 'n., v.', 'B1', 'বিষ; বিষ প্রয়োগ করা', 'Some plants contain poison.', 'কিছু উদ্ভিদে বিষ থাকে।', 444),
    ('poisonous', null, 'adj.', 'B1', 'বিষাক্ত', 'This snake is poisonous.', 'এই সাপটি বিষাক্ত।', 445),
    ('policy', null, 'n.', 'B1', 'নীতি', 'The school has a clear policy.', 'স্কুলটির একটি স্পষ্ট নীতি আছে।', 446),
    ('political', null, 'adj.', 'B1', 'রাজনৈতিক', 'They discussed political issues.', 'তারা রাজনৈতিক বিষয় নিয়ে আলোচনা করল।', 447),
    ('politician', null, 'n.', 'B1', 'রাজনীতিবিদ', 'The politician gave a speech.', 'রাজনীতিবিদ একটি বক্তৃতা দিলেন।', 448),
    ('politics', null, 'n.', 'B1', 'রাজনীতি', 'He is interested in politics.', 'সে রাজনীতিতে আগ্রহী।', 449),
    ('port', null, 'n.', 'B1', 'বন্দর', 'The ship arrived at the port.', 'জাহাজটি বন্দরে পৌঁছাল।', 450),
    ('portrait', null, 'n.', 'B1', 'প্রতিকৃতি, ছবি', 'The artist painted her portrait.', 'শিল্পী তার প্রতিকৃতি আঁকলেন।', 451),
    ('possibly', null, 'adv.', 'B1', 'সম্ভবত', 'She could possibly arrive late.', 'সে সম্ভবত দেরিতে পৌঁছাতে পারে।', 452),
    ('pot', null, 'n.', 'B1', 'পাত্র, হাঁড়ি', 'There is soup in the pot.', 'হাঁড়িতে স্যুপ আছে।', 453),
    ('pour', null, 'v.', 'B1', 'ঢালা', 'Pour the milk into the cup.', 'কাপে দুধ ঢালো।', 454),
    ('poverty', null, 'n.', 'B1', 'দারিদ্র্য', 'Many families live in poverty.', 'অনেক পরিবার দারিদ্র্যে বাস করে।', 455),
    ('powder', null, 'n.', 'B1', 'গুঁড়া, চূর্ণ', 'Add a spoon of chili powder.', 'এক চামচ মরিচের গুঁড়া যোগ কর।', 456),
    ('powerful', null, 'adj.', 'B1', 'শক্তিশালী', 'The engine is very powerful.', 'ইঞ্জিনটি খুব শক্তিশালী।', 457),
    ('practical', null, 'adj.', 'B1', 'ব্যবহারিক, বাস্তবসম্মত', 'She gave me some practical advice.', 'সে আমাকে কিছু বাস্তবসম্মত পরামর্শ দিল।', 458),
    ('pray', null, 'v.', 'B1', 'প্রার্থনা করা', 'They pray every morning.', 'তারা প্রতিদিন সকালে প্রার্থনা করে।', 459),
    ('prayer', null, 'n.', 'B1', 'প্রার্থনা', 'She said a quiet prayer.', 'সে নীরবে একটি প্রার্থনা করল।', 460),
    ('prediction', null, 'n.', 'B1', 'ভবিষ্যদ্বাণী, পূর্বাভাস', 'His prediction came true.', 'তার ভবিষ্যদ্বাণী সত্য হলো।', 461),
    ('prepared', null, 'adj.', 'B1', 'প্রস্তুত', 'Are you prepared for the exam?', 'তুমি কি পরীক্ষার জন্য প্রস্তুত?', 462),
    ('presentation', null, 'n.', 'B1', 'উপস্থাপনা', 'She gave a clear presentation.', 'সে একটি স্পষ্ট উপস্থাপনা দিল।', 463),
    ('press', null, 'n., v.', 'B1', 'সংবাদপত্র; চাপা, টেপা', 'Press this button to start.', 'শুরু করতে এই বোতামটি চাপো।', 464),
    ('pressure', null, 'n.', 'B1', 'চাপ', 'He works well under pressure.', 'সে চাপের মধ্যে ভালো কাজ করে।', 465),
    ('pretend', null, 'v.', 'B1', 'ভান করা', 'She pretended to be asleep.', 'সে ঘুমের ভান করল।', 466),
    ('previous', null, 'adj.', 'B1', 'পূর্ববর্তী, আগের', 'See the previous page.', 'আগের পৃষ্ঠাটি দেখো।', 467),
    ('previously', null, 'adv.', 'B1', 'পূর্বে, আগে', 'He had previously lived in India.', 'সে আগে ভারতে বাস করেছিল।', 468),
    ('priest', null, 'n.', 'B1', 'যাজক, পুরোহিত', 'The priest led the prayer.', 'যাজক প্রার্থনা পরিচালনা করলেন।', 469),
    ('primary', null, 'adj.', 'B1', 'প্রাথমিক, প্রধান', 'Safety is our primary concern.', 'নিরাপত্তা আমাদের প্রধান উদ্বেগ।', 470),
    ('prince', null, 'n.', 'B1', 'রাজপুত্র, যুবরাজ', 'The prince lived in a castle.', 'রাজপুত্র একটি দুর্গে বাস করতেন।', 471),
    ('princess', null, 'n.', 'B1', 'রাজকন্যা', 'The princess had a kind heart.', 'রাজকন্যার হৃদয় ছিল দয়ালু।', 472),
    ('principal', null, 'adj., n.', 'B1', 'প্রধান; অধ্যক্ষ', 'The school principal made a speech.', 'স্কুলের অধ্যক্ষ একটি বক্তৃতা দিলেন।', 473),
    ('printing', null, 'n.', 'B1', 'মুদ্রণ, ছাপা', 'The printing of the book took a week.', 'বইটির মুদ্রণে এক সপ্তাহ লাগল।', 474),
    ('prisoner', null, 'n.', 'B1', 'বন্দি, কয়েদি', 'The prisoner was set free.', 'বন্দিটিকে মুক্তি দেওয়া হলো।', 475),
    ('private', null, 'adj.', 'B1', 'ব্যক্তিগত, একান্ত', 'This is private property.', 'এটি ব্যক্তিগত সম্পত্তি।', 476),
    ('producer', null, 'n.', 'B1', 'প্রযোজক; উৎপাদক', 'He is a film producer.', 'তিনি একজন চলচ্চিত্র প্রযোজক।', 477),
    ('production', null, 'n.', 'B1', 'উৎপাদন', 'Car production increased this year.', 'এ বছর গাড়ি উৎপাদন বেড়েছে।', 478),
    ('profession', null, 'n.', 'B1', 'পেশা', 'Teaching is a noble profession.', 'শিক্ষকতা একটি মহৎ পেশা।', 479),
    ('profit', null, 'n.', 'B1', 'লাভ, মুনাফা', 'The company made a big profit.', 'কোম্পানিটি বড় মুনাফা করল।', 480),
    ('promote', null, 'v.', 'B1', 'প্রসার করা; পদোন্নতি দেওয়া', 'They promote healthy eating.', 'তারা স্বাস্থ্যকর খাবারের প্রসার করে।', 481),
    ('proper', null, 'adj.', 'B1', 'যথাযথ, উপযুক্ত', 'Wear proper shoes for running.', 'দৌড়ানোর জন্য উপযুক্ত জুতা পরো।', 482),
    ('properly', null, 'adv.', 'B1', 'যথাযথভাবে, ঠিকমতো', 'Close the door properly.', 'দরজাটি ঠিকমতো বন্ধ কর।', 483),
    ('property', null, 'n.', 'B1', 'সম্পত্তি', 'This land is his property.', 'এই জমিটি তার সম্পত্তি।', 484),
    ('protest', null, 'n., v.', 'B1', 'প্রতিবাদ; প্রতিবাদ করা', 'People protested against the new law.', 'লোকজন নতুন আইনের বিরুদ্ধে প্রতিবাদ করল।', 485),
    ('proud', null, 'adj.', 'B1', 'গর্বিত', 'I am proud of you.', 'আমি তোমার জন্য গর্বিত।', 486),
    ('prove', null, 'v.', 'B1', 'প্রমাণ করা', 'Can you prove that it is true?', 'তুমি কি প্রমাণ করতে পার যে এটা সত্য?', 487),
    ('punish', null, 'v.', 'B1', 'শাস্তি দেওয়া', 'The teacher punished the boy.', 'শিক্ষক ছেলেটিকে শাস্তি দিলেন।', 488),
    ('punishment', null, 'n.', 'B1', 'শাস্তি', 'The punishment was too harsh.', 'শাস্তিটি অত্যন্ত কঠোর ছিল।', 489),
    ('qualification', null, 'n.', 'B1', 'যোগ্যতা, শিক্ষাগত যোগ্যতা', 'She has the right qualifications.', 'তার সঠিক যোগ্যতা আছে।', 490),
    ('qualified', null, 'adj.', 'B1', 'যোগ্য, প্রশিক্ষিত', 'He is a qualified doctor.', 'তিনি একজন যোগ্য ডাক্তার।', 491),
    ('qualify', null, 'v.', 'B1', 'যোগ্যতা অর্জন করা', 'She qualified for the final round.', 'সে চূড়ান্ত পর্বের জন্য যোগ্যতা অর্জন করল।', 492),
    ('quit', null, 'v.', 'B1', 'ছেড়ে দেওয়া, ত্যাগ করা', 'He quit his job last week.', 'সে গত সপ্তাহে তার চাকরি ছেড়ে দিল।', 493),
    ('quotation', null, 'n.', 'B1', 'উদ্ধৃতি', 'She began with a famous quotation.', 'সে একটি বিখ্যাত উদ্ধৃতি দিয়ে শুরু করল।', 494),
    ('quote', null, 'n., v.', 'B1', 'উদ্ধৃতি; উদ্ধৃত করা', 'He quoted a line from the poem.', 'সে কবিতাটির একটি লাইন উদ্ধৃত করল।', 495),
    ('race', 'of people', 'n.', 'B1', 'জাতি, বর্ণ', 'People of every race are welcome.', 'প্রতিটি জাতির মানুষ এখানে স্বাগত।', 496),
    ('racing', null, 'n.', 'B1', 'রেসিং, দৌড় প্রতিযোগিতা', 'He loves car racing.', 'সে গাড়ির রেসিং ভালোবাসে।', 497),
    ('range', null, 'n., v.', 'B1', 'পরিসর, সীমা; বিস্তৃত হওয়া', 'The shop sells a wide range of books.', 'দোকানটি নানা রকমের বই বিক্রি করে।', 498),
    ('rare', null, 'adj.', 'B1', 'দুর্লভ, বিরল', 'This is a rare bird.', 'এটি একটি বিরল পাখি।', 499),
    ('rarely', null, 'adv.', 'B1', 'কদাচিৎ, খুব কমই', 'He rarely watches TV.', 'সে কদাচিৎ টিভি দেখে।', 500),
    ('reaction', null, 'n.', 'B1', 'প্রতিক্রিয়া', 'Her reaction surprised me.', 'তার প্রতিক্রিয়া আমাকে অবাক করল।', 501),
    ('reality', null, 'n.', 'B1', 'বাস্তবতা', 'The dream became a reality.', 'স্বপ্নটি বাস্তবে পরিণত হলো।', 502),
    ('receipt', null, 'n.', 'B1', 'রসিদ', 'Please keep your receipt.', 'অনুগ্রহ করে আপনার রসিদ রাখুন।', 503),
    ('recommendation', null, 'n.', 'B1', 'সুপারিশ, পরামর্শ', 'I followed the doctor''s recommendation.', 'আমি ডাক্তারের সুপারিশ অনুসরণ করলাম।', 504),
    ('reference', null, 'n.', 'B1', 'উল্লেখ, সূত্র', 'He made a reference to the report.', 'সে প্রতিবেদনটির উল্লেখ করল।', 505),
    ('reflect', null, 'v.', 'B1', 'প্রতিফলিত করা; চিন্তা করা', 'The lake reflected the mountains.', 'হ্রদটি পাহাড়গুলো প্রতিফলিত করল।', 506),
    ('regularly', null, 'adv.', 'B1', 'নিয়মিতভাবে', 'She exercises regularly.', 'সে নিয়মিতভাবে ব্যায়াম করে।', 507),
    ('reject', null, 'v.', 'B1', 'প্রত্যাখ্যান করা, বাতিল করা', 'They rejected his offer.', 'তারা তার প্রস্তাব প্রত্যাখ্যান করল।', 508),
    ('relate', null, 'v.', 'B1', 'সম্পর্কিত করা, সংযোগ করা', 'Can you relate these two events?', 'তুমি কি এই দুটি ঘটনার সম্পর্ক দেখাতে পার?', 509),
    ('related', null, 'adj.', 'B1', 'সম্পর্কিত', 'These problems are closely related.', 'এই সমস্যাগুলো ঘনিষ্ঠভাবে সম্পর্কিত।', 510),
    ('relation', null, 'n.', 'B1', 'সম্পর্ক', 'There is a relation between diet and health.', 'খাদ্য ও স্বাস্থ্যের মধ্যে একটি সম্পর্ক আছে।', 511),
    ('relative', null, 'adj., n.', 'B1', 'আপেক্ষিক; আত্মীয়', 'My relatives are coming for dinner.', 'আমার আত্মীয়রা রাতের খাবারে আসছে।', 512),
    ('relaxed', null, 'adj.', 'B1', 'স্বচ্ছন্দ, নিশ্চিন্ত', 'She felt relaxed on the holiday.', 'ছুটিতে সে স্বচ্ছন্দ বোধ করল।', 513),
    ('relaxing', null, 'adj.', 'B1', 'আরামদায়ক, প্রশান্তিদায়ক', 'A warm bath is relaxing.', 'একটি উষ্ণ স্নান আরামদায়ক।', 514),
    ('release', null, 'n., v.', 'B1', 'মুক্তি; মুক্তি দেওয়া, প্রকাশ করা', 'The band will release a new song.', 'ব্যান্ডটি একটি নতুন গান প্রকাশ করবে।', 515),
    ('reliable', null, 'adj.', 'B1', 'নির্ভরযোগ্য', 'He is a reliable friend.', 'সে একজন নির্ভরযোগ্য বন্ধু।', 516),
    ('religion', null, 'n.', 'B1', 'ধর্ম', 'People of every religion live here.', 'এখানে প্রতিটি ধর্মের মানুষ বাস করে।', 517),
    ('religious', null, 'adj.', 'B1', 'ধর্মীয়', 'They follow religious traditions.', 'তারা ধর্মীয় ঐতিহ্য অনুসরণ করে।', 518),
    ('remain', null, 'v.', 'B1', 'থেকে যাওয়া, অবশিষ্ট থাকা', 'Please remain in your seats.', 'অনুগ্রহ করে আপনার আসনে থাকুন।', 519),
    ('remind', null, 'v.', 'B1', 'মনে করিয়ে দেওয়া', 'Please remind me to call her.', 'অনুগ্রহ করে আমাকে তাকে ফোন করার কথা মনে করিয়ে দিও।', 520),
    ('remote', null, 'adj.', 'B1', 'দূরবর্তী, প্রত্যন্ত', 'They live in a remote village.', 'তারা একটি প্রত্যন্ত গ্রামে থাকে।', 521),
    ('rent', null, 'n., v.', 'B1', 'ভাড়া; ভাড়া নেওয়া', 'We rent a small apartment.', 'আমরা একটি ছোট ফ্ল্যাট ভাড়া নিই।', 522),
    ('repeated', null, 'adj.', 'B1', 'বারবার, পুনরাবৃত্ত', 'He made repeated mistakes.', 'সে বারবার ভুল করল।', 523),
    ('represent', null, 'v.', 'B1', 'প্রতিনিধিত্ব করা', 'She represents our country.', 'সে আমাদের দেশের প্রতিনিধিত্ব করে।', 524),
    ('require', null, 'v.', 'B1', 'প্রয়োজন হওয়া, দরকার হওয়া', 'This job requires patience.', 'এই কাজে ধৈর্য প্রয়োজন।', 525),
    ('reservation', null, 'n.', 'B1', 'সংরক্ষণ, আগাম বুকিং', 'I made a table reservation.', 'আমি একটি টেবিল আগাম বুক করলাম।', 526),
    ('resource', null, 'n.', 'B1', 'সম্পদ, উৎস', 'Water is a valuable resource.', 'পানি একটি মূল্যবান সম্পদ।', 527),
    ('respect', null, 'n., v.', 'B1', 'সম্মান; সম্মান করা', 'We should respect our elders.', 'আমাদের বড়দের সম্মান করা উচিত।', 528),
    ('responsibility', null, 'n.', 'B1', 'দায়িত্ব', 'It is your responsibility to check.', 'পরীক্ষা করা তোমার দায়িত্ব।', 529),
    ('responsible', null, 'adj.', 'B1', 'দায়িত্বশীল; দায়ী', 'She is responsible for the team.', 'সে দলের জন্য দায়িত্বশীল।', 530),
    ('retire', null, 'v.', 'B1', 'অবসর নেওয়া', 'He will retire next year.', 'সে আগামী বছর অবসর নেবে।', 531),
    ('retired', null, 'adj.', 'B1', 'অবসরপ্রাপ্ত', 'My father is a retired teacher.', 'আমার বাবা একজন অবসরপ্রাপ্ত শিক্ষক।', 532),
    ('revise', null, 'v.', 'B1', 'সংশোধন করা; পুনরালোচনা করা', 'I need to revise for the test.', 'আমাকে পরীক্ষার জন্য পড়া ঝালিয়ে নিতে হবে।', 533),
    ('risk', null, 'n., v.', 'B1', 'ঝুঁকি; ঝুঁকি নেওয়া', 'There is a risk of rain today.', 'আজ বৃষ্টির ঝুঁকি আছে।', 534),
    ('robot', null, 'n.', 'B1', 'রোবট, যন্ত্রমানব', 'The robot can clean the floor.', 'রোবটটি মেঝে পরিষ্কার করতে পারে।', 535),
    ('roll', null, 'n., v.', 'B1', 'গড়ানো; গুটানো', 'The ball rolled down the hill.', 'বলটি পাহাড় বেয়ে গড়িয়ে পড়ল।', 536),
    ('romantic', null, 'adj.', 'B1', 'রোমান্টিক, প্রেমঘটিত', 'They watched a romantic movie.', 'তারা একটি রোমান্টিক সিনেমা দেখল।', 537),
    ('rope', null, 'n.', 'B1', 'দড়ি', 'He tied the boat with a rope.', 'সে নৌকাটি একটি দড়ি দিয়ে বাঁধল।', 538),
    ('rough', null, 'adj.', 'B1', 'এবড়োখেবড়ো, রুক্ষ', 'The road was rough and bumpy.', 'রাস্তাটি এবড়োখেবড়ো ছিল।', 539),
    ('row', null, 'n.', 'B1', 'সারি', 'We sat in the front row.', 'আমরা সামনের সারিতে বসলাম।', 540),
    ('royal', null, 'adj.', 'B1', 'রাজকীয়', 'They visited the royal palace.', 'তারা রাজকীয় প্রাসাদটি দেখতে গেল।', 541),
    ('safety', null, 'n.', 'B1', 'নিরাপত্তা', 'Wear a helmet for your safety.', 'তোমার নিরাপত্তার জন্য হেলমেট পরো।', 542),
    ('sailor', null, 'n.', 'B1', 'নাবিক', 'The sailor sailed across the sea.', 'নাবিকটি সমুদ্র পাড়ি দিল।', 543),
    ('sample', null, 'n., v.', 'B1', 'নমুনা; নমুনা নেওয়া', 'They gave me a free sample.', 'তারা আমাকে একটি বিনামূল্যের নমুনা দিল।', 544),
    ('sand', null, 'n.', 'B1', 'বালি', 'The children played in the sand.', 'শিশুরা বালিতে খেলল।', 545),
    ('scan', null, 'v.', 'B1', 'স্ক্যান করা, খুঁটিয়ে দেখা', 'Please scan the document.', 'অনুগ্রহ করে নথিটি স্ক্যান কর।', 546),
    ('scientific', null, 'adj.', 'B1', 'বৈজ্ঞানিক', 'They used a scientific method.', 'তারা একটি বৈজ্ঞানিক পদ্ধতি ব্যবহার করল।', 547),
    ('script', null, 'n.', 'B1', 'চিত্রনাট্য, পাণ্ডুলিপি', 'The actor learned the script.', 'অভিনেতা চিত্রনাট্যটি মুখস্থ করল।', 548),
    ('sculpture', null, 'n.', 'B1', 'ভাস্কর্য', 'The museum has old sculptures.', 'জাদুঘরে পুরনো ভাস্কর্য আছে।', 549),
    ('secondary', null, 'adj.', 'B1', 'মাধ্যমিক; গৌণ', 'She teaches at a secondary school.', 'সে একটি মাধ্যমিক বিদ্যালয়ে পড়ায়।', 550),
    ('security', null, 'n.', 'B1', 'নিরাপত্তা', 'The airport has tight security.', 'বিমানবন্দরে কড়া নিরাপত্তা আছে।', 551),
    ('seed', null, 'n.', 'B1', 'বীজ', 'She planted a flower seed.', 'সে একটি ফুলের বীজ রোপণ করল।', 552),
    ('sensible', null, 'adj.', 'B1', 'বিবেচক, বুদ্ধিসম্পন্ন', 'That was a sensible decision.', 'ওটা একটি বিবেচনাপ্রসূত সিদ্ধান্ত ছিল।', 553),
    ('seriously', null, 'adv.', 'B1', 'গম্ভীরভাবে, গুরুত্ব সহকারে', 'Please take this seriously.', 'অনুগ্রহ করে এটি গুরুত্ব সহকারে নাও।', 554),
    ('servant', null, 'n.', 'B1', 'চাকর, ভৃত্য', 'The old house had many servants.', 'পুরনো বাড়িটিতে অনেক চাকর ছিল।', 555),
    ('set', 'group', 'n.', 'B1', 'সেট, সমষ্টি', 'She bought a set of cups.', 'সে এক সেট কাপ কিনল।', 556),
    ('set', 'put', 'v.', 'B1', 'রাখা, স্থাপন করা', 'Set the plate on the table.', 'প্লেটটি টেবিলে রাখো।', 557),
    ('setting', null, 'n.', 'B1', 'পরিবেশ, প্রেক্ষাপট; সেটিং', 'The story has a village setting.', 'গল্পটির প্রেক্ষাপট একটি গ্রাম।', 558),
    ('sex', null, 'n.', 'B1', 'লিঙ্গ', 'The form asks for your sex.', 'ফর্মটিতে তোমার লিঙ্গ জানতে চাওয়া হয়েছে।', 559),
    ('sexual', null, 'adj.', 'B1', 'যৌন, লিঙ্গসম্পর্কিত', 'The book explains sexual health.', 'বইটি যৌন স্বাস্থ্য ব্যাখ্যা করে।', 560),
    ('sharp', null, 'adj.', 'B1', 'ধারালো; তীক্ষ্ণ', 'Be careful, the knife is sharp.', 'সাবধান, ছুরিটি ধারালো।', 561),
    ('shelf', null, 'n.', 'B1', 'তাক, শেলফ', 'Put the book back on the shelf.', 'বইটি তাকে ফিরিয়ে রাখো।', 562),
    ('shell', null, 'n.', 'B1', 'খোলস, শামুকের খোল', 'She collected shells on the beach.', 'সে সমুদ্রসৈকতে শামুকের খোল সংগ্রহ করল।', 563),
    ('shift', null, 'n., v.', 'B1', 'পালা, শিফট; সরানো', 'He works the night shift.', 'সে রাতের পালায় কাজ করে।', 564),
    ('shine', null, 'v.', 'B1', 'উজ্জ্বল হওয়া, চকচক করা', 'The sun shines brightly today.', 'আজ সূর্য উজ্জ্বলভাবে জ্বলছে।', 565),
    ('shiny', null, 'adj.', 'B1', 'চকচকে', 'She wore shiny shoes.', 'সে চকচকে জুতা পরল।', 566),
    ('shoot', null, 'v.', 'B1', 'গুলি করা; ছবি তোলা', 'Do not shoot the birds.', 'পাখিদের গুলি করো না।', 567),
    ('shy', null, 'adj.', 'B1', 'লাজুক', 'She is too shy to speak in class.', 'সে ক্লাসে কথা বলতে খুব লাজুক।', 568),
    ('sight', null, 'n.', 'B1', 'দৃষ্টি; দৃশ্য', 'The mountains were a beautiful sight.', 'পাহাড়গুলো একটি সুন্দর দৃশ্য ছিল।', 569),
    ('signal', null, 'n., v.', 'B1', 'সংকেত; সংকেত দেওয়া', 'The green signal means go.', 'সবুজ সংকেতের অর্থ যাও।', 570),
    ('silent', null, 'adj.', 'B1', 'নীরব, নিস্তব্ধ', 'The room was completely silent.', 'ঘরটি সম্পূর্ণ নীরব ছিল।', 571),
    ('silly', null, 'adj.', 'B1', 'বোকা, হাস্যকর', 'That was a silly mistake.', 'ওটা একটি বোকা ভুল ছিল।', 572),
    ('similarity', null, 'n.', 'B1', 'মিল, সাদৃশ্য', 'There is a similarity between them.', 'তাদের মধ্যে একটি মিল আছে।', 573),
    ('similarly', null, 'adv.', 'B1', 'একইভাবে', 'Similarly, the second test failed.', 'একইভাবে, দ্বিতীয় পরীক্ষাটিও ব্যর্থ হলো।', 574),
    ('simply', null, 'adv.', 'B1', 'সহজভাবে; কেবল', 'Simply add water and mix.', 'কেবল পানি যোগ করে মিশিয়ে দাও।', 575),
    ('sink', null, 'v.', 'B1', 'ডুবে যাওয়া', 'The heavy stone sank in the water.', 'ভারী পাথরটি পানিতে ডুবে গেল।', 576),
    ('slave', null, 'n.', 'B1', 'ক্রীতদাস', 'The slaves fought for freedom.', 'ক্রীতদাসরা স্বাধীনতার জন্য লড়াই করল।', 577),
    ('slice', null, 'n., v.', 'B1', 'ফালি, টুকরো; ফালি করা', 'I ate a slice of bread.', 'আমি এক টুকরো রুটি খেলাম।', 578),
    ('slightly', null, 'adv.', 'B1', 'সামান্য, অল্প', 'The soup is slightly salty.', 'স্যুপটি সামান্য নোনতা।', 579),
    ('smooth', null, 'adj.', 'B1', 'মসৃণ', 'The table has a smooth surface.', 'টেবিলটির পৃষ্ঠ মসৃণ।', 580),
    ('software', null, 'n.', 'B1', 'সফটওয়্যার', 'This software is easy to use.', 'এই সফটওয়্যারটি ব্যবহার করা সহজ।', 581),
    ('soil', null, 'n.', 'B1', 'মাটি', 'Plants grow well in this soil.', 'এই মাটিতে গাছপালা ভালো জন্মে।', 582),
    ('solid', null, 'adj., n.', 'B1', 'কঠিন, শক্ত; কঠিন পদার্থ', 'Ice is water in solid form.', 'বরফ হলো কঠিন রূপে পানি।', 583),
    ('southern', null, 'adj.', 'B1', 'দক্ষিণাঞ্চলীয়, দক্ষিণের', 'They come from the southern part.', 'তারা দক্ষিণাঞ্চল থেকে এসেছে।', 584),
    ('specifically', null, 'adv.', 'B1', 'বিশেষভাবে, সুনির্দিষ্টভাবে', 'This book is written specifically for children.', 'এই বইটি বিশেষভাবে শিশুদের জন্য লেখা।', 585),
    ('spending', null, 'n.', 'B1', 'ব্যয়, খরচ', 'They cut their spending this month.', 'তারা এ মাসে তাদের খরচ কমাল।', 586),
    ('spicy', null, 'adj.', 'B1', 'ঝাল, মসলাদার', 'This curry is very spicy.', 'এই তরকারিটি খুব ঝাল।', 587),
    ('spirit', null, 'n.', 'B1', 'আত্মা; মনোবল', 'The team played with great spirit.', 'দলটি দারুণ মনোবল নিয়ে খেলল।', 588),
    ('spoken', null, 'adj.', 'B1', 'কথ্য, মৌখিক', 'Her spoken English is good.', 'তার কথ্য ইংরেজি ভালো।', 589),
    ('spot', null, 'n., v.', 'B1', 'স্থান, দাগ; চিহ্নিত করা, দেখতে পাওয়া', 'This is a good spot for a picnic.', 'এটি পিকনিকের জন্য একটি ভালো জায়গা।', 590),
    ('spread', null, 'n., v.', 'B1', 'বিস্তার; ছড়িয়ে দেওয়া', 'The fire spread quickly.', 'আগুন দ্রুত ছড়িয়ে পড়ল।', 591),
    ('stadium', null, 'n.', 'B1', 'স্টেডিয়াম, ক্রীড়াঙ্গন', 'The stadium was full of fans.', 'স্টেডিয়ামটি সমর্থকে পূর্ণ ছিল।', 592),
    ('staff', null, 'n.', 'B1', 'কর্মী, কর্মচারীবৃন্দ', 'The hotel staff were friendly.', 'হোটেলের কর্মীরা বন্ধুত্বপূর্ণ ছিল।', 593),
    ('standard', null, 'adj., n.', 'B1', 'মান, মানদণ্ড; আদর্শ', 'The work is of a high standard.', 'কাজটি উচ্চ মানের।', 594),
    ('statistic', null, 'n.', 'B1', 'পরিসংখ্যান', 'This statistic is surprising.', 'এই পরিসংখ্যানটি বিস্ময়কর।', 595),
    ('statue', null, 'n.', 'B1', 'মূর্তি', 'There is a statue in the park.', 'উদ্যানে একটি মূর্তি আছে।', 596),
    ('stick', 'piece of wood', 'n.', 'B1', 'লাঠি, ছড়ি', 'The dog fetched the stick.', 'কুকুরটি লাঠিটি নিয়ে এল।', 597),
    ('stick', 'push into/attach', 'v.', 'B1', 'আটকানো, লাগানো', 'Stick the stamp on the envelope.', 'খামের উপর ডাকটিকিটটি লাগাও।', 598),
    ('stranger', null, 'n.', 'B1', 'অপরিচিত ব্যক্তি', 'Do not talk to strangers.', 'অপরিচিত মানুষের সঙ্গে কথা বলো না।', 599),
    ('strength', null, 'n.', 'B1', 'শক্তি, বল', 'He does not have the strength to lift it.', 'এটি তোলার শক্তি তার নেই।', 600),
    ('string', null, 'n.', 'B1', 'সুতা, দড়ি', 'She tied the box with string.', 'সে বাক্সটি সুতা দিয়ে বাঁধল।', 601),
    ('strongly', null, 'adv.', 'B1', 'দৃঢ়ভাবে, প্রবলভাবে', 'I strongly agree with you.', 'আমি তোমার সঙ্গে দৃঢ়ভাবে একমত।', 602),
    ('studio', null, 'n.', 'B1', 'স্টুডিও, কর্মশালা', 'The artist works in a small studio.', 'শিল্পী একটি ছোট স্টুডিওতে কাজ করেন।', 603),
    ('stuff', null, 'n., v.', 'B1', 'জিনিসপত্র; ঠাসা', 'Put your stuff in the bag.', 'তোমার জিনিসপত্র ব্যাগে রাখো।', 604),
    ('substance', null, 'n.', 'B1', 'পদার্থ, বস্তু', 'Sugar is a sweet substance.', 'চিনি একটি মিষ্টি পদার্থ।', 605),
    ('successfully', null, 'adv.', 'B1', 'সফলভাবে', 'She successfully finished the course.', 'সে সফলভাবে কোর্সটি শেষ করল।', 606),
    ('sudden', null, 'adj.', 'B1', 'হঠাৎ, আকস্মিক', 'There was a sudden change in weather.', 'আবহাওয়ায় একটি আকস্মিক পরিবর্তন হলো।', 607),
    ('suffer', null, 'v.', 'B1', 'কষ্ট পাওয়া, ভোগা', 'Many people suffer from hunger.', 'অনেক মানুষ ক্ষুধায় ভোগে।', 608),
    ('suitable', null, 'adj.', 'B1', 'উপযুক্ত, মানানসই', 'This film is not suitable for children.', 'এই সিনেমাটি শিশুদের জন্য উপযুক্ত নয়।', 609),
    ('summarize', null, 'v.', 'B1', 'সংক্ষিপ্ত করা, সারাংশ করা', 'Please summarize the story.', 'অনুগ্রহ করে গল্পটির সারাংশ কর।', 610),
    ('summary', null, 'n.', 'B1', 'সারাংশ, সংক্ষিপ্তসার', 'Write a short summary of the text.', 'লেখাটির একটি সংক্ষিপ্ত সারাংশ লেখো।', 611),
    ('supply', null, 'n., v.', 'B1', 'সরবরাহ; সরবরাহ করা', 'They supply water to the village.', 'তারা গ্রামে পানি সরবরাহ করে।', 612),
    ('supporter', null, 'n.', 'B1', 'সমর্থক', 'He is a loyal supporter of the team.', 'সে দলের একজন অনুগত সমর্থক।', 613),
    ('surely', null, 'adv.', 'B1', 'নিশ্চয়ই', 'Surely you remember me?', 'নিশ্চয়ই তুমি আমাকে মনে রেখেছ?', 614),
    ('surface', null, 'n.', 'B1', 'পৃষ্ঠ, উপরিতল', 'The surface of the lake was calm.', 'হ্রদের উপরিতল শান্ত ছিল।', 615),
    ('survive', null, 'v.', 'B1', 'বেঁচে থাকা, টিকে থাকা', 'Plants cannot survive without water.', 'পানি ছাড়া গাছপালা বাঁচতে পারে না।', 616),
    ('switch', null, 'n., v.', 'B1', 'সুইচ; বদলানো, চালু-বন্ধ করা', 'Please switch off the light.', 'অনুগ্রহ করে বাতিটি বন্ধ কর।', 617),
    ('symptom', null, 'n.', 'B1', 'লক্ষণ, উপসর্গ', 'A fever is a common symptom.', 'জ্বর একটি সাধারণ উপসর্গ।', 618),
    ('tail', null, 'n.', 'B1', 'লেজ', 'The dog wagged its tail.', 'কুকুরটি তার লেজ নাড়ল।', 619),
    ('talent', null, 'n.', 'B1', 'প্রতিভা', 'She has a talent for music.', 'তার সংগীতে প্রতিভা আছে।', 620),
    ('talented', null, 'adj.', 'B1', 'প্রতিভাবান', 'He is a talented young artist.', 'সে একজন প্রতিভাবান তরুণ শিল্পী।', 621),
    ('tape', null, 'n.', 'B1', 'ফিতা, টেপ', 'Fix the paper with tape.', 'কাগজটি টেপ দিয়ে আটকাও।', 622),
    ('tax', null, 'n., v.', 'B1', 'কর, খাজনা; কর ধার্য করা', 'Everyone must pay tax.', 'সবাইকে কর দিতে হয়।', 623),
    ('technical', null, 'adj.', 'B1', 'কারিগরি, প্রযুক্তিগত', 'We had a technical problem.', 'আমাদের একটি কারিগরি সমস্যা হয়েছিল।', 624),
    ('technique', null, 'n.', 'B1', 'কৌশল, পদ্ধতি', 'She learned a new painting technique.', 'সে একটি নতুন আঁকার কৌশল শিখল।', 625),
    ('tend', null, 'v.', 'B1', 'প্রবণতা থাকা, ঝোঁক থাকা', 'He tends to arrive early.', 'তার আগে আসার প্রবণতা আছে।', 626),
    ('tent', null, 'n.', 'B1', 'তাঁবু', 'We slept in a tent.', 'আমরা একটি তাঁবুতে ঘুমালাম।', 627),
    ('theirs', null, 'pron.', 'B1', 'তাদের', 'This car is theirs.', 'এই গাড়িটি তাদের।', 628),
    ('theme', null, 'n.', 'B1', 'মূল ভাব, বিষয়', 'The theme of the story is friendship.', 'গল্পটির মূল বিষয় বন্ধুত্ব।', 629),
    ('theory', null, 'n.', 'B1', 'তত্ত্ব', 'He explained his theory clearly.', 'সে তার তত্ত্বটি স্পষ্টভাবে ব্যাখ্যা করল।', 630),
    ('therefore', null, 'adv.', 'B1', 'সুতরাং, অতএব', 'It rained; therefore, we stayed home.', 'বৃষ্টি হয়েছিল; সুতরাং, আমরা বাড়িতে থাকলাম।', 631),
    ('though', null, 'conj., adv.', 'B1', 'যদিও, তবুও', 'Though it was late, she kept working.', 'যদিও দেরি হয়ে গিয়েছিল, সে কাজ চালিয়ে গেল।', 632),
    ('throat', null, 'n.', 'B1', 'গলা, কণ্ঠনালী', 'I have a sore throat.', 'আমার গলা ব্যথা করছে।', 633),
    ('throughout', null, 'prep., adv.', 'B1', 'সর্বত্র, পুরো সময় জুড়ে', 'It rained throughout the night.', 'সারা রাত ধরে বৃষ্টি হলো।', 634),
    ('tight', null, 'adj.', 'B1', 'আঁটসাঁট, টান টান', 'These shoes are too tight.', 'এই জুতাগুলো খুব আঁটসাঁট।', 635),
    ('till', null, 'prep., conj.', 'B1', 'পর্যন্ত', 'Wait here till I come back.', 'আমি ফিরে না আসা পর্যন্ত এখানে অপেক্ষা কর।', 636),
    ('tiny', null, 'adj.', 'B1', 'অতি ক্ষুদ্র, ছোট্ট', 'A tiny insect sat on the leaf.', 'একটি ছোট্ট পোকা পাতায় বসল।', 637),
    ('tire', null, 'n.', 'B1', 'টায়ার, চাকার আবরণ', 'The car has a flat tire.', 'গাড়ির একটি টায়ার পাংচার হয়ে গেছে।', 638),
    ('toe', null, 'n.', 'B1', 'পায়ের আঙুল', 'I hurt my toe on the door.', 'দরজায় লেগে আমার পায়ের আঙুলে ব্যথা পেলাম।', 639),
    ('ton', null, 'n.', 'B1', 'টন (ওজনের একক)', 'The truck carried tons of sand.', 'ট্রাকটি টন টন বালি বহন করল।', 640),
    ('tongue', null, 'n.', 'B1', 'জিহ্বা, জিব', 'The soup burned my tongue.', 'স্যুপটি আমার জিব পুড়িয়ে দিল।', 641),
    ('total', null, 'adj., n.', 'B1', 'সম্পূর্ণ; মোট', 'What is the total cost?', 'মোট খরচ কত?', 642),
    ('totally', null, 'adv.', 'B1', 'সম্পূর্ণভাবে, একেবারে', 'I totally agree with you.', 'আমি তোমার সঙ্গে সম্পূর্ণভাবে একমত।', 643),
    ('trade', null, 'n., v.', 'B1', 'বাণিজ্য, ব্যবসা; বিনিময় করা', 'The two countries trade with each other.', 'দুই দেশ একে অপরের সঙ্গে বাণিজ্য করে।', 644),
    ('trainer', null, 'n.', 'B1', 'প্রশিক্ষক', 'The trainer taught us new skills.', 'প্রশিক্ষক আমাদের নতুন দক্ষতা শেখালেন।', 645),
    ('translate', null, 'v.', 'B1', 'অনুবাদ করা', 'Can you translate this sentence?', 'তুমি কি এই বাক্যটি অনুবাদ করতে পার?', 646),
    ('translation', null, 'n.', 'B1', 'অনুবাদ', 'This is a good translation.', 'এটি একটি ভালো অনুবাদ।', 647),
    ('transport', null, 'v.', 'B1', 'পরিবহন করা, বহন করা', 'Trucks transport goods to the market.', 'ট্রাক পণ্য বাজারে পরিবহন করে।', 648),
    ('treat', null, 'v.', 'B1', 'আচরণ করা; চিকিৎসা করা', 'The doctor treated the patient.', 'ডাক্তার রোগীর চিকিৎসা করলেন।', 649),
    ('treatment', null, 'n.', 'B1', 'চিকিৎসা; আচরণ', 'He is getting treatment for his illness.', 'সে তার অসুস্থতার চিকিৎসা নিচ্ছে।', 650),
    ('trend', null, 'n.', 'B1', 'প্রবণতা, ধারা', 'This is a new fashion trend.', 'এটি একটি নতুন ফ্যাশন ধারা।', 651),
    ('trick', null, 'n., v.', 'B1', 'কৌশল, চাতুরি; ধোঁকা দেওয়া', 'The magician showed a clever trick.', 'জাদুকর একটি চতুর কৌশল দেখাল।', 652),
    ('truth', null, 'n.', 'B1', 'সত্য', 'Please tell me the truth.', 'অনুগ্রহ করে আমাকে সত্যটি বলো।', 653),
    ('tube', null, 'n.', 'B1', 'নল, টিউব', 'Buy a tube of toothpaste.', 'এক টিউব টুথপেস্ট কিনো।', 654),
    ('typically', null, 'adv.', 'B1', 'সাধারণত, বৈশিষ্ট্যগতভাবে', 'She typically works from home.', 'সে সাধারণত বাড়ি থেকে কাজ করে।', 655),
    ('ugly', null, 'adj.', 'B1', 'কুৎসিত, বিশ্রী', 'The old building looks ugly.', 'পুরনো ভবনটি দেখতে বিশ্রী।', 656),
    ('unable', null, 'adj.', 'B1', 'অক্ষম, অসমর্থ', 'He was unable to come.', 'সে আসতে অক্ষম ছিল।', 657),
    ('uncomfortable', null, 'adj.', 'B1', 'অস্বস্তিকর', 'The chair is uncomfortable.', 'চেয়ারটি অস্বস্তিকর।', 658),
    ('underwear', null, 'n.', 'B1', 'অন্তর্বাস', 'She packed some clean underwear.', 'সে কিছু পরিষ্কার অন্তর্বাস গুছিয়ে নিল।', 659),
    ('unemployed', null, 'adj.', 'B1', 'বেকার', 'He has been unemployed for months.', 'সে কয়েক মাস ধরে বেকার।', 660),
    ('unemployment', null, 'n.', 'B1', 'বেকারত্ব', 'Unemployment is a serious problem.', 'বেকারত্ব একটি গুরুতর সমস্যা।', 661),
    ('unfair', null, 'adj.', 'B1', 'অন্যায্য, অবিচারমূলক', 'The decision was unfair.', 'সিদ্ধান্তটি অন্যায্য ছিল।', 662),
    ('union', null, 'n.', 'B1', 'সংঘ, ইউনিয়ন', 'The workers formed a union.', 'শ্রমিকরা একটি সংঘ গঠন করল।', 663),
    ('unless', null, 'conj.', 'B1', 'যদি না', 'We will not go unless it stops raining.', 'বৃষ্টি না থামলে আমরা যাব না।', 664),
    ('unlike', null, 'prep.', 'B1', 'বিপরীতে, ভিন্ন', 'Unlike her sister, she is quiet.', 'তার বোনের বিপরীতে, সে শান্ত।', 665),
    ('unlikely', null, 'adj.', 'B1', 'অসম্ভাব্য', 'It is unlikely to snow here.', 'এখানে তুষারপাত হওয়া অসম্ভাব্য।', 666),
    ('unnecessary', null, 'adj.', 'B1', 'অপ্রয়োজনীয়', 'Avoid unnecessary spending.', 'অপ্রয়োজনীয় খরচ এড়িয়ে চলো।', 667),
    ('unpleasant', null, 'adj.', 'B1', 'অপ্রীতিকর, বিরক্তিকর', 'There was an unpleasant smell.', 'একটি অপ্রীতিকর গন্ধ ছিল।', 668),
    ('update', null, 'n., v.', 'B1', 'হালনাগাদ; হালনাগাদ করা', 'Please update your address.', 'অনুগ্রহ করে আপনার ঠিকানা হালনাগাদ করুন।', 669),
    ('upon', null, 'prep.', 'B1', 'উপরে, উপর', 'The decision depends upon you.', 'সিদ্ধান্তটি তোমার উপর নির্ভর করে।', 670),
    ('upset', null, 'adj., v.', 'B1', 'মন খারাপ, বিচলিত; বিচলিত করা', 'She was upset about the news.', 'খবরটি নিয়ে সে বিচলিত হয়েছিল।', 671),
    ('used', 'familiar with', 'adj.', 'B1', 'অভ্যস্ত', 'I am used to getting up early.', 'আমি তাড়াতাড়ি ওঠায় অভ্যস্ত।', 672),
    ('used', 'secondhand', 'adj.', 'B1', 'ব্যবহৃত, পুরনো', 'They bought a used car.', 'তারা একটি পুরনো গাড়ি কিনল।', 673),
    ('valuable', null, 'adj.', 'B1', 'মূল্যবান', 'This is a valuable painting.', 'এটি একটি মূল্যবান চিত্রকর্ম।', 674),
    ('value', null, 'n., v.', 'B1', 'মূল্য, গুরুত্ব; মূল্য দেওয়া', 'I value your friendship.', 'আমি তোমার বন্ধুত্বকে মূল্য দিই।', 675),
    ('various', null, 'adj.', 'B1', 'বিভিন্ন, নানা', 'The shop sells various items.', 'দোকানটি বিভিন্ন জিনিস বিক্রি করে।', 676),
    ('version', null, 'n.', 'B1', 'সংস্করণ, রূপ', 'This is the latest version of the app.', 'এটি অ্যাপটির সর্বশেষ সংস্করণ।', 677),
    ('victim', null, 'n.', 'B1', 'শিকার, ভুক্তভোগী', 'They helped the flood victims.', 'তারা বন্যায় ভুক্তভোগীদের সাহায্য করল।', 678),
    ('viewer', null, 'n.', 'B1', 'দর্শক', 'The show has millions of viewers.', 'অনুষ্ঠানটির লক্ষ লক্ষ দর্শক আছে।', 679),
    ('violent', null, 'adj.', 'B1', 'হিংস্র, সহিংস', 'The film has violent scenes.', 'সিনেমাটিতে সহিংস দৃশ্য আছে।', 680),
    ('volunteer', null, 'n., v.', 'B1', 'স্বেচ্ছাসেবক; স্বেচ্ছায় করা', 'She works as a volunteer.', 'সে একজন স্বেচ্ছাসেবক হিসেবে কাজ করে।', 681),
    ('vote', null, 'n., v.', 'B1', 'ভোট; ভোট দেওয়া', 'Everyone has the right to vote.', 'প্রত্যেকের ভোট দেওয়ার অধিকার আছে।', 682),
    ('warn', null, 'v.', 'B1', 'সতর্ক করা', 'I warned him about the danger.', 'আমি তাকে বিপদ সম্পর্কে সতর্ক করলাম।', 683),
    ('warning', null, 'n.', 'B1', 'সতর্কবার্তা', 'They ignored the warning.', 'তারা সতর্কবার্তাটি উপেক্ষা করল।', 684),
    ('waste', null, 'adj., n., v.', 'B1', 'অপচয়, বর্জ্য; অপচয় করা', 'Do not waste food.', 'খাবার নষ্ট করো না।', 685),
    ('weapon', null, 'n.', 'B1', 'অস্ত্র', 'The soldier carried a weapon.', 'সৈনিকটি একটি অস্ত্র বহন করল।', 686),
    ('weigh', null, 'v.', 'B1', 'ওজন করা; ওজন হওয়া', 'The bag weighs five kilos.', 'ব্যাগটির ওজন পাঁচ কিলো।', 687),
    ('western', null, 'adj.', 'B1', 'পশ্চিমা, পশ্চিমাঞ্চলীয়', 'He enjoys western music.', 'সে পশ্চিমা সংগীত উপভোগ করে।', 688),
    ('whatever', null, 'pron., det.', 'B1', 'যা কিছু, যেটাই হোক', 'Do whatever you think is right.', 'যা তুমি ঠিক মনে কর তাই কর।', 689),
    ('whenever', null, 'conj.', 'B1', 'যখনই', 'Call me whenever you need help.', 'যখনই সাহায্য দরকার হয়, আমাকে ফোন কর।', 690),
    ('whether', null, 'conj.', 'B1', 'কি না, যদি', 'I do not know whether she will come.', 'সে আসবে কি না আমি জানি না।', 691),
    ('wing', null, 'n.', 'B1', 'ডানা, পাখা', 'The bird hurt its wing.', 'পাখিটি তার ডানায় আঘাত পেল।', 692),
    ('within', null, 'prep.', 'B1', 'মধ্যে, ভেতরে', 'Finish the work within an hour.', 'এক ঘণ্টার মধ্যে কাজটি শেষ কর।', 693),
    ('wonder', null, 'n., v.', 'B1', 'বিস্ময়; ভাবা, জানতে চাওয়া', 'I wonder where she is.', 'সে কোথায় আছে আমি ভাবছি।', 694),
    ('wool', null, 'n.', 'B1', 'পশম, উল', 'This sweater is made of wool.', 'এই সোয়েটারটি পশমের তৈরি।', 695),
    ('worldwide', null, 'adv., adj.', 'B1', 'বিশ্বব্যাপী', 'The company is known worldwide.', 'কোম্পানিটি বিশ্বব্যাপী পরিচিত।', 696),
    ('worth', null, 'adj., n.', 'B1', 'মূল্যবান, সমমূল্যের', 'This book is worth reading.', 'বইটি পড়ার মতো।', 697),
    ('written', null, 'adj.', 'B1', 'লিখিত', 'Please give me a written report.', 'অনুগ্রহ করে আমাকে একটি লিখিত প্রতিবেদন দাও।', 698),
    ('youth', null, 'n.', 'B1', 'যৌবন; তরুণসমাজ', 'The youth of today are ambitious.', 'আজকের তরুণসমাজ উচ্চাকাঙ্ক্ষী।', 699);
