-- V15 — seed vocabulary: Oxford 3000 (American English) B2 band, 599 headwords.
-- Generated from authored Bengali glosses + bilingual examples (scratchpad/b2_chunk_*.json).
-- Standalone reference data; see V11 for the table.

insert into vocabulary
    (headword, sense_label, part_of_speech, cefr_level, bn_gloss, example_en, example_bn, ordinal)
values
    ('abandon', null, 'v.', 'B2', 'পরিত্যাগ করা, ছেড়ে যাওয়া', 'They had to abandon the sinking ship.', 'তাদের ডুবন্ত জাহাজটি ছেড়ে যেতে হলো।', 1),
    ('abroad', null, 'adv.', 'B2', 'বিদেশে', 'She studies abroad.', 'সে বিদেশে পড়াশোনা করে।', 2),
    ('absolute', null, 'adj.', 'B2', 'সম্পূর্ণ, নিরঙ্কুশ', 'I have absolute trust in her.', 'তার প্রতি আমার সম্পূর্ণ আস্থা আছে।', 3),
    ('acceptable', null, 'adj.', 'B2', 'গ্রহণযোগ্য', 'This behavior is not acceptable.', 'এই আচরণ গ্রহণযোগ্য নয়।', 4),
    ('accompany', null, 'v.', 'B2', 'সঙ্গে যাওয়া, সঙ্গ দেওয়া', 'She accompanied me to the doctor.', 'সে আমার সঙ্গে ডাক্তারের কাছে গেল।', 5),
    ('accurate', null, 'adj.', 'B2', 'নির্ভুল, সঠিক', 'The report must be accurate.', 'প্রতিবেদনটি নির্ভুল হতে হবে।', 6),
    ('accuse', null, 'v.', 'B2', 'অভিযুক্ত করা, দোষারোপ করা', 'They accused him of stealing.', 'তারা তাকে চুরির জন্য অভিযুক্ত করল।', 7),
    ('acknowledge', null, 'v.', 'B2', 'স্বীকার করা, মেনে নেওয়া', 'He acknowledged his error.', 'সে তার ভুল স্বীকার করল।', 8),
    ('acquire', null, 'v.', 'B2', 'অর্জন করা, লাভ করা', 'She acquired new skills at work.', 'সে কাজে নতুন দক্ষতা অর্জন করল।', 9),
    ('actual', null, 'adj.', 'B2', 'প্রকৃত, বাস্তব', 'The actual cost was higher.', 'প্রকৃত খরচ আরও বেশি ছিল।', 10),
    ('adapt', null, 'v.', 'B2', 'খাপ খাওয়ানো, মানিয়ে নেওয়া', 'Children adapt quickly to change.', 'শিশুরা দ্রুত পরিবর্তনের সঙ্গে মানিয়ে নেয়।', 11),
    ('additional', null, 'adj.', 'B2', 'অতিরিক্ত', 'There is an additional fee.', 'একটি অতিরিক্ত ফি আছে।', 12),
    ('adopt', null, 'v.', 'B2', 'দত্তক নেওয়া; গ্রহণ করা', 'They decided to adopt a child.', 'তারা একটি শিশু দত্তক নেওয়ার সিদ্ধান্ত নিল।', 13),
    ('advance', null, 'adj., n., v.', 'B2', 'অগ্রগতি; এগিয়ে যাওয়া, আগাম', 'Book your ticket in advance.', 'আগেভাগে তোমার টিকিট বুক কর।', 14),
    ('affair', null, 'n.', 'B2', 'ব্যাপার, বিষয়', 'That is a private affair.', 'এটি একটি ব্যক্তিগত ব্যাপার।', 15),
    ('afterward', null, 'adv.', 'B2', 'পরে, পরবর্তীতে', 'We had dinner and talked afterward.', 'আমরা রাতের খাবার খেলাম এবং পরে গল্প করলাম।', 16),
    ('agency', null, 'n.', 'B2', 'সংস্থা, এজেন্সি', 'She works for a travel agency.', 'সে একটি ভ্রমণ সংস্থায় কাজ করে।', 17),
    ('agenda', null, 'n.', 'B2', 'আলোচ্যসূচি, কর্মসূচি', 'What is on the agenda today?', 'আজকের আলোচ্যসূচিতে কী আছে?', 18),
    ('aggressive', null, 'adj.', 'B2', 'আক্রমণাত্মক, উগ্র', 'The dog became aggressive.', 'কুকুরটি আক্রমণাত্মক হয়ে উঠল।', 19),
    ('aid', null, 'n., v.', 'B2', 'সাহায্য, ত্রাণ; সাহায্য করা', 'They sent aid to the flood victims.', 'তারা বন্যায় ভুক্তভোগীদের কাছে ত্রাণ পাঠাল।', 20),
    ('aircraft', null, 'n.', 'B2', 'উড়োজাহাজ, বিমান', 'The aircraft landed safely.', 'বিমানটি নিরাপদে অবতরণ করল।', 21),
    ('alter', null, 'v.', 'B2', 'পরিবর্তন করা, বদলানো', 'She altered the dress to fit.', 'সে পোশাকটি মাপমতো বদলে নিল।', 22),
    ('anger', null, 'n.', 'B2', 'রাগ, ক্রোধ', 'He could not hide his anger.', 'সে তার রাগ লুকাতে পারল না।', 23),
    ('angle', null, 'n.', 'B2', 'কোণ', 'Draw a right angle here.', 'এখানে একটি সমকোণ আঁকো।', 24),
    ('anniversary', null, 'n.', 'B2', 'বার্ষিকী', 'Today is their wedding anniversary.', 'আজ তাদের বিবাহবার্ষিকী।', 25),
    ('annual', null, 'adj.', 'B2', 'বার্ষিক', 'The company held its annual meeting.', 'কোম্পানিটি তার বার্ষিক সভা করল।', 26),
    ('anxious', null, 'adj.', 'B2', 'উদ্বিগ্ন, চিন্তিত', 'She felt anxious before the exam.', 'পরীক্ষার আগে সে উদ্বিগ্ন বোধ করল।', 27),
    ('apparent', null, 'adj.', 'B2', 'স্পষ্ট, আপাত', 'It was apparent that he was tired.', 'এটা স্পষ্ট ছিল যে সে ক্লান্ত।', 28),
    ('apparently', null, 'adv.', 'B2', 'স্পষ্টতই, শোনা যাচ্ছে', 'Apparently, the shop is closed today.', 'শোনা যাচ্ছে, দোকানটি আজ বন্ধ।', 29),
    ('appeal', null, 'n., v.', 'B2', 'আবেদন, আকর্ষণ; আবেদন করা', 'They made an appeal for help.', 'তারা সাহায্যের জন্য একটি আবেদন করল।', 30),
    ('approach', null, 'n., v.', 'B2', 'দৃষ্টিভঙ্গি; কাছে আসা', 'We need a new approach to the problem.', 'সমস্যাটির জন্য আমাদের একটি নতুন দৃষ্টিভঙ্গি দরকার।', 31),
    ('appropriate', null, 'adj.', 'B2', 'উপযুক্ত, যথাযথ', 'Wear appropriate clothes for the event.', 'অনুষ্ঠানের জন্য উপযুক্ত পোশাক পরো।', 32),
    ('approval', null, 'n.', 'B2', 'অনুমোদন, সম্মতি', 'The plan needs the manager''s approval.', 'পরিকল্পনাটির জন্য ব্যবস্থাপকের অনুমোদন দরকার।', 33),
    ('approve', null, 'v.', 'B2', 'অনুমোদন করা', 'The board approved the budget.', 'বোর্ড বাজেটটি অনুমোদন করল।', 34),
    ('arise', null, 'v.', 'B2', 'উদ্ভূত হওয়া, দেখা দেওয়া', 'Problems may arise later.', 'পরে সমস্যা দেখা দিতে পারে।', 35),
    ('armed', null, 'adj.', 'B2', 'সশস্ত্র', 'The bank was robbed by armed men.', 'ব্যাংকটি সশস্ত্র লোকদের দ্বারা লুট হলো।', 36),
    ('arms', null, 'n.', 'B2', 'অস্ত্রশস্ত্র', 'The soldiers laid down their arms.', 'সৈন্যরা তাদের অস্ত্র নামিয়ে রাখল।', 37),
    ('artificial', null, 'adj.', 'B2', 'কৃত্রিম', 'The drink has artificial colors.', 'পানীয়টিতে কৃত্রিম রং আছে।', 38),
    ('artistic', null, 'adj.', 'B2', 'শৈল্পিক', 'She has an artistic talent.', 'তার একটি শৈল্পিক প্রতিভা আছে।', 39),
    ('ashamed', null, 'adj.', 'B2', 'লজ্জিত', 'He was ashamed of his behavior.', 'সে তার আচরণের জন্য লজ্জিত ছিল।', 40),
    ('aside', null, 'adv.', 'B2', 'একপাশে, সরিয়ে', 'She put the book aside.', 'সে বইটি একপাশে রেখে দিল।', 41),
    ('aspect', null, 'n.', 'B2', 'দিক, পক্ষ', 'We discussed every aspect of the plan.', 'আমরা পরিকল্পনাটির প্রতিটি দিক নিয়ে আলোচনা করলাম।', 42),
    ('assess', null, 'v.', 'B2', 'মূল্যায়ন করা, নিরূপণ করা', 'Teachers assess the students'' work.', 'শিক্ষকরা শিক্ষার্থীদের কাজ মূল্যায়ন করেন।', 43),
    ('assessment', null, 'n.', 'B2', 'মূল্যায়ন', 'The assessment will be next week.', 'মূল্যায়নটি আগামী সপ্তাহে হবে।', 44),
    ('associate', null, 'v.', 'B2', 'যুক্ত করা, সংযুক্ত ভাবা', 'We associate summer with holidays.', 'আমরা গ্রীষ্মকে ছুটির সঙ্গে যুক্ত ভাবি।', 45),
    ('associated', null, 'adj.', 'B2', 'সম্পর্কিত, যুক্ত', 'Costs associated with travel are high.', 'ভ্রমণের সঙ্গে যুক্ত খরচ বেশি।', 46),
    ('association', null, 'n.', 'B2', 'সংঘ, সমিতি', 'He joined the writers'' association.', 'সে লেখকদের সমিতিতে যোগ দিল।', 47),
    ('assume', null, 'v.', 'B2', 'ধরে নেওয়া, অনুমান করা', 'I assume you have finished.', 'আমি ধরে নিচ্ছি তুমি শেষ করেছ।', 48),
    ('attempt', null, 'n., v.', 'B2', 'প্রচেষ্টা; চেষ্টা করা', 'She made an attempt to fix it.', 'সে এটি ঠিক করার একটি চেষ্টা করল।', 49),
    ('attorney', null, 'n.', 'B2', 'আইনজীবী, উকিল', 'The attorney defended his client.', 'আইনজীবী তার মক্কেলের পক্ষ সমর্থন করলেন।', 50),
    ('bacteria', null, 'n.', 'B2', 'ব্যাকটেরিয়া, জীবাণু', 'Some bacteria are harmful.', 'কিছু ব্যাকটেরিয়া ক্ষতিকর।', 51),
    ('barrier', null, 'n.', 'B2', 'বাধা, প্রতিবন্ধক', 'Language can be a barrier.', 'ভাষা একটি বাধা হতে পারে।', 52),
    ('basically', null, 'adv.', 'B2', 'মূলত, মৌলিকভাবে', 'Basically, the plan is simple.', 'মূলত, পরিকল্পনাটি সহজ।', 53),
    ('bear', 'deal with', 'v.', 'B2', 'সহ্য করা, বহন করা', 'I cannot bear this pain.', 'আমি এই যন্ত্রণা সহ্য করতে পারছি না।', 54),
    ('beg', null, 'v.', 'B2', 'ভিক্ষা করা; মিনতি করা', 'He begged them to stay.', 'সে তাদের থাকার জন্য মিনতি করল।', 55),
    ('being', null, 'n.', 'B2', 'সত্তা, প্রাণী', 'Humans are social beings.', 'মানুষ সামাজিক প্রাণী।', 56),
    ('bent', null, 'adj.', 'B2', 'বাঁকা, নত', 'The nail was bent.', 'পেরেকটি বাঁকা ছিল।', 57),
    ('bet', null, 'n., v.', 'B2', 'বাজি; বাজি ধরা', 'I bet he will win.', 'আমি বাজি ধরে বলছি সে জিতবে।', 58),
    ('beyond', null, 'prep., adv.', 'B2', 'অতিক্রম করে, ছাড়িয়ে', 'The hills lie beyond the river.', 'পাহাড়গুলো নদীর ওপারে অবস্থিত।', 59),
    ('bitter', null, 'adj.', 'B2', 'তেতো; তিক্ত', 'The medicine tasted bitter.', 'ওষুধটির স্বাদ তেতো ছিল।', 60),
    ('blame', null, 'n., v.', 'B2', 'দোষ; দোষারোপ করা', 'Do not blame others for your mistakes.', 'তোমার ভুলের জন্য অন্যদের দোষ দিও না।', 61),
    ('blind', null, 'adj.', 'B2', 'অন্ধ', 'The blind man used a stick.', 'অন্ধ লোকটি একটি লাঠি ব্যবহার করল।', 62),
    ('bond', null, 'n.', 'B2', 'বন্ধন, সম্পর্ক', 'There is a strong bond between them.', 'তাদের মধ্যে একটি দৃঢ় বন্ধন আছে।', 63),
    ('breast', null, 'n.', 'B2', 'বুক, স্তন', 'She held the baby to her breast.', 'সে শিশুটিকে বুকে জড়িয়ে ধরল।', 64),
    ('brief', null, 'adj.', 'B2', 'সংক্ষিপ্ত', 'He gave a brief reply.', 'সে একটি সংক্ষিপ্ত উত্তর দিল।', 65),
    ('broad', null, 'adj.', 'B2', 'প্রশস্ত, চওড়া', 'They walked down a broad street.', 'তারা একটি চওড়া রাস্তা ধরে হাঁটল।', 66),
    ('broadcast', null, 'n., v.', 'B2', 'সম্প্রচার; সম্প্রচার করা', 'The match was broadcast live.', 'খেলাটি সরাসরি সম্প্রচার করা হলো।', 67),
    ('budget', null, 'n.', 'B2', 'বাজেট, ব্যয়সংকুলান', 'We planned a monthly budget.', 'আমরা একটি মাসিক বাজেট পরিকল্পনা করলাম।', 68),
    ('bullet', null, 'n.', 'B2', 'গুলি, বুলেট', 'The bullet missed him.', 'গুলিটি তাকে লাগেনি।', 69),
    ('bunch', null, 'n.', 'B2', 'গুচ্ছ, তোড়া', 'He bought a bunch of bananas.', 'সে এক কাঁদি কলা কিনল।', 70),
    ('bush', null, 'n.', 'B2', 'ঝোপ, গুল্ম', 'A rabbit hid behind the bush.', 'একটি খরগোশ ঝোপের পেছনে লুকাল।', 71),
    ('calculate', null, 'v.', 'B2', 'হিসাব করা, গণনা করা', 'Calculate the total cost.', 'মোট খরচ হিসাব কর।', 72),
    ('cancel', null, 'v.', 'B2', 'বাতিল করা', 'They canceled the meeting.', 'তারা সভাটি বাতিল করল।', 73),
    ('cancer', null, 'n.', 'B2', 'ক্যান্সার', 'Smoking can cause cancer.', 'ধূমপান ক্যান্সারের কারণ হতে পারে।', 74),
    ('capable', null, 'adj.', 'B2', 'সক্ষম, যোগ্য', 'She is capable of great things.', 'সে দারুণ কিছু করতে সক্ষম।', 75),
    ('capacity', null, 'n.', 'B2', 'ধারণক্ষমতা, সামর্থ্য', 'The hall has a capacity of 200.', 'হলটির ধারণক্ষমতা ২০০ জন।', 76),
    ('capture', null, 'n., v.', 'B2', 'বন্দি করা, ধরা; ধারণ করা', 'The photo captured the moment.', 'ছবিটি মুহূর্তটি ধারণ করল।', 77),
    ('cast', null, 'n., v.', 'B2', 'অভিনেতৃবৃন্দ; নিক্ষেপ করা', 'The film has a talented cast.', 'সিনেমাটির অভিনেতৃবৃন্দ প্রতিভাবান।', 78),
    ('chairman', null, 'n.', 'B2', 'সভাপতি, চেয়ারম্যান', 'The chairman opened the meeting.', 'সভাপতি সভাটি শুরু করলেন।', 79),
    ('characteristic', null, 'adj., n.', 'B2', 'বৈশিষ্ট্য; বৈশিষ্ট্যপূর্ণ', 'Kindness is her main characteristic.', 'দয়া তার প্রধান বৈশিষ্ট্য।', 80),
    ('chief', null, 'adj., n.', 'B2', 'প্রধান; প্রধান ব্যক্তি', 'He is the chief of the department.', 'তিনি বিভাগের প্রধান।', 81),
    ('circumstance', null, 'n.', 'B2', 'পরিস্থিতি, অবস্থা', 'Under these circumstances, we must wait.', 'এই পরিস্থিতিতে আমাদের অপেক্ষা করতে হবে।', 82),
    ('cite', null, 'v.', 'B2', 'উদ্ধৃত করা, উল্লেখ করা', 'She cited several examples.', 'সে কয়েকটি উদাহরণ উল্লেখ করল।', 83),
    ('citizen', null, 'n.', 'B2', 'নাগরিক', 'Every citizen has rights.', 'প্রত্যেক নাগরিকের অধিকার আছে।', 84),
    ('civil', null, 'adj.', 'B2', 'নাগরিক, বেসামরিক', 'They fought for civil rights.', 'তারা নাগরিক অধিকারের জন্য লড়াই করল।', 85),
    ('classic', null, 'adj., n.', 'B2', 'চিরায়ত, ধ্রুপদি; ক্লাসিক', 'This is a classic novel.', 'এটি একটি ধ্রুপদি উপন্যাস।', 86),
    ('closely', null, 'adv.', 'B2', 'ঘনিষ্ঠভাবে, নিবিড়ভাবে', 'Watch the demonstration closely.', 'প্রদর্শনীটি নিবিড়ভাবে দেখো।', 87),
    ('collapse', null, 'n., v.', 'B2', 'ধস, পতন; ভেঙে পড়া', 'The old bridge collapsed.', 'পুরনো সেতুটি ভেঙে পড়ল।', 88),
    ('combination', null, 'n.', 'B2', 'সংমিশ্রণ, মিলন', 'The dish is a combination of flavors.', 'খাবারটি নানা স্বাদের একটি সংমিশ্রণ।', 89),
    ('comfort', null, 'n., v.', 'B2', 'স্বস্তি, আরাম; সান্ত্বনা দেওয়া', 'She comforted the crying child.', 'সে কাঁদতে থাকা শিশুটিকে সান্ত্বনা দিল।', 90),
    ('command', null, 'n., v.', 'B2', 'আদেশ; আদেশ দেওয়া', 'The officer gave a command.', 'কর্মকর্তা একটি আদেশ দিলেন।', 91),
    ('commission', null, 'n., v.', 'B2', 'কমিশন; দায়িত্ব দেওয়া', 'The agent earns a commission.', 'এজেন্ট একটি কমিশন পান।', 92),
    ('commitment', null, 'n.', 'B2', 'অঙ্গীকার, প্রতিশ্রুতি', 'Marriage is a lifelong commitment.', 'বিবাহ একটি আজীবন অঙ্গীকার।', 93),
    ('committee', null, 'n.', 'B2', 'কমিটি, পরিষদ', 'The committee met on Monday.', 'কমিটিটি সোমবারে বৈঠক করল।', 94),
    ('commonly', null, 'adv.', 'B2', 'সাধারণত, প্রায়শই', 'This word is commonly used.', 'এই শব্দটি প্রায়শই ব্যবহৃত হয়।', 95),
    ('complicated', null, 'adj.', 'B2', 'জটিল, পেঁচানো', 'The instructions are too complicated.', 'নির্দেশনাগুলো খুব জটিল।', 96),
    ('component', null, 'n.', 'B2', 'উপাদান, অংশ', 'Each component has a purpose.', 'প্রতিটি উপাদানের একটি উদ্দেশ্য আছে।', 97),
    ('concentration', null, 'n.', 'B2', 'মনোযোগ, একাগ্রতা', 'The task requires concentration.', 'কাজটির জন্য মনোযোগ দরকার।', 98),
    ('concept', null, 'n.', 'B2', 'ধারণা, প্রত্যয়', 'This is a difficult concept.', 'এটি একটি কঠিন ধারণা।', 99),
    ('concern', null, 'n., v.', 'B2', 'উদ্বেগ, চিন্তা; সংশ্লিষ্ট থাকা', 'Safety is our main concern.', 'নিরাপত্তা আমাদের প্রধান উদ্বেগ।', 100),
    ('concerned', null, 'adj.', 'B2', 'উদ্বিগ্ন; সংশ্লিষ্ট', 'Parents are concerned about grades.', 'অভিভাবকরা ফলাফল নিয়ে উদ্বিগ্ন।', 101),
    ('conduct', null, 'n., v.', 'B2', 'আচরণ; পরিচালনা করা', 'They will conduct a survey.', 'তারা একটি জরিপ পরিচালনা করবে।', 102),
    ('confidence', null, 'n.', 'B2', 'আত্মবিশ্বাস', 'She spoke with confidence.', 'সে আত্মবিশ্বাসের সঙ্গে কথা বলল।', 103),
    ('conflict', null, 'n., v.', 'B2', 'দ্বন্দ্ব, সংঘাত; সংঘর্ষ হওয়া', 'There was a conflict between them.', 'তাদের মধ্যে একটি দ্বন্দ্ব ছিল।', 104),
    ('confusing', null, 'adj.', 'B2', 'বিভ্রান্তিকর', 'The map was very confusing.', 'মানচিত্রটি খুব বিভ্রান্তিকর ছিল।', 105),
    ('congress', null, 'n.', 'B2', 'কংগ্রেস, আইনসভা', 'Congress passed the new law.', 'কংগ্রেস নতুন আইনটি পাস করল।', 106),
    ('conscious', null, 'adj.', 'B2', 'সচেতন, সজ্ঞান', 'He was conscious during the operation.', 'অপারেশনের সময় সে সজ্ঞান ছিল।', 107),
    ('conservative', null, 'adj., n.', 'B2', 'রক্ষণশীল', 'He has conservative views.', 'তার রক্ষণশীল দৃষ্টিভঙ্গি আছে।', 108),
    ('consideration', null, 'n.', 'B2', 'বিবেচনা', 'Please give it careful consideration.', 'অনুগ্রহ করে এটি সতর্কভাবে বিবেচনা কর।', 109),
    ('consistent', null, 'adj.', 'B2', 'সামঞ্জস্যপূর্ণ, ধারাবাহিক', 'Her work is consistent.', 'তার কাজ ধারাবাহিক।', 110),
    ('constant', null, 'adj.', 'B2', 'অবিরাম, নিরন্তর', 'There was constant noise outside.', 'বাইরে অবিরাম শব্দ ছিল।', 111),
    ('constantly', null, 'adv.', 'B2', 'অবিরামভাবে, সর্বদা', 'He constantly checks his phone.', 'সে সর্বদা তার ফোন দেখে।', 112),
    ('construct', null, 'v.', 'B2', 'নির্মাণ করা', 'They will construct a new bridge.', 'তারা একটি নতুন সেতু নির্মাণ করবে।', 113),
    ('construction', null, 'n.', 'B2', 'নির্মাণ', 'The building is under construction.', 'ভবনটি নির্মাণাধীন।', 114),
    ('contemporary', null, 'adj.', 'B2', 'সমসাময়িক, আধুনিক', 'She likes contemporary art.', 'সে সমসাময়িক শিল্প পছন্দ করে।', 115),
    ('contest', null, 'n., v.', 'B2', 'প্রতিযোগিতা; প্রতিদ্বন্দ্বিতা করা', 'She won the singing contest.', 'সে গানের প্রতিযোগিতায় জিতল।', 116),
    ('contract', null, 'n., v.', 'B2', 'চুক্তি; সংকুচিত হওয়া', 'They signed a two-year contract.', 'তারা দুই বছরের একটি চুক্তি স্বাক্ষর করল।', 117),
    ('contribute', null, 'v.', 'B2', 'অবদান রাখা, দান করা', 'Everyone contributed some money.', 'সবাই কিছু টাকা দান করল।', 118),
    ('contribution', null, 'n.', 'B2', 'অবদান', 'Her contribution was valuable.', 'তার অবদান মূল্যবান ছিল।', 119),
    ('convert', null, 'v.', 'B2', 'রূপান্তর করা', 'They converted the barn into a house.', 'তারা গোলাঘরটিকে একটি বাড়িতে রূপান্তর করল।', 120),
    ('convinced', null, 'adj.', 'B2', 'নিশ্চিত, দৃঢ়প্রত্যয়ী', 'I am convinced that she is right.', 'আমি নিশ্চিত যে সে ঠিক।', 121),
    ('core', null, 'adj., n.', 'B2', 'মূল, কেন্দ্রস্থল', 'Honesty is at the core of trust.', 'সততা বিশ্বাসের মূলে রয়েছে।', 122),
    ('corporate', null, 'adj.', 'B2', 'কর্পোরেট, প্রাতিষ্ঠানিক', 'She works in the corporate world.', 'সে কর্পোরেট জগতে কাজ করে।', 123),
    ('council', null, 'n.', 'B2', 'পরিষদ, কাউন্সিল', 'The city council made a decision.', 'নগর পরিষদ একটি সিদ্ধান্ত নিল।', 124),
    ('county', null, 'n.', 'B2', 'কাউন্টি, প্রশাসনিক অঞ্চল', 'They live in a rural county.', 'তারা একটি গ্রামীণ কাউন্টিতে থাকে।', 125),
    ('courage', null, 'n.', 'B2', 'সাহস', 'It takes courage to speak up.', 'মুখ খুলে বলতে সাহস লাগে।', 126),
    ('crash', null, 'n., v.', 'B2', 'সংঘর্ষ, বিধ্বস্ত হওয়া; দুর্ঘটনা', 'The two cars crashed on the highway.', 'গাড়ি দুটি মহাসড়কে সংঘর্ষে জড়াল।', 127),
    ('creation', null, 'n.', 'B2', 'সৃষ্টি', 'The painting is her latest creation.', 'চিত্রকর্মটি তার সর্বশেষ সৃষ্টি।', 128),
    ('creature', null, 'n.', 'B2', 'প্রাণী, জীব', 'The sea is full of strange creatures.', 'সমুদ্র অদ্ভুত প্রাণীতে পূর্ণ।', 129),
    ('crew', null, 'n.', 'B2', 'কর্মীদল, নাবিকদল', 'The ship''s crew worked hard.', 'জাহাজের নাবিকদল কঠোর পরিশ্রম করল।', 130),
    ('crisis', null, 'n.', 'B2', 'সংকট', 'The country faced an economic crisis.', 'দেশটি একটি অর্থনৈতিক সংকটের মুখোমুখি হলো।', 131),
    ('criterion', null, 'n.', 'B2', 'মানদণ্ড, নির্ণায়ক', 'Price is not the only criterion.', 'দাম একমাত্র মানদণ্ড নয়।', 132),
    ('critic', null, 'n.', 'B2', 'সমালোচক', 'The film critic wrote a review.', 'চলচ্চিত্র সমালোচক একটি পর্যালোচনা লিখলেন।', 133),
    ('critical', null, 'adj.', 'B2', 'সংকটজনক; সমালোচনামূলক', 'The patient is in a critical condition.', 'রোগীটি সংকটজনক অবস্থায় আছে।', 134),
    ('criticism', null, 'n.', 'B2', 'সমালোচনা', 'She accepted the criticism calmly.', 'সে সমালোচনা শান্তভাবে মেনে নিল।', 135),
    ('criticize', null, 'v.', 'B2', 'সমালোচনা করা', 'Do not criticize others harshly.', 'অন্যদের কঠোরভাবে সমালোচনা করো না।', 136),
    ('crop', null, 'n.', 'B2', 'ফসল, শস্য', 'The farmers harvested the crop.', 'কৃষকরা ফসল কাটল।', 137),
    ('crucial', null, 'adj.', 'B2', 'অত্যন্ত গুরুত্বপূর্ণ, নির্ণায়ক', 'This is a crucial decision.', 'এটি একটি অত্যন্ত গুরুত্বপূর্ণ সিদ্ধান্ত।', 138),
    ('cure', null, 'n., v.', 'B2', 'নিরাময়; আরোগ্য করা', 'There is no cure for the common cold.', 'সাধারণ সর্দির কোনো নিরাময় নেই।', 139),
    ('curve', null, 'n., v.', 'B2', 'বক্ররেখা; বাঁক নেওয়া', 'The road has a sharp curve.', 'রাস্তাটিতে একটি তীক্ষ্ণ বাঁক আছে।', 140),
    ('curved', null, 'adj.', 'B2', 'বাঁকানো, বক্র', 'The bridge has a curved shape.', 'সেতুটির একটি বাঁকানো আকৃতি আছে।', 141),
    ('debate', null, 'n., v.', 'B2', 'বিতর্ক; বিতর্ক করা', 'They had a long debate.', 'তাদের মধ্যে একটি দীর্ঘ বিতর্ক হলো।', 142),
    ('debt', null, 'n.', 'B2', 'ঋণ, দেনা', 'He is trying to pay off his debt.', 'সে তার ঋণ পরিশোধের চেষ্টা করছে।', 143),
    ('decent', null, 'adj.', 'B2', 'শালীন, ভদ্র; মোটামুটি ভালো', 'They earn a decent salary.', 'তারা মোটামুটি ভালো বেতন পায়।', 144),
    ('declare', null, 'v.', 'B2', 'ঘোষণা করা', 'The judge declared the result.', 'বিচারক ফলাফল ঘোষণা করলেন।', 145),
    ('decline', null, 'n., v.', 'B2', 'পতন, হ্রাস; প্রত্যাখ্যান করা', 'Sales declined last month.', 'গত মাসে বিক্রি কমে গেল।', 146),
    ('decorate', null, 'v.', 'B2', 'সাজানো, অলংকৃত করা', 'They decorated the room with flowers.', 'তারা ঘরটি ফুল দিয়ে সাজাল।', 147),
    ('decoration', null, 'n.', 'B2', 'সাজসজ্জা, অলংকরণ', 'The party decorations looked lovely.', 'পার্টির সাজসজ্জা সুন্দর দেখাল।', 148),
    ('decrease', null, 'n., v.', 'B2', 'হ্রাস; কমা', 'The price decreased last week.', 'গত সপ্তাহে দাম কমল।', 149),
    ('deeply', null, 'adv.', 'B2', 'গভীরভাবে', 'She was deeply moved by the story.', 'গল্পটি তাকে গভীরভাবে নাড়া দিল।', 150),
    ('defeat', null, 'n., v.', 'B2', 'পরাজয়; পরাজিত করা', 'They defeated the strongest team.', 'তারা সবচেয়ে শক্তিশালী দলকে পরাজিত করল।', 151),
    ('defend', null, 'v.', 'B2', 'রক্ষা করা, পক্ষ সমর্থন করা', 'The soldiers defended the city.', 'সৈন্যরা শহরটি রক্ষা করল।', 152),
    ('defense', null, 'n.', 'B2', 'প্রতিরক্ষা, রক্ষা', 'The team has a strong defense.', 'দলটির একটি শক্তিশালী রক্ষণভাগ আছে।', 153),
    ('delay', null, 'n., v.', 'B2', 'বিলম্ব; দেরি করা', 'The flight was delayed by an hour.', 'ফ্লাইটটি এক ঘণ্টা দেরি হলো।', 154),
    ('deliberate', null, 'adj.', 'B2', 'ইচ্ছাকৃত, সুচিন্তিত', 'It was a deliberate mistake.', 'এটি একটি ইচ্ছাকৃত ভুল ছিল।', 155),
    ('deliberately', null, 'adv.', 'B2', 'ইচ্ছাকৃতভাবে', 'He deliberately ignored me.', 'সে ইচ্ছাকৃতভাবে আমাকে উপেক্ষা করল।', 156),
    ('delivery', null, 'n.', 'B2', 'সরবরাহ, পৌঁছে দেওয়া', 'The delivery will arrive tomorrow.', 'সরবরাহটি আগামীকাল পৌঁছাবে।', 157),
    ('demand', null, 'n., v.', 'B2', 'চাহিদা, দাবি; দাবি করা', 'There is a high demand for the product.', 'পণ্যটির প্রচুর চাহিদা আছে।', 158),
    ('demonstrate', null, 'v.', 'B2', 'প্রদর্শন করা, দেখানো', 'He demonstrated how to use it.', 'সে কীভাবে এটি ব্যবহার করতে হয় দেখাল।', 159),
    ('deny', null, 'v.', 'B2', 'অস্বীকার করা', 'She denied taking the money.', 'সে টাকা নেওয়ার কথা অস্বীকার করল।', 160),
    ('depressed', null, 'adj.', 'B2', 'বিষণ্ণ, হতাশ', 'He felt depressed after the loss.', 'ক্ষতির পর সে বিষণ্ণ বোধ করল।', 161),
    ('depressing', null, 'adj.', 'B2', 'বিষণ্ণকর, হতাশাজনক', 'The news was depressing.', 'খবরটি হতাশাজনক ছিল।', 162),
    ('depth', null, 'n.', 'B2', 'গভীরতা', 'What is the depth of the well?', 'কূপটির গভীরতা কত?', 163),
    ('deserve', null, 'v.', 'B2', 'প্রাপ্য হওয়া, যোগ্য হওয়া', 'You deserve a reward.', 'তুমি একটি পুরস্কার পাওয়ার যোগ্য।', 164),
    ('desire', null, 'n., v.', 'B2', 'আকাঙ্ক্ষা, ইচ্ছা; কামনা করা', 'She has a strong desire to learn.', 'তার শেখার প্রবল ইচ্ছা আছে।', 165),
    ('desperate', null, 'adj.', 'B2', 'মরিয়া, হতাশ', 'He was desperate for help.', 'সে সাহায্যের জন্য মরিয়া ছিল।', 166),
    ('detailed', null, 'adj.', 'B2', 'বিস্তারিত', 'She gave a detailed explanation.', 'সে একটি বিস্তারিত ব্যাখ্যা দিল।', 167),
    ('detect', null, 'v.', 'B2', 'শনাক্ত করা, ধরা পড়া', 'The device detects smoke.', 'যন্ত্রটি ধোঁয়া শনাক্ত করে।', 168),
    ('dig', null, 'v.', 'B2', 'খনন করা, খোঁড়া', 'They dug a hole in the garden.', 'তারা বাগানে একটি গর্ত খুঁড়ল।', 169),
    ('discipline', null, 'n.', 'B2', 'শৃঙ্খলা', 'Good discipline is important in school.', 'স্কুলে ভালো শৃঙ্খলা গুরুত্বপূর্ণ।', 170),
    ('dishonest', null, 'adj.', 'B2', 'অসৎ', 'It is dishonest to cheat.', 'প্রতারণা করা অসততা।', 171),
    ('disk', null, 'n.', 'B2', 'ডিস্ক, চাকতি', 'He saved the file on a disk.', 'সে ফাইলটি একটি ডিস্কে সংরক্ষণ করল।', 172),
    ('dismiss', null, 'v.', 'B2', 'বরখাস্ত করা; উড়িয়ে দেওয়া', 'The teacher dismissed the class.', 'শিক্ষক ক্লাস ছুটি দিলেন।', 173),
    ('display', null, 'n., v.', 'B2', 'প্রদর্শন; প্রদর্শন করা', 'The shop displayed new clothes.', 'দোকানটি নতুন পোশাক প্রদর্শন করল।', 174),
    ('distribute', null, 'v.', 'B2', 'বিতরণ করা', 'They distributed food to the poor.', 'তারা দরিদ্রদের মধ্যে খাবার বিতরণ করল।', 175),
    ('distribution', null, 'n.', 'B2', 'বিতরণ, বণ্টন', 'The distribution of aid was fair.', 'ত্রাণের বণ্টন ন্যায্য ছিল।', 176),
    ('division', null, 'n.', 'B2', 'বিভাগ; ভাগ', 'He works in the sales division.', 'সে বিক্রয় বিভাগে কাজ করে।', 177),
    ('domestic', null, 'adj.', 'B2', 'গার্হস্থ্য, অভ্যন্তরীণ', 'They took a domestic flight.', 'তারা একটি অভ্যন্তরীণ ফ্লাইট নিল।', 178),
    ('dominate', null, 'v.', 'B2', 'আধিপত্য বিস্তার করা', 'One team dominated the match.', 'একটি দল খেলায় আধিপত্য বিস্তার করল।', 179),
    ('downward', null, 'adv., adj.', 'B2', 'নিম্নমুখী, নিচের দিকে', 'Prices moved downward.', 'দাম নিম্নমুখী হলো।', 180),
    ('dozen', null, 'det., n.', 'B2', 'ডজন, বারোটি', 'She bought a dozen eggs.', 'সে এক ডজন ডিম কিনল।', 181),
    ('draft', null, 'n., v.', 'B2', 'খসড়া; খসড়া করা', 'He wrote a first draft of the essay.', 'সে প্রবন্ধটির একটি প্রথম খসড়া লিখল।', 182),
    ('drag', null, 'v.', 'B2', 'টেনে নেওয়া, হেঁচড়ানো', 'He dragged the heavy box.', 'সে ভারী বাক্সটি টেনে নিল।', 183),
    ('dramatic', null, 'adj.', 'B2', 'নাটকীয়', 'There was a dramatic change.', 'একটি নাটকীয় পরিবর্তন হলো।', 184),
    ('edit', null, 'v.', 'B2', 'সম্পাদনা করা', 'Please edit this document.', 'অনুগ্রহ করে এই নথিটি সম্পাদনা কর।', 185),
    ('edition', null, 'n.', 'B2', 'সংস্করণ', 'This is the first edition of the book.', 'এটি বইটির প্রথম সংস্করণ।', 186),
    ('efficient', null, 'adj.', 'B2', 'দক্ষ, কার্যকর', 'She is an efficient worker.', 'সে একজন দক্ষ কর্মী।', 187),
    ('elderly', null, 'adj.', 'B2', 'বয়স্ক, প্রবীণ', 'We should help elderly people.', 'আমাদের বয়স্ক মানুষদের সাহায্য করা উচিত।', 188),
    ('elect', null, 'v.', 'B2', 'নির্বাচিত করা', 'They elected a new leader.', 'তারা একজন নতুন নেতা নির্বাচিত করল।', 189),
    ('elsewhere', null, 'adv.', 'B2', 'অন্য কোথাও', 'If it is closed, we will eat elsewhere.', 'বন্ধ থাকলে, আমরা অন্য কোথাও খাব।', 190),
    ('emerge', null, 'v.', 'B2', 'আবির্ভূত হওয়া, বেরিয়ে আসা', 'The sun emerged from the clouds.', 'সূর্য মেঘ থেকে বেরিয়ে এল।', 191),
    ('emotional', null, 'adj.', 'B2', 'আবেগপ্রবণ, আবেগময়', 'It was an emotional farewell.', 'এটি একটি আবেগময় বিদায় ছিল।', 192),
    ('emphasis', null, 'n.', 'B2', 'জোর, গুরুত্ব', 'They put emphasis on safety.', 'তারা নিরাপত্তার উপর জোর দিল।', 193),
    ('emphasize', null, 'v.', 'B2', 'জোর দেওয়া', 'She emphasized the main point.', 'সে মূল বিষয়টির উপর জোর দিল।', 194),
    ('enable', null, 'v.', 'B2', 'সক্ষম করা, সুযোগ দেওয়া', 'This tool enables faster work.', 'এই যন্ত্রটি দ্রুত কাজ করতে সক্ষম করে।', 195),
    ('encounter', null, 'n., v.', 'B2', 'সাক্ষাৎ, মুখোমুখি হওয়া', 'We encountered many problems.', 'আমরা অনেক সমস্যার মুখোমুখি হলাম।', 196),
    ('engage', null, 'v.', 'B2', 'নিযুক্ত করা, জড়িত করা', 'The teacher engaged the students.', 'শিক্ষক শিক্ষার্থীদের সম্পৃক্ত করলেন।', 197),
    ('enhance', null, 'v.', 'B2', 'বৃদ্ধি করা, উন্নত করা', 'Music can enhance your mood.', 'সংগীত তোমার মেজাজ উন্নত করতে পারে।', 198),
    ('ensure', null, 'v.', 'B2', 'নিশ্চিত করা', 'Please ensure the door is locked.', 'অনুগ্রহ করে দরজাটি তালাবদ্ধ কিনা নিশ্চিত কর।', 199),
    ('enthusiasm', null, 'n.', 'B2', 'উৎসাহ, উদ্দীপনা', 'She spoke with great enthusiasm.', 'সে দারুণ উৎসাহের সঙ্গে কথা বলল।', 200),
    ('enthusiastic', null, 'adj.', 'B2', 'উৎসাহী', 'The students were enthusiastic.', 'শিক্ষার্থীরা উৎসাহী ছিল।', 201),
    ('entire', null, 'adj.', 'B2', 'সম্পূর্ণ, সমগ্র', 'She read the entire book in a day.', 'সে একদিনে পুরো বইটি পড়ল।', 202),
    ('entirely', null, 'adv.', 'B2', 'সম্পূর্ণভাবে', 'I entirely agree with you.', 'আমি তোমার সঙ্গে সম্পূর্ণভাবে একমত।', 203),
    ('establish', null, 'v.', 'B2', 'প্রতিষ্ঠা করা', 'They established a new school.', 'তারা একটি নতুন স্কুল প্রতিষ্ঠা করল।', 204),
    ('estate', null, 'n.', 'B2', 'সম্পত্তি, ভূসম্পত্তি', 'He owns a large estate.', 'তার একটি বিশাল ভূসম্পত্তি আছে।', 205),
    ('estimate', null, 'n., v.', 'B2', 'অনুমান, প্রাক্কলন; আনুমানিক হিসাব করা', 'They estimated the cost at $500.', 'তারা খরচ ৫০০ ডলার অনুমান করল।', 206),
    ('ethical', null, 'adj.', 'B2', 'নৈতিক', 'This raises an ethical question.', 'এটি একটি নৈতিক প্রশ্ন তোলে।', 207),
    ('evaluate', null, 'v.', 'B2', 'মূল্যায়ন করা', 'We need to evaluate the results.', 'আমাদের ফলাফল মূল্যায়ন করতে হবে।', 208),
    ('evil', null, 'adj., n.', 'B2', 'অশুভ, মন্দ; অমঙ্গল', 'The story is about good and evil.', 'গল্পটি ভালো ও মন্দ নিয়ে।', 209),
    ('examination', null, 'n.', 'B2', 'পরীক্ষা, নিরীক্ষা', 'The doctor did a careful examination.', 'ডাক্তার একটি সতর্ক পরীক্ষা করলেন।', 210),
    ('excuse', null, 'n., v.', 'B2', 'অজুহাত; ক্ষমা করা', 'That is no excuse for being late.', 'দেরি করার জন্য এটা কোনো অজুহাত নয়।', 211),
    ('executive', null, 'adj., n.', 'B2', 'নির্বাহী; নির্বাহী কর্মকর্তা', 'She is a business executive.', 'সে একজন ব্যবসায়িক নির্বাহী।', 212),
    ('exhibit', null, 'n., v.', 'B2', 'প্রদর্শনী; প্রদর্শন করা', 'The museum exhibits old coins.', 'জাদুঘরটি পুরনো মুদ্রা প্রদর্শন করে।', 213),
    ('existence', null, 'n.', 'B2', 'অস্তিত্ব', 'They believe in the existence of aliens.', 'তারা ভিনগ্রহীদের অস্তিত্বে বিশ্বাস করে।', 214),
    ('expectation', null, 'n.', 'B2', 'প্রত্যাশা', 'The result met our expectations.', 'ফলাফল আমাদের প্রত্যাশা পূরণ করল।', 215),
    ('expense', null, 'n.', 'B2', 'ব্যয়, খরচ', 'Travel is a big expense.', 'ভ্রমণ একটি বড় খরচ।', 216),
    ('exploration', null, 'n.', 'B2', 'অনুসন্ধান, অভিযান', 'Space exploration is expensive.', 'মহাকাশ অভিযান ব্যয়বহুল।', 217),
    ('expose', null, 'v.', 'B2', 'উন্মোচন করা, প্রকাশ করা', 'The report exposed the truth.', 'প্রতিবেদনটি সত্য উন্মোচন করল।', 218),
    ('extend', null, 'v.', 'B2', 'প্রসারিত করা, বাড়ানো', 'They extended the deadline.', 'তারা সময়সীমা বাড়াল।', 219),
    ('extent', null, 'n.', 'B2', 'পরিমাণ, ব্যাপ্তি', 'To some extent, I agree.', 'কিছুটা পরিমাণে, আমি একমত।', 220),
    ('external', null, 'adj.', 'B2', 'বাহ্যিক, বহিঃস্থ', 'The medicine is for external use.', 'ওষুধটি বাহ্যিক ব্যবহারের জন্য।', 221),
    ('extraordinary', null, 'adj.', 'B2', 'অসাধারণ', 'She has an extraordinary memory.', 'তার একটি অসাধারণ স্মৃতিশক্তি আছে।', 222),
    ('facility', null, 'n.', 'B2', 'সুবিধা, স্থাপনা', 'The gym has modern facilities.', 'জিমটিতে আধুনিক সুবিধা আছে।', 223),
    ('failure', null, 'n.', 'B2', 'ব্যর্থতা', 'Failure is part of learning.', 'ব্যর্থতা শেখার একটি অংশ।', 224),
    ('faith', null, 'n.', 'B2', 'বিশ্বাস, আস্থা', 'She has faith in her team.', 'তার দলের উপর আস্থা আছে।', 225),
    ('fault', null, 'n.', 'B2', 'দোষ, ত্রুটি', 'It was not my fault.', 'এটা আমার দোষ ছিল না।', 226),
    ('feather', null, 'n.', 'B2', 'পালক', 'A bird''s feather fell on the ground.', 'একটি পাখির পালক মাটিতে পড়ল।', 227),
    ('fee', null, 'n.', 'B2', 'ফি, মাশুল', 'The entry fee is ten dollars.', 'প্রবেশ ফি দশ ডলার।', 228),
    ('feedback', null, 'n.', 'B2', 'প্রতিক্রিয়া, মতামত', 'The teacher gave helpful feedback.', 'শিক্ষক সহায়ক মতামত দিলেন।', 229),
    ('fellow', null, 'adj.', 'B2', 'সহযোগী, সহকর্মী', 'He helped his fellow students.', 'সে তার সহপাঠীদের সাহায্য করল।', 230),
    ('finance', null, 'n., v.', 'B2', 'অর্থব্যবস্থা, অর্থায়ন; অর্থ জোগানো', 'She studies finance at college.', 'সে কলেজে অর্থব্যবস্থা পড়ছে।', 231),
    ('finding', null, 'n.', 'B2', 'অনুসন্ধানলব্ধ ফল, সিদ্ধান্ত', 'The study''s findings were clear.', 'গবেষণার ফলাফল স্পষ্ট ছিল।', 232),
    ('firm', null, 'n.', 'B2', 'প্রতিষ্ঠান, কোম্পানি', 'She works for a law firm.', 'সে একটি আইনি প্রতিষ্ঠানে কাজ করে।', 233),
    ('flame', null, 'n.', 'B2', 'শিখা, অগ্নিশিখা', 'The candle flame flickered.', 'মোমবাতির শিখা কেঁপে উঠল।', 234),
    ('flash', null, 'n., v.', 'B2', 'ঝলক; ঝলসে ওঠা', 'A flash of lightning lit the sky.', 'বিদ্যুতের একটি ঝলক আকাশ আলোকিত করল।', 235),
    ('flexible', null, 'adj.', 'B2', 'নমনীয়', 'My schedule is flexible.', 'আমার সময়সূচি নমনীয়।', 236),
    ('float', null, 'v.', 'B2', 'ভেসে থাকা, ভাসা', 'The boat floated on the water.', 'নৌকাটি পানিতে ভেসে থাকল।', 237),
    ('folding', null, 'adj.', 'B2', 'ভাঁজযোগ্য', 'They brought folding chairs.', 'তারা ভাঁজযোগ্য চেয়ার নিয়ে এল।', 238),
    ('forgive', null, 'v.', 'B2', 'ক্ষমা করা', 'Please forgive me for my mistake.', 'অনুগ্রহ করে আমার ভুলের জন্য আমাকে ক্ষমা কর।', 239),
    ('former', null, 'adj.', 'B2', 'প্রাক্তন, পূর্বতন', 'He is a former teacher.', 'তিনি একজন প্রাক্তন শিক্ষক।', 240),
    ('fortune', null, 'n.', 'B2', 'সৌভাগ্য; বিপুল সম্পদ', 'He made a fortune in business.', 'সে ব্যবসায় বিপুল সম্পদ গড়ল।', 241),
    ('found', null, 'v.', 'B2', 'প্রতিষ্ঠা করা, স্থাপন করা', 'They founded the company in 1990.', 'তারা ১৯৯০ সালে কোম্পানিটি প্রতিষ্ঠা করল।', 242),
    ('freedom', null, 'n.', 'B2', 'স্বাধীনতা, মুক্তি', 'People value their freedom.', 'মানুষ তাদের স্বাধীনতাকে মূল্য দেয়।', 243),
    ('frequency', null, 'n.', 'B2', 'কম্পাঙ্ক; পুনরাবৃত্তির হার', 'The frequency of storms increased.', 'ঝড়ের পুনরাবৃত্তির হার বেড়ে গেল।', 244),
    ('fully', null, 'adv.', 'B2', 'সম্পূর্ণরূপে, পুরোপুরি', 'I fully understand the problem.', 'আমি সমস্যাটি পুরোপুরি বুঝি।', 245),
    ('fund', null, 'n., v.', 'B2', 'তহবিল; অর্থ জোগানো', 'The government funds the project.', 'সরকার প্রকল্পটিতে অর্থ জোগায়।', 246),
    ('fundamental', null, 'adj.', 'B2', 'মৌলিক, প্রাথমিক', 'This is a fundamental rule.', 'এটি একটি মৌলিক নিয়ম।', 247),
    ('funding', null, 'n.', 'B2', 'অর্থায়ন, তহবিল সরবরাহ', 'The school needs more funding.', 'স্কুলটির আরও অর্থায়ন দরকার।', 248),
    ('furthermore', null, 'adv.', 'B2', 'অধিকন্তু, তদুপরি', 'Furthermore, the plan is cheap.', 'অধিকন্তু, পরিকল্পনাটি সস্তা।', 249),
    ('gain', null, 'n., v.', 'B2', 'লাভ; অর্জন করা', 'She gained a lot of experience.', 'সে অনেক অভিজ্ঞতা অর্জন করল।', 250),
    ('gang', null, 'n.', 'B2', 'দল, চক্র', 'A gang of thieves robbed the shop.', 'একদল চোর দোকানটি লুট করল।', 251),
    ('generate', null, 'v.', 'B2', 'উৎপন্ন করা, সৃষ্টি করা', 'Wind can generate electricity.', 'বাতাস বিদ্যুৎ উৎপন্ন করতে পারে।', 252),
    ('genre', null, 'n.', 'B2', 'ধরন, ঘরানা', 'Comedy is my favorite genre.', 'কমেডি আমার প্রিয় ঘরানা।', 253),
    ('goods', null, 'n.', 'B2', 'পণ্য, মালামাল', 'The truck carried goods to the city.', 'ট্রাকটি শহরে পণ্য বহন করল।', 254),
    ('govern', null, 'v.', 'B2', 'শাসন করা, পরিচালনা করা', 'Clear rules govern the game.', 'স্পষ্ট নিয়ম খেলাটি পরিচালনা করে।', 255),
    ('governor', null, 'n.', 'B2', 'গভর্নর, রাজ্যপাল', 'The governor visited the town.', 'গভর্নর শহরটি পরিদর্শন করলেন।', 256),
    ('grab', null, 'v.', 'B2', 'খপ করে ধরা, ছোঁ মারা', 'He grabbed my arm suddenly.', 'সে হঠাৎ আমার হাত খপ করে ধরল।', 257),
    ('gradually', null, 'adv.', 'B2', 'ধীরে ধীরে, ক্রমশ', 'The weather gradually got warmer.', 'আবহাওয়া ধীরে ধীরে উষ্ণ হলো।', 258),
    ('grand', null, 'adj.', 'B2', 'বিশাল, জমকালো', 'They live in a grand house.', 'তারা একটি জমকালো বাড়িতে থাকে।', 259),
    ('grant', null, 'n., v.', 'B2', 'অনুদান; মঞ্জুর করা', 'She received a research grant.', 'সে একটি গবেষণা অনুদান পেল।', 260),
    ('guarantee', null, 'n., v.', 'B2', 'নিশ্চয়তা, ওয়ারেন্টি; নিশ্চয়তা দেওয়া', 'The product has a one-year guarantee.', 'পণ্যটির এক বছরের নিশ্চয়তা আছে।', 261),
    ('handle', null, 'n., v.', 'B2', 'হাতল; সামলানো, নিয়ন্ত্রণ করা', 'She handled the situation well.', 'সে পরিস্থিতিটি ভালোভাবে সামলাল।', 262),
    ('harm', null, 'n., v.', 'B2', 'ক্ষতি; ক্ষতি করা', 'The chemical can harm your skin.', 'রাসায়নিকটি তোমার ত্বকের ক্ষতি করতে পারে।', 263),
    ('harmful', null, 'adj.', 'B2', 'ক্ষতিকর', 'Too much sun is harmful.', 'অতিরিক্ত রোদ ক্ষতিকর।', 264),
    ('hearing', null, 'n.', 'B2', 'শ্রবণশক্তি; শুনানি', 'His hearing is not good.', 'তার শ্রবণশক্তি ভালো নয়।', 265),
    ('heaven', null, 'n.', 'B2', 'স্বর্গ', 'They believe in heaven.', 'তারা স্বর্গে বিশ্বাস করে।', 266),
    ('heel', null, 'n.', 'B2', 'গোড়ালি', 'My shoe hurts my heel.', 'আমার জুতা গোড়ালিতে ব্যথা দিচ্ছে।', 267),
    ('hell', null, 'n.', 'B2', 'নরক', 'The story describes heaven and hell.', 'গল্পটি স্বর্গ ও নরকের বর্ণনা দেয়।', 268),
    ('hesitate', null, 'v.', 'B2', 'দ্বিধা করা, ইতস্তত করা', 'Do not hesitate to ask questions.', 'প্রশ্ন করতে দ্বিধা করো না।', 269),
    ('hollow', null, 'adj.', 'B2', 'ফাঁপা', 'The tree trunk was hollow.', 'গাছের গুঁড়িটি ফাঁপা ছিল।', 270),
    ('holy', null, 'adj.', 'B2', 'পবিত্র', 'They visited a holy place.', 'তারা একটি পবিত্র স্থান পরিদর্শন করল।', 271),
    ('honor', null, 'n., v.', 'B2', 'সম্মান, মর্যাদা; সম্মান করা', 'It is an honor to meet you.', 'তোমার সঙ্গে দেখা করা একটি সম্মানের বিষয়।', 272),
    ('household', null, 'n.', 'B2', 'পরিবার, গৃহস্থালি', 'Every household needs water.', 'প্রতিটি পরিবারের পানি দরকার।', 273),
    ('housing', null, 'n.', 'B2', 'আবাসন, বাসস্থান', 'Housing is expensive in the city.', 'শহরে আবাসন ব্যয়বহুল।', 274),
    ('humor', null, 'n.', 'B2', 'রসবোধ, হাস্যরস', 'He has a great sense of humor.', 'তার দারুণ রসবোধ আছে।', 275),
    ('humorous', null, 'adj.', 'B2', 'হাস্যরসাত্মক, মজার', 'She told a humorous story.', 'সে একটি মজার গল্প বলল।', 276),
    ('hunting', null, 'n.', 'B2', 'শিকার', 'Hunting is banned in this forest.', 'এই বনে শিকার নিষিদ্ধ।', 277),
    ('illustrate', null, 'v.', 'B2', 'চিত্রিত করা, দৃষ্টান্ত দিয়ে বোঝানো', 'The example illustrates the rule.', 'উদাহরণটি নিয়মটি বোঝায়।', 278),
    ('illustration', null, 'n.', 'B2', 'চিত্র, দৃষ্টান্ত', 'The book has colorful illustrations.', 'বইটিতে রঙিন চিত্র আছে।', 279),
    ('imagination', null, 'n.', 'B2', 'কল্পনাশক্তি', 'Children have a vivid imagination.', 'শিশুদের প্রাণবন্ত কল্পনাশক্তি আছে।', 280),
    ('impatient', null, 'adj.', 'B2', 'অধৈর্য', 'He was impatient to leave.', 'সে যাওয়ার জন্য অধৈর্য ছিল।', 281),
    ('imply', null, 'v.', 'B2', 'ইঙ্গিত করা, বোঝানো', 'Her tone implied anger.', 'তার কণ্ঠস্বর রাগের ইঙ্গিত দিল।', 282),
    ('impose', null, 'v.', 'B2', 'আরোপ করা, চাপিয়ে দেওয়া', 'They imposed a new tax.', 'তারা একটি নতুন কর আরোপ করল।', 283),
    ('impress', null, 'v.', 'B2', 'মুগ্ধ করা, প্রভাবিত করা', 'Her speech impressed everyone.', 'তার বক্তৃতা সবাইকে মুগ্ধ করল।', 284),
    ('impressed', null, 'adj.', 'B2', 'মুগ্ধ, প্রভাবিত', 'I was impressed by his work.', 'তার কাজ দেখে আমি মুগ্ধ হলাম।', 285),
    ('inch', null, 'n.', 'B2', 'ইঞ্চি (দৈর্ঘ্যের একক)', 'The nail is two inches long.', 'পেরেকটি দুই ইঞ্চি লম্বা।', 286),
    ('incident', null, 'n.', 'B2', 'ঘটনা', 'The incident was reported to the police.', 'ঘটনাটি পুলিশে জানানো হলো।', 287),
    ('income', null, 'n.', 'B2', 'আয়, উপার্জন', 'Their income is quite low.', 'তাদের আয় বেশ কম।', 288),
    ('increasingly', null, 'adv.', 'B2', 'ক্রমবর্ধমানভাবে', 'It is increasingly difficult to find work.', 'কাজ খুঁজে পাওয়া ক্রমশ কঠিন হচ্ছে।', 289),
    ('industrial', null, 'adj.', 'B2', 'শিল্পসংক্রান্ত, শিল্পোন্নত', 'This is an industrial area.', 'এটি একটি শিল্প এলাকা।', 290),
    ('infection', null, 'n.', 'B2', 'সংক্রমণ', 'Wash the wound to prevent infection.', 'সংক্রমণ ঠেকাতে ক্ষতটি ধুয়ে ফেলো।', 291),
    ('inform', null, 'v.', 'B2', 'জানানো, অবহিত করা', 'Please inform me of any changes.', 'অনুগ্রহ করে কোনো পরিবর্তন হলে আমাকে জানিও।', 292),
    ('initial', null, 'adj.', 'B2', 'প্রাথমিক, শুরুর', 'The initial plan was different.', 'প্রাথমিক পরিকল্পনাটি ভিন্ন ছিল।', 293),
    ('initially', null, 'adv.', 'B2', 'প্রথমে, শুরুতে', 'Initially, she was nervous.', 'শুরুতে, সে নার্ভাস ছিল।', 294),
    ('initiative', null, 'n.', 'B2', 'উদ্যোগ', 'She took the initiative to help.', 'সে সাহায্যের উদ্যোগ নিল।', 295),
    ('inner', null, 'adj.', 'B2', 'অভ্যন্তরীণ, ভেতরের', 'The inner room was dark.', 'ভেতরের ঘরটি অন্ধকার ছিল।', 296),
    ('inquiry', null, 'n.', 'B2', 'অনুসন্ধান, জিজ্ঞাসা', 'They started an inquiry into the crash.', 'তারা দুর্ঘটনাটির তদন্ত শুরু করল।', 297),
    ('insight', null, 'n.', 'B2', 'অন্তর্দৃষ্টি, গভীর উপলব্ধি', 'The book gives insight into history.', 'বইটি ইতিহাস সম্পর্কে গভীর উপলব্ধি দেয়।', 298),
    ('insist', null, 'v.', 'B2', 'জোর দেওয়া, পীড়াপীড়ি করা', 'She insisted on paying the bill.', 'সে বিল পরিশোধ করার জন্য পীড়াপীড়ি করল।', 299),
    ('inspire', null, 'v.', 'B2', 'অনুপ্রাণিত করা', 'Her story inspired many people.', 'তার গল্প অনেক মানুষকে অনুপ্রাণিত করল।', 300),
    ('install', null, 'v.', 'B2', 'স্থাপন করা, ইনস্টল করা', 'They installed a new fan.', 'তারা একটি নতুন পাখা স্থাপন করল।', 301),
    ('instance', null, 'n.', 'B2', 'উদাহরণ, দৃষ্টান্ত', 'For instance, take this case.', 'উদাহরণস্বরূপ, এই ঘটনাটি ধরো।', 302),
    ('institute', null, 'n.', 'B2', 'প্রতিষ্ঠান, ইনস্টিটিউট', 'He studies at a research institute.', 'সে একটি গবেষণা প্রতিষ্ঠানে পড়ে।', 303),
    ('institution', null, 'n.', 'B2', 'প্রতিষ্ঠান', 'Banks are financial institutions.', 'ব্যাংক হলো আর্থিক প্রতিষ্ঠান।', 304),
    ('insurance', null, 'n.', 'B2', 'বিমা', 'He bought health insurance.', 'সে স্বাস্থ্য বিমা কিনল।', 305),
    ('intended', null, 'adj.', 'B2', 'উদ্দিষ্ট, অভিপ্রেত', 'This book is intended for children.', 'এই বইটি শিশুদের জন্য উদ্দিষ্ট।', 306),
    ('intense', null, 'adj.', 'B2', 'তীব্র, প্রবল', 'The heat was intense today.', 'আজ গরম তীব্র ছিল।', 307),
    ('internal', null, 'adj.', 'B2', 'অভ্যন্তরীণ', 'The company made internal changes.', 'কোম্পানিটি অভ্যন্তরীণ পরিবর্তন আনল।', 308),
    ('interpret', null, 'v.', 'B2', 'ব্যাখ্যা করা; অনুবাদ করা', 'How do you interpret this poem?', 'তুমি এই কবিতাটি কীভাবে ব্যাখ্যা কর?', 309),
    ('interrupt', null, 'v.', 'B2', 'বাধা দেওয়া, ব্যাঘাত ঘটানো', 'Please do not interrupt me.', 'অনুগ্রহ করে আমাকে বাধা দিও না।', 310),
    ('investigation', null, 'n.', 'B2', 'তদন্ত', 'The investigation lasted a month.', 'তদন্তটি এক মাস ধরে চলল।', 311),
    ('investment', null, 'n.', 'B2', 'বিনিয়োগ', 'Education is a good investment.', 'শিক্ষা একটি ভালো বিনিয়োগ।', 312),
    ('joy', null, 'n.', 'B2', 'আনন্দ, খুশি', 'The news brought her great joy.', 'খবরটি তাকে দারুণ আনন্দ দিল।', 313),
    ('judgment', null, 'n.', 'B2', 'বিচার, রায়; বিচারবুদ্ধি', 'I trust her judgment.', 'আমি তার বিচারবুদ্ধিকে বিশ্বাস করি।', 314),
    ('junior', null, 'adj.', 'B2', 'কনিষ্ঠ, নিম্নপদস্থ', 'He is a junior member of the team.', 'সে দলের একজন কনিষ্ঠ সদস্য।', 315),
    ('justice', null, 'n.', 'B2', 'ন্যায়বিচার', 'They fought for justice.', 'তারা ন্যায়বিচারের জন্য লড়াই করল।', 316),
    ('justify', null, 'v.', 'B2', 'যুক্তিসঙ্গত প্রমাণ করা, সাফাই দেওয়া', 'Nothing can justify violence.', 'কোনো কিছুই সহিংসতাকে যুক্তিসঙ্গত করতে পারে না।', 317),
    ('labor', null, 'n.', 'B2', 'শ্রম, পরিশ্রম', 'The job requires hard labor.', 'কাজটির জন্য কঠোর পরিশ্রম দরকার।', 318),
    ('landscape', null, 'n.', 'B2', 'ভূদৃশ্য, প্রাকৃতিক দৃশ্য', 'The mountain landscape was stunning.', 'পাহাড়ি ভূদৃশ্যটি অপূর্ব ছিল।', 319),
    ('largely', null, 'adv.', 'B2', 'অনেকাংশে, প্রধানত', 'The success was largely due to luck.', 'সাফল্যটি অনেকাংশে ভাগ্যের কারণে।', 320),
    ('launch', null, 'n., v.', 'B2', 'উদ্বোধন, সূচনা; চালু করা', 'They will launch a new product.', 'তারা একটি নতুন পণ্য চালু করবে।', 321),
    ('leadership', null, 'n.', 'B2', 'নেতৃত্ব', 'The team needs strong leadership.', 'দলটির শক্তিশালী নেতৃত্ব দরকার।', 322),
    ('league', null, 'n.', 'B2', 'লিগ, সংঘ', 'Their team plays in the top league.', 'তাদের দল শীর্ষ লিগে খেলে।', 323),
    ('lean', null, 'v.', 'B2', 'হেলান দেওয়া, ঝোঁকা', 'He leaned against the wall.', 'সে দেয়ালে হেলান দিল।', 324),
    ('license', null, 'n.', 'B2', 'লাইসেন্স, অনুমতিপত্র', 'You need a license to drive.', 'গাড়ি চালাতে তোমার একটি লাইসেন্স দরকার।', 325),
    ('limited', null, 'adj.', 'B2', 'সীমিত', 'We have limited time.', 'আমাদের সীমিত সময় আছে।', 326),
    ('lively', null, 'adj.', 'B2', 'প্রাণবন্ত, সজীব', 'It was a lively party.', 'এটি একটি প্রাণবন্ত পার্টি ছিল।', 327),
    ('load', null, 'n., v.', 'B2', 'বোঝা, ভার; বোঝাই করা', 'They loaded the boxes onto the truck.', 'তারা বাক্সগুলো ট্রাকে বোঝাই করল।', 328),
    ('loan', null, 'n.', 'B2', 'ঋণ, ধার', 'He took a loan to buy a car.', 'সে গাড়ি কিনতে একটি ঋণ নিল।', 329),
    ('logical', null, 'adj.', 'B2', 'যুক্তিসঙ্গত, যৌক্তিক', 'That is a logical conclusion.', 'এটি একটি যৌক্তিক সিদ্ধান্ত।', 330),
    ('long-term', null, 'adv., adj.', 'B2', 'দীর্ঘমেয়াদি', 'They have a long-term plan.', 'তাদের একটি দীর্ঘমেয়াদি পরিকল্পনা আছে।', 331),
    ('loose', null, 'adj.', 'B2', 'ঢিলা, আলগা', 'This shirt is too loose.', 'এই শার্টটি খুব ঢিলা।', 332),
    ('lord', null, 'n.', 'B2', 'প্রভু; সম্ভ্রান্ত ব্যক্তি', 'The people prayed to their lord.', 'লোকজন তাদের প্রভুর কাছে প্রার্থনা করল।', 333),
    ('lower', null, 'v.', 'B2', 'নামানো, কমানো', 'Please lower your voice.', 'অনুগ্রহ করে তোমার গলা নামাও।', 334),
    ('lung', null, 'n.', 'B2', 'ফুসফুস', 'Smoking damages the lungs.', 'ধূমপান ফুসফুসের ক্ষতি করে।', 335),
    ('maintain', null, 'v.', 'B2', 'বজায় রাখা; রক্ষণাবেক্ষণ করা', 'It is hard to maintain a garden.', 'একটি বাগান রক্ষণাবেক্ষণ করা কঠিন।', 336),
    ('majority', null, 'n.', 'B2', 'সংখ্যাগরিষ্ঠতা, অধিকাংশ', 'The majority voted for the plan.', 'অধিকাংশ মানুষ পরিকল্পনাটির পক্ষে ভোট দিল।', 337),
    ('mass', null, 'adj., n.', 'B2', 'ভর; বিশাল সমষ্টি, গণ', 'There was a mass of people at the gate.', 'ফটকের কাছে বিশাল জনসমাগম ছিল।', 338),
    ('massive', null, 'adj.', 'B2', 'বিশাল, প্রকাণ্ড', 'They built a massive stadium.', 'তারা একটি বিশাল স্টেডিয়াম বানাল।', 339),
    ('master', null, 'n., v.', 'B2', 'গুরু, দক্ষ ব্যক্তি; আয়ত্ত করা', 'She mastered three languages.', 'সে তিনটি ভাষা আয়ত্ত করল।', 340),
    ('matching', null, 'adj.', 'B2', 'মানানসই, সদৃশ', 'They wore matching shirts.', 'তারা মানানসই শার্ট পরল।', 341),
    ('maximum', null, 'adj., n.', 'B2', 'সর্বাধিক, সর্বোচ্চ', 'The maximum speed is 100.', 'সর্বোচ্চ গতি ১০০।', 342),
    ('means', null, 'n.', 'B2', 'উপায়, মাধ্যম', 'A car is a means of transport.', 'গাড়ি একটি পরিবহনের মাধ্যম।', 343),
    ('measurement', null, 'n.', 'B2', 'পরিমাপ', 'Take the measurements of the room.', 'ঘরটির পরিমাপ নাও।', 344),
    ('melt', null, 'v.', 'B2', 'গলা, গলে যাওয়া', 'The ice melted in the sun.', 'বরফ রোদে গলে গেল।', 345),
    ('military', null, 'adj., n.', 'B2', 'সামরিক; সেনাবাহিনী', 'He joined the military.', 'সে সেনাবাহিনীতে যোগ দিল।', 346),
    ('mineral', null, 'n.', 'B2', 'খনিজ পদার্থ', 'Milk contains useful minerals.', 'দুধে দরকারি খনিজ পদার্থ থাকে।', 347),
    ('minimum', null, 'adj., n.', 'B2', 'ন্যূনতম, সর্বনিম্ন', 'The minimum age is eighteen.', 'ন্যূনতম বয়স আঠারো।', 348),
    ('minister', null, 'n.', 'B2', 'মন্ত্রী', 'The minister gave a speech.', 'মন্ত্রী একটি বক্তৃতা দিলেন।', 349),
    ('minor', null, 'adj.', 'B2', 'গৌণ, ছোটখাটো', 'It was only a minor problem.', 'এটি কেবল একটি ছোটখাটো সমস্যা ছিল।', 350),
    ('minority', null, 'n.', 'B2', 'সংখ্যালঘু, অল্পসংখ্যক', 'Only a minority disagreed.', 'কেবল অল্পসংখ্যক দ্বিমত পোষণ করল।', 351),
    ('mission', null, 'n.', 'B2', 'অভিযান, দায়িত্ব', 'Their mission was to find water.', 'তাদের দায়িত্ব ছিল পানি খুঁজে বের করা।', 352),
    ('mixed', null, 'adj.', 'B2', 'মিশ্র', 'I have mixed feelings about it.', 'এটি নিয়ে আমার মিশ্র অনুভূতি আছে।', 353),
    ('modify', null, 'v.', 'B2', 'পরিবর্তন করা, রূপান্তর করা', 'They modified the design slightly.', 'তারা নকশাটি সামান্য পরিবর্তন করল।', 354),
    ('monitor', null, 'n., v.', 'B2', 'মনিটর, পর্দা; নজর রাখা', 'Doctors monitor the patient closely.', 'ডাক্তাররা রোগীর উপর নিবিড় নজর রাখেন।', 355),
    ('moral', null, 'adj., n.', 'B2', 'নৈতিক; নীতিকথা', 'The story teaches a moral lesson.', 'গল্পটি একটি নৈতিক শিক্ষা দেয়।', 356),
    ('motor', null, 'adj., n.', 'B2', 'মোটর, ইঞ্জিন', 'The boat has a small motor.', 'নৌকাটিতে একটি ছোট মোটর আছে।', 357),
    ('mount', null, 'v.', 'B2', 'আরোহণ করা, ওঠা; স্থাপন করা', 'He mounted the horse.', 'সে ঘোড়ায় চড়ল।', 358),
    ('multiple', null, 'adj.', 'B2', 'একাধিক, বহুবিধ', 'The test has multiple questions.', 'পরীক্ষাটিতে একাধিক প্রশ্ন আছে।', 359),
    ('multiply', null, 'v.', 'B2', 'গুণ করা; বহুগুণ বৃদ্ধি পাওয়া', 'Multiply four by five.', 'চারকে পাঁচ দিয়ে গুণ কর।', 360),
    ('mysterious', null, 'adj.', 'B2', 'রহস্যময়', 'A mysterious light appeared in the sky.', 'আকাশে একটি রহস্যময় আলো দেখা দিল।', 361),
    ('nerve', null, 'n.', 'B2', 'স্নায়ু; সাহস', 'He did not have the nerve to ask.', 'জিজ্ঞেস করার সাহস তার ছিল না।', 362),
    ('nevertheless', null, 'adv.', 'B2', 'তথাপি, তবুও', 'It was hard; nevertheless, she finished.', 'এটা কঠিন ছিল; তবুও, সে শেষ করল।', 363),
    ('nightmare', null, 'n.', 'B2', 'দুঃস্বপ্ন', 'She woke up from a nightmare.', 'সে একটি দুঃস্বপ্ন থেকে জেগে উঠল।', 364),
    ('notion', null, 'n.', 'B2', 'ধারণা', 'He has a strange notion of fun.', 'মজা সম্পর্কে তার একটি অদ্ভুত ধারণা আছে।', 365),
    ('numerous', null, 'adj.', 'B2', 'অসংখ্য, বহুসংখ্যক', 'There were numerous mistakes.', 'অসংখ্য ভুল ছিল।', 366),
    ('obey', null, 'v.', 'B2', 'মান্য করা, আনুগত্য করা', 'You must obey the rules.', 'তোমাকে নিয়ম মান্য করতে হবে।', 367),
    ('objective', null, 'adj., n.', 'B2', 'লক্ষ্য; বস্তুনিষ্ঠ', 'Our main objective is safety.', 'আমাদের প্রধান লক্ষ্য নিরাপত্তা।', 368),
    ('obligation', null, 'n.', 'B2', 'বাধ্যবাধকতা, কর্তব্য', 'You have no obligation to stay.', 'থাকার কোনো বাধ্যবাধকতা তোমার নেই।', 369),
    ('observation', null, 'n.', 'B2', 'পর্যবেক্ষণ', 'His observation was correct.', 'তার পর্যবেক্ষণ সঠিক ছিল।', 370),
    ('obtain', null, 'v.', 'B2', 'লাভ করা, সংগ্রহ করা', 'She obtained a visa quickly.', 'সে দ্রুত একটি ভিসা সংগ্রহ করল।', 371),
    ('occasionally', null, 'adv.', 'B2', 'মাঝেমধ্যে', 'We occasionally eat out.', 'আমরা মাঝেমধ্যে বাইরে খাই।', 372),
    ('offend', null, 'v.', 'B2', 'অসন্তুষ্ট করা, আঘাত দেওয়া', 'I did not mean to offend you.', 'আমি তোমাকে আঘাত দিতে চাইনি।', 373),
    ('offense', null, 'n.', 'B2', 'অপরাধ; আঘাত', 'Lying is a serious offense.', 'মিথ্যা বলা একটি গুরুতর অপরাধ।', 374),
    ('offensive', null, 'adj.', 'B2', 'আক্রমণাত্মক; আপত্তিকর', 'His comment was offensive.', 'তার মন্তব্যটি আপত্তিকর ছিল।', 375),
    ('opening', null, 'n.', 'B2', 'উদ্বোধন; খোলা জায়গা', 'We attended the shop''s opening.', 'আমরা দোকানটির উদ্বোধনে গেলাম।', 376),
    ('operate', null, 'v.', 'B2', 'পরিচালনা করা; অস্ত্রোপচার করা', 'She knows how to operate the machine.', 'সে যন্ত্রটি কীভাবে পরিচালনা করতে হয় জানে।', 377),
    ('opponent', null, 'n.', 'B2', 'প্রতিপক্ষ, প্রতিদ্বন্দ্বী', 'He beat his opponent easily.', 'সে সহজেই তার প্রতিপক্ষকে হারাল।', 378),
    ('oppose', null, 'v.', 'B2', 'বিরোধিতা করা', 'Many people opposed the plan.', 'অনেক মানুষ পরিকল্পনাটির বিরোধিতা করল।', 379),
    ('opposed', null, 'adj.', 'B2', 'বিরোধী, বিপরীত', 'She is opposed to the idea.', 'সে ধারণাটির বিরোধী।', 380),
    ('opposition', null, 'n.', 'B2', 'বিরোধিতা; বিরোধী পক্ষ', 'The plan faced strong opposition.', 'পরিকল্পনাটি প্রবল বিরোধিতার মুখে পড়ল।', 381),
    ('organ', null, 'n.', 'B2', 'অঙ্গ, ইন্দ্রিয়', 'The heart is a vital organ.', 'হৃৎপিণ্ড একটি গুরুত্বপূর্ণ অঙ্গ।', 382),
    ('origin', null, 'n.', 'B2', 'উৎপত্তি, উৎস', 'The word has a Latin origin.', 'শব্দটির উৎপত্তি ল্যাটিন ভাষায়।', 383),
    ('otherwise', null, 'adv.', 'B2', 'নতুবা, অন্যথায়', 'Hurry, otherwise you will be late.', 'তাড়াতাড়ি কর, নতুবা তুমি দেরি করবে।', 384),
    ('outcome', null, 'n.', 'B2', 'ফলাফল, পরিণতি', 'The outcome was a surprise.', 'ফলাফলটি একটি চমক ছিল।', 385),
    ('outer', null, 'adj.', 'B2', 'বাইরের, বহিঃস্থ', 'The outer wall is very thick.', 'বাইরের দেয়ালটি খুব পুরু।', 386),
    ('outline', null, 'n., v.', 'B2', 'রূপরেখা; রূপরেখা দেওয়া', 'She outlined her plan clearly.', 'সে তার পরিকল্পনার রূপরেখা স্পষ্টভাবে দিল।', 387),
    ('overall', null, 'adv., adj.', 'B2', 'সামগ্রিক, মোটের উপর', 'Overall, the trip was a success.', 'মোটের উপর, ভ্রমণটি সফল ছিল।', 388),
    ('owe', null, 'v.', 'B2', 'ঋণী থাকা, পাওনা থাকা', 'I owe you ten dollars.', 'আমি তোমার কাছে দশ ডলার ঋণী।', 389),
    ('pace', null, 'n., v.', 'B2', 'গতি, চলার হার', 'He walked at a slow pace.', 'সে ধীর গতিতে হাঁটল।', 390),
    ('panel', null, 'n.', 'B2', 'প্যানেল, বিচারকমণ্ডলী', 'A panel of judges chose the winner.', 'একটি বিচারকমণ্ডলী বিজয়ী নির্বাচন করল।', 391),
    ('participant', null, 'n.', 'B2', 'অংশগ্রহণকারী', 'Every participant got a prize.', 'প্রত্যেক অংশগ্রহণকারী একটি পুরস্কার পেল।', 392),
    ('partly', null, 'adv.', 'B2', 'আংশিকভাবে', 'The delay was partly my fault.', 'দেরিটা আংশিকভাবে আমার দোষ ছিল।', 393),
    ('passage', null, 'n.', 'B2', 'অনুচ্ছেদ; পথ', 'Read this passage aloud.', 'এই অনুচ্ছেদটি জোরে পড়ো।', 394),
    ('permanent', null, 'adj.', 'B2', 'স্থায়ী', 'He got a permanent job.', 'সে একটি স্থায়ী চাকরি পেল।', 395),
    ('permit', null, 'n., v.', 'B2', 'অনুমতি; অনুমতি দেওয়া', 'The rules do not permit this.', 'নিয়মে এটি অনুমতি দেয় না।', 396),
    ('perspective', null, 'n.', 'B2', 'দৃষ্টিভঙ্গি', 'Try to see it from my perspective.', 'আমার দৃষ্টিভঙ্গি থেকে এটি দেখার চেষ্টা কর।', 397),
    ('phase', null, 'n.', 'B2', 'পর্যায়, দশা', 'The project is in its final phase.', 'প্রকল্পটি তার চূড়ান্ত পর্যায়ে আছে।', 398),
    ('phenomenon', null, 'n.', 'B2', 'ঘটনা, প্রপঞ্চ', 'Rainbows are a natural phenomenon.', 'রংধনু একটি প্রাকৃতিক ঘটনা।', 399),
    ('philosophy', null, 'n.', 'B2', 'দর্শন', 'She studies philosophy at university.', 'সে বিশ্ববিদ্যালয়ে দর্শন পড়ে।', 400),
    ('pile', null, 'n., v.', 'B2', 'স্তূপ; স্তূপ করা', 'There is a pile of books on the desk.', 'ডেস্কে একটি বইয়ের স্তূপ আছে।', 401),
    ('pitch', null, 'n.', 'B2', 'খেলার মাঠ; সুরের চড়াই', 'The players ran onto the pitch.', 'খেলোয়াড়রা মাঠে দৌড়ে নামল।', 402),
    ('plain', null, 'adj.', 'B2', 'সাদাসিধা, সরল; স্পষ্ট', 'She wore a plain white dress.', 'সে একটি সাদাসিধা সাদা পোশাক পরল।', 403),
    ('pointed', null, 'adj.', 'B2', 'সূচালো, তীক্ষ্ণ', 'The pencil has a pointed tip.', 'পেন্সিলটির আগা সূচালো।', 404),
    ('popularity', null, 'n.', 'B2', 'জনপ্রিয়তা', 'The song gained popularity fast.', 'গানটি দ্রুত জনপ্রিয়তা পেল।', 405),
    ('pose', null, 'v.', 'B2', 'ভঙ্গি করা; সৃষ্টি করা', 'They posed for a photo.', 'তারা একটি ছবির জন্য ভঙ্গি করল।', 406),
    ('possess', null, 'v.', 'B2', 'অধিকারে রাখা, মালিক হওয়া', 'She possesses great talent.', 'তার দারুণ প্রতিভা আছে।', 407),
    ('potential', null, 'adj., n.', 'B2', 'সম্ভাবনাময়; সম্ভাবনা', 'He has great potential.', 'তার দারুণ সম্ভাবনা আছে।', 408),
    ('praise', null, 'n., v.', 'B2', 'প্রশংসা; প্রশংসা করা', 'The teacher praised her work.', 'শিক্ষক তার কাজের প্রশংসা করলেন।', 409),
    ('pregnant', null, 'adj.', 'B2', 'গর্ভবতী, অন্তঃসত্ত্বা', 'His sister is pregnant.', 'তার বোন গর্ভবতী।', 410),
    ('preparation', null, 'n.', 'B2', 'প্রস্তুতি', 'Preparation for the exam takes time.', 'পরীক্ষার প্রস্তুতিতে সময় লাগে।', 411),
    ('presence', null, 'n.', 'B2', 'উপস্থিতি', 'Your presence made her happy.', 'তোমার উপস্থিতি তাকে খুশি করল।', 412),
    ('preserve', null, 'v.', 'B2', 'সংরক্ষণ করা, রক্ষা করা', 'We must preserve old buildings.', 'আমাদের পুরনো ভবন সংরক্ষণ করতে হবে।', 413),
    ('prime', null, 'adj.', 'B2', 'প্রধান, মুখ্য', 'Safety is of prime importance.', 'নিরাপত্তা প্রধান গুরুত্বপূর্ণ।', 414),
    ('principle', null, 'n.', 'B2', 'নীতি, মূলনীতি', 'He lives by strong principles.', 'সে দৃঢ় নীতি মেনে জীবনযাপন করে।', 415),
    ('priority', null, 'n.', 'B2', 'অগ্রাধিকার', 'Health is my top priority.', 'স্বাস্থ্য আমার সর্বোচ্চ অগ্রাধিকার।', 416),
    ('privacy', null, 'n.', 'B2', 'গোপনীয়তা, নিভৃতি', 'Everyone needs some privacy.', 'প্রত্যেকের কিছুটা গোপনীয়তা দরকার।', 417),
    ('procedure', null, 'n.', 'B2', 'পদ্ধতি, কার্যপ্রণালী', 'Follow the correct procedure.', 'সঠিক পদ্ধতি অনুসরণ কর।', 418),
    ('proof', null, 'n.', 'B2', 'প্রমাণ', 'Do you have any proof?', 'তোমার কাছে কি কোনো প্রমাণ আছে?', 419),
    ('proposal', null, 'n.', 'B2', 'প্রস্তাব', 'They accepted our proposal.', 'তারা আমাদের প্রস্তাব গ্রহণ করল।', 420),
    ('propose', null, 'v.', 'B2', 'প্রস্তাব করা', 'I propose a short break.', 'আমি একটি সংক্ষিপ্ত বিরতির প্রস্তাব করছি।', 421),
    ('prospect', null, 'n.', 'B2', 'সম্ভাবনা, প্রত্যাশা', 'There is a good prospect of success.', 'সাফল্যের ভালো সম্ভাবনা আছে।', 422),
    ('protection', null, 'n.', 'B2', 'সুরক্ষা, রক্ষা', 'The cream gives protection from the sun.', 'ক্রিমটি রোদ থেকে সুরক্ষা দেয়।', 423),
    ('psychologist', null, 'n.', 'B2', 'মনোবিজ্ঞানী', 'She saw a psychologist for help.', 'সে সাহায্যের জন্য একজন মনোবিজ্ঞানীর কাছে গেল।', 424),
    ('psychology', null, 'n.', 'B2', 'মনোবিজ্ঞান', 'He is interested in child psychology.', 'সে শিশু মনোবিজ্ঞানে আগ্রহী।', 425),
    ('publication', null, 'n.', 'B2', 'প্রকাশনা', 'The book''s publication was delayed.', 'বইটির প্রকাশনা দেরি হলো।', 426),
    ('purchase', null, 'n., v.', 'B2', 'ক্রয়; কেনা', 'She made a large purchase.', 'সে একটি বড় কেনাকাটা করল।', 427),
    ('pure', null, 'adj.', 'B2', 'বিশুদ্ধ, খাঁটি', 'This is pure honey.', 'এটি খাঁটি মধু।', 428),
    ('pursue', null, 'v.', 'B2', 'অনুসরণ করা; চালিয়ে যাওয়া', 'She wants to pursue a career in music.', 'সে সংগীতে ক্যারিয়ার গড়তে চায়।', 429),
    ('rank', null, 'n., v.', 'B2', 'পদমর্যাদা, স্তর; স্থান দেওয়া', 'He holds a high rank in the army.', 'সেনাবাহিনীতে তার উচ্চ পদমর্যাদা আছে।', 430),
    ('rapid', null, 'adj.', 'B2', 'দ্রুত, ত্বরিত', 'There was a rapid rise in prices.', 'দামে একটি দ্রুত বৃদ্ধি হলো।', 431),
    ('rapidly', null, 'adv.', 'B2', 'দ্রুতগতিতে', 'The city is growing rapidly.', 'শহরটি দ্রুতগতিতে বাড়ছে।', 432),
    ('raw', null, 'adj.', 'B2', 'কাঁচা; অপরিশোধিত', 'Do not eat raw meat.', 'কাঁচা মাংস খেও না।', 433),
    ('realistic', null, 'adj.', 'B2', 'বাস্তবসম্মত, বাস্তবধর্মী', 'Set realistic goals.', 'বাস্তবসম্মত লক্ষ্য নির্ধারণ কর।', 434),
    ('reasonable', null, 'adj.', 'B2', 'যুক্তিসঙ্গত, ন্যায্য', 'The price is quite reasonable.', 'দামটি বেশ যুক্তিসঙ্গত।', 435),
    ('recall', null, 'v.', 'B2', 'স্মরণ করা, মনে করা', 'I cannot recall his name.', 'আমি তার নাম মনে করতে পারছি না।', 436),
    ('recover', null, 'v.', 'B2', 'সুস্থ হওয়া; ফিরে পাওয়া', 'He recovered from his illness.', 'সে তার অসুস্থতা থেকে সেরে উঠল।', 437),
    ('reduction', null, 'n.', 'B2', 'হ্রাস, কমতি', 'There was a reduction in costs.', 'খরচে একটি হ্রাস হলো।', 438),
    ('regard', null, 'n., v.', 'B2', 'বিবেচনা করা, গণ্য করা; সম্মান', 'I regard her as a friend.', 'আমি তাকে একজন বন্ধু হিসেবে গণ্য করি।', 439),
    ('regional', null, 'adj.', 'B2', 'আঞ্চলিক', 'They sell regional products.', 'তারা আঞ্চলিক পণ্য বিক্রি করে।', 440),
    ('register', null, 'n., v.', 'B2', 'নিবন্ধন; নিবন্ধন করা', 'Please register before the class.', 'অনুগ্রহ করে ক্লাসের আগে নিবন্ধন কর।', 441),
    ('regret', null, 'n., v.', 'B2', 'অনুশোচনা; অনুতপ্ত হওয়া', 'I regret my decision.', 'আমি আমার সিদ্ধান্তের জন্য অনুতপ্ত।', 442),
    ('regulation', null, 'n.', 'B2', 'বিধি, নিয়মকানুন', 'Follow the safety regulations.', 'নিরাপত্তা বিধিগুলো মেনে চলো।', 443),
    ('relatively', null, 'adv.', 'B2', 'তুলনামূলকভাবে', 'The exam was relatively easy.', 'পরীক্ষাটি তুলনামূলকভাবে সহজ ছিল।', 444),
    ('relevant', null, 'adj.', 'B2', 'প্রাসঙ্গিক', 'Please give relevant examples.', 'অনুগ্রহ করে প্রাসঙ্গিক উদাহরণ দাও।', 445),
    ('relief', null, 'n.', 'B2', 'স্বস্তি; ত্রাণ', 'It was a great relief to hear the news.', 'খবরটি শুনে দারুণ স্বস্তি পেলাম।', 446),
    ('rely', null, 'v.', 'B2', 'নির্ভর করা', 'You can rely on me.', 'তুমি আমার উপর নির্ভর করতে পার।', 447),
    ('remark', null, 'n., v.', 'B2', 'মন্তব্য; মন্তব্য করা', 'He made a kind remark.', 'সে একটি সদয় মন্তব্য করল।', 448),
    ('representative', null, 'adj., n.', 'B2', 'প্রতিনিধি; প্রতিনিধিত্বমূলক', 'She is our class representative.', 'সে আমাদের শ্রেণির প্রতিনিধি।', 449),
    ('reputation', null, 'n.', 'B2', 'সুনাম, খ্যাতি', 'The hotel has a good reputation.', 'হোটেলটির সুনাম আছে।', 450),
    ('requirement', null, 'n.', 'B2', 'প্রয়োজন, শর্ত', 'Meet all the requirements first.', 'প্রথমে সব শর্ত পূরণ কর।', 451),
    ('rescue', null, 'n., v.', 'B2', 'উদ্ধার; উদ্ধার করা', 'They rescued the boy from the river.', 'তারা ছেলেটিকে নদী থেকে উদ্ধার করল।', 452),
    ('reserve', null, 'n., v.', 'B2', 'সংরক্ষণ; সংরক্ষিত রাখা', 'I reserved a room for two nights.', 'আমি দুই রাতের জন্য একটি ঘর সংরক্ষণ করলাম।', 453),
    ('resident', null, 'adj., n.', 'B2', 'বাসিন্দা, নিবাসী', 'The residents complained about noise.', 'বাসিন্দারা শব্দ নিয়ে অভিযোগ করল।', 454),
    ('resist', null, 'v.', 'B2', 'প্রতিরোধ করা, বাধা দেওয়া', 'I could not resist the cake.', 'আমি কেকটির লোভ সামলাতে পারলাম না।', 455),
    ('resolve', null, 'v.', 'B2', 'সমাধান করা, মীমাংসা করা', 'They resolved the dispute peacefully.', 'তারা বিরোধটি শান্তিপূর্ণভাবে মীমাংসা করল।', 456),
    ('resort', null, 'n.', 'B2', 'রিসোর্ট, অবকাশকেন্দ্র', 'They stayed at a beach resort.', 'তারা একটি সৈকত রিসোর্টে থাকল।', 457),
    ('retain', null, 'v.', 'B2', 'ধরে রাখা, বজায় রাখা', 'The soil retains water well.', 'মাটি ভালোভাবে পানি ধরে রাখে।', 458),
    ('reveal', null, 'v.', 'B2', 'প্রকাশ করা, উন্মোচন করা', 'She revealed her secret.', 'সে তার গোপন কথা প্রকাশ করল।', 459),
    ('revolution', null, 'n.', 'B2', 'বিপ্লব', 'The revolution changed the country.', 'বিপ্লবটি দেশটিকে বদলে দিল।', 460),
    ('reward', null, 'n., v.', 'B2', 'পুরস্কার; পুরস্কৃত করা', 'Hard work brings its reward.', 'পরিশ্রম তার পুরস্কার নিয়ে আসে।', 461),
    ('rhythm', null, 'n.', 'B2', 'ছন্দ, তাল', 'The song has a fast rhythm.', 'গানটির একটি দ্রুত ছন্দ আছে।', 462),
    ('rid', null, 'v.', 'B2', 'মুক্ত করা, দূর করা', 'We must get rid of these weeds.', 'আমাদের এই আগাছাগুলো দূর করতে হবে।', 463),
    ('root', null, 'n.', 'B2', 'শিকড়, মূল', 'The tree has deep roots.', 'গাছটির গভীর শিকড় আছে।', 464),
    ('rub', null, 'v.', 'B2', 'ঘষা, মালিশ করা', 'She rubbed her cold hands.', 'সে তার ঠান্ডা হাত ঘষল।', 465),
    ('rubber', null, 'adj., n.', 'B2', 'রাবার', 'The boots are made of rubber.', 'বুটগুলো রাবারের তৈরি।', 466),
    ('rural', null, 'adj.', 'B2', 'গ্রামীণ', 'They moved to a rural area.', 'তারা একটি গ্রামীণ এলাকায় চলে গেল।', 467),
    ('rush', null, 'n., v.', 'B2', 'তাড়াহুড়া; ছুটে যাওয়া', 'Do not rush your work.', 'তোমার কাজে তাড়াহুড়া করো না।', 468),
    ('satellite', null, 'n.', 'B2', 'উপগ্রহ, স্যাটেলাইট', 'The satellite sends weather data.', 'উপগ্রহটি আবহাওয়ার তথ্য পাঠায়।', 469),
    ('satisfied', null, 'adj.', 'B2', 'সন্তুষ্ট', 'The customers were satisfied.', 'ক্রেতারা সন্তুষ্ট ছিল।', 470),
    ('satisfy', null, 'v.', 'B2', 'সন্তুষ্ট করা', 'The answer did not satisfy her.', 'উত্তরটি তাকে সন্তুষ্ট করল না।', 471),
    ('saving', null, 'n.', 'B2', 'সঞ্চয়', 'She put her savings in the bank.', 'সে তার সঞ্চয় ব্যাংকে রাখল।', 472),
    ('scale', null, 'n.', 'B2', 'মাপকাঠি, পরিমাপ; আঁশ', 'The map is drawn to scale.', 'মানচিত্রটি মাপ অনুযায়ী আঁকা।', 473),
    ('scream', null, 'n., v.', 'B2', 'চিৎকার; আর্তনাদ করা', 'She screamed in fear.', 'সে ভয়ে চিৎকার করল।', 474),
    ('sector', null, 'n.', 'B2', 'খাত, ক্ষেত্র', 'He works in the private sector.', 'সে বেসরকারি খাতে কাজ করে।', 475),
    ('secure', null, 'adj., v.', 'B2', 'নিরাপদ; সুরক্ষিত করা', 'Keep your password secure.', 'তোমার পাসওয়ার্ড সুরক্ষিত রাখো।', 476),
    ('seek', null, 'v.', 'B2', 'খোঁজা, অন্বেষণ করা', 'They seek a better life.', 'তারা একটি উন্নত জীবন খোঁজে।', 477),
    ('select', null, 'v.', 'B2', 'নির্বাচন করা, বাছাই করা', 'Select the correct answer.', 'সঠিক উত্তরটি বাছাই কর।', 478),
    ('selection', null, 'n.', 'B2', 'নির্বাচন, বাছাই', 'The shop has a wide selection.', 'দোকানটিতে বিস্তৃত বাছাই আছে।', 479),
    ('self', null, 'n.', 'B2', 'নিজ, আত্ম', 'She is her old self again.', 'সে আবার তার আগের রূপে ফিরেছে।', 480),
    ('senate', null, 'n.', 'B2', 'সেনেট, উচ্চকক্ষ', 'The senate passed the bill.', 'সেনেট বিলটি পাস করল।', 481),
    ('senator', null, 'n.', 'B2', 'সেনেটর', 'The senator gave a long speech.', 'সেনেটর একটি দীর্ঘ বক্তৃতা দিলেন।', 482),
    ('senior', null, 'adj.', 'B2', 'জ্যেষ্ঠ, ঊর্ধ্বতন', 'He is a senior manager.', 'তিনি একজন ঊর্ধ্বতন ব্যবস্থাপক।', 483),
    ('sensitive', null, 'adj.', 'B2', 'সংবেদনশীল, স্পর্শকাতর', 'She has sensitive skin.', 'তার ত্বক স্পর্শকাতর।', 484),
    ('sequence', null, 'n.', 'B2', 'ক্রম, ধারাক্রম', 'Put the pictures in the right sequence.', 'ছবিগুলো সঠিক ক্রমে সাজাও।', 485),
    ('session', null, 'n.', 'B2', 'অধিবেশন, পর্ব', 'The training session lasted two hours.', 'প্রশিক্ষণ পর্বটি দুই ঘণ্টা চলল।', 486),
    ('settle', null, 'v.', 'B2', 'স্থিত হওয়া, বসতি স্থাপন করা; মীমাংসা করা', 'They settled in a small town.', 'তারা একটি ছোট শহরে বসতি স্থাপন করল।', 487),
    ('severe', null, 'adj.', 'B2', 'তীব্র, প্রকট; কঠোর', 'He has a severe headache.', 'তার তীব্র মাথাব্যথা হচ্ছে।', 488),
    ('shade', null, 'n.', 'B2', 'ছায়া; রঙের ছটা', 'We sat in the shade of a tree.', 'আমরা একটি গাছের ছায়ায় বসলাম।', 489),
    ('shadow', null, 'n.', 'B2', 'ছায়া', 'His shadow fell on the wall.', 'তার ছায়া দেয়ালে পড়ল।', 490),
    ('shall', null, 'modal v., v.', 'B2', 'করব, হবে (ভবিষ্যৎ/প্রস্তাব)', 'Shall we go now?', 'আমরা কি এখন যাব?', 491),
    ('shallow', null, 'adj.', 'B2', 'অগভীর, ছিছলে', 'The river is shallow here.', 'নদীটি এখানে অগভীর।', 492),
    ('shame', null, 'n.', 'B2', 'লজ্জা; আফসোসের বিষয়', 'What a shame that you missed it.', 'কী আফসোস যে তুমি এটা মিস করলে।', 493),
    ('shelter', null, 'n., v.', 'B2', 'আশ্রয়; আশ্রয় দেওয়া', 'They took shelter from the rain.', 'তারা বৃষ্টি থেকে আশ্রয় নিল।', 494),
    ('shock', null, 'n., v.', 'B2', 'আঘাত, ধাক্কা; হতবাক করা', 'The news came as a shock.', 'খবরটি একটি ধাক্কা হয়ে এল।', 495),
    ('shocked', null, 'adj.', 'B2', 'হতবাক, স্তম্ভিত', 'We were shocked by the accident.', 'দুর্ঘটনাটি দেখে আমরা হতবাক হয়ে গেলাম।', 496),
    ('shooting', null, 'n.', 'B2', 'গুলিবর্ষণ; শুটিং', 'The film shooting took a month.', 'সিনেমার শুটিং এক মাস সময় নিল।', 497),
    ('shot', null, 'n.', 'B2', 'গুলি; শট; প্রচেষ্টা', 'He took a shot at the goal.', 'সে গোলের দিকে একটি শট নিল।', 498),
    ('significant', null, 'adj.', 'B2', 'তাৎপর্যপূর্ণ, উল্লেখযোগ্য', 'There was a significant improvement.', 'একটি উল্লেখযোগ্য উন্নতি হলো।', 499),
    ('significantly', null, 'adv.', 'B2', 'উল্লেখযোগ্যভাবে', 'Prices rose significantly.', 'দাম উল্লেখযোগ্যভাবে বাড়ল।', 500),
    ('silence', null, 'n.', 'B2', 'নীরবতা, নিস্তব্ধতা', 'There was a long silence.', 'একটি দীর্ঘ নীরবতা ছিল।', 501),
    ('silk', null, 'n.', 'B2', 'রেশম, সিল্ক', 'She wore a silk scarf.', 'সে একটি রেশমি স্কার্ফ পরল।', 502),
    ('sincere', null, 'adj.', 'B2', 'আন্তরিক, অকপট', 'Please accept my sincere thanks.', 'অনুগ্রহ করে আমার আন্তরিক ধন্যবাদ গ্রহণ কর।', 503),
    ('slide', null, 'n., v.', 'B2', 'পিছলে যাওয়া; স্লাইড', 'The children love the slide.', 'শিশুরা স্লাইডটি ভালোবাসে।', 504),
    ('slight', null, 'adj.', 'B2', 'সামান্য, অল্প', 'There was a slight delay.', 'একটি সামান্য দেরি হলো।', 505),
    ('slip', null, 'v.', 'B2', 'পিছলে পড়া, ফসকে যাওয়া', 'She slipped on the wet floor.', 'সে ভেজা মেঝেতে পিছলে পড়ল।', 506),
    ('slope', null, 'n., v.', 'B2', 'ঢাল; ঢালু হওয়া', 'They skied down the slope.', 'তারা ঢাল বেয়ে স্কি করে নামল।', 507),
    ('solar', null, 'adj.', 'B2', 'সৌর, সূর্য-সম্পর্কিত', 'They use solar energy.', 'তারা সৌরশক্তি ব্যবহার করে।', 508),
    ('somewhat', null, 'adv.', 'B2', 'কিছুটা, খানিকটা', 'The result was somewhat surprising.', 'ফলাফলটি কিছুটা বিস্ময়কর ছিল।', 509),
    ('soul', null, 'n.', 'B2', 'আত্মা', 'Music touches the soul.', 'সংগীত আত্মাকে স্পর্শ করে।', 510),
    ('specialist', null, 'adj., n.', 'B2', 'বিশেষজ্ঞ', 'She is a heart specialist.', 'সে একজন হৃদরোগ বিশেষজ্ঞ।', 511),
    ('species', null, 'n.', 'B2', 'প্রজাতি', 'This species of bird is rare.', 'এই প্রজাতির পাখি বিরল।', 512),
    ('spiritual', null, 'adj.', 'B2', 'আধ্যাত্মিক', 'They went on a spiritual journey.', 'তারা একটি আধ্যাত্মিক যাত্রায় গেল।', 513),
    ('split', null, 'n., v.', 'B2', 'বিভাজন; ভাগ করা, বিভক্ত হওয়া', 'They split the bill equally.', 'তারা বিলটি সমানভাবে ভাগ করল।', 514),
    ('sponsor', null, 'n., v.', 'B2', 'পৃষ্ঠপোষক; পৃষ্ঠপোষকতা করা', 'A local company sponsored the event.', 'একটি স্থানীয় কোম্পানি অনুষ্ঠানটির পৃষ্ঠপোষকতা করল।', 515),
    ('stable', null, 'adj.', 'B2', 'স্থিতিশীল, দৃঢ়', 'His condition is now stable.', 'তার অবস্থা এখন স্থিতিশীল।', 516),
    ('stare', null, 'v.', 'B2', 'একদৃষ্টে তাকিয়ে থাকা', 'It is rude to stare at people.', 'মানুষের দিকে একদৃষ্টে তাকিয়ে থাকা অভদ্রতা।', 517),
    ('status', null, 'n.', 'B2', 'অবস্থা, মর্যাদা', 'Check the status of your order.', 'তোমার অর্ডারের অবস্থা দেখে নাও।', 518),
    ('steady', null, 'adj.', 'B2', 'স্থির, অবিচল', 'Keep the ladder steady.', 'মইটি স্থির রাখো।', 519),
    ('steel', null, 'n.', 'B2', 'ইস্পাত', 'The bridge is made of steel.', 'সেতুটি ইস্পাতের তৈরি।', 520),
    ('steep', null, 'adj.', 'B2', 'খাড়া, ঢালু', 'The path up the hill is steep.', 'পাহাড়ে ওঠার পথটি খাড়া।', 521),
    ('sticky', null, 'adj.', 'B2', 'আঠালো, চটচটে', 'My hands are sticky with honey.', 'আমার হাত মধুতে আঠালো হয়ে গেছে।', 522),
    ('stiff', null, 'adj.', 'B2', 'শক্ত, অনমনীয়', 'My neck feels stiff.', 'আমার ঘাড় শক্ত হয়ে আছে।', 523),
    ('stock', null, 'n.', 'B2', 'মজুত; শেয়ার', 'The item is out of stock.', 'পণ্যটি মজুত শেষ।', 524),
    ('stream', null, 'n.', 'B2', 'স্রোত, ছোট নদী', 'A small stream runs nearby.', 'কাছেই একটি ছোট ঝরনা বয়ে যায়।', 525),
    ('stretch', null, 'n., v.', 'B2', 'প্রসারিত করা, টানটান করা', 'Stretch your arms before running.', 'দৌড়ানোর আগে তোমার বাহু প্রসারিত কর।', 526),
    ('strict', null, 'adj.', 'B2', 'কঠোর, কড়া', 'Our teacher is very strict.', 'আমাদের শিক্ষক খুব কড়া।', 527),
    ('strike', null, 'n., v.', 'B2', 'ধর্মঘট; আঘাত করা', 'The workers went on strike.', 'শ্রমিকরা ধর্মঘটে গেল।', 528),
    ('struggle', null, 'n., v.', 'B2', 'সংগ্রাম; লড়াই করা', 'They struggled to survive.', 'তারা বেঁচে থাকার জন্য সংগ্রাম করল।', 529),
    ('submit', null, 'v.', 'B2', 'জমা দেওয়া, দাখিল করা', 'Submit your form by Friday.', 'শুক্রবারের মধ্যে তোমার ফর্ম জমা দাও।', 530),
    ('sum', null, 'n., v.', 'B2', 'যোগফল, পরিমাণ; সংক্ষেপে বলা', 'He paid a large sum of money.', 'সে একটি বড় অঙ্কের টাকা পরিশোধ করল।', 531),
    ('surgery', null, 'n.', 'B2', 'অস্ত্রোপচার, শল্যচিকিৎসা', 'She needs surgery on her knee.', 'তার হাঁটুতে অস্ত্রোপচার দরকার।', 532),
    ('surround', null, 'v.', 'B2', 'ঘিরে ফেলা, পরিবেষ্টন করা', 'Tall trees surround the house.', 'উঁচু গাছ বাড়িটিকে ঘিরে আছে।', 533),
    ('surrounding', null, 'adj.', 'B2', 'পার্শ্ববর্তী, চারপাশের', 'They explored the surrounding hills.', 'তারা চারপাশের পাহাড়গুলো ঘুরে দেখল।', 534),
    ('suspect', null, 'n., v.', 'B2', 'সন্দেহভাজন; সন্দেহ করা', 'The police questioned the suspect.', 'পুলিশ সন্দেহভাজনকে জিজ্ঞাসাবাদ করল।', 535),
    ('swear', null, 'v.', 'B2', 'শপথ করা; গালি দেওয়া', 'He swore to tell the truth.', 'সে সত্য বলার শপথ করল।', 536),
    ('sweep', null, 'v.', 'B2', 'ঝাড়ু দেওয়া, ঝাঁট দেওয়া', 'Please sweep the floor.', 'অনুগ্রহ করে মেঝেটি ঝাড়ু দাও।', 537),
    ('sympathy', null, 'n.', 'B2', 'সহানুভূতি', 'She showed sympathy for the poor.', 'সে দরিদ্রদের প্রতি সহানুভূতি দেখাল।', 538),
    ('tale', null, 'n.', 'B2', 'কাহিনি, গল্প', 'Grandmother told us a folk tale.', 'দাদি আমাদের একটি লোককাহিনি বললেন।', 539),
    ('tank', null, 'n.', 'B2', 'ট্যাংক, জলাধার', 'The water tank is full.', 'পানির ট্যাংকটি ভর্তি।', 540),
    ('tear', 'from crying', 'n.', 'B2', 'অশ্রু, চোখের জল', 'A tear ran down her cheek.', 'তার গাল বেয়ে একটি অশ্রু গড়িয়ে পড়ল।', 541),
    ('tear', 'rip', 'n., v.', 'B2', 'ছিঁড়ে ফেলা; ছেঁড়া', 'Be careful not to tear the paper.', 'সাবধান, কাগজটি যেন ছিঁড়ে না যায়।', 542),
    ('temporary', null, 'adj.', 'B2', 'অস্থায়ী, সাময়িক', 'This is a temporary solution.', 'এটি একটি অস্থায়ী সমাধান।', 543),
    ('therapy', null, 'n.', 'B2', 'থেরাপি, চিকিৎসা', 'He is having therapy for his back.', 'সে তার পিঠের জন্য থেরাপি নিচ্ছে।', 544),
    ('threat', null, 'n.', 'B2', 'হুমকি, ভীতি', 'Pollution is a threat to health.', 'দূষণ স্বাস্থ্যের জন্য একটি হুমকি।', 545),
    ('threaten', null, 'v.', 'B2', 'হুমকি দেওয়া', 'They threatened to leave.', 'তারা চলে যাওয়ার হুমকি দিল।', 546),
    ('thus', null, 'adv.', 'B2', 'এভাবে, অতএব', 'He was ill; thus, he stayed home.', 'সে অসুস্থ ছিল; অতএব, সে বাড়িতে থাকল।', 547),
    ('tone', null, 'n.', 'B2', 'সুর, স্বর', 'She spoke in a gentle tone.', 'সে একটি কোমল স্বরে কথা বলল।', 548),
    ('tough', null, 'adj.', 'B2', 'কঠিন, শক্ত', 'It was a tough decision.', 'এটি একটি কঠিন সিদ্ধান্ত ছিল।', 549),
    ('transfer', null, 'n., v.', 'B2', 'স্থানান্তর; স্থানান্তর করা', 'He transferred to another school.', 'সে অন্য একটি স্কুলে স্থানান্তরিত হলো।', 550),
    ('transform', null, 'v.', 'B2', 'রূপান্তরিত করা', 'The internet transformed our lives.', 'ইন্টারনেট আমাদের জীবন রূপান্তরিত করল।', 551),
    ('transition', null, 'n.', 'B2', 'পরিবর্তন, উত্তরণ', 'The transition to college was hard.', 'কলেজে উত্তরণটি কঠিন ছিল।', 552),
    ('trial', null, 'n.', 'B2', 'বিচার; পরীক্ষা', 'The trial lasted three days.', 'বিচারটি তিন দিন চলল।', 553),
    ('tropical', null, 'adj.', 'B2', 'গ্রীষ্মমণ্ডলীয়', 'They visited a tropical island.', 'তারা একটি গ্রীষ্মমণ্ডলীয় দ্বীপে গেল।', 554),
    ('truly', null, 'adv.', 'B2', 'সত্যিই, প্রকৃতপক্ষে', 'I am truly grateful.', 'আমি সত্যিই কৃতজ্ঞ।', 555),
    ('trust', null, 'n., v.', 'B2', 'বিশ্বাস; বিশ্বাস করা', 'I trust you completely.', 'আমি তোমাকে সম্পূর্ণভাবে বিশ্বাস করি।', 556),
    ('tune', null, 'n.', 'B2', 'সুর', 'She hummed a happy tune.', 'সে একটি আনন্দময় সুর গুনগুন করল।', 557),
    ('tunnel', null, 'n.', 'B2', 'সুড়ঙ্গ', 'The train went through a tunnel.', 'ট্রেনটি একটি সুড়ঙ্গের মধ্য দিয়ে গেল।', 558),
    ('ultimately', null, 'adv.', 'B2', 'শেষ পর্যন্ত, চূড়ান্তভাবে', 'Ultimately, the choice is yours.', 'শেষ পর্যন্ত, সিদ্ধান্তটি তোমার।', 559),
    ('unconscious', null, 'adj.', 'B2', 'অচেতন, সংজ্ঞাহীন', 'The fall left him unconscious.', 'পড়ে গিয়ে সে অচেতন হয়ে পড়ল।', 560),
    ('unexpected', null, 'adj.', 'B2', 'অপ্রত্যাশিত', 'It was an unexpected visit.', 'এটি একটি অপ্রত্যাশিত সাক্ষাৎ ছিল।', 561),
    ('unique', null, 'adj.', 'B2', 'অনন্য, স্বতন্ত্র', 'Each snowflake is unique.', 'প্রতিটি তুষারকণা অনন্য।', 562),
    ('universe', null, 'n.', 'B2', 'মহাবিশ্ব', 'The universe is vast.', 'মহাবিশ্ব বিশাল।', 563),
    ('unknown', null, 'adj.', 'B2', 'অজানা, অজ্ঞাত', 'The cause is still unknown.', 'কারণটি এখনো অজানা।', 564),
    ('upper', null, 'adj.', 'B2', 'উপরের, ঊর্ধ্বতন', 'Her office is on the upper floor.', 'তার অফিস উপরের তলায়।', 565),
    ('upward', null, 'adv.', 'B2', 'ঊর্ধ্বমুখী, উপরের দিকে', 'The balloon floated upward.', 'বেলুনটি উপরের দিকে ভেসে গেল।', 566),
    ('urban', null, 'adj.', 'B2', 'শহুরে, নাগরিক', 'Urban life is fast and busy.', 'শহুরে জীবন দ্রুত ও ব্যস্ত।', 567),
    ('urge', null, 'v.', 'B2', 'তাগিদ দেওয়া, অনুরোধ করা', 'Doctors urge people to exercise.', 'ডাক্তাররা মানুষকে ব্যায়াম করার তাগিদ দেন।', 568),
    ('van', null, 'n.', 'B2', 'ভ্যান, মালবাহী গাড়ি', 'They moved the boxes in a van.', 'তারা বাক্সগুলো একটি ভ্যানে সরাল।', 569),
    ('vary', null, 'v.', 'B2', 'বিভিন্ন হওয়া, ভিন্ন হওয়া', 'Prices vary from shop to shop.', 'দোকানভেদে দাম ভিন্ন হয়।', 570),
    ('vast', null, 'adj.', 'B2', 'বিশাল, বিস্তীর্ণ', 'The desert is a vast empty space.', 'মরুভূমি একটি বিস্তীর্ণ শূন্য স্থান।', 571),
    ('venue', null, 'n.', 'B2', 'স্থান, আয়োজনস্থল', 'The concert venue was crowded.', 'কনসার্টের আয়োজনস্থলটি জনাকীর্ণ ছিল।', 572),
    ('via', null, 'prep.', 'B2', 'মাধ্যমে, হয়ে', 'We flew to Dhaka via Dubai.', 'আমরা দুবাই হয়ে ঢাকায় উড়ে গেলাম।', 573),
    ('victory', null, 'n.', 'B2', 'বিজয়, জয়', 'The team celebrated their victory.', 'দলটি তাদের বিজয় উদযাপন করল।', 574),
    ('violence', null, 'n.', 'B2', 'সহিংসতা, হিংসা', 'They protested against violence.', 'তারা সহিংসতার বিরুদ্ধে প্রতিবাদ করল।', 575),
    ('virtual', null, 'adj.', 'B2', 'ভার্চুয়াল, প্রায়-বাস্তব', 'We had a virtual meeting online.', 'আমরা অনলাইনে একটি ভার্চুয়াল সভা করলাম।', 576),
    ('vision', null, 'n.', 'B2', 'দৃষ্টিশক্তি; দূরদৃষ্টি', 'She has a clear vision for the future.', 'ভবিষ্যতের জন্য তার একটি স্পষ্ট দূরদৃষ্টি আছে।', 577),
    ('visual', null, 'adj.', 'B2', 'দৃশ্যমান, চাক্ষুষ', 'The film has great visual effects.', 'সিনেমাটির দারুণ দৃশ্যগত প্রভাব আছে।', 578),
    ('vital', null, 'adj.', 'B2', 'অত্যাবশ্যক, অতি গুরুত্বপূর্ণ', 'Sleep is vital for good health.', 'সুস্বাস্থ্যের জন্য ঘুম অত্যাবশ্যক।', 579),
    ('vitamin', null, 'n.', 'B2', 'ভিটামিন', 'Oranges are rich in vitamin C.', 'কমলায় প্রচুর ভিটামিন সি থাকে।', 580),
    ('volume', null, 'n.', 'B2', 'আয়তন, পরিমাণ; শব্দের মাত্রা', 'Please turn down the volume.', 'অনুগ্রহ করে শব্দ কমাও।', 581),
    ('wage', null, 'n.', 'B2', 'মজুরি, বেতন', 'The workers want higher wages.', 'শ্রমিকরা বেশি মজুরি চায়।', 582),
    ('weakness', null, 'n.', 'B2', 'দুর্বলতা', 'Everyone has a weakness.', 'প্রত্যেকেরই একটি দুর্বলতা আছে।', 583),
    ('wealth', null, 'n.', 'B2', 'সম্পদ, ধন', 'Health is greater than wealth.', 'স্বাস্থ্য সম্পদের চেয়ে বড়।', 584),
    ('wealthy', null, 'adj.', 'B2', 'ধনী, সম্পদশালী', 'He comes from a wealthy family.', 'সে একটি ধনী পরিবার থেকে এসেছে।', 585),
    ('whereas', null, 'conj.', 'B2', 'যেখানে, পক্ষান্তরে', 'He likes tea, whereas I prefer coffee.', 'সে চা পছন্দ করে, পক্ষান্তরে আমি কফি পছন্দ করি।', 586),
    ('wherever', null, 'conj.', 'B2', 'যেখানেই', 'I will follow you wherever you go.', 'তুমি যেখানেই যাও, আমি তোমাকে অনুসরণ করব।', 587),
    ('whisper', null, 'n., v.', 'B2', 'ফিসফিসানি; ফিসফিস করা', 'She whispered a secret in my ear.', 'সে আমার কানে একটি গোপন কথা ফিসফিস করে বলল।', 588),
    ('whom', null, 'pron.', 'B2', 'যাকে, কাকে', 'To whom did you give the book?', 'তুমি কাকে বইটি দিলে?', 589),
    ('widely', null, 'adv.', 'B2', 'ব্যাপকভাবে', 'The news spread widely.', 'খবরটি ব্যাপকভাবে ছড়িয়ে পড়ল।', 590),
    ('wildlife', null, 'n.', 'B2', 'বন্যপ্রাণী', 'The park protects wildlife.', 'উদ্যানটি বন্যপ্রাণী রক্ষা করে।', 591),
    ('willing', null, 'adj.', 'B2', 'ইচ্ছুক, রাজি', 'She is willing to help.', 'সে সাহায্য করতে ইচ্ছুক।', 592),
    ('wind', null, 'v.', 'B2', 'পাক খাওয়ানো; ঘোরানো', 'The road winds through the hills.', 'রাস্তাটি পাহাড়ের মধ্য দিয়ে এঁকেবেঁকে গেছে।', 593),
    ('wire', null, 'n.', 'B2', 'তার', 'Do not touch the electric wire.', 'বিদ্যুতের তারটি স্পর্শ করো না।', 594),
    ('wise', null, 'adj.', 'B2', 'বিজ্ঞ, বুদ্ধিমান', 'That was a wise choice.', 'ওটা একটি বিজ্ঞ পছন্দ ছিল।', 595),
    ('witness', null, 'n., v.', 'B2', 'সাক্ষী; সাক্ষী হওয়া', 'She was a witness to the accident.', 'সে দুর্ঘটনাটির একজন সাক্ষী ছিল।', 596),
    ('wound', null, 'n., v.', 'B2', 'ক্ষত, আঘাত; আহত করা', 'The wound healed slowly.', 'ক্ষতটি ধীরে ধীরে সেরে উঠল।', 597),
    ('wrap', null, 'v.', 'B2', 'মোড়ানো, জড়ানো', 'She wrapped the gift in paper.', 'সে উপহারটি কাগজে মুড়ল।', 598),
    ('zone', null, 'n.', 'B2', 'অঞ্চল, এলাকা', 'This is a no-parking zone.', 'এটি একটি গাড়ি রাখা নিষিদ্ধ এলাকা।', 599);
