-- V18 — seed vocabulary: Oxford 5000 (American English) additions, 702 rows.
-- Generated from authored Bengali glosses + bilingual examples (scratchpad/ox5000_*_chunk*.json).
-- Standalone reference data; see V11 for the table, V17 for the C1 level addition.

insert into vocabulary
    (headword, sense_label, part_of_speech, cefr_level, bn_gloss, example_en, example_bn, ordinal)
values
    ('absorb', null, 'v.', 'B2', 'শোষণ করা, আত্মস্থ করা', 'Plants absorb sunlight to grow.', 'গাছ বেড়ে ওঠার জন্য সূর্যালোক শোষণ করে।', 600),
    ('abstract', null, 'adj.', 'B2', 'বিমূর্ত', 'It''s hard to explain such an abstract idea.', 'এত বিমূর্ত ধারণা ব্যাখ্যা করা কঠিন।', 601),
    ('accent', null, 'n.', 'B2', 'উচ্চারণভঙ্গি, আঞ্চলিক টান', 'She speaks English with a French accent.', 'সে ফরাসি টানে ইংরেজি বলে।', 602),
    ('accidentally', null, 'adv.', 'B2', 'দুর্ঘটনাক্রমে, ভুলবশত', 'I accidentally deleted the file.', 'আমি ভুলবশত ফাইলটি মুছে ফেলেছি।', 603),
    ('accommodate', null, 'v.', 'B2', 'থাকার ব্যবস্থা করা, সমন্বয় করা', 'The hotel can accommodate two hundred guests.', 'হোটেলটিতে দুইশ অতিথির থাকার ব্যবস্থা আছে।', 604),
    ('accommodation', null, 'n.', 'B2', 'থাকার ব্যবস্থা, বাসস্থান', 'We booked accommodation near the beach.', 'আমরা সৈকতের কাছে থাকার ব্যবস্থা বুক করেছি।', 605),
    ('accomplish', null, 'v.', 'B2', 'সম্পন্ন করা, অর্জন করা', 'She worked hard to accomplish her goal.', 'সে তার লক্ষ্য অর্জন করতে কঠোর পরিশ্রম করেছে।', 606),
    ('accountant', null, 'n.', 'B2', 'হিসাবরক্ষক', 'My uncle works as an accountant.', 'আমার চাচা হিসাবরক্ষক হিসেবে কাজ করেন।', 607),
    ('accuracy', null, 'n.', 'B2', 'নির্ভুলতা, যথার্থতা', 'The device measures speed with great accuracy.', 'যন্ত্রটি গতি অত্যন্ত নির্ভুলভাবে পরিমাপ করে।', 608),
    ('accurately', null, 'adv.', 'B2', 'নির্ভুলভাবে', 'Please copy the numbers accurately.', 'দয়া করে সংখ্যাগুলো নির্ভুলভাবে লিখুন।', 609),
    ('acid', null, 'n.', 'B2', 'অ্যাসিড, অম্ল', 'The acid burned a hole in the cloth.', 'অ্যাসিডটি কাপড়ে একটি ছিদ্র তৈরি করল।', 610),
    ('acre', null, 'n.', 'B2', 'একর (জমির পরিমাপ)', 'The farm covers one acre of land.', 'খামারটি এক একর জমি জুড়ে বিস্তৃত।', 611),
    ('activate', null, 'v.', 'B2', 'সক্রিয় করা, চালু করা', 'Press this button to activate the alarm.', 'অ্যালার্ম সক্রিয় করতে এই বোতাম চাপুন।', 612),
    ('addiction', null, 'n.', 'B2', 'আসক্তি, নেশা', 'He struggled with a drug addiction.', 'সে মাদকাসক্তির সঙ্গে লড়াই করছিল।', 613),
    ('additionally', null, 'adv.', 'B2', 'অতিরিক্তভাবে, উপরন্তু', 'Additionally, the price includes breakfast.', 'উপরন্তু, দামের মধ্যে নাশতা অন্তর্ভুক্ত।', 614),
    ('adequate', null, 'adj.', 'B2', 'পর্যাপ্ত', 'We need adequate light to read.', 'পড়ার জন্য আমাদের পর্যাপ্ত আলো দরকার।', 615),
    ('adequately', null, 'adv.', 'B2', 'পর্যাপ্তভাবে', 'The room was not adequately heated.', 'ঘরটি পর্যাপ্তভাবে গরম রাখা হয়নি।', 616),
    ('adjust', null, 'v.', 'B2', 'সামঞ্জস্য করা, ঠিক করা', 'Please adjust your seat before takeoff.', 'উড্ডয়নের আগে আপনার আসন ঠিক করুন।', 617),
    ('affordable', null, 'adj.', 'B2', 'সাশ্রয়ী, সামর্থ্যের মধ্যে', 'We need affordable housing for everyone.', 'আমাদের সবার জন্য সাশ্রয়ী আবাসন দরকার।', 618),
    ('aged', null, 'adj.', 'B2', 'বয়স্ক, বয়সী', 'He looks after his aged parents.', 'সে তার বয়স্ক বাবা-মায়ের দেখাশোনা করে।', 619),
    ('agriculture', null, 'n.', 'B2', 'কৃষি', 'Agriculture is the main job in this village.', 'এই গ্রামের প্রধান কাজ কৃষি।', 620),
    ('AIDS', null, 'n.', 'B2', 'এইডস (একটি রোগ)', 'Doctors are working to prevent AIDS.', 'ডাক্তাররা এইডস প্রতিরোধে কাজ করছেন।', 621),
    ('alien', null, 'n.', 'B2', 'ভিনগ্রহী; বিদেশি নাগরিক', 'The movie is about an alien from space.', 'সিনেমাটি মহাকাশ থেকে আসা এক ভিনগ্রহীকে নিয়ে।', 622),
    ('alongside', null, 'prep.', 'B2', 'পাশাপাশি, সাথে', 'He parked his car alongside mine.', 'সে তার গাড়িটি আমার গাড়ির পাশে রাখল।', 623),
    ('altogether', null, 'adv.', 'B2', 'সম্পূর্ণভাবে, সব মিলিয়ে', 'The plan was altogether different from before.', 'পরিকল্পনাটি আগের থেকে সম্পূর্ণভাবে ভিন্ন ছিল।', 624),
    ('ambitious', null, 'adj.', 'B2', 'উচ্চাকাঙ্ক্ষী', 'She is an ambitious young lawyer.', 'সে একজন উচ্চাকাঙ্ক্ষী তরুণ আইনজীবী।', 625),
    ('ambulance', null, 'n.', 'B2', 'অ্যাম্বুলেন্স', 'They called an ambulance for the injured man.', 'তারা আহত লোকটির জন্য অ্যাম্বুলেন্স ডাকল।', 626),
    ('amusing', null, 'adj.', 'B2', 'মজাদার, চিত্তবিনোদনকর', 'He told an amusing story about his trip.', 'সে তার ভ্রমণ নিয়ে একটি মজাদার গল্প বলল।', 627),
    ('analyst', null, 'n.', 'B2', 'বিশ্লেষক', 'The analyst studies changes in the market.', 'বিশ্লেষক বাজারের পরিবর্তন নিয়ে গবেষণা করেন।', 628),
    ('ancestor', null, 'n.', 'B2', 'পূর্বপুরুষ', 'He wrote about his famous ancestor.', 'সে তার বিখ্যাত পূর্বপুরুষ সম্পর্কে লিখল।', 629),
    ('animation', null, 'n.', 'B2', 'অ্যানিমেশন, রেখাচিত্র চলচ্চিত্র', 'Kids love watching animation movies.', 'বাচ্চারা অ্যানিমেশন সিনেমা দেখতে পছন্দ করে।', 630),
    ('annually', null, 'adv.', 'B2', 'বার্ষিকভাবে, প্রতি বছর', 'The festival is held annually in May.', 'উৎসবটি প্রতি বছর মে মাসে অনুষ্ঠিত হয়।', 631),
    ('anticipate', null, 'v.', 'B2', 'প্রত্যাশা করা, পূর্বানুমান করা', 'We anticipate heavy rain tomorrow.', 'আমরা আগামীকাল ভারী বৃষ্টির প্রত্যাশা করছি।', 632),
    ('anxiety', null, 'n.', 'B2', 'উদ্বেগ, দুশ্চিন্তা', 'He felt anxiety before the exam.', 'পরীক্ষার আগে সে উদ্বেগ অনুভব করল।', 633),
    ('apology', null, 'n.', 'B2', 'ক্ষমাপ্রার্থনা', 'She wrote a letter of apology to her teacher.', 'সে তার শিক্ষকের কাছে ক্ষমাপ্রার্থনার চিঠি লিখল।', 634),
    ('applicant', null, 'n.', 'B2', 'আবেদনকারী', 'The applicant seemed very confident.', 'আবেদনকারীটি খুব আত্মবিশ্বাসী মনে হলো।', 635),
    ('appropriately', null, 'adv.', 'B2', 'যথাযথভাবে, উপযুক্তভাবে', 'Please dress appropriately for the interview.', 'সাক্ষাৎকারের জন্য যথাযথভাবে পোশাক পরুন।', 636),
    ('arrow', null, 'n.', 'B2', 'তীর (চিহ্ন বা অস্ত্র)', 'Follow the arrow to find the exit.', 'প্রস্থানপথ খুঁজে পেতে তীর চিহ্ন অনুসরণ করুন।', 637),
    ('artwork', null, 'n.', 'B2', 'শিল্পকর্ম', 'The museum displays artwork from many countries.', 'জাদুঘরে অনেক দেশের শিল্পকর্ম প্রদর্শিত হয়।', 638),
    ('asset', null, 'n.', 'B2', 'সম্পদ, মূল্যবান বৈশিষ্ট্য', 'Her experience is a great asset to the team.', 'তার অভিজ্ঞতা দলের জন্য একটি বড় সম্পদ।', 639),
    ('assign', null, 'v.', 'B2', 'দায়িত্ব দেওয়া, নির্ধারণ করা', 'The teacher will assign homework today.', 'শিক্ষক আজ বাড়ির কাজ নির্ধারণ করে দেবেন।', 640),
    ('assistance', null, 'n.', 'B2', 'সহায়তা', 'Thank you for your assistance with the project.', 'প্রকল্পে সহায়তার জন্য আপনাকে ধন্যবাদ।', 641),
    ('assumption', null, 'n.', 'B2', 'অনুমান, ধারণা', 'That is a false assumption about her.', 'তার সম্পর্কে এটি একটি ভুল অনুমান।', 642),
    ('assure', null, 'v.', 'B2', 'নিশ্চয়তা দেওয়া, আশ্বস্ত করা', 'I assure you the food is safe.', 'আমি আপনাকে নিশ্চয়তা দিচ্ছি খাবারটি নিরাপদ।', 643),
    ('astonishing', null, 'adj.', 'B2', 'বিস্ময়কর', 'The magician did an astonishing trick.', 'জাদুকর একটি বিস্ময়কর কৌশল দেখাল।', 644),
    ('athletic', null, 'adj.', 'B2', 'ক্রীড়াবিদসুলভ, সুঠাম', 'He has an athletic body from years of training.', 'বছরের পর বছর অনুশীলনে তার শরীর সুঠাম হয়েছে।', 645),
    ('attachment', null, 'n.', 'B2', 'সংযুক্তি; মায়া, সংযুক্ত হওয়ার অনুভূতি', 'She has a strong attachment to her hometown.', 'তার নিজ শহরের প্রতি গভীর মায়া আছে।', 646),
    ('audio', null, 'adj.', 'B2', 'শ্রবণ-সংক্রান্ত, অডিও', 'The audio quality of this video is poor.', 'এই ভিডিওটির অডিও মান খারাপ।', 647),
    ('awareness', null, 'n.', 'B2', 'সচেতনতা', 'The campaign raises awareness about pollution.', 'প্রচারাভিযানটি দূষণ সম্পর্কে সচেতনতা বাড়ায়।', 648),
    ('awkward', null, 'adj.', 'B2', 'বিব্রতকর, অস্বস্তিকর', 'There was an awkward silence in the room.', 'ঘরে একটি অস্বস্তিকর নীরবতা নেমে এলো।', 649),
    ('badge', null, 'n.', 'B2', 'ব্যাজ, পরিচয়সূচক চিহ্ন', 'The guard checked my badge at the door.', 'রক্ষী দরজায় আমার ব্যাজ পরীক্ষা করলেন।', 650),
    ('balanced', null, 'adj.', 'B2', 'সুষম, ভারসাম্যপূর্ণ', 'Eat a balanced diet every day.', 'প্রতিদিন সুষম খাদ্য গ্রহণ করুন।', 651),
    ('ballet', null, 'n.', 'B2', 'ব্যালে নৃত্য', 'She has danced ballet since childhood.', 'সে ছোটবেলা থেকেই ব্যালে নাচছে।', 652),
    ('balloon', null, 'n.', 'B2', 'বেলুন', 'The child held a red balloon.', 'শিশুটি একটি লাল বেলুন ধরে রেখেছিল।', 653),
    ('barely', null, 'adv.', 'B2', 'কোনোমতে, সবেমাত্র', 'I barely finished the race.', 'আমি কোনোমতে দৌড়টি শেষ করেছি।', 654),
    ('bargain', null, 'n.', 'B2', 'সস্তা দর, লাভজনক চুক্তি', 'This laptop was a real bargain.', 'এই ল্যাপটপটি সত্যিই সস্তায় পাওয়া গেছে।', 655),
    ('basement', null, 'n.', 'B2', 'বেসমেন্ট, ভূগর্ভস্থ তলা', 'We store old boxes in the basement.', 'আমরা পুরনো বাক্সগুলো বেসমেন্টে রাখি।', 656),
    ('basket', null, 'n.', 'B2', 'ঝুড়ি, বাস্কেট', 'She carried apples in a basket.', 'সে ঝুড়িতে আপেল বহন করছিল।', 657),
    ('bat', null, 'n.', 'B2', 'ব্যাট (খেলার); বাদুড়', 'He hit the ball with a bat.', 'সে ব্যাট দিয়ে বলটি আঘাত করল।', 658),
    ('beneficial', null, 'adj.', 'B2', 'উপকারী, কল্যাণকর', 'Exercise is beneficial for your health.', 'ব্যায়াম আপনার স্বাস্থ্যের জন্য উপকারী।', 659),
    ('beside', null, 'prep.', 'B2', 'পাশে', 'Sit beside me on the bench.', 'বেঞ্চে আমার পাশে বসো।', 660),
    ('besides', null, 'prep., adv.', 'B2', 'এছাড়াও, ছাড়াও', 'Besides English, she speaks French.', 'ইংরেজি ছাড়াও, সে ফরাসি ভাষায় কথা বলে।', 661),
    ('bias', null, 'n.', 'B2', 'পক্ষপাত, কুসংস্কার', 'The judge must avoid any bias.', 'বিচারককে যেকোনো পক্ষপাত এড়িয়ে চলতে হবে।', 662),
    ('bid', null, 'n., v.', 'B2', 'দরপত্র, দর হাঁকা; দরপত্র দেওয়া', 'The company made a bid for the contract.', 'কোম্পানিটি চুক্তির জন্য একটি দরপত্র দিল।', 663),
    ('biological', null, 'adj.', 'B2', 'জৈবিক', 'She met her biological father last year.', 'সে গত বছর তার জৈবিক বাবার সাথে দেখা করেছিল।', 664),
    ('blanket', null, 'n.', 'B2', 'কম্বল', 'I pulled the blanket over me at night.', 'রাতে আমি নিজের গায়ে কম্বল টেনে নিলাম।', 665),
    ('blow', null, 'n.', 'B2', 'আঘাত, ধাক্কা', 'Losing the game was a big blow to the team.', 'খেলায় হেরে যাওয়া দলটির জন্য বড় একটি আঘাত ছিল।', 666),
    ('bold', null, 'adj.', 'B2', 'সাহসী; গাঢ় (মোটা অক্ষর)', 'It was a bold decision to quit his job.', 'চাকরি ছেড়ে দেওয়াটা একটি সাহসী সিদ্ধান্ত ছিল।', 667),
    ('bombing', null, 'n.', 'B2', 'বোমা হামলা', 'The bombing destroyed several buildings.', 'বোমা হামলায় বেশ কয়েকটি ভবন ধ্বংস হয়েছে।', 668),
    ('boost', null, 'v., n.', 'B2', 'বাড়ানো, চাঙ্গা করা; উদ্দীপনা', 'The win will boost the team''s confidence.', 'জয়টি দলের আত্মবিশ্বাস বাড়িয়ে দেবে।', 669),
    ('bound', null, 'adj.', 'B2', 'বাধ্য; নির্দিষ্ট গন্তব্যের উদ্দেশ্যে', 'The plane is bound for London.', 'উড়োজাহাজটি লন্ডনের উদ্দেশ্যে রওনা হয়েছে।', 670),
    ('brick', null, 'n.', 'B2', 'ইট', 'The house is made of red brick.', 'বাড়িটি লাল ইট দিয়ে তৈরি।', 671),
    ('briefly', null, 'adv.', 'B2', 'সংক্ষেপে', 'Let me briefly explain the plan.', 'আমাকে সংক্ষেপে পরিকল্পনাটি ব্যাখ্যা করতে দিন।', 672),
    ('broadcaster', null, 'n.', 'B2', 'সম্প্রচারক (রেডিও/টিভি)', 'She works as a news broadcaster.', 'সে একজন সংবাদ সম্প্রচারক হিসেবে কাজ করে।', 673),
    ('broadly', null, 'adv.', 'B2', 'বিস্তৃতভাবে, মোটামুটিভাবে', 'Broadly speaking, the plan worked well.', 'বিস্তৃতভাবে বলতে গেলে, পরিকল্পনাটি ভালোভাবে কাজ করেছে।', 674),
    ('buck', null, 'n.', 'B2', 'ডলার (কথ্য); পুরুষ হরিণ', 'It only cost me one buck.', 'এটির দাম আমার মাত্র এক ডলার পড়েছে।', 675),
    ('bug', null, 'n.', 'B2', 'পোকা; ত্রুটি (সফটওয়্যার)', 'There is a bug in this computer program.', 'এই কম্পিউটার প্রোগ্রামে একটি ত্রুটি আছে।', 676),
    ('cabin', null, 'n.', 'B2', 'কেবিন, কুটির', 'We stayed in a small cabin in the woods.', 'আমরা জঙ্গলের মধ্যে একটি ছোট কুটিরে থেকেছিলাম।', 677),
    ('canal', null, 'n.', 'B2', 'খাল', 'Boats travel through the canal every day.', 'নৌকাগুলো প্রতিদিন খাল দিয়ে চলাচল করে।', 678),
    ('candle', null, 'n.', 'B2', 'মোমবাতি', 'She lit a candle in the dark room.', 'সে অন্ধকার ঘরে একটি মোমবাতি জ্বালাল।', 679),
    ('carbon', null, 'n.', 'B2', 'কার্বন', 'Cars produce carbon when they burn fuel.', 'গাড়ি জ্বালানি পোড়ালে কার্বন উৎপন্ন করে।', 680),
    ('castle', null, 'n.', 'B2', 'দুর্গ, প্রাসাদ', 'The old castle stands on a hill.', 'পুরনো দুর্গটি একটি পাহাড়ের উপর দাঁড়িয়ে আছে।', 681),
    ('casual', null, 'adj.', 'B2', 'অনানুষ্ঠানিক, নৈমিত্তিক', 'You can wear casual clothes to the party.', 'আপনি পার্টিতে অনানুষ্ঠানিক পোশাক পরতে পারেন।', 682),
    ('cave', null, 'n.', 'B2', 'গুহা', 'The bear was sleeping inside the cave.', 'ভালুকটি গুহার ভেতরে ঘুমাচ্ছিল।', 683),
    ('certainty', null, 'n.', 'B2', 'নিশ্চয়তা', 'There is no certainty that it will rain.', 'বৃষ্টি হবে তার কোনো নিশ্চয়তা নেই।', 684),
    ('certificate', null, 'n.', 'B2', 'সনদপত্র, প্রশংসাপত্র', 'She received a certificate for finishing the course.', 'কোর্স শেষ করার জন্য সে একটি সনদপত্র পেল।', 685),
    ('challenging', null, 'adj.', 'B2', 'চ্যালেঞ্জিং, কঠিন', 'This is a challenging job for a beginner.', 'একজন নতুনের জন্য এটি একটি চ্যালেঞ্জিং কাজ।', 686),
    ('championship', null, 'n.', 'B2', 'চ্যাম্পিয়নশিপ', 'Our team won the national championship.', 'আমাদের দল জাতীয় চ্যাম্পিয়নশিপ জিতেছে।', 687),
    ('charming', null, 'adj.', 'B2', 'মনোমুগ্ধকর, আকর্ষণীয়', 'The old town has a charming atmosphere.', 'পুরনো শহরটির পরিবেশ মনোমুগ্ধকর।', 688),
    ('chase', null, 'v., n.', 'B2', 'তাড়া করা; তাড়া', 'The dog began to chase the cat.', 'কুকুরটি বিড়ালটিকে তাড়া করতে শুরু করল।', 689),
    ('cheek', null, 'n.', 'B2', 'গাল', 'She kissed him on the cheek.', 'সে তার গালে চুমু দিল।', 690),
    ('cheer', null, 'v., n.', 'B2', 'উল্লাস করা; উল্লাস', 'The crowd began to cheer loudly.', 'জনতা জোরে উল্লাস করতে শুরু করল।', 691),
    ('chop', null, 'v.', 'B2', 'কাটা, টুকরো করা', 'She likes to chop vegetables for dinner.', 'সে রাতের খাবারের জন্য সবজি কাটতে পছন্দ করে।', 692),
    ('circuit', null, 'n.', 'B2', 'বর্তনী, চক্র', 'The wire connects to complete the circuit.', 'বর্তনী সম্পূর্ণ করতে তারটি সংযুক্ত করা হয়।', 693),
    ('civilization', null, 'n.', 'B2', 'সভ্যতা', 'This river valley is home to an ancient civilization.', 'এই নদী উপত্যকা একটি প্রাচীন সভ্যতার আবাসস্থল।', 694),
    ('clarify', null, 'v.', 'B2', 'স্পষ্ট করা', 'Can you clarify what you mean?', 'আপনি কী বোঝাতে চাইছেন তা কি স্পষ্ট করতে পারবেন?', 695),
    ('classify', null, 'v.', 'B2', 'শ্রেণীবদ্ধ করা', 'Scientists classify animals into different groups.', 'বিজ্ঞানীরা প্রাণীদের বিভিন্ন দলে শ্রেণীবদ্ধ করেন।', 696),
    ('cliff', null, 'n.', 'B2', 'খাড়া পাহাড়, উপকূলীয় খাড়া ঢাল', 'The house stands on the edge of a cliff.', 'বাড়িটি একটি খাড়া পাহাড়ের কিনারায় দাঁড়িয়ে আছে।', 697),
    ('clinic', null, 'n.', 'B2', 'ক্লিনিক, চিকিৎসাকেন্দ্র', 'She works at a small local clinic.', 'সে একটি ছোট স্থানীয় ক্লিনিকে কাজ করে।', 698),
    ('clip', null, 'n.', 'B2', 'ক্লিপ (ছোট অংশ বা ধরার যন্ত্র)', 'I watched a short clip of the movie.', 'আমি সিনেমাটির একটি ছোট ক্লিপ দেখলাম।', 699),
    ('coincidence', null, 'n.', 'B2', 'কাকতালীয় ঘটনা', 'Meeting you here is a strange coincidence.', 'এখানে তোমার সাথে দেখা হওয়া একটি অদ্ভুত কাকতালীয় ঘটনা।', 700),
    ('collector', null, 'n.', 'B2', 'সংগ্রাহক', 'He is a collector of old coins.', 'সে পুরনো মুদ্রার একজন সংগ্রাহক।', 701),
    ('colony', null, 'n.', 'B2', 'উপনিবেশ; প্রাণীর দল/বসতি', 'India was once a British colony.', 'ভারত একসময় ব্রিটিশদের একটি উপনিবেশ ছিল।', 702),
    ('colorful', null, 'adj.', 'B2', 'রঙিন', 'The market was full of colorful fruits.', 'বাজারটি রঙিন ফলে ভরা ছিল।', 703),
    ('comic', null, 'adj., n.', 'B2', 'হাস্যরসাত্মক; কমিক বই', 'He bought a comic to read on the bus.', 'সে বাসে পড়ার জন্য একটি কমিক বই কিনল।', 704),
    ('commander', null, 'n.', 'B2', 'সেনাপতি, অধিনায়ক', 'The commander gave orders to the soldiers.', 'সেনাপতি সৈনিকদের নির্দেশ দিলেন।', 705),
    ('comparative', null, 'adj.', 'B2', 'তুলনামূলক', 'We studied the comparative cost of the two plans.', 'আমরা দুটি পরিকল্পনার তুলনামূলক খরচ যাচাই করেছি।', 706),
    ('completion', null, 'n.', 'B2', 'সমাপ্তি, সম্পূর্ণতা', 'The bridge is near completion.', 'সেতুটি প্রায় সমাপ্তির কাছাকাছি।', 707),
    ('compose', null, 'v.', 'B2', 'রচনা করা (গান/লেখা), সৃষ্টি করা', 'She likes to compose songs for films.', 'সে চলচ্চিত্রের জন্য গান রচনা করতে পছন্দ করে।', 708),
    ('composer', null, 'n.', 'B2', 'সুরকার', 'The composer wrote music for the movie.', 'সুরকার চলচ্চিত্রটির জন্য সুর সৃষ্টি করলেন।', 709),
    ('compound', null, 'n.', 'B2', 'যৌগ (রাসায়নিক); ঘেরাও করা এলাকা', 'Water is a compound of hydrogen and oxygen.', 'পানি হাইড্রোজেন ও অক্সিজেনের একটি যৌগ।', 710),
    ('comprehensive', null, 'adj.', 'B2', 'ব্যাপক, বিস্তৃত', 'The book gives a comprehensive view of history.', 'বইটি ইতিহাসের একটি ব্যাপক ধারণা দেয়।', 711),
    ('comprise', null, 'v.', 'B2', 'গঠিত হওয়া, অন্তর্ভুক্ত থাকা', 'Ten members comprise the whole team.', 'দশজন সদস্য নিয়ে পুরো দলটি গঠিত।', 712),
    ('compulsory', null, 'adj.', 'B2', 'বাধ্যতামূলক', 'Wearing a helmet is compulsory here.', 'এখানে হেলমেট পরা বাধ্যতামূলক।', 713),
    ('concrete', null, 'adj., n.', 'B2', 'কংক্রিট; সুনির্দিষ্ট, বাস্তব', 'They poured concrete for the new floor.', 'তারা নতুন মেঝের জন্য কংক্রিট ঢালল।', 714),
    ('confess', null, 'v.', 'B2', 'স্বীকার করা, দোষ স্বীকার করা', 'He will confess if you ask him.', 'তুমি জিজ্ঞাসা করলে সে স্বীকার করবে।', 715),
    ('confusion', null, 'n.', 'B2', 'বিভ্রান্তি', 'There was some confusion about the time.', 'সময় নিয়ে কিছুটা বিভ্রান্তি ছিল।', 716),
    ('consequently', null, 'adv.', 'B2', 'ফলস্বরূপ, সেই কারণে', 'He was late; consequently, he missed the bus.', 'সে দেরি করেছিল; ফলস্বরূপ, বাসটি মিস করল।', 717),
    ('conservation', null, 'n.', 'B2', 'সংরক্ষণ', 'The group works on forest conservation.', 'দলটি বন সংরক্ষণের কাজ করে।', 718),
    ('considerable', null, 'adj.', 'B2', 'যথেষ্ট, উল্লেখযোগ্য', 'He spent a considerable amount of time on this.', 'সে এতে যথেষ্ট পরিমাণ সময় ব্যয় করেছে।', 719),
    ('considerably', null, 'adv.', 'B2', 'যথেষ্ট পরিমাণে', 'Prices have risen considerably this year.', 'এই বছর দাম যথেষ্ট পরিমাণে বেড়েছে।', 720),
    ('consistently', null, 'adv.', 'B2', 'ধারাবাহিকভাবে', 'She has consistently scored well in exams.', 'সে পরীক্ষায় ধারাবাহিকভাবে ভালো ফল করেছে।', 721),
    ('conspiracy', null, 'n.', 'B2', 'ষড়যন্ত্র', 'The film is about a political conspiracy.', 'চলচ্চিত্রটি একটি রাজনৈতিক ষড়যন্ত্র নিয়ে।', 722),
    ('consult', null, 'v.', 'B2', 'পরামর্শ নেওয়া', 'You should consult a doctor about this pain.', 'এই ব্যথা নিয়ে আপনার একজন ডাক্তারের পরামর্শ নেওয়া উচিত।', 723),
    ('consultant', null, 'n.', 'B2', 'পরামর্শদাতা', 'She works as a business consultant.', 'সে একজন ব্যবসায়িক পরামর্শদাতা হিসেবে কাজ করে।', 724),
    ('consumption', null, 'n.', 'B2', 'ভোগ, ব্যবহার (খরচ)', 'The country reduced its energy consumption.', 'দেশটি তার জ্বালানি ভোগ কমিয়েছে।', 725),
    ('controversial', null, 'adj.', 'B2', 'বিতর্কিত', 'He made a controversial statement on TV.', 'সে টিভিতে একটি বিতর্কিত মন্তব্য করেছে।', 726),
    ('controversy', null, 'n.', 'B2', 'বিতর্ক', 'The new law caused a lot of controversy.', 'নতুন আইনটি ব্যাপক বিতর্কের জন্ম দিয়েছে।', 727),
    ('convenience', null, 'n.', 'B2', 'সুবিধা', 'The store is open all night for your convenience.', 'আপনার সুবিধার জন্য দোকানটি সারা রাত খোলা থাকে।', 728),
    ('convention', null, 'n.', 'B2', 'প্রথা, রীতি; সম্মেলন', 'It is a convention to shake hands when meeting.', 'দেখা হলে হাত মেলানো একটি প্রথা।', 729),
    ('conventional', null, 'adj.', 'B2', 'প্রথাগত, প্রচলিত', 'She rejected the conventional way of teaching.', 'সে শিক্ষাদানের প্রথাগত পদ্ধতি প্রত্যাখ্যান করেছে।', 730),
    ('convey', null, 'v.', 'B2', 'বহন করা, প্রকাশ করা (ভাব)', 'Her eyes convey deep sadness.', 'তার চোখ গভীর দুঃখ প্রকাশ করে।', 731),
    ('convincing', null, 'adj.', 'B2', 'বিশ্বাসযোগ্য, প্ররোচক', 'He gave a convincing argument for the plan.', 'সে পরিকল্পনাটির পক্ষে একটি বিশ্বাসযোগ্য যুক্তি দিল।', 732),
    ('cop', null, 'n.', 'B2', 'পুলিশ (কথ্য)', 'The cop stopped the car for speeding.', 'পুলিশটি গতিসীমা ভাঙার জন্য গাড়িটি থামাল।', 733),
    ('cope', null, 'v.', 'B2', 'মোকাবিলা করা, সামলানো', 'It is hard to cope with so much stress.', 'এত চাপ মোকাবিলা করা কঠিন।', 734),
    ('corporation', null, 'n.', 'B2', 'কর্পোরেশন, বৃহৎ কোম্পানি', 'He works for a large corporation.', 'সে একটি বড় কর্পোরেশনে কাজ করে।', 735),
    ('corridor', null, 'n.', 'B2', 'করিডোর, বারান্দা (ভবনের ভেতরে)', 'The classroom is at the end of the corridor.', 'ক্লাসরুমটি করিডোরের শেষ প্রান্তে অবস্থিত।', 736),
    ('counter', 'long flat surface', 'n.', 'B2', 'কাউন্টার, লম্বা সমতল টেবিল', 'She put the bags on the kitchen counter.', 'সে ব্যাগগুলো রান্নাঘরের কাউন্টারে রাখল।', 737),
    ('coverage', null, 'n.', 'B2', 'সংবাদ প্রচার, কাভারেজ; বীমার আওতা', 'The news gave full coverage of the election.', 'সংবাদমাধ্যমটি নির্বাচনের পূর্ণাঙ্গ কাভারেজ দিয়েছে।', 738),
    ('cowboy', null, 'n.', 'B2', 'কাউবয়, রাখাল (আমেরিকান)', 'The cowboy rode his horse across the field.', 'কাউবয়টি মাঠ জুড়ে তার ঘোড়ায় চড়ল।', 739),
    ('crack', null, 'v., n.', 'B2', 'ফাটল ধরা/ফাটানো; ফাটল', 'The glass began to crack in the heat.', 'গরমে কাচটি ফাটতে শুরু করল।', 740),
    ('craft', null, 'n.', 'B2', 'কারুশিল্প, নৈপুণ্য', 'Pottery is a traditional craft.', 'মৃৎশিল্প একটি ঐতিহ্যবাহী কারুশিল্প।', 741),
    ('creativity', null, 'n.', 'B2', 'সৃজনশীলতা', 'The job requires creativity.', 'চাকরিটির জন্য সৃজনশীলতা প্রয়োজন।', 742),
    ('critically', null, 'adv.', 'B2', 'গুরুতরভাবে, সংকটজনকভাবে', 'The patient is critically ill.', 'রোগীর অবস্থা গুরুতর।', 743),
    ('cruise', null, 'n., v.', 'B2', 'প্রমোদভ্রমণ (জাহাজে); ধীর গতিতে ভ্রমণ করা', 'We went on a Caribbean cruise.', 'আমরা ক্যারিবিয়ানে একটি প্রমোদভ্রমণে গিয়েছিলাম।', 744),
    ('cue', null, 'n.', 'B2', 'ইঙ্গিত, সংকেত', 'Wait for my cue to start.', 'শুরু করার জন্য আমার ইঙ্গিতের অপেক্ষা করো।', 745),
    ('curious', null, 'adj.', 'B2', 'কৌতূহলী', 'The curious child asked many questions.', 'কৌতূহলী শিশুটি অনেক প্রশ্ন জিজ্ঞেস করল।', 746),
    ('curriculum', null, 'n.', 'B2', 'পাঠ্যক্রম', 'Math is part of the school curriculum.', 'গণিত স্কুলের পাঠ্যক্রমের অংশ।', 747),
    ('cute', null, 'adj.', 'B2', 'সুন্দর, আদুরে', 'The puppy looks so cute.', 'কুকুরছানাটি দেখতে খুব আদুরে।', 748),
    ('dairy', null, 'n., adj.', 'B2', 'দুগ্ধজাত দ্রব্য; দুগ্ধজাত', 'Dairy products are rich in calcium.', 'দুগ্ধজাত দ্রব্যে প্রচুর ক্যালসিয়াম থাকে।', 749),
    ('dare', null, 'v.', 'B2', 'সাহস করা', 'He didn''t dare to speak.', 'সে কথা বলার সাহস করল না।', 750),
    ('darkness', null, 'n.', 'B2', 'অন্ধকার', 'The room was full of darkness.', 'ঘরটি অন্ধকারে পূর্ণ ছিল।', 751),
    ('database', null, 'n.', 'B2', 'উপাত্তভান্ডার, ডেটাবেস', 'We store all data in this database.', 'আমরা সব তথ্য এই ডেটাবেসে সংরক্ষণ করি।', 752),
    ('deadline', null, 'n.', 'B2', 'সময়সীমা, শেষ তারিখ', 'The deadline for the project is Friday.', 'প্রকল্পটির সময়সীমা শুক্রবার।', 753),
    ('deadly', null, 'adj.', 'B2', 'মারাত্মক, প্রাণঘাতী', 'The snake''s bite is deadly.', 'সাপটির কামড় প্রাণঘাতী।', 754),
    ('dealer', null, 'n.', 'B2', 'বিক্রেতা, ব্যবসায়ী', 'He is a car dealer.', 'তিনি একজন গাড়ি বিক্রেতা।', 755),
    ('deck', null, 'n.', 'B2', 'জাহাজের ডেক', 'We stood on the deck of the ship.', 'আমরা জাহাজের ডেকে দাঁড়িয়ে ছিলাম।', 756),
    ('defender', null, 'n.', 'B2', 'রক্ষক; ডিফেন্ডার (খেলায়)', 'The defender blocked the shot.', 'ডিফেন্ডারটি শটটি আটকে দিল।', 757),
    ('delete', null, 'v.', 'B2', 'মুছে ফেলা', 'Please delete this file.', 'দয়া করে এই ফাইলটি মুছে ফেলো।', 758),
    ('delighted', null, 'adj.', 'B2', 'আনন্দিত, উৎফুল্ল', 'She was delighted with the gift.', 'সে উপহার পেয়ে আনন্দিত হলো।', 759),
    ('democracy', null, 'n.', 'B2', 'গণতন্ত্র', 'India is the largest democracy.', 'ভারত সবচেয়ে বড় গণতন্ত্র।', 760),
    ('democratic', null, 'adj.', 'B2', 'গণতান্ত্রিক', 'They held a democratic election.', 'তারা একটি গণতান্ত্রিক নির্বাচন অনুষ্ঠিত করল।', 761),
    ('demonstration', null, 'n.', 'B2', 'বিক্ষোভ', 'Thousands joined the demonstration.', 'হাজার হাজার মানুষ বিক্ষোভে যোগ দিল।', 762),
    ('depart', null, 'v.', 'B2', 'ছেড়ে যাওয়া, রওনা হওয়া', 'The train will depart at noon.', 'ট্রেনটি দুপুরে ছেড়ে যাবে।', 763),
    ('dependent', null, 'adj.', 'B2', 'নির্ভরশীল', 'Children are dependent on their parents.', 'শিশুরা তাদের বাবা-মায়ের উপর নির্ভরশীল।', 764),
    ('deposit', null, 'n., v.', 'B2', 'জমা (অর্থ); জমা দেওয়া', 'Please deposit the money in the bank.', 'টাকাটি ব্যাংকে জমা দিন।', 765),
    ('depression', null, 'n.', 'B2', 'বিষণ্নতা', 'He suffered from depression.', 'সে বিষণ্নতায় ভুগছিল।', 766),
    ('derive', null, 'v.', 'B2', 'উদ্ভূত হওয়া, লাভ করা', 'She likes to derive pleasure from reading.', 'সে পড়াশোনা থেকে আনন্দ লাভ করতে পছন্দ করে।', 767),
    ('desperately', null, 'adv.', 'B2', 'মরিয়া হয়ে, প্রাণপণে', 'He desperately needed a job.', 'তার প্রাণপণে একটি চাকরি দরকার ছিল।', 768),
    ('destruction', null, 'n.', 'B2', 'ধ্বংস', 'The storm caused massive destruction.', 'ঝড়টি ব্যাপক ধ্বংস ডেকে আনল।', 769),
    ('determination', null, 'n.', 'B2', 'দৃঢ়সংকল্প, দৃঢ়তা', 'She showed great determination.', 'সে দারুণ দৃঢ়সংকল্প দেখাল।', 770),
    ('devote', null, 'v.', 'B2', 'উৎসর্গ করা, নিবেদন করা', 'He likes to devote his time to charity.', 'সে দাতব্য কাজে তার সময় উৎসর্গ করতে পছন্দ করে।', 771),
    ('differ', null, 'v.', 'B2', 'ভিন্ন হওয়া, পার্থক্য থাকা', 'Our opinions differ on this.', 'এই বিষয়ে আমাদের মতামত ভিন্ন।', 772),
    ('dime', null, 'n.', 'B2', 'ডাইম (দশ সেন্টের মুদ্রা)', 'He found a dime on the floor.', 'সে মেঝেতে একটি ডাইম কুড়িয়ে পেল।', 773),
    ('disability', null, 'n.', 'B2', 'প্রতিবন্ধিতা', 'The ramp helps people with a disability.', 'র‍্যাম্পটি প্রতিবন্ধিতাগ্রস্ত মানুষদের সাহায্য করে।', 774),
    ('disabled', null, 'adj.', 'B2', 'প্রতিবন্ধী', 'The building has disabled parking.', 'ভবনটিতে প্রতিবন্ধী ব্যক্তিদের জন্য পার্কিং আছে।', 775),
    ('disagreement', null, 'n.', 'B2', 'মতবিরোধ, দ্বিমত', 'They had a disagreement about money.', 'টাকা নিয়ে তাদের মধ্যে মতবিরোধ হলো।', 776),
    ('disappoint', null, 'v.', 'B2', 'হতাশ করা', 'I don''t want to disappoint you.', 'আমি তোমাকে হতাশ করতে চাই না।', 777),
    ('disappointment', null, 'n.', 'B2', 'হতাশা', 'Losing the match was a big disappointment.', 'ম্যাচ হারাটা বড় হতাশার ছিল।', 778),
    ('discourage', null, 'v.', 'B2', 'নিরুৎসাহিত করা', 'Don''t let failure discourage you.', 'ব্যর্থতা যেন তোমাকে নিরুৎসাহিত না করে।', 779),
    ('disorder', null, 'n.', 'B2', 'ব্যাধি, রোগ', 'She has an eating disorder.', 'তার একটি খাদ্যাভ্যাসজনিত ব্যাধি আছে।', 780),
    ('distant', null, 'adj.', 'B2', 'দূরবর্তী', 'They live in a distant village.', 'তারা একটি দূরবর্তী গ্রামে থাকে।', 781),
    ('distinct', null, 'adj.', 'B2', 'স্বতন্ত্র, স্পষ্ট', 'The two smells are quite distinct.', 'গন্ধ দুটি বেশ স্বতন্ত্র।', 782),
    ('distinguish', null, 'v.', 'B2', 'পার্থক্য করা, চিহ্নিত করা', 'Can you distinguish these two colors?', 'তুমি কি এই দুই রঙের পার্থক্য করতে পারো?', 783),
    ('distract', null, 'v.', 'B2', 'মনোযোগ বিঘ্নিত করা', 'Noise can distract students in class.', 'শব্দ ক্লাসে শিক্ষার্থীদের মনোযোগ বিঘ্নিত করতে পারে।', 784),
    ('disturb', null, 'v.', 'B2', 'বিরক্ত করা, ব্যাঘাত ঘটানো', 'Please don''t disturb the baby.', 'দয়া করে শিশুটিকে বিরক্ত করো না।', 785),
    ('dive', null, 'v., n.', 'B2', 'ডুব দেওয়া; ডুব', 'They dive into the lake every morning.', 'তারা প্রতিদিন সকালে হ্রদে ডুব দেয়।', 786),
    ('diverse', null, 'adj.', 'B2', 'বৈচিত্র্যময়', 'The city has a diverse population.', 'শহরটির জনসংখ্যা বৈচিত্র্যময়।', 787),
    ('diversity', null, 'n.', 'B2', 'বৈচিত্র্য', 'The school celebrates cultural diversity.', 'স্কুলটি সাংস্কৃতিক বৈচিত্র্য উদযাপন করে।', 788),
    ('divorce', null, 'n., v.', 'B2', 'বিবাহবিচ্ছেদ; বিবাহবিচ্ছেদ করা', 'They decided to get a divorce.', 'তারা বিবাহবিচ্ছেদ ঘটানোর সিদ্ধান্ত নিল।', 789),
    ('dominant', null, 'adj.', 'B2', 'প্রভাবশালী, প্রধান', 'English is the dominant language here.', 'এখানে ইংরেজি প্রধান ভাষা।', 790),
    ('donation', null, 'n.', 'B2', 'অনুদান, দান', 'They made a large donation to the school.', 'তারা স্কুলে বড় অঙ্কের অনুদান দিল।', 791),
    ('dot', null, 'n.', 'B2', 'বিন্দু', 'Draw a dot on the paper.', 'কাগজে একটি বিন্দু আঁকো।', 792),
    ('dramatically', null, 'adv.', 'B2', 'নাটকীয়ভাবে', 'Prices rose dramatically last year.', 'গত বছর দাম নাটকীয়ভাবে বেড়ে গেল।', 793),
    ('drought', null, 'n.', 'B2', 'খরা', 'The drought destroyed the crops.', 'খরা ফসল নষ্ট করে দিল।', 794),
    ('dull', null, 'adj.', 'B2', 'নিরস, বিরক্তিকর', 'The movie was dull.', 'সিনেমাটি নিরস ছিল।', 795),
    ('dump', null, 'v.', 'B2', 'ফেলে দেওয়া, স্তূপ করা', 'Don''t dump garbage here.', 'এখানে আবর্জনা ফেলো না।', 796),
    ('duration', null, 'n.', 'B2', 'স্থিতিকাল, ব্যাপ্তি', 'The flight duration is six hours.', 'ফ্লাইটের স্থিতিকাল ছয় ঘণ্টা।', 797),
    ('dynamic', null, 'adj.', 'B2', 'গতিশীল, প্রাণবন্ত', 'She has a dynamic personality.', 'তার ব্যক্তিত্ব গতিশীল ও প্রাণবন্ত।', 798),
    ('eager', null, 'adj.', 'B2', 'উৎসুক, আগ্রহী', 'The students were eager to learn.', 'শিক্ষার্থীরা শিখতে আগ্রহী ছিল।', 799),
    ('economics', null, 'n.', 'B2', 'অর্থনীতি (বিষয়)', 'She studies economics at university.', 'সে বিশ্ববিদ্যালয়ে অর্থনীতি নিয়ে পড়ে।', 800),
    ('economist', null, 'n.', 'B2', 'অর্থনীতিবিদ', 'The economist predicted a recession.', 'অর্থনীতিবিদ মন্দার পূর্বাভাস দিলেন।', 801),
    ('editorial', null, 'adj.', 'B2', 'সম্পাদকীয়', 'The newspaper made an editorial decision.', 'পত্রিকাটি একটি সম্পাদকীয় সিদ্ধান্ত নিল।', 802),
    ('efficiently', null, 'adv.', 'B2', 'দক্ষতার সাথে', 'The team worked efficiently.', 'দলটি দক্ষতার সাথে কাজ করল।', 803),
    ('elbow', null, 'n.', 'B2', 'কনুই', 'She hurt her elbow while falling.', 'পড়ে গিয়ে সে তার কনুইয়ে ব্যথা পেল।', 804),
    ('electronics', null, 'n.', 'B2', 'ইলেকট্রনিক্স', 'He studies electronics engineering.', 'সে ইলেকট্রনিক্স প্রকৌশল নিয়ে পড়ে।', 805),
    ('elegant', null, 'adj.', 'B2', 'মার্জিত, রুচিসম্পন্ন', 'She wore an elegant dress.', 'সে একটি মার্জিত পোশাক পরেছিল।', 806),
    ('elementary', null, 'adj.', 'B2', 'প্রাথমিক', 'He teaches at an elementary school.', 'সে একটি প্রাথমিক বিদ্যালয়ে পড়ায়।', 807),
    ('eliminate', null, 'v.', 'B2', 'বাদ দেওয়া, দূর করা', 'We need to eliminate this problem.', 'আমাদের এই সমস্যাটি দূর করতে হবে।', 808),
    ('embrace', null, 'v.', 'B2', 'আলিঙ্গন করা', 'She will embrace her mother at the airport.', 'সে বিমানবন্দরে তার মাকে আলিঙ্গন করবে।', 809),
    ('emission', null, 'n.', 'B2', 'নিঃসরণ (গ্যাস)', 'This car has low emission levels.', 'এই গাড়ির নিঃসরণের মাত্রা কম।', 810),
    ('emotionally', null, 'adv.', 'B2', 'আবেগগতভাবে', 'The film was emotionally powerful.', 'চলচ্চিত্রটি আবেগগতভাবে শক্তিশালী ছিল।', 811),
    ('empire', null, 'n.', 'B2', 'সাম্রাজ্য', 'The Roman Empire covered many countries.', 'রোমান সাম্রাজ্য অনেক দেশজুড়ে বিস্তৃত ছিল।', 812),
    ('enjoyable', null, 'adj.', 'B2', 'উপভোগ্য', 'The trip was very enjoyable.', 'ভ্রমণটি খুবই উপভোগ্য ছিল।', 813),
    ('entertaining', null, 'adj.', 'B2', 'বিনোদনমূলক, আনন্দদায়ক', 'The show was entertaining.', 'অনুষ্ঠানটি বিনোদনমূলক ছিল।', 814),
    ('entrepreneur', null, 'n.', 'B2', 'উদ্যোক্তা', 'She became a successful entrepreneur.', 'সে একজন সফল উদ্যোক্তা হয়ে উঠল।', 815),
    ('envelope', null, 'n.', 'B2', 'খাম', 'He sealed the envelope.', 'সে খামটি সিল করল।', 816),
    ('equip', null, 'v.', 'B2', 'সজ্জিত করা, প্রস্তুত করা', 'This course will equip you with new skills.', 'এই কোর্স তোমাকে নতুন দক্ষতায় সজ্জিত করবে।', 817),
    ('equivalent', null, 'n., adj.', 'B2', 'সমতুল্য; সমপরিমাণ', 'A kilometer is roughly equivalent to 0.6 miles.', 'এক কিলোমিটার প্রায় ০.৬ মাইলের সমতুল্য।', 818),
    ('era', null, 'n.', 'B2', 'যুগ', 'We live in the digital era.', 'আমরা ডিজিটাল যুগে বাস করি।', 819),
    ('erupt', null, 'v.', 'B2', 'অগ্ন্যুৎপাত ঘটা, বিস্ফোরিত হওয়া', 'The volcano could erupt any time.', 'আগ্নেয়গিরিটি যেকোনো সময় অগ্ন্যুৎপাত ঘটাতে পারে।', 820),
    ('essentially', null, 'adv.', 'B2', 'মূলত', 'The two plans are essentially the same.', 'দুটি পরিকল্পনা মূলত একই।', 821),
    ('ethic', null, 'n.', 'B2', 'নীতি, নৈতিকতা', 'She has a strong work ethic.', 'কাজের প্রতি তার দৃঢ় নিষ্ঠা আছে।', 822),
    ('ethnic', null, 'adj.', 'B2', 'জাতিগত, নৃতাত্ত্বিক', 'The city has many ethnic groups.', 'শহরটিতে অনেক জাতিগত গোষ্ঠী আছে।', 823),
    ('evaluation', null, 'n.', 'B2', 'মূল্যায়ন', 'The teacher wrote a fair evaluation.', 'শিক্ষক একটি ন্যায্য মূল্যায়ন লিখলেন।', 824),
    ('evident', null, 'adj.', 'B2', 'স্পষ্ট, প্রতীয়মান', 'Her talent was evident from the start.', 'তার প্রতিভা শুরু থেকেই স্পষ্ট ছিল।', 825),
    ('evolution', null, 'n.', 'B2', 'বিবর্তন', 'Darwin studied the evolution of species.', 'ডারউইন প্রজাতির বিবর্তন নিয়ে গবেষণা করেছিলেন।', 826),
    ('evolve', null, 'v.', 'B2', 'বিবর্তিত হওয়া, ক্রমবিকশিত হওয়া', 'Languages evolve over time.', 'ভাষা সময়ের সাথে ক্রমবিকশিত হয়।', 827),
    ('exceed', null, 'v.', 'B2', 'অতিক্রম করা, ছাড়িয়ে যাওয়া', 'The results may exceed our expectations.', 'ফলাফল আমাদের প্রত্যাশা ছাড়িয়ে যেতে পারে।', 828),
    ('exception', null, 'n.', 'B2', 'ব্যতিক্রম', 'Everyone was late, with one exception.', 'একজন ব্যতিক্রম ছাড়া সবাই দেরি করল।', 829),
    ('excessive', null, 'adj.', 'B2', 'অতিরিক্ত', 'Excessive noise disturbs the neighbors.', 'অতিরিক্ত শব্দ প্রতিবেশীদের বিরক্ত করে।', 830),
    ('exclude', null, 'v.', 'B2', 'বাদ দেওয়া, বহিষ্কার করা', 'This list does not exclude anyone.', 'এই তালিকা কাউকে বাদ দেয় না।', 831),
    ('exotic', null, 'adj.', 'B2', 'বহিরাগত, ব্যতিক্রমী (বিদেশি)', 'The garden has many exotic plants.', 'বাগানে অনেক বিদেশি উদ্ভিদ আছে।', 832),
    ('expansion', null, 'n.', 'B2', 'সম্প্রসারণ, বিস্তার', 'The company plans further expansion.', 'কোম্পানিটি আরও সম্প্রসারণের পরিকল্পনা করছে।', 833),
    ('expedition', null, 'n.', 'B2', 'অভিযান', 'They joined an expedition to the mountains.', 'তারা পাহাড়ে একটি অভিযানে যোগ দিল।', 834),
    ('expertise', null, 'n.', 'B2', 'দক্ষতা, বিশেষজ্ঞতা', 'He has great expertise in law.', 'আইনে তার দারুণ দক্ষতা আছে।', 835),
    ('exploit', null, 'v.', 'B2', 'শোষণ করা', 'The company began to exploit the workers.', 'কোম্পানিটি শ্রমিকদের শোষণ করতে শুরু করল।', 836),
    ('exposure', null, 'n.', 'B2', 'উন্মুক্ততা, প্রকাশ', 'Too much sun exposure can be harmful.', 'অতিরিক্ত রোদের সংস্পর্শ ক্ষতিকর হতে পারে।', 837),
    ('extension', null, 'n.', 'B2', 'সম্প্রসারণ, বর্ধিতাংশ', 'She asked for a deadline extension.', 'সে সময়সীমা বাড়ানোর অনুরোধ করল।', 838),
    ('extensive', null, 'adj.', 'B2', 'ব্যাপক, বিস্তৃত', 'The fire caused extensive damage.', 'আগুন ব্যাপক ক্ষতি করল।', 839),
    ('extensively', null, 'adv.', 'B2', 'ব্যাপকভাবে', 'She has traveled extensively.', 'সে ব্যাপকভাবে ভ্রমণ করেছে।', 840),
    ('extract', null, 'n.', 'B2', 'উদ্ধৃতাংশ, অংশবিশেষ', 'Read this extract from the novel.', 'উপন্যাসের এই অংশটি পড়ো।', 841),
    ('fabric', null, 'n.', 'B2', 'কাপড়, বস্ত্র', 'This fabric feels very soft.', 'এই কাপড়টি খুব নরম লাগে।', 842),
    ('fabulous', null, 'adj.', 'B2', 'চমৎকার, অসাধারণ', 'We had a fabulous time.', 'আমরা অসাধারণ সময় কাটিয়েছি।', 843),
    ('faculty', null, 'n.', 'B2', 'অনুষদ (বিশ্ববিদ্যালয়ের বিভাগ)', 'She teaches in the science faculty.', 'সে বিজ্ঞান অনুষদে পড়ায়।', 844),
    ('failed', null, 'adj.', 'B2', 'ব্যর্থ', 'It was a failed attempt.', 'এটি একটি ব্যর্থ প্রচেষ্টা ছিল।', 845),
    ('fake', null, 'adj.', 'B2', 'নকল, ভুয়া', 'She was wearing fake jewelry.', 'সে নকল গয়না পরেছিল।', 846),
    ('fame', null, 'n.', 'B2', 'খ্যাতি', 'The singer gained worldwide fame.', 'গায়কটি বিশ্বব্যাপী খ্যাতি অর্জন করল।', 847),
    ('fantasy', null, 'n.', 'B2', 'কল্পনা, কল্পবিজ্ঞান', 'He loves reading fantasy novels.', 'সে কল্পবিজ্ঞান উপন্যাস পড়তে ভালোবাসে।', 848),
    ('fare', null, 'n.', 'B2', 'ভাড়া (যাত্রার)', 'The bus fare has increased.', 'বাসের ভাড়া বেড়েছে।', 849),
    ('firefighter', null, 'n.', 'B2', 'দমকলকর্মী', 'The firefighter rescued the child.', 'দমকলকর্মী শিশুটিকে উদ্ধার করল।', 850),
    ('firework', null, 'n.', 'B2', 'আতশবাজি', 'They watched the firework display.', 'তারা আতশবাজির প্রদর্শনী দেখল।', 851),
    ('firm', null, 'adj.', 'B2', 'দৃঢ়, শক্ত', 'She gave a firm answer.', 'সে একটি দৃঢ় উত্তর দিল।', 852),
    ('firmly', null, 'adv.', 'B2', 'দৃঢ়ভাবে', 'He firmly believes in honesty.', 'সে সততায় দৃঢ়ভাবে বিশ্বাস করে।', 853),
    ('flavor', null, 'n.', 'B2', 'স্বাদ', 'This ice cream has a great flavor.', 'এই আইসক্রিমের স্বাদ দারুণ।', 854),
    ('fond', null, 'adj.', 'B2', 'অনুরাগী, ভালোবাসে এমন', 'She is fond of music.', 'সে সংগীত ভালোবাসে।', 855),
    ('fool', null, 'n.', 'B2', 'বোকা, নির্বোধ ব্যক্তি', 'Don''t act like a fool.', 'বোকার মতো আচরণ করো না।', 856),
    ('forbid', null, 'v.', 'B2', 'নিষেধ করা', 'The rules forbid smoking here.', 'নিয়ম এখানে ধূমপান নিষেধ করে।', 857),
    ('forecast', null, 'n., v.', 'B2', 'পূর্বাভাস; পূর্বাভাস দেওয়া', 'The weather forecast says it will rain.', 'আবহাওয়ার পূর্বাভাসে বলা হচ্ছে বৃষ্টি হবে।', 858),
    ('format', null, 'n.', 'B2', 'বিন্যাস, ফরম্যাট', 'Save the file in PDF format.', 'ফাইলটি পিডিএফ ফরম্যাটে সংরক্ষণ করো।', 859),
    ('formation', null, 'n.', 'B2', 'গঠন, সংগঠন', 'The formation of clouds was beautiful.', 'মেঘের গঠন ছিল সুন্দর।', 860),
    ('formerly', null, 'adv.', 'B2', 'পূর্বে, আগে', 'This city was formerly a small village.', 'এই শহরটি পূর্বে একটি ছোট গ্রাম ছিল।', 861),
    ('fortunate', null, 'adj.', 'B2', 'ভাগ্যবান', 'We are fortunate to have good friends.', 'ভালো বন্ধু পাওয়ায় আমরা ভাগ্যবান।', 862),
    ('forum', null, 'n.', 'B2', 'মঞ্চ, আলোচনাসভা', 'She posted a question on the forum.', 'সে ফোরামে একটি প্রশ্ন পোস্ট করল।', 863),
    ('fossil', null, 'n.', 'B2', 'জীবাশ্ম', 'They found a dinosaur fossil.', 'তারা একটি ডাইনোসরের জীবাশ্ম খুঁজে পেল।', 864),
    ('foundation', null, 'n.', 'B2', 'ভিত্তি', 'They laid the foundation of the building.', 'তারা ভবনের ভিত্তি স্থাপন করল।', 865),
    ('founder', null, 'n.', 'B2', 'প্রতিষ্ঠাতা', 'He is the founder of this company.', 'তিনি এই কোম্পানির প্রতিষ্ঠাতা।', 866),
    ('fraction', null, 'n.', 'B2', 'ভগ্নাংশ', 'Only a fraction of students passed.', 'শিক্ষার্থীদের একটি ক্ষুদ্র অংশ পাস করল।', 867),
    ('fragment', null, 'n.', 'B2', 'খণ্ড, অংশ', 'She found a fragment of the vase.', 'সে ফুলদানির একটি খণ্ড খুঁজে পেল।', 868),
    ('framework', null, 'n.', 'B2', 'কাঠামো', 'The law provides a legal framework.', 'আইনটি একটি আইনি কাঠামো প্রদান করে।', 869),
    ('fraud', null, 'n.', 'B2', 'প্রতারণা, জালিয়াতি', 'He was arrested for fraud.', 'জালিয়াতির জন্য তাকে গ্রেপ্তার করা হলো।', 870),
    ('freely', null, 'adv.', 'B2', 'স্বাধীনভাবে, অবাধে', 'You can speak freely here.', 'তুমি এখানে স্বাধীনভাবে কথা বলতে পারো।', 871),
    ('frequent', null, 'adj.', 'B2', 'ঘন ঘন ঘটে এমন, নিয়মিত', 'She is a frequent visitor here.', 'সে এখানে নিয়মিত আসে।', 872),
    ('fulfill', null, 'v.', 'B2', 'পূর্ণ করা, সম্পন্ন করা', 'He worked hard to fulfill his dream.', 'সে তার স্বপ্ন পূর্ণ করতে কঠোর পরিশ্রম করল।', 873),
    ('full-time', null, 'adv.', 'B2', 'পূর্ণকালীনভাবে', 'She works full-time now.', 'সে এখন পূর্ণকালীনভাবে কাজ করে।', 874),
    ('fundamentally', null, 'adv.', 'B2', 'মৌলিকভাবে', 'The two ideas are fundamentally different.', 'ধারণা দুটি মৌলিকভাবে ভিন্ন।', 875),
    ('furious', null, 'adj.', 'B2', 'অত্যন্ত ক্ষুব্ধ, ক্ষিপ্ত', 'She was furious about the delay.', 'দেরি হওয়ায় সে অত্যন্ত ক্ষুব্ধ হলো।', 876),
    ('gallon', null, 'n.', 'B2', 'গ্যালন', 'The car uses one gallon per trip.', 'গাড়িটি প্রতি যাত্রায় এক গ্যালন জ্বালানি ব্যবহার করে।', 877),
    ('gaming', null, 'n.', 'B2', 'গেমিং, ভিডিও গেম খেলা', 'He spends hours on gaming.', 'সে গেমিংয়ে ঘণ্টার পর ঘণ্টা ব্যয় করে।', 878),
    ('gay', null, 'adj.', 'B2', 'সমকামী', 'He came out as gay.', 'সে নিজেকে সমকামী বলে প্রকাশ করল।', 879),
    ('gender', null, 'n.', 'B2', 'লিঙ্গ', 'The form asks for your gender.', 'ফর্মে তোমার লিঙ্গ জিজ্ঞেস করা হয়েছে।', 880),
    ('gene', null, 'n.', 'B2', 'জিন', 'This gene controls eye color.', 'এই জিনটি চোখের রঙ নিয়ন্ত্রণ করে।', 881),
    ('genetic', null, 'adj.', 'B2', 'জিনগত, বংশগত', 'Genetic diseases can pass from parents to children.', 'জিনগত রোগ বাবা-মা থেকে সন্তানদের মধ্যে ছড়াতে পারে।', 882),
    ('genius', null, 'n.', 'B2', 'প্রতিভা, প্রতিভাবান ব্যক্তি', 'Einstein was a genius.', 'আইনস্টাইন একজন প্রতিভাবান ব্যক্তি ছিলেন।', 883),
    ('genuine', null, 'adj.', 'B2', 'প্রকৃত, খাঁটি', 'She showed genuine interest in the project.', 'সে প্রকল্পের প্রতি প্রকৃত আগ্রহ দেখিয়েছিল।', 884),
    ('genuinely', null, 'adv.', 'B2', 'প্রকৃতপক্ষে, সত্যিকারভাবে', 'He genuinely wants to help.', 'সে সত্যিকারভাবে সাহায্য করতে চায়।', 885),
    ('gesture', null, 'n.', 'B2', 'অঙ্গভঙ্গি, ইশারা', 'He made a friendly gesture with his hand.', 'সে হাত দিয়ে একটি বন্ধুত্বপূর্ণ ইশারা করল।', 886),
    ('globalization', null, 'n.', 'B2', 'বিশ্বায়ন', 'Globalization has changed how we trade.', 'বিশ্বায়ন আমাদের বাণিজ্যের ধরন পাল্টে দিয়েছে।', 887),
    ('globe', null, 'n.', 'B2', 'পৃথিবী, বিশ্ব (গোলক)', 'People all over the globe watched the match.', 'পুরো বিশ্বের মানুষ খেলাটি দেখেছিল।', 888),
    ('golden', null, 'adj.', 'B2', 'সোনালি, স্বর্ণালি', 'The beach had golden sand.', 'সৈকতে সোনালি বালি ছিল।', 889),
    ('goodness', null, 'n.', 'B2', 'মঙ্গল, ভালোত্ব', 'She believes in the goodness of people.', 'সে মানুষের ভালোত্বে বিশ্বাস করে।', 890),
    ('gorgeous', null, 'adj.', 'B2', 'অপরূপ সুন্দর', 'The sunset was gorgeous tonight.', 'আজ রাতে সূর্যাস্ত ছিল অপরূপ সুন্দর।', 891),
    ('graphic', null, 'adj.', 'B2', 'চিত্রভিত্তিক; স্পষ্ট ও বিশদ', 'The book had graphic illustrations.', 'বইটিতে চিত্রভিত্তিক ছবি ছিল।', 892),
    ('graphics', null, 'n.', 'B2', 'গ্রাফিক্স, চিত্রকলা', 'The game has amazing graphics.', 'গেমটির গ্রাফিক্স চমৎকার।', 893),
    ('greatly', null, 'adv.', 'B2', 'ব্যাপকভাবে, অনেকখানি', 'The city has greatly changed.', 'শহরটি ব্যাপকভাবে পরিবর্তিত হয়েছে।', 894),
    ('greenhouse', null, 'n.', 'B2', 'গ্রিনহাউস (কাচঘর, যেখানে গাছ জন্মানো হয়)', 'We grow tomatoes in the greenhouse.', 'আমরা গ্রিনহাউসে টমেটো চাষ করি।', 895),
    ('guideline', null, 'n.', 'B2', 'নির্দেশিকা, নিয়মাবলি', 'Please follow the safety guidelines.', 'দয়া করে নিরাপত্তা নির্দেশিকা মেনে চলুন।', 896),
    ('habitat', null, 'n.', 'B2', 'প্রাকৃতিক বাসস্থান', 'This forest is the natural habitat of tigers.', 'এই বনটি বাঘদের প্রাকৃতিক বাসস্থান।', 897),
    ('harbor', null, 'n.', 'B2', 'পোতাশ্রয়, বন্দর', 'Ships were anchored in the harbor.', 'জাহাজগুলো পোতাশ্রয়ে নোঙর করা ছিল।', 898),
    ('headquarters', null, 'n.', 'B2', 'সদর দপ্তর', 'The company''s headquarters is in New York.', 'কোম্পানিটির সদর দপ্তর নিউ ইয়র্কে।', 899),
    ('heal', null, 'v.', 'B2', 'সেরে ওঠা, নিরাময় করা', 'The wound will heal in a few days.', 'ক্ষতটি কয়েকদিনে সেরে যাবে।', 900),
    ('healthcare', null, 'n.', 'B2', 'স্বাস্থ্যসেবা', 'Everyone deserves good healthcare.', 'সবার ভালো স্বাস্থ্যসেবা পাওয়ার অধিকার আছে।', 901),
    ('helmet', null, 'n.', 'B2', 'হেলমেট, শিরস্ত্রাণ', 'Always wear a helmet on a bike.', 'বাইকে সবসময় হেলমেট পরুন।', 902),
    ('hence', null, 'adv.', 'B2', 'অতএব, সেজন্য', 'It rained hard, hence the delay.', 'প্রবল বৃষ্টি হয়েছিল, সেজন্যই দেরি হলো।', 903),
    ('herb', null, 'n.', 'B2', 'ভেষজ, গুল্ম', 'She added fresh herbs to the soup.', 'সে স্যুপে তাজা ভেষজ যোগ করল।', 904),
    ('hidden', null, 'adj.', 'B2', 'লুকানো, গোপন', 'There is a hidden room behind the wall.', 'দেওয়ালের পেছনে একটি লুকানো কক্ষ আছে।', 905),
    ('hilarious', null, 'adj.', 'B2', 'অত্যন্ত মজার, হাস্যকর', 'The movie was hilarious.', 'সিনেমাটি ছিল অত্যন্ত মজার।', 906),
    ('hip', null, 'n.', 'B2', 'নিতম্ব, কোমরের পাশ', 'She hurt her hip while running.', 'দৌড়ানোর সময় সে তার নিতম্বে ব্যথা পেল।', 907),
    ('historian', null, 'n.', 'B2', 'ইতিহাসবিদ', 'The historian wrote a book about ancient Rome.', 'ইতিহাসবিদটি প্রাচীন রোম নিয়ে একটি বই লিখেছিলেন।', 908),
    ('homeless', null, 'adj.', 'B2', 'গৃহহীন, আশ্রয়হীন', 'They help homeless people find shelter.', 'তারা গৃহহীন মানুষদের আশ্রয় খুঁজে পেতে সাহায্য করে।', 909),
    ('honesty', null, 'n.', 'B2', 'সততা', 'Honesty is the best policy.', 'সততাই সর্বোত্তম নীতি।', 910),
    ('honey', null, 'n.', 'B2', 'মধু', 'She put honey in her tea.', 'সে চায়ে মধু মেশাল।', 911),
    ('hook', null, 'n., v.', 'B2', 'হুক, আঁকশি; হুক দিয়ে আটকানো', 'Hang your coat on the hook.', 'তোমার কোটটি হুকে ঝোলাও।', 912),
    ('hopefully', null, 'adv.', 'B2', 'আশা করা যায়, আশা করি', 'Hopefully, it won''t rain tomorrow.', 'আশা করি, আগামীকাল বৃষ্টি হবে না।', 913),
    ('hunger', null, 'n.', 'B2', 'ক্ষুধা', 'The charity fights hunger around the world.', 'দাতব্য সংস্থাটি বিশ্বজুড়ে ক্ষুধার বিরুদ্ধে লড়াই করে।', 914),
    ('hypothesis', null, 'n.', 'B2', 'প্রকল্পনা, অনুমিতি', 'The scientist tested her hypothesis.', 'বিজ্ঞানী তার প্রকল্পনা পরীক্ষা করলেন।', 915),
    ('icon', null, 'n.', 'B2', 'প্রতিমূর্তি, আইকন', 'Click the icon to open the app.', 'অ্যাপটি খুলতে আইকনে ক্লিক করুন।', 916),
    ('ID', null, 'n.', 'B2', 'পরিচয়পত্র', 'Please show your ID at the gate.', 'গেটে দয়া করে আপনার পরিচয়পত্র দেখান।', 917),
    ('identical', null, 'adj.', 'B2', 'অভিন্ন, একই রকম', 'The twins look identical.', 'যমজ দুজনকে দেখতে একই রকম লাগে।', 918),
    ('illusion', null, 'n.', 'B2', 'বিভ্রম, মায়া', 'It was just an optical illusion.', 'এটি নিছক একটি অপটিক্যাল বিভ্রম ছিল।', 919),
    ('immigration', null, 'n.', 'B2', 'অভিবাসন', 'Immigration rules have changed this year.', 'এই বছর অভিবাসন নিয়ম পাল্টেছে।', 920),
    ('immune', null, 'adj.', 'B2', 'রোগ প্রতিরোধী, অনাক্রম্য', 'The vaccine makes you immune to the disease.', 'টিকাটি আপনাকে রোগটির বিরুদ্ধে প্রতিরোধী করে তোলে।', 921),
    ('implement', null, 'v.', 'B2', 'বাস্তবায়ন করা, কার্যকর করা', 'The school will implement a new policy.', 'স্কুলটি একটি নতুন নীতি বাস্তবায়ন করবে।', 922),
    ('implication', null, 'n.', 'B2', 'অন্তর্নিহিত অর্থ, প্রভাব', 'We must think about the implications of this decision.', 'আমাদের এই সিদ্ধান্তের প্রভাব সম্পর্কে ভাবতে হবে।', 923),
    ('incentive', null, 'n.', 'B2', 'প্রণোদনা, উৎসাহ', 'The company offers incentives for hard work.', 'কোম্পানিটি কঠোর পরিশ্রমের জন্য প্রণোদনা দেয়।', 924),
    ('incorporate', null, 'v.', 'B2', 'অন্তর্ভুক্ত করা, সংযুক্ত করা', 'The recipe incorporates fresh vegetables.', 'রেসিপিটিতে তাজা সবজি অন্তর্ভুক্ত করা হয়েছে।', 925),
    ('incorrect', null, 'adj.', 'B2', 'ভুল, অশুদ্ধ', 'Your answer is incorrect.', 'তোমার উত্তরটি ভুল।', 926),
    ('independence', null, 'n.', 'B2', 'স্বাধীনতা', 'The country gained independence in 1947.', 'দেশটি ১৯৪৭ সালে স্বাধীনতা লাভ করে।', 927),
    ('index', null, 'n.', 'B2', 'সূচক, সূচি', 'Check the index at the back of the book.', 'বইয়ের পেছনের সূচিটি দেখুন।', 928),
    ('indication', null, 'n.', 'B2', 'ইঙ্গিত, লক্ষণ', 'There was no indication of danger.', 'বিপদের কোনো ইঙ্গিত ছিল না।', 929),
    ('inevitable', null, 'adj.', 'B2', 'অনিবার্য', 'Change is inevitable.', 'পরিবর্তন অনিবার্য।', 930),
    ('inevitably', null, 'adv.', 'B2', 'অনিবার্যভাবে', 'Prices will inevitably rise.', 'দাম অনিবার্যভাবে বাড়বে।', 931),
    ('infer', null, 'v.', 'B2', 'অনুমান করা', 'We can infer his mood from his face.', 'তার মুখ দেখে আমরা তার মেজাজ অনুমান করতে পারি।', 932),
    ('inflation', null, 'n.', 'B2', 'মুদ্রাস্ফীতি', 'Inflation has made food more expensive.', 'মুদ্রাস্ফীতির কারণে খাবার আরও দামি হয়ে গেছে।', 933),
    ('info', null, 'n.', 'B2', 'তথ্য', 'Can you send me more info?', 'তুমি কি আমাকে আরও তথ্য পাঠাতে পারবে?', 934),
    ('infrastructure', null, 'n.', 'B2', 'অবকাঠামো', 'The city needs better infrastructure.', 'শহরটির আরও ভালো অবকাঠামো প্রয়োজন।', 935),
    ('inhabitant', null, 'n.', 'B2', 'অধিবাসী', 'The island has few inhabitants.', 'দ্বীপটিতে অল্প সংখ্যক অধিবাসী আছে।', 936),
    ('inherit', null, 'v.', 'B2', 'উত্তরাধিকারসূত্রে পাওয়া', 'She will inherit her grandmother''s house.', 'সে তার দাদির বাড়িটি উত্তরাধিকারসূত্রে পাবে।', 937),
    ('ink', null, 'n.', 'B2', 'কালি', 'The pen ran out of ink.', 'কলমের কালি ফুরিয়ে গেল।', 938),
    ('innovation', null, 'n.', 'B2', 'উদ্ভাবন', 'The company is known for innovation.', 'কোম্পানিটি উদ্ভাবনের জন্য পরিচিত।', 939),
    ('innovative', null, 'adj.', 'B2', 'উদ্ভাবনী', 'They developed an innovative solution.', 'তারা একটি উদ্ভাবনী সমাধান তৈরি করেছে।', 940),
    ('input', null, 'n.', 'B2', 'ইনপুট, মতামত', 'We need your input on this plan.', 'এই পরিকল্পনায় আমাদের তোমার মতামত দরকার।', 941),
    ('insert', null, 'v.', 'B2', 'প্রবেশ করানো, ঢোকানো', 'Insert the key into the lock.', 'তালাটির মধ্যে চাবি প্রবেশ করাও।', 942),
    ('inspector', null, 'n.', 'B2', 'পরিদর্শক', 'The inspector checked the factory.', 'পরিদর্শক কারখানাটি পরিদর্শন করলেন।', 943),
    ('installation', null, 'n.', 'B2', 'স্থাপন, ইনস্টলেশন', 'The installation of the software took an hour.', 'সফটওয়্যারটি ইনস্টল করতে এক ঘণ্টা লাগল।', 944),
    ('instant', null, 'adj.', 'B2', 'তাৎক্ষণিক', 'The photo gave instant results.', 'ছবিটি তাৎক্ষণিক ফলাফল দিল।', 945),
    ('instantly', null, 'adv.', 'B2', 'তাৎক্ষণিকভাবে', 'The lights turned on instantly.', 'আলোগুলো তাৎক্ষণিকভাবে জ্বলে উঠল।', 946),
    ('integrate', null, 'v.', 'B2', 'সংযুক্ত করা, একীভূত করা', 'The new students quickly integrated into the class.', 'নতুন ছাত্ররা দ্রুত ক্লাসে একীভূত হয়ে গেল।', 947),
    ('intellectual', null, 'adj.', 'B2', 'বুদ্ধিবৃত্তিক, মেধাবী', 'She enjoys intellectual conversations.', 'সে বুদ্ধিবৃত্তিক আলোচনা উপভোগ করে।', 948),
    ('interact', null, 'v.', 'B2', 'মিথস্ক্রিয়া করা, যোগাযোগ করা', 'Children learn to interact with others.', 'শিশুরা অন্যদের সঙ্গে মিথস্ক্রিয়া করতে শেখে।', 949),
    ('interaction', null, 'n.', 'B2', 'মিথস্ক্রিয়া', 'Social interaction is important for children.', 'সামাজিক মিথস্ক্রিয়া শিশুদের জন্য গুরুত্বপূর্ণ।', 950),
    ('interpretation', null, 'n.', 'B2', 'ব্যাখ্যা, অর্থবিশ্লেষণ', 'Everyone has a different interpretation of the poem.', 'কবিতাটির ব্যাখ্যা প্রত্যেকের কাছে ভিন্ন।', 951),
    ('interval', null, 'n.', 'B2', 'বিরতি, ব্যবধান', 'There was a short interval between the two songs.', 'দুটি গানের মাঝে একটি ছোট বিরতি ছিল।', 952),
    ('invade', null, 'v.', 'B2', 'আক্রমণ করা, হানা দেওয়া', 'The army invaded the neighboring country.', 'সেনাবাহিনী প্রতিবেশী দেশটি আক্রমণ করল।', 953),
    ('invasion', null, 'n.', 'B2', 'আক্রমণ', 'The invasion began at dawn.', 'আক্রমণটি ভোরবেলা শুরু হলো।', 954),
    ('investor', null, 'n.', 'B2', 'বিনিয়োগকারী', 'Investors are worried about the market.', 'বিনিয়োগকারীরা বাজার নিয়ে চিন্তিত।', 955),
    ('isolate', null, 'v.', 'B2', 'পৃথক করা, বিচ্ছিন্ন করা', 'Doctors had to isolate the patient.', 'ডাক্তারদের রোগীটিকে বিচ্ছিন্ন করতে হয়েছিল।', 956),
    ('isolated', null, 'adj.', 'B2', 'বিচ্ছিন্ন, নির্জন', 'The village is very isolated.', 'গ্রামটি খুবই বিচ্ছিন্ন।', 957),
    ('jail', null, 'n., v.', 'B2', 'কারাগার; কারারুদ্ধ করা', 'He spent five years in jail.', 'সে পাঁচ বছর কারাগারে কাটাল।', 958),
    ('jet', null, 'n.', 'B2', 'জেট বিমান', 'The jet took off smoothly.', 'জেট বিমানটি মসৃণভাবে উড়াল দিল।', 959),
    ('joint', null, 'adj., n.', 'B2', 'যৌথ; অস্থিসন্ধি', 'They made a joint decision.', 'তারা একটি যৌথ সিদ্ধান্ত নিল।', 960),
    ('journalism', null, 'n.', 'B2', 'সাংবাদিকতা', 'She studied journalism at university.', 'সে বিশ্ববিদ্যালয়ে সাংবাদিকতা পড়েছে।', 961),
    ('jury', null, 'n.', 'B2', 'জুরি, বিচারক মণ্ডলী', 'The jury found him guilty.', 'জুরি তাকে দোষী সাব্যস্ত করল।', 962),
    ('kindergarten', null, 'n.', 'B2', 'কিন্ডারগার্টেন, শিশু শ্রেণি', 'My son starts kindergarten this year.', 'আমার ছেলে এই বছর কিন্ডারগার্টেন শুরু করছে।', 963),
    ('kit', null, 'n.', 'B2', 'সরঞ্জাম বাক্স, কিট', 'He keeps a first-aid kit in the car.', 'সে গাড়িতে একটি প্রাথমিক চিকিৎসার কিট রাখে।', 964),
    ('ladder', null, 'n.', 'B2', 'মই, সিঁড়ি', 'He climbed the ladder to fix the roof.', 'ছাদ মেরামত করতে সে মই বেয়ে উঠল।', 965),
    ('landing', null, 'n.', 'B2', 'অবতরণ', 'The plane made a smooth landing.', 'প্লেনটি মসৃণভাবে অবতরণ করল।', 966),
    ('lane', null, 'n.', 'B2', 'সরু পথ, লেন', 'Stay in your lane while driving.', 'গাড়ি চালানোর সময় নিজের লেনে থাকুন।', 967),
    ('lately', null, 'adv.', 'B2', 'সম্প্রতি, আজকাল', 'I haven''t seen her lately.', 'আমি সম্প্রতি তাকে দেখিনি।', 968),
    ('legend', null, 'n.', 'B2', 'কিংবদন্তি', 'There is a local legend about the lake.', 'হ্রদটি নিয়ে একটি স্থানীয় কিংবদন্তি আছে।', 969),
    ('lens', null, 'n.', 'B2', 'লেন্স', 'The camera has a wide lens.', 'ক্যামেরাটির একটি প্রশস্ত লেন্স আছে।', 970),
    ('lifetime', null, 'n.', 'B2', 'জীবনকাল', 'It was the chance of a lifetime.', 'এটি ছিল জীবনের এক দুর্লভ সুযোগ।', 971),
    ('lighting', null, 'n.', 'B2', 'আলোকসজ্জা', 'The restaurant had soft lighting.', 'রেস্তোরাঁটিতে নরম আলোকসজ্জা ছিল।', 972),
    ('likewise', null, 'adv.', 'B2', 'অনুরূপভাবে, একইভাবে', 'He bowed, and she did likewise.', 'সে মাথা নত করল, এবং সেও একইভাবে করল।', 973),
    ('limitation', null, 'n.', 'B2', 'সীমাবদ্ধতা', 'Every plan has its limitations.', 'প্রতিটি পরিকল্পনার নিজস্ব সীমাবদ্ধতা আছে।', 974),
    ('literally', null, 'adv.', 'B2', 'আক্ষরিক অর্থে', 'He literally ran a marathon yesterday.', 'সে গতকাল আক্ষরিক অর্থেই একটি ম্যারাথন দৌড়েছে।', 975),
    ('literary', null, 'adj.', 'B2', 'সাহিত্যিক', 'She has great literary talent.', 'তার অসাধারণ সাহিত্যিক প্রতিভা আছে।', 976),
    ('litter', null, 'n.', 'B2', 'আবর্জনা, ছড়ানো ময়লা', 'Please don''t throw litter on the street.', 'রাস্তায় আবর্জনা ফেলবেন না।', 977),
    ('logo', null, 'n.', 'B2', 'লোগো, প্রতীক চিহ্ন', 'The company changed its logo.', 'কোম্পানিটি তার লোগো পরিবর্তন করেছে।', 978),
    ('lottery', null, 'n.', 'B2', 'লটারি', 'He won the lottery last month.', 'সে গত মাসে লটারি জিতেছিল।', 979),
    ('loyal', null, 'adj.', 'B2', 'অনুগত, বিশ্বস্ত', 'Dogs are very loyal animals.', 'কুকুর খুবই অনুগত প্রাণী।', 980),
    ('lyric', null, 'n.', 'B2', 'গানের কথা', 'I love the lyrics of this song.', 'আমি এই গানের কথাগুলো পছন্দ করি।', 981),
    ('magnificent', null, 'adj.', 'B2', 'জাঁকজমকপূর্ণ, চমৎকার', 'The palace looked magnificent at night.', 'রাতে প্রাসাদটিকে জাঁকজমকপূর্ণ দেখাচ্ছিল।', 982),
    ('makeup', null, 'n.', 'B2', 'প্রসাধনী, মেকআপ', 'She doesn''t like wearing makeup.', 'সে মেকআপ পরতে পছন্দ করে না।', 983),
    ('making', null, 'n.', 'B2', 'তৈরির প্রক্রিয়া, নির্মাণ', 'This crisis has been years in the making.', 'এই সংকটটি বছরের পর বছর ধরে তৈরি হয়েছে।', 984),
    ('manufacture', null, 'v.', 'B2', 'উৎপাদন করা, তৈরি করা', 'The factory manufactures cars.', 'কারখানাটি গাড়ি উৎপাদন করে।', 985),
    ('manufacturing', null, 'n.', 'B2', 'উৎপাদন শিল্প', 'Manufacturing jobs are declining in the area.', 'এলাকায় উৎপাদন শিল্পের চাকরি কমছে।', 986),
    ('marathon', null, 'n.', 'B2', 'ম্যারাথন দৌড়', 'She trained hard for the marathon.', 'সে ম্যারাথনের জন্য কঠোর অনুশীলন করেছে।', 987),
    ('margin', null, 'n.', 'B2', 'প্রান্ত, মার্জিন', 'He wrote notes in the margin of the page.', 'সে পাতার মার্জিনে নোট লিখল।', 988),
    ('marker', null, 'n.', 'B2', 'মার্কার (কলম), চিহ্নক', 'She drew the poster with a marker.', 'সে মার্কার দিয়ে পোস্টারটি আঁকল।', 989),
    ('martial', null, 'adj.', 'B2', 'সামরিক, যুদ্ধ-সংক্রান্ত', 'He practices martial arts.', 'সে মার্শাল আর্ট অনুশীলন করে।', 990),
    ('mate', null, 'n., v.', 'B2', 'সঙ্গী, বন্ধু; মিলিত হওয়া (প্রাণীদের)', 'He is my best mate.', 'সে আমার সবচেয়ে ভালো বন্ধু।', 991),
    ('mechanic', null, 'n.', 'B2', 'মেকানিক, যন্ত্রবিদ', 'The mechanic fixed my car.', 'মেকানিক আমার গাড়ি ঠিক করে দিল।', 992),
    ('mechanical', null, 'adj.', 'B2', 'যান্ত্রিক', 'There was a mechanical problem with the engine.', 'ইঞ্জিনে একটি যান্ত্রিক সমস্যা ছিল।', 993),
    ('mechanism', null, 'n.', 'B2', 'কলাকৌশল, যন্ত্রকৌশল', 'The clock has a complex mechanism.', 'ঘড়িটির একটি জটিল কলাকৌশল আছে।', 994),
    ('medal', null, 'n.', 'B2', 'পদক', 'She won a gold medal.', 'সে একটি স্বর্ণপদক জিতেছে।', 995),
    ('medication', null, 'n.', 'B2', 'ওষুধ', 'The doctor prescribed new medication.', 'ডাক্তার নতুন ওষুধ লিখে দিলেন।', 996),
    ('membership', null, 'n.', 'B2', 'সদস্যপদ', 'He bought a gym membership.', 'সে জিমের সদস্যপদ কিনল।', 997),
    ('memorable', null, 'adj.', 'B2', 'স্মরণীয়', 'It was a memorable trip.', 'এটি ছিল একটি স্মরণীয় ভ্রমণ।', 998),
    ('metaphor', null, 'n.', 'B2', 'রূপক', 'The poem uses a metaphor for life.', 'কবিতাটি জীবনের জন্য একটি রূপক ব্যবহার করেছে।', 999),
    ('miner', null, 'n.', 'B2', 'খনি শ্রমিক', 'The miner worked deep underground.', 'খনি শ্রমিকটি মাটির অনেক গভীরে কাজ করত।', 1000),
    ('miserable', null, 'adj.', 'B2', 'দুঃখী, শোচনীয়', 'He felt miserable after losing the game.', 'খেলায় হেরে সে দুঃখী বোধ করল।', 1001),
    ('mode', null, 'n.', 'B2', 'পদ্ধতি, ধরন', 'Switch the phone to silent mode.', 'ফোনটি নীরব মোডে পরিবর্তন করো।', 1002),
    ('modest', null, 'adj.', 'B2', 'বিনয়ী, শালীন', 'She is modest about her success.', 'সে তার সাফল্য নিয়ে বিনয়ী।', 1003),
    ('monster', null, 'n.', 'B2', 'দানব, রাক্ষস', 'The child was scared of the monster in the story.', 'গল্পের দানবকে দেখে শিশুটি ভয় পেয়েছিল।', 1004),
    ('monthly', null, 'adj.', 'B2', 'মাসিক', 'We pay a monthly rent.', 'আমরা মাসিক ভাড়া দিই।', 1005),
    ('monument', null, 'n.', 'B2', 'স্মৃতিস্তম্ভ', 'The monument honors fallen soldiers.', 'স্মৃতিস্তম্ভটি শহীদ সৈনিকদের সম্মানে নির্মিত।', 1006),
    ('moreover', null, 'adv.', 'B2', 'তদুপরি, এছাড়াও', 'The plan is costly; moreover, it is risky.', 'পরিকল্পনাটি ব্যয়বহুল; তদুপরি, এটি ঝুঁকিপূর্ণও।', 1007),
    ('mortgage', null, 'n.', 'B2', 'বন্ধকী ঋণ', 'They took out a mortgage to buy the house.', 'বাড়ি কেনার জন্য তারা বন্ধকী ঋণ নিল।', 1008),
    ('mosque', null, 'n.', 'B2', 'মসজিদ', 'They pray at the mosque every Friday.', 'তারা প্রতি শুক্রবার মসজিদে নামাজ পড়ে।', 1009),
    ('mosquito', null, 'n.', 'B2', 'মশা', 'A mosquito bit me last night.', 'গতরাতে একটি মশা আমাকে কামড়েছিল।', 1010),
    ('motion', null, 'n.', 'B2', 'গতি, নড়াচড়া', 'The sensor detects motion.', 'সেন্সরটি নড়াচড়া শনাক্ত করে।', 1011),
    ('motivate', null, 'v.', 'B2', 'উদ্বুদ্ধ করা, অনুপ্রাণিত করা', 'The coach motivated the team to win.', 'কোচ দলটিকে জিততে উদ্বুদ্ধ করলেন।', 1012),
    ('motivation', null, 'n.', 'B2', 'প্রেরণা, উদ্দীপনা', 'She lacks motivation to study.', 'তার পড়াশোনার প্রেরণা নেই।', 1013),
    ('moving', null, 'adj.', 'B2', 'হৃদয়স্পর্শী, আবেগঘন', 'It was a moving speech.', 'এটি ছিল একটি হৃদয়স্পর্শী বক্তৃতা।', 1014),
    ('myth', null, 'n.', 'B2', 'পুরাণ, ভুল ধারণা', 'It''s a myth that we only use 10% of our brain.', 'আমরা মস্তিষ্কের মাত্র ১০% ব্যবহার করি, এটি একটি ভুল ধারণা।', 1015),
    ('naked', null, 'adj.', 'B2', 'উলঙ্গ, নগ্ন', 'You can see the stars with the naked eye.', 'খালি চোখে তুমি তারা দেখতে পারো।', 1016),
    ('nasty', null, 'adj.', 'B2', 'বিশ্রী, জঘন্য', 'That''s a nasty cut on your arm.', 'তোমার হাতে সেটা একটা বিশ্রী কাটা দাগ।', 1017),
    ('navigation', null, 'n.', 'B2', 'পথনির্দেশনা, নৌচালনা', 'The ship''s navigation system failed.', 'জাহাজটির পথনির্দেশনা ব্যবস্থা বিকল হয়ে গেল।', 1018),
    ('nearby', null, 'adj., adv.', 'B2', 'কাছাকাছি, নিকটবর্তী', 'There is a park nearby.', 'কাছাকাছি একটি পার্ক আছে।', 1019),
    ('necessity', null, 'n.', 'B2', 'প্রয়োজনীয়তা, অপরিহার্য বস্তু', 'Water is a basic necessity.', 'পানি একটি মৌলিক প্রয়োজনীয়তা।', 1020),
    ('negotiate', null, 'v.', 'B2', 'দরকষাকষি করা, আলোচনা করা', 'They negotiated a better price.', 'তারা আরও ভালো দামের জন্য দরকষাকষি করল।', 1021),
    ('negotiation', null, 'n.', 'B2', 'আলোচনা, দরকষাকষি', 'The negotiation lasted for hours.', 'আলোচনাটি ঘণ্টার পর ঘণ্টা ধরে চলল।', 1022),
    ('neutral', null, 'adj.', 'B2', 'নিরপেক্ষ', 'Switzerland stayed neutral during the war.', 'যুদ্ধের সময় সুইজারল্যান্ড নিরপেক্ষ ছিল।', 1023),
    ('newly', null, 'adv.', 'B2', 'সদ্য, নতুনভাবে', 'They are a newly married couple.', 'তারা সদ্য বিবাহিত এক দম্পতি।', 1024),
    ('nickel', null, 'n.', 'B2', 'নিকেল (ধাতু)', 'The coin is made of nickel.', 'কয়েনটি নিকেল দিয়ে তৈরি।', 1025),
    ('norm', null, 'n.', 'B2', 'প্রচলিত রীতি, মানদণ্ড', 'Wearing a helmet is the norm here.', 'এখানে হেলমেট পরা প্রচলিত রীতি।', 1026),
    ('notebook', null, 'n.', 'B2', 'খাতা, নোটবুক', 'She wrote the address in her notebook.', 'সে তার নোটবুকে ঠিকানাটি লিখল।', 1027),
    ('novelist', null, 'n.', 'B2', 'ঔপন্যাসিক', 'The novelist wrote ten books.', 'ঔপন্যাসিক দশটি বই লিখেছেন।', 1028),
    ('nowadays', null, 'adv.', 'B2', 'আজকাল', 'Nowadays, everyone has a phone.', 'আজকাল সবার কাছে একটি ফোন আছে।', 1029),
    ('nursing', null, 'adj.', 'B2', 'সেবামূলক, নার্সিং-সংক্রান্ত', 'She works at a nursing home.', 'সে একটি নার্সিং হোমে কাজ করে।', 1030),
    ('nutrition', null, 'n.', 'B2', 'পুষ্টি', 'Good nutrition keeps you healthy.', 'ভালো পুষ্টি আপনাকে সুস্থ রাখে।', 1031),
    ('obesity', null, 'n.', 'B2', 'স্থূলতা', 'Obesity can cause health problems.', 'স্থূলতা স্বাস্থ্য সমস্যা সৃষ্টি করতে পারে।', 1032),
    ('observer', null, 'n.', 'B2', 'পর্যবেক্ষক', 'An observer watched the election closely.', 'একজন পর্যবেক্ষক নির্বাচনটি ঘনিষ্ঠভাবে পর্যবেক্ষণ করলেন।', 1033),
    ('obstacle', null, 'n.', 'B2', 'বাধা, প্রতিবন্ধক', 'Fear is a big obstacle to success.', 'ভয় সাফল্যের একটি বড় বাধা।', 1034),
    ('occupation', null, 'n.', 'B2', 'পেশা', 'What is your occupation?', 'আপনার পেশা কী?', 1035),
    ('occupy', null, 'v.', 'B2', 'দখল করা, অধিকার করা', 'Soldiers occupy the old fort.', 'সৈন্যরা পুরনো দুর্গটি দখল করে আছে।', 1036),
    ('offender', null, 'n.', 'B2', 'অপরাধী', 'The offender was sent to prison.', 'অপরাধীকে কারাগারে পাঠানো হয়েছিল।', 1037),
    ('ongoing', null, 'adj.', 'B2', 'চলমান', 'There is an ongoing investigation.', 'একটি চলমান তদন্ত চলছে।', 1038),
    ('openly', null, 'adv.', 'B2', 'প্রকাশ্যে, খোলাখুলিভাবে', 'He spoke openly about his fears.', 'সে তার ভয়ের কথা খোলাখুলিভাবে বলল।', 1039),
    ('opera', null, 'n.', 'B2', 'অপেরা (সংগীতনাট্য)', 'We watched an opera last night.', 'আমরা গতরাতে একটি অপেরা দেখেছি।', 1040),
    ('operator', null, 'n.', 'B2', 'পরিচালক, অপারেটর', 'The operator answered my call.', 'অপারেটর আমার ফোন ধরল।', 1041),
    ('optimistic', null, 'adj.', 'B2', 'আশাবাদী', 'She is optimistic about the future.', 'সে ভবিষ্যৎ নিয়ে আশাবাদী।', 1042),
    ('orchestra', null, 'n.', 'B2', 'বাদ্যযন্ত্রীদল, অর্কেস্ট্রা', 'The orchestra played a beautiful song.', 'অর্কেস্ট্রাটি একটি সুন্দর গান বাজাল।', 1043),
    ('organic', null, 'adj.', 'B2', 'জৈব', 'We only eat organic vegetables.', 'আমরা শুধু জৈব সবজি খাই।', 1044),
    ('outfit', null, 'n.', 'B2', 'পোশাক', 'She wore a new outfit to the party.', 'সে পার্টিতে নতুন পোশাক পরেছিল।', 1045),
    ('output', null, 'n.', 'B2', 'উৎপাদন, ফলাফল', 'The factory increased its output.', 'কারখানাটি তার উৎপাদন বাড়িয়েছে।', 1046),
    ('outstanding', null, 'adj.', 'B2', 'অসাধারণ, চমৎকার', 'She gave an outstanding performance.', 'সে একটি অসাধারণ পারফরম্যান্স দিয়েছে।', 1047),
    ('overcome', null, 'v.', 'B2', 'কাটিয়ে ওঠা, জয় করা', 'He worked hard to overcome his fear.', 'সে তার ভয় কাটিয়ে উঠতে কঠোর পরিশ্রম করেছিল।', 1048),
    ('overnight', null, 'adv.', 'B2', 'রাতারাতি', 'The situation changed overnight.', 'পরিস্থিতি রাতারাতি বদলে গেল।', 1049),
    ('ownership', null, 'n.', 'B2', 'মালিকানা', 'He proved ownership of the land.', 'সে জমির মালিকানা প্রমাণ করল।', 1050),
    ('oxygen', null, 'n.', 'B2', 'অক্সিজেন', 'We need oxygen to breathe.', 'শ্বাস নেওয়ার জন্য আমাদের অক্সিজেন দরকার।', 1051),
    ('packet', null, 'n.', 'B2', 'প্যাকেট', 'She bought a packet of biscuits.', 'সে এক প্যাকেট বিস্কুট কিনল।', 1052),
    ('palm', null, 'n.', 'B2', 'হাতের তালু', 'She held the coin in her palm.', 'সে হাতের তালুতে কয়েনটি ধরে রাখল।', 1053),
    ('panic', null, 'n.', 'B2', 'আতঙ্ক, ভীতি', 'The fire caused panic in the building.', 'আগুন ভবনে আতঙ্ক সৃষ্টি করল।', 1054),
    ('parade', null, 'n.', 'B2', 'কুচকাওয়াজ, শোভাযাত্রা', 'We watched the parade on Independence Day.', 'আমরা স্বাধীনতা দিবসে কুচকাওয়াজ দেখলাম।', 1055),
    ('parallel', null, 'adj., n.', 'B2', 'সমান্তরাল; তুলনীয় বিষয়/সাদৃশ্য', 'These two lines are parallel.', 'এই দুটি রেখা সমান্তরাল।', 1056),
    ('part-time', null, 'adv.', 'B2', 'খণ্ডকালীনভাবে', 'She works part-time at a cafe.', 'সে একটি ক্যাফেতে খণ্ডকালীনভাবে কাজ করে।', 1057),
    ('participation', null, 'n.', 'B2', 'অংশগ্রহণ', 'Participation in the event is free.', 'অনুষ্ঠানে অংশগ্রহণ বিনামূল্যে।', 1058),
    ('partnership', null, 'n.', 'B2', 'অংশীদারত্ব', 'The two companies formed a partnership.', 'দুটি কোম্পানি একটি অংশীদারত্ব গঠন করল।', 1059),
    ('passionate', null, 'adj.', 'B2', 'উদ্দীপ্ত, প্রবল অনুরাগী', 'He is passionate about music.', 'সে সংগীতের প্রতি অত্যন্ত অনুরাগী।', 1060),
    ('password', null, 'n.', 'B2', 'পাসওয়ার্ড', 'I forgot my email password.', 'আমি আমার ইমেইলের পাসওয়ার্ড ভুলে গেছি।', 1061),
    ('patch', null, 'n.', 'B2', 'তালি, ছোট অংশ', 'He sewed a patch on his jeans.', 'সে তার জিন্সে একটি তালি সেলাই করল।', 1062),
    ('patience', null, 'n.', 'B2', 'ধৈর্য', 'Teaching children requires patience.', 'শিশুদের শেখানোর জন্য ধৈর্য প্রয়োজন।', 1063),
    ('pause', null, 'v., n.', 'B2', 'থামা; বিরতি', 'She paused for a moment before speaking.', 'সে কথা বলার আগে এক মুহূর্ত থামল।', 1064),
    ('peer', null, 'n.', 'B2', 'সমবয়সী, সমকক্ষ', 'Teenagers often follow their peers.', 'কিশোর-কিশোরীরা প্রায়ই তাদের সমবয়সীদের অনুসরণ করে।', 1065),
    ('penalty', null, 'n.', 'B2', 'শাস্তি, জরিমানা', 'There is a penalty for being late.', 'দেরিতে আসার জন্য জরিমানা আছে।', 1066),
    ('perceive', null, 'v.', 'B2', 'উপলব্ধি করা, বোঝা', 'We perceive danger through our senses.', 'আমরা ইন্দ্রিয়ের মাধ্যমে বিপদ উপলব্ধি করি।', 1067),
    ('perception', null, 'n.', 'B2', 'উপলব্ধি, ধারণা', 'Her perception of time is different.', 'সময় সম্পর্কে তার ধারণা ভিন্ন।', 1068),
    ('permanently', null, 'adv.', 'B2', 'স্থায়ীভাবে', 'He moved permanently to Canada.', 'সে স্থায়ীভাবে কানাডায় চলে গেল।', 1069),
    ('pharmacy', null, 'n.', 'B2', 'ওষুধের দোকান, ফার্মেসি', 'I bought medicine at the pharmacy.', 'আমি ফার্মেসি থেকে ওষুধ কিনলাম।', 1070),
    ('physician', null, 'n.', 'B2', 'চিকিৎসক', 'The physician examined the patient.', 'চিকিৎসক রোগীকে পরীক্ষা করলেন।', 1071),
    ('pill', null, 'n.', 'B2', 'বড়ি, ট্যাবলেট', 'She took a pill for her headache.', 'সে মাথাব্যথার জন্য একটি বড়ি খেল।', 1072),
    ('pity', null, 'n.', 'B2', 'করুণা, দুঃখের বিষয়', 'It''s a pity you can''t come.', 'তুমি আসতে পারবে না, এটা দুঃখের বিষয়।', 1073),
    ('placement', null, 'n.', 'B2', 'নিয়োগ, স্থাপন', 'The agency helped with his job placement.', 'সংস্থাটি তার চাকরির নিয়োগে সাহায্য করেছিল।', 1074),
    ('portion', null, 'n.', 'B2', 'অংশ, ভাগ', 'She ate only a small portion of food.', 'সে খাবারের শুধু একটি ছোট অংশ খেল।', 1075),
    ('potentially', null, 'adv.', 'B2', 'সম্ভাব্যভাবে', 'This drug is potentially dangerous.', 'এই ওষুধটি সম্ভাব্যভাবে বিপজ্জনক।', 1076),
    ('precede', null, 'v.', 'B2', 'পূর্বে ঘটা, আগে থাকা', 'A loud noise preceded the explosion.', 'বিস্ফোরণের আগে একটি জোরালো শব্দ হয়েছিল।', 1077),
    ('precious', null, 'adj.', 'B2', 'মূল্যবান', 'Time is more precious than gold.', 'সময় সোনার চেয়েও মূল্যবান।', 1078),
    ('precise', null, 'adj.', 'B2', 'সুনির্দিষ্ট, সঠিক', 'I need the precise time of the meeting.', 'আমার মিটিংয়ের সুনির্দিষ্ট সময় দরকার।', 1079),
    ('precisely', null, 'adv.', 'B2', 'সুনির্দিষ্টভাবে, ঠিক', 'That is precisely what I meant.', 'আমি ঠিক এটাই বলতে চেয়েছিলাম।', 1080),
    ('predictable', null, 'adj.', 'B2', 'অনুমানযোগ্য', 'The ending of the movie was predictable.', 'সিনেমার শেষটি অনুমানযোগ্য ছিল।', 1081),
    ('preference', null, 'n.', 'B2', 'পছন্দ, অগ্রাধিকার', 'What is your preference, tea or coffee?', 'তোমার পছন্দ কী, চা নাকি কফি?', 1082),
    ('presidential', null, 'adj.', 'B2', 'রাষ্ট্রপতি সংক্রান্ত', 'The presidential election is next year.', 'রাষ্ট্রপতি নির্বাচন আগামী বছর।', 1083),
    ('pride', null, 'n.', 'B2', 'গর্ব', 'She felt pride in her son''s success.', 'সে তার ছেলের সাফল্যে গর্ব অনুভব করল।', 1084),
    ('primarily', null, 'adv.', 'B2', 'প্রধানত', 'The book is primarily for children.', 'বইটি প্রধানত শিশুদের জন্য।', 1085),
    ('principal', null, 'adj.', 'B2', 'প্রধান', 'The principal reason was money.', 'প্রধান কারণ ছিল টাকা।', 1086),
    ('prior', null, 'adj.', 'B2', 'পূর্ববর্তী', 'She has no prior experience in teaching.', 'শিক্ষকতায় তার কোনো পূর্ব অভিজ্ঞতা নেই।', 1087),
    ('probability', null, 'n.', 'B2', 'সম্ভাবনা', 'The probability of rain is high today.', 'আজ বৃষ্টির সম্ভাবনা বেশি।', 1088),
    ('probable', null, 'adj.', 'B2', 'সম্ভাব্য', 'Rain is probable this afternoon.', 'আজ বিকেলে বৃষ্টি হওয়া সম্ভাব্য।', 1089),
    ('proceed', null, 'v.', 'B2', 'এগিয়ে যাওয়া, শুরু করা', 'Let''s proceed with the plan.', 'চলো পরিকল্পনা অনুযায়ী এগিয়ে যাই।', 1090),
    ('programming', null, 'n.', 'B2', 'প্রোগ্রামিং', 'He is learning computer programming.', 'সে কম্পিউটার প্রোগ্রামিং শিখছে।', 1091),
    ('progressive', null, 'adj.', 'B2', 'প্রগতিশীল', 'She has progressive ideas about education.', 'শিক্ষা নিয়ে তার প্রগতিশীল ধারণা আছে।', 1092),
    ('prohibit', null, 'v.', 'B2', 'নিষিদ্ধ করা', 'The law prohibits smoking here.', 'আইন এখানে ধূমপান নিষিদ্ধ করে।', 1093),
    ('promising', null, 'adj.', 'B2', 'সম্ভাবনাময়, প্রতিশ্রুতিশীল', 'She is a promising young artist.', 'সে একজন সম্ভাবনাময় তরুণ শিল্পী।', 1094),
    ('promotion', null, 'n.', 'B2', 'পদোন্নতি, প্রচার', 'He got a promotion at work.', 'সে কাজে পদোন্নতি পেয়েছে।', 1095),
    ('prompt', null, 'v.', 'B2', 'প্ররোচিত করা, তাগিদ দেওয়া', 'Her question prompted a long discussion.', 'তার প্রশ্ন একটি দীর্ঘ আলোচনার জন্ম দিল।', 1096),
    ('proportion', null, 'n.', 'B2', 'অনুপাত', 'A large proportion of students passed.', 'শিক্ষার্থীদের একটি বড় অংশ পাস করেছে।', 1097),
    ('protein', null, 'n.', 'B2', 'প্রোটিন', 'Eggs are rich in protein.', 'ডিমে প্রচুর প্রোটিন থাকে।', 1098),
    ('protester', null, 'n.', 'B2', 'বিক্ষোভকারী', 'Protesters gathered outside the building.', 'বিক্ষোভকারীরা ভবনের বাইরে জড়ো হলো।', 1099),
    ('psychological', null, 'adj.', 'B2', 'মনস্তাত্ত্বিক', 'The illness has a psychological cause.', 'রোগটির একটি মনস্তাত্ত্বিক কারণ আছে।', 1100),
    ('publicity', null, 'n.', 'B2', 'প্রচার', 'The movie got a lot of publicity.', 'সিনেমাটি প্রচুর প্রচার পেয়েছে।', 1101),
    ('publishing', null, 'n.', 'B2', 'প্রকাশনা', 'She works in the publishing industry.', 'সে প্রকাশনা শিল্পে কাজ করে।', 1102),
    ('punk', null, 'n.', 'B2', 'পাংক (উপসংস্কৃতি/সংগীতধারা)', 'He loves punk music.', 'সে পাংক সংগীত পছন্দ করে।', 1103),
    ('purely', null, 'adv.', 'B2', 'একেবারে, শুধুমাত্র', 'It happened purely by chance.', 'এটি একেবারে কাকতালীয়ভাবে ঘটেছিল।', 1104),
    ('pursuit', null, 'n.', 'B2', 'অনুসরণ, সাধনা', 'She quit her job in pursuit of happiness.', 'সে সুখের সন্ধানে চাকরি ছেড়ে দিল।', 1105),
    ('puzzle', null, 'n.', 'B2', 'ধাঁধা', 'The children solved the puzzle quickly.', 'বাচ্চারা দ্রুত ধাঁধাটি সমাধান করল।', 1106),
    ('questionnaire', null, 'n.', 'B2', 'প্রশ্নপত্র, জরিপপত্র', 'Please fill out this questionnaire.', 'দয়া করে এই প্রশ্নপত্রটি পূরণ করুন।', 1107),
    ('racial', null, 'adj.', 'B2', 'বর্ণগত, জাতিগত', 'The city has a history of racial tension.', 'শহরটির বর্ণগত উত্তেজনার ইতিহাস আছে।', 1108),
    ('racism', null, 'n.', 'B2', 'বর্ণবাদ', 'The film deals with racism in society.', 'চলচ্চিত্রটি সমাজে বর্ণবাদ নিয়ে কথা বলে।', 1109),
    ('racist', null, 'adj., n.', 'B2', 'বর্ণবাদী', 'He made a racist comment.', 'সে একটি বর্ণবাদী মন্তব্য করেছিল।', 1110),
    ('radiation', null, 'n.', 'B2', 'বিকিরণ', 'Radiation from the sun can be harmful.', 'সূর্যের বিকিরণ ক্ষতিকর হতে পারে।', 1111),
    ('rail', null, 'n.', 'B2', 'রেল, রেললাইন', 'We traveled to the city by rail.', 'আমরা রেলপথে শহরে ভ্রমণ করেছিলাম।', 1112),
    ('random', null, 'adj.', 'B2', 'এলোমেলো, দৈব', 'She picked a random number.', 'সে একটি এলোমেলো সংখ্যা বেছে নিল।', 1113),
    ('rat', null, 'n.', 'B2', 'ইঁদুর', 'A rat ran across the kitchen floor.', 'একটি ইঁদুর রান্নাঘরের মেঝে দিয়ে দৌড়ে গেল।', 1114),
    ('rating', null, 'n.', 'B2', 'রেটিং, মূল্যায়ন', 'The movie got a high rating.', 'সিনেমাটি উচ্চ রেটিং পেয়েছে।', 1115),
    ('reasonably', null, 'adv.', 'B2', 'যুক্তিসঙ্গতভাবে, মোটামুটি', 'The food here is reasonably priced.', 'এখানকার খাবারের দাম যুক্তিসঙ্গত।', 1116),
    ('rebuild', null, 'v.', 'B2', 'পুনর্নির্মাণ করা', 'They will rebuild the house after the fire.', 'আগুনের পর তারা বাড়িটি পুনর্নির্মাণ করবে।', 1117),
    ('receiver', null, 'n.', 'B2', 'গ্রাহক, রিসিভার', 'She picked up the phone receiver.', 'সে ফোনের রিসিভার তুলল।', 1118),
    ('recession', null, 'n.', 'B2', 'অর্থনৈতিক মন্দা', 'Many people lost jobs during the recession.', 'মন্দার সময় অনেকে চাকরি হারিয়েছিল।', 1119),
    ('reckon', null, 'v.', 'B2', 'মনে করা, অনুমান করা', 'I reckon it will rain tomorrow.', 'আমার মনে হয় আগামীকাল বৃষ্টি হবে।', 1120),
    ('recognition', null, 'n.', 'B2', 'স্বীকৃতি', 'She received recognition for her work.', 'সে তার কাজের জন্য স্বীকৃতি পেয়েছে।', 1121),
    ('recovery', null, 'n.', 'B2', 'আরোগ্য, পুনরুদ্ধার', 'His recovery from surgery was quick.', 'অস্ত্রোপচার থেকে তার আরোগ্য দ্রুত হয়েছিল।', 1122),
    ('recruit', null, 'v., n.', 'B2', 'নিয়োগ করা; নবাগত সদস্য', 'The army will recruit new soldiers.', 'সেনাবাহিনী নতুন সৈন্য নিয়োগ করবে।', 1123),
    ('referee', null, 'n.', 'B2', 'রেফারি, বিচারক', 'The referee stopped the match.', 'রেফারি ম্যাচটি থামিয়ে দিলেন।', 1124),
    ('refugee', null, 'n.', 'B2', 'শরণার্থী', 'The refugee family found a new home.', 'শরণার্থী পরিবারটি একটি নতুন আশ্রয় খুঁজে পেল।', 1125),
    ('registration', null, 'n.', 'B2', 'নিবন্ধন', 'Registration for the course starts tomorrow.', 'কোর্সের নিবন্ধন আগামীকাল শুরু হবে।', 1126),
    ('regulate', null, 'v.', 'B2', 'নিয়ন্ত্রণ করা', 'The government will regulate food prices.', 'সরকার খাদ্যের দাম নিয়ন্ত্রণ করবে।', 1127),
    ('reinforce', null, 'v.', 'B2', 'শক্তিশালী করা, জোরদার করা', 'They reinforced the wall with steel.', 'তারা ইস্পাত দিয়ে দেয়ালটি শক্তিশালী করল।', 1128),
    ('relieve', null, 'v.', 'B2', 'উপশম করা, লাঘব করা', 'This medicine will relieve your pain.', 'এই ওষুধ তোমার ব্যথা উপশম করবে।', 1129),
    ('relieved', null, 'adj.', 'B2', 'স্বস্তিপ্রাপ্ত, নিশ্চিন্ত', 'She felt relieved after the exam.', 'পরীক্ষার পর সে স্বস্তি বোধ করল।', 1130),
    ('remarkable', null, 'adj.', 'B2', 'উল্লেখযোগ্য, অসাধারণ', 'She made a remarkable recovery.', 'সে অসাধারণভাবে সুস্থ হয়ে উঠেছে।', 1131),
    ('remarkably', null, 'adv.', 'B2', 'উল্লেখযোগ্যভাবে', 'The two paintings look remarkably similar.', 'ছবি দুটি উল্লেখযোগ্যভাবে একই রকম দেখতে।', 1132),
    ('reporting', null, 'n.', 'B2', 'প্রতিবেদন প্রণয়ন', 'The news channel is known for honest reporting.', 'নিউজ চ্যানেলটি সৎ প্রতিবেদনের জন্য পরিচিত।', 1133),
    ('resign', null, 'v.', 'B2', 'পদত্যাগ করা', 'He decided to resign from his job.', 'সে তার চাকরি থেকে পদত্যাগ করার সিদ্ধান্ত নিল।', 1134),
    ('resolution', null, 'n.', 'B2', 'সিদ্ধান্ত, সমাধান', 'She made a resolution to exercise daily.', 'সে প্রতিদিন ব্যায়াম করার সিদ্ধান্ত নিল।', 1135),
    ('restore', null, 'v.', 'B2', 'পুনরুদ্ধার করা', 'They worked to restore the old building.', 'তারা পুরনো ভবনটি পুনরুদ্ধার করতে কাজ করল।', 1136),
    ('restrict', null, 'v.', 'B2', 'সীমাবদ্ধ করা', 'The rules restrict access to the area.', 'নিয়মগুলো এই এলাকায় প্রবেশ সীমাবদ্ধ করে।', 1137),
    ('restriction', null, 'n.', 'B2', 'বিধিনিষেধ', 'There are new restrictions on travel.', 'ভ্রমণের ওপর নতুন বিধিনিষেধ আছে।', 1138),
    ('retail', null, 'n.', 'B2', 'খুচরা বিক্রয়', 'She works in retail at a clothing store.', 'সে একটি পোশাকের দোকানে খুচরা বিক্রয়ে কাজ করে।', 1139),
    ('retirement', null, 'n.', 'B2', 'অবসর', 'He is looking forward to retirement.', 'সে অবসরের অপেক্ষায় আছে।', 1140),
    ('revenue', null, 'n.', 'B2', 'রাজস্ব, আয়', 'The company''s revenue grew last year.', 'গত বছর কোম্পানির রাজস্ব বেড়েছে।', 1141),
    ('revision', null, 'n.', 'B2', 'পুনর্বিবেচনা, সংশোধন', 'The essay needs one more revision.', 'প্রবন্ধটির আরেকটি সংশোধন দরকার।', 1142),
    ('ridiculous', null, 'adj.', 'B2', 'হাস্যকর', 'That excuse sounds ridiculous.', 'সেই অজুহাতটি হাস্যকর শোনাচ্ছে।', 1143),
    ('risky', null, 'adj.', 'B2', 'ঝুঁকিপূর্ণ', 'Climbing without ropes is risky.', 'দড়ি ছাড়া আরোহণ করা ঝুঁকিপূর্ণ।', 1144),
    ('rival', null, 'n., adj.', 'B2', 'প্রতিদ্বন্দ্বী', 'The two teams are old rivals.', 'দুটি দল পুরনো প্রতিদ্বন্দ্বী।', 1145),
    ('rob', null, 'v.', 'B2', 'ডাকাতি করা, লুট করা', 'Thieves tried to rob the bank.', 'চোরেরা ব্যাংক ডাকাতির চেষ্টা করেছিল।', 1146),
    ('robbery', null, 'n.', 'B2', 'ডাকাতি', 'Police investigated the bank robbery.', 'পুলিশ ব্যাংক ডাকাতির তদন্ত করল।', 1147),
    ('rocket', null, 'n.', 'B2', 'রকেট', 'The rocket launched into space.', 'রকেটটি মহাকাশে উৎক্ষেপণ করা হলো।', 1148),
    ('romance', null, 'n.', 'B2', 'প্রণয়, রোমান্স', 'The movie is about romance and adventure.', 'সিনেমাটি প্রণয় ও দুঃসাহসিকতা নিয়ে।', 1149),
    ('rose', null, 'n.', 'B2', 'গোলাপ', 'He gave her a red rose.', 'সে তাকে একটি লাল গোলাপ দিল।', 1150),
    ('roughly', null, 'adv.', 'B2', 'মোটামুটি, আনুমানিক', 'It takes roughly two hours to get there.', 'সেখানে পৌঁছাতে মোটামুটি দুই ঘণ্টা লাগে।', 1151),
    ('ruin', null, 'v., n.', 'B2', 'ধ্বংস করা; ধ্বংসাবশেষ', 'The rain will ruin our picnic.', 'বৃষ্টি আমাদের বনভোজন নষ্ট করে দেবে।', 1152),
    ('résumé', null, 'n.', 'B2', 'জীবনবৃত্তান্ত, সিভি', 'Please send me your résumé.', 'দয়া করে আমাকে তোমার জীবনবৃত্তান্ত পাঠাও।', 1153),
    ('satisfaction', null, 'n.', 'B2', 'সন্তুষ্টি', 'Her work gives her great satisfaction.', 'তার কাজ তাকে অনেক সন্তুষ্টি দেয়।', 1154),
    ('scandal', null, 'n.', 'B2', 'কেলেঙ্কারি', 'The scandal ended his career.', 'কেলেঙ্কারিটি তার ক্যারিয়ার শেষ করে দিল।', 1155),
    ('scare', null, 'v., n.', 'B2', 'ভয় দেখানো; ভীতি', 'The loud noise scared the baby.', 'জোরালো শব্দ শিশুটিকে ভয় দেখাল।', 1156),
    ('scenario', null, 'n.', 'B2', 'পরিস্থিতি, সম্ভাব্য ঘটনাক্রম', 'Let''s imagine a different scenario.', 'চলো একটি ভিন্ন পরিস্থিতি কল্পনা করি।', 1157),
    ('scholar', null, 'n.', 'B2', 'পণ্ডিত, বিদ্বান', 'The scholar wrote many research papers.', 'পণ্ডিতটি অনেক গবেষণাপত্র লিখেছেন।', 1158),
    ('scholarship', null, 'n.', 'B2', 'বৃত্তি (শিক্ষাবৃত্তি)', 'She won a scholarship to study abroad.', 'সে বিদেশে পড়াশোনার জন্য একটি বৃত্তি পেয়েছে।', 1159),
    ('scratch', null, 'v., n.', 'B2', 'আঁচড়ানো; আঁচড়', 'The cat tried to scratch me.', 'বিড়ালটি আমাকে আঁচড়াতে চেষ্টা করল।', 1160),
    ('screening', null, 'n.', 'B2', 'স্বাস্থ্য পরীক্ষণ, প্রদর্শনী', 'The hospital offers free health screening.', 'হাসপাতালটি বিনামূল্যে স্বাস্থ্য স্ক্রিনিং প্রদান করে।', 1161),
    ('seeker', null, 'n.', 'B2', 'অন্বেষণকারী, প্রার্থী', 'He is a job seeker in the city.', 'সে শহরে একজন চাকরি প্রার্থী।', 1162),
    ('seminar', null, 'n.', 'B2', 'সেমিনার', 'We attended a seminar on climate change.', 'আমরা জলবায়ু পরিবর্তনের ওপর একটি সেমিনারে অংশ নিলাম।', 1163),
    ('settler', null, 'n.', 'B2', 'উপনিবেশ স্থাপনকারী, বসতি স্থাপনকারী', 'The settlers built new homes on the land.', 'বসতি স্থাপনকারীরা জমিতে নতুন ঘর তৈরি করল।', 1164),
    ('severely', null, 'adv.', 'B2', 'কঠোরভাবে, তীব্রভাবে', 'He was severely injured in the accident.', 'দুর্ঘটনায় সে গুরুতরভাবে আহত হয়েছিল।', 1165),
    ('sexy', null, 'adj.', 'B2', 'যৌন আবেদনময়, আকর্ষণীয়', 'She wore a sexy red dress.', 'সে একটি আকর্ষণীয় লাল পোশাক পরেছিল।', 1166),
    ('shaped', null, 'adj.', 'B2', 'নির্দিষ্ট আকৃতিবিশিষ্ট, ...-আকৃতির', 'The cake was shaped like a heart.', 'কেকটি হৃদয়ের আকৃতির ছিল।', 1167),
    ('shocking', null, 'adj.', 'B2', 'মর্মান্তিক, স্তম্ভিতকর', 'The news was shocking to everyone.', 'খবরটি সবার কাছে মর্মান্তিক ছিল।', 1168),
    ('shore', null, 'n.', 'B2', 'তীর, উপকূল', 'We walked along the shore.', 'আমরা তীর ধরে হাঁটলাম।', 1169),
    ('short-term', null, 'adj.', 'B2', 'স্বল্পমেয়াদী', 'This is only a short-term solution.', 'এটি শুধু একটি স্বল্পমেয়াদী সমাধান।', 1170),
    ('shortage', null, 'n.', 'B2', 'ঘাটতি, অভাব', 'There is a shortage of water in summer.', 'গ্রীষ্মে পানির ঘাটতি দেখা দেয়।', 1171),
    ('shortly', null, 'adv.', 'B2', 'শীঘ্রই', 'The meeting will start shortly.', 'সভা শীঘ্রই শুরু হবে।', 1172),
    ('sibling', null, 'n.', 'B2', 'ভাইবোন (সহোদর)', 'I have two siblings, a brother and a sister.', 'আমার দুই ভাইবোন আছে, একজন ভাই ও একজন বোন।', 1173),
    ('sidewalk', null, 'n.', 'B2', 'ফুটপাত', 'Children were playing on the sidewalk.', 'বাচ্চারা ফুটপাতে খেলছিল।', 1174),
    ('signature', null, 'n.', 'B2', 'স্বাক্ষর', 'Please put your signature here.', 'দয়া করে এখানে আপনার স্বাক্ষর দিন।', 1175),
    ('significance', null, 'n.', 'B2', 'গুরুত্ব, তাৎপর্য', 'This discovery has great significance.', 'এই আবিষ্কারের অনেক তাৎপর্য আছে।', 1176),
    ('skilled', null, 'adj.', 'B2', 'দক্ষ, নিপুণ', 'We need a skilled worker for this job.', 'এই কাজের জন্য আমাদের একজন দক্ষ শ্রমিক দরকার।', 1177),
    ('skull', null, 'n.', 'B2', 'মাথার খুলি', 'The skull protects the brain.', 'মাথার খুলি মস্তিষ্ককে রক্ষা করে।', 1178),
    ('slogan', null, 'n.', 'B2', 'স্লোগান, প্রচারবাক্য', 'The company created a new slogan.', 'কোম্পানিটি একটি নতুন স্লোগান তৈরি করল।', 1179),
    ('so-called', null, 'adj.', 'B2', 'তথাকথিত', 'The so-called expert gave wrong advice.', 'তথাকথিত বিশেষজ্ঞটি ভুল পরামর্শ দিয়েছিল।', 1180),
    ('somehow', null, 'adv.', 'B2', 'কোনোভাবে', 'Somehow, we finished the project on time.', 'কোনোভাবে আমরা সময়মতো প্রকল্পটি শেষ করলাম।', 1181),
    ('sometime', null, 'adv.', 'B2', 'কোনো এক সময়', 'Let''s meet sometime next week.', 'আসুন আগামী সপ্তাহে কোনো এক সময় দেখা করি।', 1182),
    ('sophisticated', null, 'adj.', 'B2', 'জটিল ও উন্নত, পরিশীলিত', 'The new phone has sophisticated technology.', 'নতুন ফোনটিতে উন্নত প্রযুক্তি আছে।', 1183),
    ('spare', null, 'adj.', 'B2', 'অতিরিক্ত, বাড়তি', 'I always carry a spare tire.', 'আমি সবসময় একটি অতিরিক্ত টায়ার সঙ্গে রাখি।', 1184),
    ('specify', null, 'v.', 'B2', 'নির্দিষ্ট করে বলা, উল্লেখ করা', 'Please specify your requirements clearly.', 'দয়া করে আপনার চাহিদা স্পষ্টভাবে উল্লেখ করুন।', 1185),
    ('spectacular', null, 'adj.', 'B2', 'দর্শনীয়, চমৎকার', 'The view from the mountain was spectacular.', 'পাহাড় থেকে দৃশ্যটি ছিল দর্শনীয়।', 1186),
    ('spectator', null, 'n.', 'B2', 'দর্শক', 'Thousands of spectators watched the match.', 'হাজার হাজার দর্শক ম্যাচটি দেখলেন।', 1187),
    ('speculate', null, 'v.', 'B2', 'অনুমান করা, জল্পনা করা', 'People speculate about the company''s future.', 'মানুষ কোম্পানিটির ভবিষ্যৎ নিয়ে জল্পনা করছে।', 1188),
    ('speculation', null, 'n.', 'B2', 'অনুমান, জল্পনা', 'There is much speculation about the election.', 'নির্বাচন নিয়ে অনেক জল্পনা চলছে।', 1189),
    ('spice', null, 'n.', 'B2', 'মসলা', 'This curry needs more spice.', 'এই তরকারিতে আরও মসলা দরকার।', 1190),
    ('spill', null, 'v.', 'B2', 'ছলকে পড়া, ফেলে দেওয়া', 'Be careful not to spill the milk.', 'দুধ যাতে না পড়ে সেদিকে খেয়াল রাখো।', 1191),
    ('spite', null, 'n.', 'B2', 'বিদ্বেষ, রাগ', 'He did it out of spite.', 'সে বিদ্বেষ থেকে এটা করেছিল।', 1192),
    ('spoil', null, 'v.', 'B2', 'নষ্ট করা; (সন্তানকে) অতিরিক্ত আদরে বিগড়ে দেওয়া', 'Don''t spoil the surprise for her.', 'তার জন্য চমকটা নষ্ট কোরো না।', 1193),
    ('spokesman', null, 'n.', 'B2', 'মুখপাত্র (পুরুষ)', 'The spokesman announced the new policy.', 'মুখপাত্র নতুন নীতি ঘোষণা করলেন।', 1194),
    ('spokesperson', null, 'n.', 'B2', 'মুখপাত্র (লিঙ্গনিরপেক্ষ)', 'A spokesperson confirmed the news.', 'একজন মুখপাত্র খবরটি নিশ্চিত করলেন।', 1195),
    ('spokeswoman', null, 'n.', 'B2', 'মুখপাত্র (নারী)', 'The spokeswoman answered all questions.', 'নারী মুখপাত্রটি সব প্রশ্নের উত্তর দিলেন।', 1196),
    ('sponsorship', null, 'n.', 'B2', 'পৃষ্ঠপোষকতা', 'The team needs sponsorship to compete.', 'প্রতিযোগিতায় অংশ নিতে দলটির পৃষ্ঠপোষকতা দরকার।', 1197),
    ('stall', null, 'n.', 'B2', 'দোকান, স্টল (ছোট বিক্রয়স্থান)', 'She sells flowers at a small stall.', 'সে একটি ছোট স্টলে ফুল বিক্রি করে।', 1198),
    ('stance', null, 'n.', 'B2', 'অবস্থান, দৃষ্টিভঙ্গি', 'The government changed its stance on tax.', 'সরকার করনীতি নিয়ে তাদের অবস্থান পরিবর্তন করেছে।', 1199),
    ('starve', null, 'v.', 'B2', 'অনাহারে থাকা, ক্ষুধায় মরা', 'Many people starve during a famine.', 'দুর্ভিক্ষের সময় অনেক মানুষ অনাহারে থাকে।', 1200),
    ('steadily', null, 'adv.', 'B2', 'ধীরে ধীরে ও স্থিরভাবে', 'Prices have risen steadily this year.', 'এই বছর দাম ধীরে ধীরে বেড়েছে।', 1201),
    ('steam', null, 'n.', 'B2', 'বাষ্প', 'Steam rose from the hot tea.', 'গরম চা থেকে বাষ্প উঠছিল।', 1202),
    ('stimulate', null, 'v.', 'B2', 'উদ্দীপিত করা, উৎসাহিত করা', 'Exercise can stimulate the brain.', 'ব্যায়াম মস্তিষ্ককে উদ্দীপিত করতে পারে।', 1203),
    ('strengthen', null, 'v.', 'B2', 'শক্তিশালী করা', 'We must strengthen our defenses.', 'আমাদের প্রতিরক্ষা শক্তিশালী করতে হবে।', 1204),
    ('strictly', null, 'adv.', 'B2', 'কঠোরভাবে', 'Smoking is strictly forbidden here.', 'এখানে ধূমপান কঠোরভাবে নিষিদ্ধ।', 1205),
    ('striking', null, 'adj.', 'B2', 'নজরকাড়া, চোখে পড়ার মতো', 'She has striking blue eyes.', 'তার নীল চোখ দুটি নজরকাড়া।', 1206),
    ('stroke', null, 'n.', 'B2', 'স্ট্রোক (মস্তিষ্কের রোগ); আঘাত', 'Her grandfather had a stroke last year.', 'তার দাদার গত বছর স্ট্রোক হয়েছিল।', 1207),
    ('stunning', null, 'adj.', 'B2', 'অতি সুন্দর, অসাধারণ', 'The bride looked stunning in her dress.', 'বধূকে তার পোশাকে অসাধারণ সুন্দর লাগছিল।', 1208),
    ('subsequent', null, 'adj.', 'B2', 'পরবর্তী', 'Subsequent events proved him right.', 'পরবর্তী ঘটনাগুলো তাকে সঠিক প্রমাণ করেছিল।', 1209),
    ('subsequently', null, 'adv.', 'B2', 'পরবর্তীতে', 'He was arrested and subsequently released.', 'তাকে গ্রেপ্তার করা হয় এবং পরবর্তীতে মুক্তি দেওয়া হয়।', 1210),
    ('suburb', null, 'n.', 'B2', 'শহরতলি', 'They live in a quiet suburb.', 'তারা একটি শান্ত শহরতলিতে থাকে।', 1211),
    ('suffering', null, 'n.', 'B2', 'কষ্ট, যন্ত্রণা', 'The war caused great suffering.', 'যুদ্ধ অনেক কষ্টের কারণ হয়েছিল।', 1212),
    ('sufficient', null, 'adj.', 'B2', 'পর্যাপ্ত', 'We have sufficient food for the trip.', 'ভ্রমণের জন্য আমাদের পর্যাপ্ত খাবার আছে।', 1213),
    ('sufficiently', null, 'adv.', 'B2', 'পর্যাপ্তভাবে', 'The room was not sufficiently heated.', 'ঘরটি পর্যাপ্তভাবে গরম করা হয়নি।', 1214),
    ('super', null, 'adj.', 'B2', 'চমৎকার, দারুণ', 'That was a super idea!', 'এটা দারুণ একটা আইডিয়া ছিল!', 1215),
    ('surgeon', null, 'n.', 'B2', 'শল্যচিকিৎসক', 'The surgeon operated on his heart.', 'শল্যচিকিৎসক তার হৃদয়ে অস্ত্রোপচার করলেন।', 1216),
    ('survival', null, 'n.', 'B2', 'বেঁচে থাকা, বাঁচার সংগ্রাম', 'Water is essential for survival.', 'বেঁচে থাকার জন্য পানি অপরিহার্য।', 1217),
    ('survivor', null, 'n.', 'B2', 'বেঁচে যাওয়া ব্যক্তি', 'The survivor told his story to reporters.', 'বেঁচে যাওয়া ব্যক্তিটি সাংবাদিকদের তার গল্প বললেন।', 1218),
    ('suspend', null, 'v.', 'B2', 'স্থগিত করা, সাময়িকভাবে বন্ধ রাখা', 'The school decided to suspend classes.', 'স্কুল ক্লাস স্থগিত করার সিদ্ধান্ত নিল।', 1219),
    ('sustainable', null, 'adj.', 'B2', 'টেকসই', 'We need sustainable energy sources.', 'আমাদের টেকসই জ্বালানি উৎস দরকার।', 1220),
    ('swallow', null, 'v.', 'B2', 'গিলে ফেলা', 'It is hard to swallow this pill.', 'এই বড়িটা গেলা কঠিন।', 1221),
    ('sympathetic', null, 'adj.', 'B2', 'সহানুভূতিশীল', 'The doctor was very sympathetic to her fear.', 'ডাক্তার তার ভয়ের প্রতি খুব সহানুভূতিশীল ছিলেন।', 1222),
    ('tackle', null, 'v.', 'B2', 'মোকাবিলা করা, সমাধানে হাত দেওয়া', 'The government must tackle poverty.', 'সরকারকে দারিদ্র্য মোকাবিলা করতে হবে।', 1223),
    ('tag', null, 'n., v.', 'B2', 'ট্যাগ, লেবেল; ট্যাগ লাগানো', 'She put a price tag on the item.', 'সে জিনিসটির গায়ে একটি দামের ট্যাগ লাগাল।', 1224),
    ('tap', null, 'v., n.', 'B2', 'আলতো করে টোকা দেওয়া; কল, ট্যাপ', 'He tapped the window to say hello.', 'সে হ্যালো বলতে জানালায় টোকা দিল।', 1225),
    ('technological', null, 'adj.', 'B2', 'প্রযুক্তিগত', 'We live in an age of technological change.', 'আমরা প্রযুক্তিগত পরিবর্তনের যুগে বাস করি।', 1226),
    ('teen', null, 'n., adj.', 'B2', 'কিশোর-কিশোরী; কিশোর বয়সী', 'Many teens use social media daily.', 'অনেক কিশোর-কিশোরী প্রতিদিন সামাজিক মাধ্যম ব্যবহার করে।', 1227),
    ('temple', null, 'n.', 'B2', 'মন্দির', 'They visited an old temple in the village.', 'তারা গ্রামের একটি পুরনো মন্দির পরিদর্শন করল।', 1228),
    ('temporarily', null, 'adv.', 'B2', 'সাময়িকভাবে', 'The road is temporarily closed.', 'রাস্তাটি সাময়িকভাবে বন্ধ আছে।', 1229),
    ('tendency', null, 'n.', 'B2', 'প্রবণতা', 'He has a tendency to arrive late.', 'তার দেরিতে আসার প্রবণতা আছে।', 1230),
    ('tension', null, 'n.', 'B2', 'উত্তেজনা, চাপ', 'There was tension between the two teams.', 'দুই দলের মধ্যে উত্তেজনা ছিল।', 1231),
    ('terminal', null, 'n.', 'B2', 'টার্মিনাল (স্টেশন/বিমানবন্দর অংশ)', 'Our flight leaves from terminal two.', 'আমাদের ফ্লাইট দুই নম্বর টার্মিনাল থেকে ছাড়বে।', 1232),
    ('terms', null, 'n.', 'B2', 'শর্তাবলি', 'Please read the terms before signing.', 'স্বাক্ষর করার আগে শর্তাবলি পড়ুন।', 1233),
    ('terribly', null, 'adv.', 'B2', 'ভীষণভাবে, খুব', 'I feel terribly sorry for the mistake.', 'ভুলটির জন্য আমি ভীষণ দুঃখিত বোধ করছি।', 1234),
    ('terrify', null, 'v.', 'B2', 'আতঙ্কিত করা, ভয় পাওয়ানো', 'Loud noises terrify the small child.', 'জোরে শব্দ ছোট শিশুটিকে আতঙ্কিত করে।', 1235),
    ('territory', null, 'n.', 'B2', 'অঞ্চল, ভূখণ্ড', 'The army entered enemy territory.', 'সেনাবাহিনী শত্রুর ভূখণ্ডে প্রবেশ করল।', 1236),
    ('terror', null, 'n.', 'B2', 'ভয়, ত্রাস', 'The city lived in terror of attacks.', 'শহরটি হামলার ভয়ে ত্রস্ত ছিল।', 1237),
    ('terrorism', null, 'n.', 'B2', 'সন্ত্রাসবাদ', 'The government fights against terrorism.', 'সরকার সন্ত্রাসবাদের বিরুদ্ধে লড়ছে।', 1238),
    ('terrorist', null, 'n.', 'B2', 'সন্ত্রাসী', 'Police arrested the terrorist last night.', 'পুলিশ গত রাতে সন্ত্রাসীকে গ্রেপ্তার করেছে।', 1239),
    ('testing', null, 'n.', 'B2', 'পরীক্ষণ, পরীক্ষা', 'The new drug is still in testing.', 'নতুন ওষুধটি এখনও পরীক্ষণ পর্যায়ে আছে।', 1240),
    ('textbook', null, 'n.', 'B2', 'পাঠ্যপুস্তক', 'She forgot her textbook at school.', 'সে স্কুলে তার পাঠ্যপুস্তক ফেলে এসেছে।', 1241),
    ('theft', null, 'n.', 'B2', 'চুরি', 'He was arrested for theft.', 'চুরির অভিযোগে তাকে গ্রেপ্তার করা হয়েছিল।', 1242),
    ('therapist', null, 'n.', 'B2', 'থেরাপিস্ট, চিকিৎসক', 'She sees a therapist every week.', 'সে প্রতি সপ্তাহে একজন থেরাপিস্টের কাছে যায়।', 1243),
    ('thesis', null, 'n.', 'B2', 'গবেষণাপত্র, থিসিস', 'He is writing his master''s thesis.', 'সে তার স্নাতকোত্তর থিসিস লিখছে।', 1244),
    ('thorough', null, 'adj.', 'B2', 'পুঙ্খানুপুঙ্খ, সম্পূর্ণ', 'The police did a thorough search.', 'পুলিশ একটি পুঙ্খানুপুঙ্খ তল্লাশি চালাল।', 1245),
    ('thoroughly', null, 'adv.', 'B2', 'পুঙ্খানুপুঙ্খভাবে, সম্পূর্ণরূপে', 'Please clean the kitchen thoroughly.', 'দয়া করে রান্নাঘরটি পুঙ্খানুপুঙ্খভাবে পরিষ্কার করুন।', 1246),
    ('thumb', null, 'n.', 'B2', 'বৃদ্ধাঙ্গুলি', 'He hurt his thumb while working.', 'কাজ করার সময় সে তার বৃদ্ধাঙ্গুলিতে আঘাত পেল।', 1247),
    ('timing', null, 'n.', 'B2', 'সময়নির্ধারণ, সময়জ্ঞান', 'Your timing for the joke was perfect.', 'কৌতুকটি বলার সময়নির্ধারণ নিখুঁত ছিল।', 1248),
    ('tissue', null, 'n.', 'B2', 'টিস্যু (কাগজ); দেহকলা', 'She wiped her nose with a tissue.', 'সে টিস্যু দিয়ে নাক মুছল।', 1249),
    ('tournament', null, 'n.', 'B2', 'প্রতিযোগিতা, টুর্নামেন্ট', 'Our team won the tournament last year.', 'আমাদের দল গত বছর টুর্নামেন্টে জিতেছিল।', 1250),
    ('trace', null, 'v.', 'B2', 'খুঁজে বের করা, উৎস অনুসন্ধান করা', 'Police could not trace the missing man.', 'পুলিশ নিখোঁজ ব্যক্তিটিকে খুঁজে বের করতে পারেনি।', 1251),
    ('trading', null, 'n.', 'B2', 'ব্যবসা, লেনদেন', 'He works in international trading.', 'সে আন্তর্জাতিক ব্যবসায় কাজ করে।', 1252),
    ('tragedy', null, 'n.', 'B2', 'মর্মান্তিক ঘটনা, ট্র্যাজেডি', 'The accident was a terrible tragedy.', 'দুর্ঘটনাটি ছিল একটি ভয়ংকর ট্র্যাজেডি।', 1253),
    ('tragic', null, 'adj.', 'B2', 'মর্মান্তিক', 'The tragic accident shocked the town.', 'মর্মান্তিক দুর্ঘটনাটি শহরকে হতবাক করেছিল।', 1254),
    ('trait', null, 'n.', 'B2', 'বৈশিষ্ট্য, স্বভাবগুণ', 'Honesty is an important trait.', 'সততা একটি গুরুত্বপূর্ণ বৈশিষ্ট্য।', 1255),
    ('transmit', null, 'v.', 'B2', 'প্রেরণ করা, ছড়ানো (রোগ)', 'Mosquitoes can transmit dangerous diseases.', 'মশা বিপজ্জনক রোগ ছড়াতে পারে।', 1256),
    ('trap', null, 'v., n.', 'B2', 'ফাঁদে ফেলা; ফাঁদ', 'Hunters set a trap for the fox.', 'শিকারিরা শিয়ালের জন্য একটি ফাঁদ পাতল।', 1257),
    ('treasure', null, 'n.', 'B2', 'ধনসম্পদ, গুপ্তধন', 'They found buried treasure on the island.', 'তারা দ্বীপে পোঁতা গুপ্তধন খুঁজে পেল।', 1258),
    ('tribe', null, 'n.', 'B2', 'উপজাতি, গোষ্ঠী', 'This tribe lives deep in the forest.', 'এই উপজাতি জঙ্গলের গভীরে বাস করে।', 1259),
    ('trigger', null, 'v.', 'B2', 'সূচনা করা, উদ্রেক করা', 'Loud noises can trigger her headache.', 'জোরে শব্দ তার মাথাব্যথার উদ্রেক করতে পারে।', 1260),
    ('trillion', null, 'number', 'B2', 'লক্ষ কোটি (ট্রিলিয়ন)', 'The company is worth one trillion dollars.', 'কোম্পানিটির মূল্য এক ট্রিলিয়ন ডলার।', 1261),
    ('troop', null, 'n.', 'B2', 'সৈন্যদল', 'More troops arrived at the border.', 'সীমান্তে আরও সৈন্য পৌঁছাল।', 1262),
    ('tsunami', null, 'n.', 'B2', 'সুনামি', 'A tsunami hit the coast in 2004.', '২০০৪ সালে উপকূলে একটি সুনামি আঘাত হেনেছিল।', 1263),
    ('ultimate', null, 'adj.', 'B2', 'চূড়ান্ত, শেষতম', 'Winning the cup was the ultimate goal.', 'কাপ জেতাই ছিল চূড়ান্ত লক্ষ্য।', 1264),
    ('unacceptable', null, 'adj.', 'B2', 'অগ্রহণযোগ্য', 'This kind of behavior is unacceptable.', 'এই ধরনের আচরণ অগ্রহণযোগ্য।', 1265),
    ('uncertainty', null, 'n.', 'B2', 'অনিশ্চয়তা', 'There is uncertainty about the weather.', 'আবহাওয়া নিয়ে অনিশ্চয়তা রয়েছে।', 1266),
    ('undergo', null, 'v.', 'B2', 'সহ্য করা, ভেতর দিয়ে যাওয়া', 'She will undergo surgery next week.', 'সে আগামী সপ্তাহে অস্ত্রোপচারের মধ্য দিয়ে যাবে।', 1267),
    ('undertake', null, 'v.', 'B2', 'গ্রহণ করা, দায়িত্ব নেওয়া', 'The team will undertake a new project.', 'দলটি একটি নতুন প্রকল্পের দায়িত্ব নেবে।', 1268),
    ('unfold', null, 'v.', 'B2', 'উন্মোচিত হওয়া, ধীরে ধীরে প্রকাশ পাওয়া', 'The story began to unfold slowly.', 'গল্পটি ধীরে ধীরে উন্মোচিত হতে লাগল।', 1269),
    ('unfortunate', null, 'adj.', 'B2', 'দুর্ভাগ্যজনক', 'It was an unfortunate mistake.', 'এটি একটি দুর্ভাগ্যজনক ভুল ছিল।', 1270),
    ('unite', null, 'v.', 'B2', 'ঐক্যবদ্ধ করা/হওয়া', 'The crisis united the whole nation.', 'সংকটটি পুরো জাতিকে ঐক্যবদ্ধ করল।', 1271),
    ('unity', null, 'n.', 'B2', 'ঐক্য', 'The country needs peace and unity.', 'দেশের শান্তি ও ঐক্য দরকার।', 1272),
    ('universal', null, 'adj.', 'B2', 'সার্বজনীন', 'Love is a universal language.', 'ভালোবাসা একটি সার্বজনীন ভাষা।', 1273),
    ('urgent', null, 'adj.', 'B2', 'জরুরি', 'I have an urgent message for you.', 'তোমার জন্য আমার একটি জরুরি বার্তা আছে।', 1274),
    ('usage', null, 'n.', 'B2', 'ব্যবহার', 'Water usage increases in summer.', 'গ্রীষ্মে পানির ব্যবহার বেড়ে যায়।', 1275),
    ('useless', null, 'adj.', 'B2', 'অকেজো, অকার্যকর', 'This old phone is now useless.', 'পুরনো ফোনটি এখন অকেজো।', 1276),
    ('valid', null, 'adj.', 'B2', 'বৈধ, যথাযথ', 'Your passport is no longer valid.', 'তোমার পাসপোর্টটি আর বৈধ নয়।', 1277),
    ('variation', null, 'n.', 'B2', 'তারতম্য, পরিবর্তন', 'There is some variation in prices.', 'দামের মধ্যে কিছুটা তারতম্য আছে।', 1278),
    ('vertical', null, 'adj.', 'B2', 'উলম্ব, খাড়া', 'Draw a vertical line on the paper.', 'কাগজে একটি উলম্ব রেখা আঁকো।', 1279),
    ('viewpoint', null, 'n.', 'B2', 'দৃষ্টিভঙ্গি', 'I respect your viewpoint on this issue.', 'এই বিষয়ে আমি তোমার দৃষ্টিভঙ্গিকে সম্মান করি।', 1280),
    ('visa', null, 'n.', 'B2', 'ভিসা', 'She applied for a student visa.', 'সে একটি ছাত্র ভিসার জন্য আবেদন করল।', 1281),
    ('visible', null, 'adj.', 'B2', 'দৃশ্যমান', 'The mountain was visible from our window.', 'আমাদের জানালা থেকে পাহাড়টি দৃশ্যমান ছিল।', 1282),
    ('voluntary', null, 'adj.', 'B2', 'স্বেচ্ছাসেবী, স্বেচ্ছাপ্রণোদিত', 'He does voluntary work at the hospital.', 'সে হাসপাতালে স্বেচ্ছাসেবী কাজ করে।', 1283),
    ('voting', null, 'n.', 'B2', 'ভোটদান', 'Voting starts at eight in the morning.', 'সকাল আটটায় ভোটদান শুরু হয়।', 1284),
    ('wander', null, 'v.', 'B2', 'ঘুরে বেড়ানো, উদ্দেশ্যহীনভাবে হাঁটা', 'We wandered around the old city.', 'আমরা পুরনো শহরে ঘুরে বেড়ালাম।', 1285),
    ('warming', null, 'n.', 'B2', 'উষ্ণায়ন', 'Global warming affects the whole planet.', 'বৈশ্বিক উষ্ণায়ন সমগ্র গ্রহকে প্রভাবিত করে।', 1286),
    ('weekly', null, 'adj.', 'B2', 'সাপ্তাহিক', 'We have a weekly meeting on Mondays.', 'সোমবার আমাদের একটি সাপ্তাহিক সভা হয়।', 1287),
    ('weird', null, 'adj.', 'B2', 'অদ্ভুত, বিচিত্র', 'That was a weird dream last night.', 'গত রাতে সেটা একটা অদ্ভুত স্বপ্ন ছিল।', 1288),
    ('welfare', null, 'n.', 'B2', 'কল্যাণ', 'The charity works for child welfare.', 'দাতব্য সংস্থাটি শিশু কল্যাণের জন্য কাজ করে।', 1289),
    ('wheat', null, 'n.', 'B2', 'গম', 'Farmers grow wheat in this region.', 'এই অঞ্চলে কৃষকরা গম চাষ করে।', 1290),
    ('whoever', null, 'pron.', 'B2', 'যে কেউ, যিনিই', 'Whoever finishes first wins the prize.', 'যে কেউ প্রথমে শেষ করবে সে পুরস্কার জিতবে।', 1291),
    ('widespread', null, 'adj.', 'B2', 'ব্যাপক, বিস্তৃত', 'There is widespread support for the plan.', 'পরিকল্পনাটির জন্য ব্যাপক সমর্থন রয়েছে।', 1292),
    ('wisdom', null, 'n.', 'B2', 'প্রজ্ঞা, জ্ঞান', 'Age often brings wisdom.', 'বয়স প্রায়ই প্রজ্ঞা নিয়ে আসে।', 1293),
    ('withdraw', null, 'v.', 'B2', 'প্রত্যাহার করা, তুলে নেওয়া', 'He decided to withdraw from the race.', 'সে প্রতিযোগিতা থেকে সরে যাওয়ার সিদ্ধান্ত নিল।', 1294),
    ('wolf', null, 'n.', 'B2', 'নেকড়ে', 'A wolf howled in the dark forest.', 'অন্ধকার জঙ্গলে একটি নেকড়ে ডাকল।', 1295),
    ('workforce', null, 'n.', 'B2', 'কর্মীবাহিনী, শ্রমশক্তি', 'Women make up half the workforce.', 'নারীরা কর্মীবাহিনীর অর্ধেক অংশ।', 1296),
    ('workplace', null, 'n.', 'B2', 'কর্মক্ষেত্র', 'Safety is important in every workplace.', 'প্রতিটি কর্মক্ষেত্রে নিরাপত্তা গুরুত্বপূর্ণ।', 1297),
    ('workshop', null, 'n.', 'B2', 'কর্মশালা', 'She attended a writing workshop last week.', 'সে গত সপ্তাহে একটি লেখালেখি কর্মশালায় অংশ নিয়েছিল।', 1298),
    ('worm', null, 'n.', 'B2', 'কেঁচো, কীট', 'The bird pulled a worm from the ground.', 'পাখিটি মাটি থেকে একটি কেঁচো টেনে বের করল।', 1299),
    ('wrist', null, 'n.', 'B2', 'কব্জি', 'She wears a watch on her wrist.', 'সে তার কব্জিতে একটি ঘড়ি পরে।', 1300),
    ('specialize', null, 'v.', 'B1', 'বিশেষায়িত হওয়া, নির্দিষ্ট বিষয়ে দক্ষতা অর্জন করা', 'She wants to specialize in law.', 'সে আইন বিষয়ে বিশেষজ্ঞ হতে চায়।', 700);
